### ISSUE TITLE
New Logo!

### ISSUE THREAD

**Issue by jadjoubran** [jadjoubran/laravel5-angular-material-starter#105]
![laravel angular](https://cloud.githubusercontent.com/assets/2265232/11324985/250a18a0-914a-11e5-9d6a-31c4e230291e.png)

@Bodom78 @rooferz @masterpowers @palpalani @GrahamCampbell @palpalani 

I'd love to get your feedback on the new logo by @nicolesaidy! :rocket:

**Comment by GrahamCampbell** [comment]
:+1:

**Comment by ptondereau** [comment]
Nice love it

**Comment by Bodom78** [comment]
Love the subtle L and A from the two simple shapes which works really well as do the two colors for Laravel/Angular.

Overall I think it's fantastic, well done.

**Comment by ekvedaras** [comment]
:+1:

**Comment by jadjoubran** [comment]
Awesome :smile:

**Comment by jadsalhani** [comment]
:+1:

**Comment by palpalani** [comment]
It represents Laravel, Angular and Material. Great!

**Comment by ChadTaljaardt** [comment]
:+1:

**Comment by nicolesaidy** [comment]
Thanks everyone for the positive feedback. Glad you like it!

**Comment by shiruken1** [comment]
Nice!

**Comment by rafalradomski** [comment]
Look nice! :)

**Comment by m33ch** [comment]
Cool!

**Comment by odyright** [comment]
Hello @jadjoubran , it looks very nice but if you add some material design effect with illustrator or photoshop it would be  greater.

**Comment by jadjoubran** [comment]
Thank you for your feedback @odyright 
We'll keep it in mind for the next iteration!
