### ISSUE TITLE
Debugbar doesn't display API queries

### ISSUE THREAD

**Issue by edbentinck** [jadjoubran/laravel5-angular-material-starter#106]
I can't seem to get the debugbar to display any queries performed from the API. I don't know if I'm just missing something plainly obvious, but I've even tried a straight-forward `\Debugbar::info('Hello, world!');` to no avail.

It works from top-level controllers like `WelcomeController.php` without problems.

I don't know if it's got anything to do with [this Dingo issue](https://github.com/barryvdh/laravel-debugbar/issues/235). Anyone else got any issues with debugbar?

**Comment by jadjoubran** [comment]
Hi @edbentinck 

Thanks for your feedback

Indeed this is related to the dingo issue you mentioned. I remember stumbling upon it when I originally had the same issue.

Although this [issue](https://github.com/dingo/api/issues/363) says that it's working

I'm going to keep this open and dig through DebugBar

I'll keep you posted if I can make it work

**Comment by jadjoubran** [comment]
In the meantime, this [package](https://github.com/daylerees/anbu) might be useful

**Comment by edbentinck** [comment]
Thanks, @jadjoubran. Bittersweet knowing that I'm not just mad... Hope we can find a fix soon! :grin:

That other package will do for now.

**Comment by jadjoubran** [comment]
Mentioned limitation in documentation - must keep it in sync if this gets resolved
https://laravel-angular.readme.io/docs/debugbar

**Comment by jadjoubran** [comment]
There seems to be an upcoming upstream fix for this [here](https://github.com/barryvdh/laravel-debugbar/pull/399)

**Comment by edbentinck** [comment]
Interesting... let's hope they move along with it. Keep up the awesome work!

**Comment by jadjoubran** [comment]
Debugbar has been removed as of version 3.1 since it doesn't work with APIs yet..
Will re-open as soon as there's progress on the upstream issue
