### ISSUE TITLE
Bootstrap alternative

### ISSUE THREAD

**Issue by flaird** [jadjoubran/laravel5-angular-material-starter#114]
This might be considered off-topic but I want to suggest the following as from what I've found, it's a great starter kit for implementing AngularJS and Laravel together with all other great plugins you have included here, even without Angular Material.

Implement the option to choose between Angular Material and Bootstrap, perhaps even Foundation.
I think this package can become so much more if it aimed for a more general approach in regards to which design package it implements.

I've chosen to try and remove Angular Material and go with Bootstrap instead as Angular Material is a bit more demanding on the client browser than what Bootstrap is, but I have not started this yet and when I thought of it, perhaps you would be interested in creating the above? Just my 2 cents!

**Comment by jadjoubran** [comment]
Hi @sagaio 
Thank you so much for this suggestion. It's not off-topic at all.

Allowing the end user to make a choice for the UI library would need to conver this starter package into a yeoman generator. I know that there's a great potential for this but it just happened that I started with this `starter` package..

If anyone is interested in making this happen, I can definitely help.. but I already have a crazy roadmap for Versions 3.0, 3.1 & 3.2 so I won't be able to take the lead for that.

Having said that, replacing Angular Material in favor of ui-bootstrap (or just bootstrap) is extremely easy. I'll try to list the steps, please tell me if it works for you:
- remove angular-material dependencies from bower.json
- `bower update`
- edit `main.js` and remove `'ngMaterial'` module
- delete dialog.js and toast.js services
- remove all features from /angular/app/**/

If you think that there's an easier way, please feel free to suggest it

Cheers :smile:

**Comment by jadjoubran** [comment]
Also, as of Version 3, you can remove the Angular generators (remove them from composer.json and from providers)

**Comment by jadjoubran** [comment]
Feel free to re-open if you have comments/suggestions :D

**Comment by iannazzi** [comment]
I am going to agree with @sagaio . Great starting point for angular + laravel, however I am so much farther along using bootstrap in a few hours  after spending some time 'suffering' with angular material. There are just far more examples and better docs for bootstrap.  It was pretty simple adding bootstrap, I just left angular-material in there, probably a bad idea, we will see.

For others I added this code to bower.json in addition to adding the bootstrap dependency

```

"overrides": {
    "bootstrap": {
      "main": [
        "dist/css/bootstrap.css",
        "dist/css/bootstrap-theme.css",
        "dist/js/bootstrap.js"]
    }
```

Gulp will pick up on this and you will be up and running in seconds.
