### ISSUE TITLE
Karma tests setup for Angular

### ISSUE THREAD

**Issue by jadjoubran** [jadjoubran/laravel5-angular-material-starter#117]
Current repo is missing setup for Angular unit tests using ngAnnotate

**Comment by kujtimiihoxha** [comment]
@jadjoubran  Is there any work being done on this issue, it would be really  nice to have tests in the next release. Thanks.

**Comment by jadjoubran** [comment]
@kujtimiihoxha unfortunately this is not planned for the next release since there are more critical features.. especially JWT and everything around it

However feel free to submit a Pull Request for this

**Comment by kujtimiihoxha** [comment]
@jadjoubran I have tried to implement karma tests but did not succeed, I will try again to implement this feature in the coming days, as soon as I have it ready I will  submit a Pull Request .

**Comment by kujtimiihoxha** [comment]
@jadjoubran look at PR #219

**Comment by kujtimiihoxha** [comment]
@jadjoubran Tell me if you have any tests in mind and I will implement them ;).

**Comment by jadjoubran** [comment]
Thanks again :smile:

Actually I just remembered that it would make sense to setup [ngDescribe](https://github.com/kensho/ng-describe) on top of this.. since it removes all the boilerplate
I can help you with it if you want

**Comment by kujtimiihoxha** [comment]
I will see what I can do, I will try to implement this today.

**Comment by kujtimiihoxha** [comment]
@jadjoubran tests can now use ngDescribe ;) tell me what you think about the folder structure I proposed and I will implement that ;)

**Comment by jadjoubran** [comment]
@kujtimiihoxha thank you so much
I think we're almost done :smile: just a few minor fixes

**Comment by kujtimiihoxha** [comment]
@jadjoubran All done, take a look at my commit, tell me if there is anything else needed.
