### ISSUE TITLE
Hashtags

### ISSUE THREAD

**Issue by shiruken1** [jadjoubran/laravel5-angular-material-starter#118]
Hey y'all!

Just wondering if there was any reason for keeping the hashtags prefix on the URLs, or if I could sink my teeth into removing them.

I haven't used ui-router yet, but Zemke's boiler implemented a neat solution with ngRoute that I'd like to see if I can pull off.

**Comment by jadjoubran** [comment]
Hi @shiruken1 

If you need to remove tags (aka enable HTML5 mode), you need to setup a catch all route in Laravel's route.

ui-router is much more powerful than ngRoute

Let me know if you need help enabling HTML5 mode

**Comment by shiruken1** [comment]
Ah, thanks!
