### ISSUE TITLE
How To Update - Documentation

### ISSUE THREAD

**Issue by bravocado** [jadjoubran/laravel5-angular-material-starter#119]
Adding how to update the starter to documentation?

**Comment by jadjoubran** [comment]
Hi @bravocado 
It will be available very soon :smile: 

Will post here when it's done

**Comment by jadjoubran** [comment]
[Upgrade guide](https://laravel-angular.readme.io/docs/upgrade-guide) is now available.

Let me know if anything is unclear

Cheers
