### ISSUE TITLE
Upgrade to Laravel 5.2

### ISSUE THREAD

**Issue by jadjoubran** [jadjoubran/laravel5-angular-material-starter#121]

**Comment by jadjoubran** [comment]
@GrahamCampbell would you recommend following the migration guide or starting with a fresh 5.2 installation?

**Comment by GrahamCampbell** [comment]
Depending on what features are used, the migration to L5.2 can be very trivial.

**Comment by GrahamCampbell** [comment]
I'd recommend diffing the laravel/laravel repo against the state it was when you started the project here, then copying over needed changes, then just having a flick through the upgrading docs.

**Comment by GrahamCampbell** [comment]
The only important changes to laravel/laravel are in the config folder though as far as I know.

**Comment by jadjoubran** [comment]
@GrahamCampbell in this case migration to L5.2 is trivial. But here's my point of view:

This is a starter project, which means a starting point for lots of people..
Isn't it better to start off with a fresh installation of 5.2 + features that this starter introduces
rather than starting off with a 5.1 upgraded to 5.2 version of Laravel + features that this starter introduces?

**Comment by GrahamCampbell** [comment]
> Isn't it better to start off with a fresh installation of 5.2 + features that this starter introduces
> rather than starting off with a 5.1 upgraded to 5.2 version of Laravel + features that this starter introduces?

Well, the two are the same if you copy over the changes from laravel/laravel?

**Comment by jadjoubran** [comment]
hmm.. I remember there were lots of changes when upgrading from 5.0 to 5.1 compared to a fresh 5.1 installation..
How would you suggest that I copy the changes from laravel/laravel?

**Comment by GrahamCampbell** [comment]
I just manually go through the diff and manually apply the changes I want.

**Comment by GrahamCampbell** [comment]
https://github.com/laravel/laravel/compare/v5.1.11...master#files_bucket

**Comment by GrahamCampbell** [comment]
Replace `v5.1.11` with the commit you used to create the project, or whatever.

**Comment by GrahamCampbell** [comment]
> hmm.. I remember there were lots of changes when upgrading from 5.0 to 5.1 compared to a fresh 5.1 installation..

Yeh, that was true. 5.2 is a much smaller change set.

**Comment by jadjoubran** [comment]
Oh okay!

Then I guess it makes sense to just follow the upgrade guide

Thanks

**Comment by GrahamCampbell** [comment]
I'd still recommend doing the diff and copy for the best results before then going through the upgrading guide.

**Comment by jadjoubran** [comment]
Okay.. a silly question though.. How can I do that using git?

**Comment by GrahamCampbell** [comment]
Probably with difficulty.

**Comment by GrahamCampbell** [comment]
I'd recommend just using github's "compare" stuff, like in that example url I gave.

**Comment by jadjoubran** [comment]
Okay

**Comment by ChadTaljaardt** [comment]
Is this going forward?

**Comment by jadjoubran** [comment]
yes it is! It's the highest priority task :smile:

**Comment by edbentinck** [comment]
Slightly off-topic question, but in terms of upgrades what would you suggest as the easiest way to upgrade an existing repo based on `laravel-angular` v2.10 and adding the improvements made in v3.0 ? I haven't been through the commits in detail, but I'm interested in your thoughts :)

**Comment by jadjoubran** [comment]
Hi @edbentinck 
Can you please open a new issue? so that we can discuss freely
Thanks!

**Comment by jadjoubran** [comment]
- [x] upgrade to Laravel 5.2
- [x] configure middlewares
- [x] documentation upgrade guide from 3.0 to 3.1 ( generators & laravel 5.2)
- [ ] update readme.md
- [ ] create a new documentation for 3.1 & update it
- [ ] update landing code to ES6

**Comment by ChadTaljaardt** [comment]
How is this going? I see 5.2.13 is released now :+1:

**Comment by jadjoubran** [comment]
@ChadTaljaardt Still didn't have time yet :(
hopefully soon

**Comment by jadjoubran** [comment]
Upgraded to Laravel 5.2 :smile: 
I still have some fixes before the 3.1 release
I'd love it if anyone can test using the latest unstable version

**Comment by jadjoubran** [comment]
I just published the [v3.1 documentation](https://laravel-angular.readme.io/v3.1/docs) - currently in draft mode.

I would love to get some feedback, proof reading, comments, etc.. :smile: 
Thanks!

**Comment by ChadTaljaardt** [comment]
Ill take a look
