### ISSUE TITLE
Out of the box password reset functionality (using JWT)

### ISSUE THREAD

**Issue by jadjoubran** [jadjoubran/laravel5-angular-material-starter#129]

**Comment by jadjoubran** [comment]
This would make sense in a generator, after implementing #151

**Comment by jadjoubran** [comment]
- [x] forgot password page
- [x] forgot password component
- [x] reset password page
- [x] show loader while checking code validity
- [x] reset password component
- [x] migration? use Laravel's
- [x] change controller route to explicit definition
- [x] PasswordController tests & functionality
- [x] make PasswordController easily configurable
- [x] fix front-end tests
- [x] styling for both pages
- [x] double check design with Nicole

**Comment by ChadTaljaardt** [comment]
I think this is essential

**Comment by jadjoubran** [comment]
This is done and ready for testing 😄
