### ISSUE TITLE
Bower components directory does not exist

### ISSUE THREAD

**Issue by palpalani** [jadjoubran/laravel5-angular-material-starter#13]
Fresh install in my windows machine with xampp stack.

When i run `gulp`, i am geeting the followin error.
`Error: Bower components directory does not exist at d:\xampp\htdocs\l
aravel5-angular-material-starter\bower_components`

**Comment by jadjoubran** [comment]
I think you forgot to run the `bower install` command
Let me know if that fixes it for you

**Comment by palpalani** [comment]
I did `bower install` and the packages are under `www\packages` folder.

**Comment by jadjoubran** [comment]
Do you have a global .bowerrc that changes the default folder to www\packages? There isn't any .bowerrc committed in this repository so it must be something on your end changing the default directory for bower.
Can you check if there's a .bowerrc anywhere?

**Comment by palpalani** [comment]
I don't see the file `.bowerrc`.
i just removed `www\packages` the folder and i run again `bower install`, it store the file under `www\packages` only.

Then i created new file `.bowerrc` with contents
`{
    "directory": "bower_components"
}`
Now works every think.

Thanks

**Comment by jadjoubran** [comment]
I guess you have a global .bowerrc
Can you check if you have one in your root directory? (I guess it's C:/users/your-username)
