### ISSUE TITLE
Restangular not liking Laravel's output

### ISSUE THREAD

**Issue by shiruken1** [jadjoubran/laravel5-angular-material-starter#135]
Why do I get...

```
Error: Response for getList SHOULD be an array and not an object or something else
```

when I run (as Martin's example shows):

```
        API.all("responses").getList().then(function(data) {
          vm.categories = angular.fromJson(data.category_responses);
        });
```

but not when I run (as your step-through in SitePoint showed):

```
        API.all("responses").doGET().then(function(data) {
          vm.categories = angular.fromJson(data.category_responses);
        });
```

here's my server-side, in case my screw up's coming from there:

```
    public function index()
    {
        // get all responses and bring along their groups' info
        $responses_grouped = CategoryResponses::with('group', 'category')->get();

        return $responses_grouped;
    }
```

Isn't getList supposed to start with an array, then fill it when the server returns the data?

Sorry if this question is dumb!

**Comment by jadjoubran** [comment]
Hi @shiruken1 

`.getList()` expects an array to be returned..
Can you please try adding `->all()` after your `->get()`? This will convert the object into an array..
Let me know if this works for you

**Comment by jadjoubran** [comment]
And you probably don't need the `angular.fromJson`

**Comment by shiruken1** [comment]
It doesn't :disappointed: Also, if I take away the angular.fromJson (using the doGET) it won't work. Here's my output with the ->all(), btw:

```
[
    {
        "category": {
            "id": 1,
            "name": "testGroup"
        },
        "group": {
            "id": 1,
            "name": "testGroup"
        },
        "id": 1,
        "response": "fake response from testGroup, for testCat"
    }
]
```

And here it is without it:

```
{
    "category_responses": [
        {
            "category": {
                "id": 1,
                "name": "testCat"
            },
            "group": {
                "id": 1,
                "name": "testGroup"
            },
            "id": 1,
            "response": "fake response from testGroup, for testCat"
        }
    ]
}
```

**Comment by shiruken1** [comment]
Well, it pays to prettify your JSON **before** reading it...

Turns out I just needed to remove the .category_responses _and_ the fromJson. 

But now, why doesn't  chaining work?

```
AutoResponses.getList("create").then
```

shows "http://localhost/api/responses?0=c&1=r&2=e&3=a&4=t&5=e" being requested in the Network console, instead of "http://localhost/api/responses/create" which is what it's supposed to be hitting, no?

**Comment by jadjoubran** [comment]
hm... can you show me the full code for this?

**Comment by shiruken1** [comment]
No worries. Thank you so much, though!

So either Martin's examples are either out of date, or I'm not getting it, since getList is supposed to handle arrays...

Regardless, since I was returning an array with 2 sub-arrays from Laravel, like so:

```
return array('groups' => Groups::all(), 'categories' => Category::all());
```

it turns out I needed to change it from:

```
AutoResponses.getList("create").then(function(data) {
```

to:

```
AutoResponses.all("create").doGET().then(function(data) {
```

In order to make it understand the output, let alone send the correct request (to http://localhost/api/responses/create)

I sure hope this helps someone else out in the future!

**Comment by jadjoubran** [comment]
Ah yes.. I guess this is a requirement for Restangular's `getList`..
the endpoint should return an array of data..
so yeah that's the issue

it's better if you can use `.get()` instead of `doGET()` if you want to benefit from the API configuration available
