### ISSUE TITLE
php artisan jwt:generate error

### ISSUE THREAD

**Issue by JoshuaBedford** [jadjoubran/laravel5-angular-material-starter#14]
PHP Warning:  require(/Library/WebServer/Documents/laravel5-angular-material-starter/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /Library/WebServer/Documents/laravel5-angular-material-starter/bootstrap/autoload.php on line 17

PHP Fatal error:  require(): Failed opening required '/Library/WebServer/Documents/laravel5-angular-material-starter/bootstrap/../vendor/autoload.php' (include_path='.:') in /Library/WebServer/Documents/laravel5-angular-material-starter/bootstrap/autoload.php on line 17

These are the error codes I received when I attempted to install it. The first part went fine, then this happened! I'm fairly new to this area of things, though I've been programming for years. Not sure if this is on your end or mine.

**Comment by jadjoubran** [comment]
Hi @JoshuaBedford!

Thank you for opening an issue.

The problem indeed is from the documentation. I just fixed the installation steps in the readme.
You should just proceed normally with the commands after `git clone`.

Let me know if this works for you.

**Comment by jadjoubran** [comment]
Closing this. Feel free to re-open if you have any issues!

**Comment by JoshuaBedford** [comment]
It worked, thanks! Sorry I got back into building and didn't realize I never responded! Thanks for your support and hard work.

**Comment by jadjoubran** [comment]
Glad to hear that:D No worries
I'd love to hear your feedback.. feel free to open a new issue if you'd like to suggest a new feature or something else
