### ISSUE TITLE
Change name to Larangular

### ISSUE THREAD

**Issue by jadsalhani** [jadjoubran/laravel5-angular-material-starter#140]
I was thinking of a name for this starter, since laravel-angular is a bit too long..
Larangular came to mind I kinda liked it :D Just wanted to see what other think!

**Comment by jadjoubran** [comment]
This has been suggested before by @rooferz
Honestly I didn't like the name at first.. but now that I heart it every couple of days at work.. I must admit I love it :smile: 

Let's see what other people think

**Comment by ptondereau** [comment]
I can't dislike my idea. So it's good to me  :)

**Comment by jadjoubran** [comment]
haha :+1:

**Comment by ChadTaljaardt** [comment]
:+1:

**Comment by naerymdan** [comment]
Like this existing laravel+angular tutorial: https://github.com/bestmomo/larangular ?

**Comment by charl-kruger** [comment]
Given that there is la..ravel and lu..men, I think langular and lungular would be more suitable if you were to do the same with lumen.

**Comment by brunogonncalves** [comment]
To me it is ridiculous, because laravel is a thing and angular is other thing. This name songs me a new project separated using laravel + angular, and it is not true, this project is just the laravel framework + vendor libraries + front-end configured with gulp and bower, including generators.

**Comment by jadjoubran** [comment]
I knwo that the name "laravel5-angular-material-starter" is huge, but as @Bodom78 mentioned on the trello board, at least it's obvious. Users would directly understand the use of this package
Also, "Larangular" is tongue-twister
