### ISSUE TITLE
Remove ability to pass $scope in DialogService

### ISSUE THREAD

**Issue by jadjoubran** [jadjoubran/laravel5-angular-material-starter#141]
Since all controllers & directives are now using ControllerAs syntax.
Communication inside dialogs should use services

**Comment by shiruken1** [comment]
I like the idea, so long as it's well documented, so that a newbie to
Angular doesn't ask why it's not working, or become frustrated
unnecessarily.

**Comment by jadjoubran** [comment]
:+1:

**Comment by jadjoubran** [comment]
Updated!
Second argument is now the additional options that are passed to $mdDialog
