### ISSUE TITLE
Update angular folder structure/naming & fix generators accordingly

### ISSUE THREAD

**Issue by jadjoubran** [jadjoubran/laravel5-angular-material-starter#142]
- [x] `angular/app` should be renamed to `angular/app/pages/`
- [x] `angular/directives` should be renamed to `angular/app/components`
- [x] `.directive.js` should become `.component.js`
- [x] page_name`.page.html` (for page views)
- [x] finalize other breaking changes
- [x] update documentation
- [x] upgrade guide

Most of these tasks help in angular 2 migration

**Comment by jadjoubran** [comment]
ping @jsalhani
Let me know if there's anything else that needs to be fixed

**Comment by jadsalhani** [comment]
Maybe have them all under app?

```
app/
     components/
     pages/
```

Something like this would make a bit more sense imo since they all make the app
And also the html in the pages could have something like .page.html or .container.html to differentiate

**Comment by jadjoubran** [comment]
awesome, thanks!
updated the description

**Comment by jadjoubran** [comment]
Thanks @jsalhani for reviewing this!

Will be available as of version 3.1 with #121 (contains breaking changes)

**Comment by ChadTaljaardt** [comment]
Thanks for the updates :+1:

**Comment by jadjoubran** [comment]
:rocket:
