### ISSUE TITLE
Dialog is not working when minify css

### ISSUE THREAD

**Issue by kiro64** [jadjoubran/laravel5-angular-material-starter#144]
i saw this project on version 3 have change css minify to use `gulp-cssnano`.
this cause an issue on "Confirm Dialog" can not interact with user, ( can not click on any button and need to press "esc" on key board to close a dialog)

anyone have a solution on this problem?

**Comment by jadjoubran** [comment]
@kiro64 did you check your console for javascript errprs?
If you try to `insect element` does the button seem clickable? or is it covered by other elements?

It's not really an issue with this starter package but we can keep it open for a bit if anyone has a solution

**Comment by kiro64** [comment]
there's no error in console because it's css problem. Actually, it's have a problem with all Dialog Type.
The problem come up when i run `gulp --production` to minify css and deploy project on production. 

i'm turn back to `gulp-minify-css` with no problem for a while.

**Comment by jadjoubran** [comment]
@kiro64 would you be able to provide a codepen to test this?
It would be useful especially if it's something that might affect other users
Thanks!

**Comment by jadjoubran** [comment]
Hi @kiro64 
Thanks for reporting this, I was able to reproduce it
I'm reverting to `gulp-minify-css`

**Comment by jadjoubran** [comment]
It seems that in elixir 4.2 unsafe cssnano optimizations were disabled
I'll give this is a shot and see if it works
https://www.npmjs.com/package/laravel-elixir#421

**Comment by jadjoubran** [comment]
Also confirmed by @bampakoa's post.. I just saw it :smile:
