### ISSUE TITLE
Integrating UIkit

### ISSUE THREAD

**Issue by ghost** [jadjoubran/laravel5-angular-material-starter#145]
Hi,

just planning to integrate uikit-frontend (https://github.com/uikit/uikit) but I dont know what is best way to do it. What is your suggestion?

Thanks!

**Comment by jadjoubran** [comment]
Hi @regisaih 

I'm guessing you need to remove angular material first and everything that depends on it.
This involves (at least) running `bower uninstall angular-material`.
Then you have to remove the module from `angular/main.js`.
Other services such as `toast.service.js` and `dialog.toast.js` also need to be removed.

Then you'd just need to follow the installation steps for uikit!

Let me know if this answers your question

**Comment by ghost** [comment]
Thanks @jadjoubran. Perhaps angular/material folder have to remove aswell. Maybe I create angular/uikit folder and copy all needed less and js files there. Jquery is dependency and is easiest to install with bower. And font files I can copy directly to public/fonts.

**Comment by jadjoubran** [comment]
yep!
But if you're not using Angular then I don't think this starter package will be useful for you. Especially that you'll be loosing the gulp tasks and other features

**Comment by ghost** [comment]
Ok, I'm not going to remove angular. But there is not much pure angular frontend frameworks(?) Angular material is too limited for my needs.

**Comment by jadjoubran** [comment]
@regisaih I totally understand.. I just don't want to recommend my starter if you're not going to use Angular
Good luck :smile:
