### ISSUE TITLE
Form validation needs a seperate ngMessages module

### ISSUE THREAD

**Issue by DennisOng** [jadjoubran/laravel5-angular-material-starter#147]
Ran into this issue when trying to use form validation.

http://stackoverflow.com/questions/31174523/angular-material-input-validation-error-messages

Basically, the error message (in red) below the input will not go away even if a proper input is given.

What worked for me was to install "angular-messages" via bower, and to include the angular module 'ngMessages'.

(Thanks for this awesome starter codebase you have! Finding it really helpful indeed)

**Comment by jadjoubran** [comment]
Thanks @DennisOng! I'm glad you liked the repo

It's awesome that we have this issue here, people would find it useful if they have the same issue.

So you're suggesting to include angular-messages out of the box?
I would try and avoid adding lots of libraries out of the box.. unless they're deeply integrated with what the repository presents..

So do you think there's a way to automate ng-messages with the Restangular error interceptor then it would be great
Let me know what you think

**Comment by DennisOng** [comment]
Yup I do think including this out of the box is the way to go. Since when you copy & paste the examples from the official Angular Material demos:
https://material.angularjs.org/latest/demo/input

then you do run into this issue. It seems that Angular Material's demo just assumes that the module is included.

I'm not really sure how you would be able to "automate ng-messages with the Restangular error interceptor" though, from my understanding ng-messages is for front-end validation for forms, while Restangular's error interceptor can only return errors provided via the backend?

Someone more knowledgable might be able to shed some light here. I'm still pretty new to this whole thing I must admit :)

**Comment by jadjoubran** [comment]
It seems to me that this would fit in more in as a `recipe`..
(more on that in #148 and #143)
I'll update this thread as soon as I have more info regarding the recipes architecture

Thanks again :smile:

**Comment by DennisOng** [comment]
Sounds good :) Thanks! :+1:

**Comment by sam-g-roberts** [comment]
Thanks for posting this @DennisOng i just came across exactly the same problem and you saved me hours of debugging.

**Comment by sam-g-roberts** [comment]
@DennisOng quick question, did you add the ngMessages in main.js? i've installed angular-messages in bower and added ngMessages onto app.controllers but now my form errors don't show up at all. Is there a step i'm missing?

**Comment by DennisOng** [comment]
Glad that it helped! Did took me a while to figure this out haha

**Comment by jadjoubran** [comment]
Hi @DennisOng 
Thanks again for reporting this and saving time for other users :smile: 
I wanted to open an issue on angular material's repository, but I found one [here](https://github.com/angular/material/issues/1284) and I also sent them a Pull Request

I believe that angular material is the right place to fix such issue

Thanks again :smile:

**Comment by jadjoubran** [comment]
@sam-g-roberts @DennisOng 
They just released a version with the fix :smile: 
https://material.angularjs.org/latest/demo/input
They now mention the dependency on ngMessages

**Comment by DennisOng** [comment]
good to know :) thanks! :)
