### ISSUE TITLE
Recipes & Plugins

### ISSUE THREAD

**Issue by jadjoubran** [jadjoubran/laravel5-angular-material-starter#149]
As forecasted on the [trello board](https://trello.com/b/tZ997reo/laravel-angular-material-starter) this starter requires some kind of recipes.

After giving it some thought, it seems that what we might need is the following:
1. Recipes
2. Plugins
#### Recipes

Recipes would allow you to achieve common tasks by following a set of simple instructions. For example #147 and #148  
##### Show validation messages in forms:

npm install angular-messages
add module to `main.js`
link to angular-messages docs
##### Internationalization for your app:

npm install angular-translate
add module to `main.js`
link to angular-translate docs
#### Plugins

Plugins are also not included out of the box in the repository, and allow you to follow a set of installation steps (usually involving your backend and/or front-end).
Check out the `plugins` column on the [trello board](https://trello.com/b/tZ997reo/laravel-angular-material-starter) for examples.

Another reason why I'm thinking of such approach, is that this repository does **not** intend to depend on way too many unused packages. Even if it was a font package, we don't include material-design-icons out of the box, because some users might be used to font-awesome (and so on..).

For now, it seems that **recipes** are defintely needed whereas the exact use cases of plugins is still vague.. So I'll probably start with recipes as of version 3.1

The best place for recipes, would probably be the documentation

I'd love to get feedback on this :smile:

**Comment by shiruken1** [comment]
Will there be documentation on how to write these recipes? I'd love to chip in with the localization, and others.

**Comment by jadjoubran** [comment]
Hi @shiruken1 
Thank you for your interest!

For now, you can just create a new issue or comment here.. You can write it in Markdown comment and I'll port it to the relevant documentation page :smile:

**Comment by shiruken1** [comment]
@jadjoubran Should I paste the contents of the files here, or does this link suffice? [Localization](https://github.com/shiruken1/laravel5-angular-material-starter/tree/langular-localization)

The main components are:
- App/Helpers/Translations::translate()  The main code to convert the JSON's, and the function you'll need to call from any back-end method besides a controller
- App/Http/Controllers/Controller::d() the wrapper for controllers to use
- Angular/config/translate.config.js (What tells angular-translate to look for the json files as soon as you change states)
- public/lang/{en}/*.json (The json files under the respective locale designator 'en', in this case)

Translate.config.js will automatically try to load the name of the state with the .json extension, without the "app." prefix. For example, if you've clicked/loaded the login page, and it's state is defined as app.login in the routes.js file, angular-translate will look for "public/lang/en/login.json"

When using it from a blade view (for example, when emailing something), all you'll need to code is:

```
@inject('T', 'App\Helpers\Translations')
<p>{{ $T->translate('EMAIL_GREETING', '', 'email', 'en') }}</p>
```

Translations::translate(), in this use case, will look for the EMAIL_GREETING key "public/lang/en/email.json"

@jadjoubran Let me know if I should include anything else!

**Comment by jadjoubran** [comment]
Thanks @shiruken1 
I'll check this in the coming week (or two)
I will of course extract the necessary files from your repo so that we make sure this solution will always work
I will also prepare the documentation setup for this
Thanks again :smile:

**Comment by jadjoubran** [comment]
- Additional comment from @shiruken1 https://github.com/jadjoubran/laravel5-angular-material-starter/issues/200#issuecomment-217962556
- recipe redirect-to from #297

**Comment by jadjoubran** [comment]
https://github.com/jadjoubran/laravel-angular-recipes

So I thought about starting with an easy way (github repo for instance) and then once we have a lot of recipes and other features such as search and voting (etc.) are required, I will develop a separate page/website

Let me know what you think! 😄 
And feel free to send your Recipes
