### ISSUE TITLE
Auth scaffolding

### ISSUE THREAD

**Issue by jadjoubran** [jadjoubran/laravel5-angular-material-starter#151]
`artisan ng:auth` would generate scaffolding that is similar to Laravel 5.2's auth scaffolding, but based on Angular Material.

**Comment by odyright** [comment]
:ok_hand: `artisan ng:auth`

**Comment by ghost** [comment]
hi @jadjoubran,

this is great idea! Can I have your estimation of merging date?

**Comment by shiruken1** [comment]
I'm still waiting on the UI folks in our team to finish their work, so I can provide the views for it. I'll need @jadjoubran's code for the functionality, since I'm still using Satellizer.

**Comment by jadjoubran** [comment]
@shiruken1 Thanks for this!

@regisaih I still haven't had the time to upgrade to Laravel 5.2.. #121 

I'm expecting the following
1. Upgrade to laravel 5.2 & fix test helpers
2. Release version 3.1 with documentation
3. Start working on ng:auth

Hopefully I can upgrade this weekend!
I'm also planning new screencasts (What's new in 3.1?)

**Comment by ghost** [comment]
Sounds great! Take your time and keep on good work. Thanks for answers for both of you.

**Comment by Z1Play-com** [comment]
Nice work

**Comment by shiruken1** [comment]
So the UI folks delivered a "materialized" Bootstrap theme... yey.

Will update once they actually return a material-design compliant UI

**Comment by chojuanillo** [comment]
your work is amazing , my most sincere congratulations

**Comment by chojuanillo** [comment]
@jadjoubran your work is amazing , my most sincere congratulations

**Comment by jadjoubran** [comment]
Thanks @chojuanillo I'm glad you think it's great
Feel free to subscribe on my [blog](https://blog.jadjoubran.io/) for development articles

**Comment by jadjoubran** [comment]
I'm thinking of providing JWT authentication out of the box.. without having to generate it..
I think it'll be a requirement for most apps and even if someone doesn't need the particular views, they'll probably be a good start
Any thoughts?

**Comment by jadjoubran** [comment]
Closed in favour of #202
