### ISSUE TITLE
Incorrect routing when validation fails on a request

### ISSUE THREAD

**Issue by KevinMace** [jadjoubran/laravel5-angular-material-starter#157]
Got a bit of an unusual issue occurring with an app i'm developing. The Scenario is as follows..
- There are two routes in a group, a POST and a GET
- The POST route uses a Request to validate the submitted data
- If the validation fails, rather than return the validation error messages back to the user, the GET method is called and the controller method is returning completely irrelevant data back to the use.

This is the code being called, I have added dd() / var_dump() for debugging purposes to rule out another piece of code causing the condition.

The routes

```
$api->group(
    ['middleware' => 'api.auth'],
    function ($api) {

        $api->group(
            ['namespace' => ‘Group’, 'prefix' => ‘group’],
            function ($api) {

                $api->group(
                    ['prefix' => ‘data’],
                    function ($api) {
                        $api->post(‘create’, ‘GroupController@create');
                        $api->get('overdue', ‘GroupController@overdue');
                     }
                );

            }
        );
    }
);
```

The request doing the validation

```
<?php namespace App\Http\Requests;

use App\Http\Requests\Request;

class GroupRequest extends Request
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'month' => 'date_format:Y-m-d',
            'group_id' => 'numeric|required',
        ];
    }
}
```

The controller tied to the routes

```
<?php

namespace App\Http\Controllers\Group;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Http\Requests\GroupRequest;

class GroupController extends Controller
{

    public function overdue()
    {
        var_dump('this route');
    }


    public function create(GroupRequest $request)
    {
        dd($request->all());
    }
}
```

**Comment by jadjoubran** [comment]
Hi @KevinMace 
Thanks for posting here
What do you mean by completely irrelevant data?
Are you able to provide a dump of what's being returned?

Initially I thought this is something related to a bug with [Request Validations & Dingo api](https://github.com/dingo/api/issues/462) but I'm not sure if it's the case

**Comment by shiruken1** [comment]
@KevinMace make sure to add 'domain' => 'localhost' (or whatever's appropriate) just in case.

Took me almost 2 days to find that obscure glitch with Dingo. It's an issue that's still open.

**Comment by jadjoubran** [comment]
Thanks @shiruken1 
Would you please link us to the issue on dingo/api?
It sounds like this is something that can be fixed out of the box

**Comment by jadjoubran** [comment]
especially if @KevinMace confirms that it worked for him

**Comment by shiruken1** [comment]
Sure thing! Sorry for my delays... in the middle of a cross-country trip.

[Here you go](https://github.com/dingo/api/issues/570)

Cheers!

**Comment by jadjoubran** [comment]
Oh okay so this only happens if you're using API Domain so it's not an issue from this starter (I mean by default)

**Comment by shiruken1** [comment]
The issue I was having was that if I didn't include the domain directive,
Dingo wouldn't work at all.

**Comment by KevinMace** [comment]
Sorry I should have been clearer. Rather than dumping the data from request in the 'Store' method, it's actually returning the 'var_dump('this route')' from the 'Overdue' method. Even though at no point is the 'Overdue' method called

**Comment by jadjoubran** [comment]
@KevinMace Thanks for your reply.
Would you be able to show the equivalent Restangular code?
Or postman screenshot

**Comment by KevinMace** [comment]
I have just added the API Domain/Url parameters to my .ENV for Dingo (as per the link posted by @shiruken1 ) , but the issue is still occurring.

I'm using Postman for testing the API, this is a screenshot of the request body i'm posting..

<img width="1098" alt="screen shot 2016-02-01 at 10 38 44" src="https://cloud.githubusercontent.com/assets/1065240/12715080/2967e040-c8d0-11e5-84ab-7dfd7f206a7c.png">

The unexpected behaviour is caused If I change the value for "group_id" to a string causing the validation to fail. The URL is incorrect in the screenshot, that isn't the cause of the issue, just me trying to work too fast adding the data to postman to get you a screenshot haha.

**Comment by shiruken1** [comment]
That's the thing about the issue, @Kevin, we all had the domain in the
.ENV, but Dingo wasn't reading it. Hence having to add it to the routes
file, along with the other group parameters. i.e: ["domain" => "localhost"]
or whatever your site's domain is.

I have just added the API Domain/Url parameters to my .ENV for Dingo (as
per the link posted by @shiruken1 https://github.com/shiruken1 ) , but
the issue is still occurring.

I'm using Postman for testing the API, this is a screenshot of the request
body i'm posting..

[image: screen shot 2016-02-01 at 10 38 44]
https://cloud.githubusercontent.com/assets/1065240/12715080/2967e040-c8d0-11e5-84ab-7dfd7f206a7c.png

The unexpected behaviour is caused If I change the value for "group_id" to
a string causing the validation to fail.

**Comment by KevinMace** [comment]
@shiruken1 Thank you for clarifying what I needed to do. I have done as you said and added the domain to my route, unfortunately the issue still exists.
I'm not getting a 404 or any other HTTP errors, it's like the internal routing is getting mixed up when the validation fails.

**Comment by jadjoubran** [comment]
Hi @KevinMace 
I'm suspecting this is related to my first comment.

Please try the following and let me know:
1. Don't use request validation for now
2. Test endpoint using Postman (make sure you have valid JSON - you added an additional colon at the end which breaks it). It should work.
3. Use $this->validate and let me know if it works

if it does, then it's probably what I mentioned in my first comment

**Comment by KevinMace** [comment]
Hi @jadjoubran 

I have tried what you requested and the validation is working correctly, so it's as you said in the first comment.

Thank you for your help.

**Comment by jadjoubran** [comment]
@KevinMace no worries!
But then how did you fix it?
Have you tried following the steps mentioned on dingo?

**Comment by KevinMace** [comment]
If you're using the Dingo API and using Laravel Requests to do your validation you must extend the 

```
Dingo\Api\Http\FormRequest
```

and not the standard Laravel Request class

```
App\Http\Requests\Request
```

**Comment by jadjoubran** [comment]
Okay sounds great, thanks!
