### ISSUE TITLE
Adding new header menu

### ISSUE THREAD

**Issue by srmishra** [jadjoubran/laravel5-angular-material-starter#158]
error  "vm" is defined but never used  no-unused-vars

Plz help

**Comment by jadjoubran** [comment]
Hi @srmishra
That's only a warning from eslint
Because the variable vm is not used yet

**Comment by jadjoubran** [comment]
Here's the rule on [eslint](http://eslint.org/docs/rules/no-unused-vars.html)

You could either comment out the `var vm = this;` from the file or just disregard the warning for now

**Comment by jadjoubran** [comment]
Feel free to comment again if you're still facing this issue
Thanks!
