### ISSUE TITLE
Demo site navigation not working.

### ISSUE THREAD

**Issue by Bodom78** [jadjoubran/laravel5-angular-material-starter#16]
Noticed that clicking on the side menu items does not direct to the page.

I had to manually modify the address to see the other pages.

Firefox 39.0:   Not working
IE 11:              Not working
Chrome 44.x:  Working

**Comment by jadjoubran** [comment]
Hi @Bodom78
Thank you for the bug report!

It now works on Firefox
Can you let me know if it works on IE11? I only have Edge here and the developer tools emulation are not working

**Comment by Bodom78** [comment]
I can confirm that it's working in Firefox now.

IE11 menu now works but noticed a couple more issues.
The alert and toast buttons do not work.
Vertical alignment of menu items not centered.

Here is an image which shows the styling issue and the console error when clicking on the alert button.

![ie11-errors](https://cloud.githubusercontent.com/assets/139152/9112764/0cd94ce8-3c94-11e5-87b4-bac980f2470a.JPG)

**Comment by jadjoubran** [comment]
Hmm it seems like an upstream issue (Angular Material) with IE11..
Can you visit the following and let me know if they work for you:

Toast: https://material.angularjs.org/latest/#/demo/material.components.toast
Dialog: https://material.angularjs.org/latest/#/demo/material.components.dialog
List: https://material.angularjs.org/latest/#/demo/material.components.list

**Comment by Bodom78** [comment]
Toast, Dialog and List demos all worked fine in IE11 on the Angular Material site with the 0.10.0 release.

**Comment by jadjoubran** [comment]
Okay, I'm looking into it!

**Comment by jadjoubran** [comment]
Since I have updated to Windows 10, it's impossible to install IE11 or even enable it in Developer Tools Emulation.

Would you be able to help me a bit on this? I have a few ideas in mind that I wanted to try.

1) Can you try replacing <div> with <p> in `sidebar.html` inside `md-list-item` and see if it works on IE11?

2) Can you try removing the `"use strict";` from `landing.js` and check if toasts and dialogs work..

Thanks!

**Comment by Bodom78** [comment]
I'll have to try on Monday on my work PC.

On my laptop I've tried for about 5 hours to install the npm dependencies but they always fail with varying errors that I just cannot resolve.

**Comment by jadjoubran** [comment]
Okay thanks!

You can try [clearing NPM's cache](https://origin1tech.wordpress.com/2013/08/31/clearing-nodes-npm-cache/). This has worked several times for me when I was faced with random errors

**Comment by Bodom78** [comment]
Clearing the NPM cache was something I tried. It fixed the tar errors but now I have a heap of new ones that look like they are releated to the elixir npm dependencies.

What version of Node and NPM are you using? I will try the same on my machine.

**Comment by jadjoubran** [comment]
hmm I'm not sure if that would be related..

$ node -v
v0.12.2

$ npm -v
2.7.4

**Comment by Bodom78** [comment]
OK, I just set the site up on my wamp and worked on the already compiled files for the sake of testing.

Removing use strict from the landing module did not work. The error is actually coming from the vendor.js so I did a find and replace to remove all instances of it.

This did stop the error however the alert and toast buttons still no not work. No new errors show up.

What did you want replaced in sidebar.html?, the instructions in your post looks like it's missing from the first part.

**Comment by jadjoubran** [comment]
Hi @Bodom78, thanks a lot for helping on this issue. I'm going to create a new issue specifically for the sidebar and we'll keep this for the toast and dialog.js. I don't have an update on the toast and dialogs yet but I'm working on a new service for toasts and dialogs.

**Comment by jadjoubran** [comment]
So now everything is working on Firefox.. we still have the IE11 issue for taosts and dialogs

**Comment by jadjoubran** [comment]
It turned out to be an issue in [Angular Material #3943](https://github.com/angular/material/issues/3943)

So this should work now.. Let me know!

**Comment by Bodom78** [comment]
Nice, I can confirm alerts and toasts are now working in IE11.
