### ISSUE TITLE
Specifying a controller in the routes

### ISSUE THREAD

**Issue by shiruken1** [jadjoubran/laravel5-angular-material-starter#160]
Hey hey! Does anyone know why I can't seem to get a controller running if I specify it in the routes file?

I've tried just about everything I can think of to no avail.

Thanks!

**Comment by jadjoubran** [comment]
Hi @shiruken1 

1) are you running `gulp watch`?
2) do you have an error in your console?
3) Are you using ControllerAs? if yes are you using the correct syntax in the view
4) If you just created a new file, you might need to restart `gulp && gulp watch` for it to pick it up

**Comment by shiruken1** [comment]
Hey @jadjoubran! Thanks for taking the time.

1: Yup.
2: Nope. I get nothing.
3: Nope, I have no view.
4: Yup. Did that

Here's my route:

```
            .state('app.test', {
                url: '/test',
                controller: "testController",
            })
```

And here's the controller:

```
(function(){
    "use strict";

    angular.module('app.controllers').controller('testController', testController);

    function testController($log){
        $log.info('Here');
    }

})();
```

**Comment by jadjoubran** [comment]
hmm are you navigating to this route? /test

**Comment by shiruken1** [comment]
yup

**Comment by jadjoubran** [comment]
@jadsalhani any idea?
I think it's because you don't have a view..
Try adding a `template: 'test'` to your ui-router

**Comment by shiruken1** [comment]
Didn't work either, but what did work was adding:

```
views: {
    'main@': { template: "<div ng-controller=\"testController as vm\"></div>" },
}
```

Could this be a ui-router issue, or is it how Angular works and I'm just still too new and don't yet understand the logic behind it? :confused:

**Comment by anonymoussc** [comment]
That how it is supposed to be. Check [View Names - Relative vs. Absolute Names](https://github.com/angular-ui/ui-router/wiki/Multiple-Named-Views#view-names---relative-vs-absolute-names).

**Comment by jadjoubran** [comment]
oh makes sense..
that's because your view wasn't showing at all..
I guess if you do this it'll work:

```
views: {
    'main@': { template: "hello world" },
}
```

**Comment by jadjoubran** [comment]
It's because we have 3 views, main, header & footer
all views are named.. so `template` or `templateUrl` alone won't work (unless you fix your index.blade.php)

**Comment by shiruken1** [comment]
Actually, that's the thing... this is the only code that would get it to work, and just this. I could add the header and footer sections if I wanted, obviously, but they weren't necessary. Only this was critical:

```
views: {
    'main@': { template: "<div ng-controller=\"testController as vm\"></div>" },
}
```

This did not work, for example:

```
views: {
    'main@': { template: "<h1>Test</h1>" }
}
```

:confounded:

**Comment by jadsalhani** [comment]
@shiruken1 This is the exact way you have to do it:

```
.state('app.test', {
    url: '/test',
    views: {
        'main@': {
            template: 'Hello',
            controller: 'testController',
        }
    }
});
```

Why? Because:
- This starter project is using nested and named views, so you specify which `ui-view` you want to load, i.e. `main@`
- That said, for the controller to fire the view has to be loaded, by specifying a state without `main@`, the state is not loaded anywhere thus the controller is not called.
- Naming of the state must be `app.test` because of the `abstract: true` state app, so for ui-router to recognise it as a sub-state, it should be under `app`

PS: You can even remove the `template` part, the controller will still get called.

**Comment by shiruken1** [comment]
aaah. That makes so much more sense, now. Thank you so much!!

**Comment by jadjoubran** [comment]
Thanks @JadSalhani :D
