### ISSUE TITLE
Problem artisan

### ISSUE THREAD

**Issue by franklupo** [jadjoubran/laravel5-angular-material-starter#161]
Hi,
in current version 

> composer create-project jadjoubran/laravel5-angular-material-starter --prefer-dist

the command 

> artisan ng:feature 

generate error.

```
[InvalidArgumentException]            
Command "ng:feature" is not defined.  
Did you mean one of these?            
       ng:filter                         
       ng:service                        
       ng:page                           
       ng:component                      
       ng:dialog                         
       ng:config    
```

What the problem?
Thanks

**Comment by jadjoubran** [comment]
Hi @franklupo 
Thanks for posting here

`ng:feature` was removed in favor of `ng:page` and `ng:component` (which also replaced `ng:directive`)
The reason why is that we're encouraging Angular's community best practices

However you can just downgrade the generators in your composer.json to a version that suits your need. But this also requires that you delete your `config/generator.php` and running `artisan vendor:publish` again

Let me know if this works for you

**Comment by franklupo** [comment]
Ok perfect.

Thanks.

**Comment by shiruken1** [comment]
Quick question, @jadjoubran which version number was the last before switching? I can't seem to figure it out from the docs. Thanks!

**Comment by jadjoubran** [comment]
Apologies for the problems.. 
Check this link here
https://github.com/jadjoubran/laravel-ng-artisan-generators/releases

You're looking for version 1.5.2

**Comment by shiruken1** [comment]
Ah! There it is. Thank you so much, sorry about that.
