### ISSUE TITLE
OS X El Capitan + Laravel Homestead

### ISSUE THREAD

**Issue by odyright** [jadjoubran/laravel5-angular-material-starter#163]
RECENTLY I decide to use Laravel homestead with OS X El Capitan Althoughthe I was using the starter project without problems. Now Os x El Capitan I can not run the bower command. I installed Node, npm globaly on my mac and bower.
here in vagrant homestead i got this:

```
vagrant@homestead:~/Code/laravel5-angular-material-starter$ npm install -g gulp bower
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0
/home/vagrant/.npm-packages/bin/bower -> /home/vagrant/.npm-packages/lib/node_modules/bower/bin/bower
/home/vagrant/.npm-packages/bin/gulp -> /home/vagrant/.npm-packages/lib/node_modules/gulp/bin/gulp.js
/home/vagrant/.npm-packages/lib
├── bower@1.7.7 
└── gulp@3.9.0 

vagrant@homestead:~/Code/laravel5-angular-material-starter$ npm install 
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.7
vagrant@homestead:~/Code/laravel5-angular-material-starter$ bower install
bower: command not found
```

Also with sudo (witch is a bad method)

```
vagrant@homestead:~/Code/laravel5-angular-material-starter$ sudo bower install
sudo: bower: command not found
```

could you help to have the starter project works!

**Comment by jadjoubran** [comment]
Hi @odyright

It seems that you're missing bower. 

Run `npm install -g bower`

**Comment by odyright** [comment]
Hi @jadjoubran , yes i know that but, should i run `npm install -g bower` in my project folder before i do `vagrant ssh`or after i did it?

**Comment by jadjoubran** [comment]
I'm guessing after you run `vagrant ssh`
Let me know if it works

**Comment by odyright** [comment]
Hello, it doesn't work for me. but i opened the project folder in his path in an other tab of my terminal... all these commands work and then i ran `gulp && gulp watch`. when i returned to the first tab i ran the `vagrant ssh` , it seems to have no conflict of operation.

But what do think? am i in right way?

**Comment by jadjoubran** [comment]
@odyright unfortunately I've never worked in a VM..
maybe @rooferz can help?

**Comment by ptondereau** [comment]
Hello @odyright

When I install a npm package globally, I use root privileges (sudo) because of shared PATH. 

Npm install in or outside vagrant will give the same result on Mac OSX (not on Windows)

For fsevent error, you should take a look to issues in the dedicated github repo.

P.S I don't use Mac OSX. I use Windows only without vagrant

**Comment by jadjoubran** [comment]
Thanks for your input @rooferz

**Comment by odyright** [comment]
THANKS @jadjoubran @rooferz.
