### ISSUE TITLE
Components and Authentication

### ISSUE THREAD

**Issue by ghost** [jadjoubran/laravel5-angular-material-starter#164]
Good Day,

First thank you for such an awesome project, words cannot express how valuable a learning resource it is. In my case, namely because I had been putting of learning angular however, finding it coupled with my favourite php framework got me hooked. 

Consequently, my angular knowledge and skill are noob level, laravel semi-intermediate. Thus, I have been tackling documentation and even followed along with the screencasts, however an update to the laravel-angular-generators prompted some confusion. Namely in regards to the change of moving from the use of controllers (and directives) to components in order to get the repo angular 2.0 ready.

Thus my question is how would one create a register/login in form with Authentication using this new method. Thus, I tried to merge some of the info disclosed in the screencasts with this change and my attempt resulted in the following:

**register-form.component.js**

```
export function registerFormComponent() {
    'ngInject';

    var component = {
        restrict: 'E',
        templateUrl: './views/app/components/register-form/register-form.component.html',
        controller: RegisterFormController,
        controllerAs: 'vm',
        scope: {},
        bindToController: true
    };

    return component;
}

class RegisterFormController{
    constructor(){
        'ngInject';
        var vm = this;
        vm.starter = 'Laravel & Angular';
        //
    }
}
```

**register-form.component.html**

```
<p>
    You are using {{vm.starter}}
</p>
```

**register.html** in app/pages/register

```
<md-content class="Register" ng-controller="RegisterFormController as vm">
          <h2>Register Form</h2>
          <register-form>{{vm.starter}}</register-form>
</md-content>
```

**index.components.js**

```
import {registerFormComponent}  from './app/components/register-form/register-form.component';

angular.module('app.components')
    .component('registerForm',registerFormComponent);
```

However, on visiting the register link {{vm.starter}} is displayed as is and the value I set it to is not picked up. Where am I going wrong or have I not read up enough? Please feel free to direct me and call out any errors.

Moreover, I am trying to create something similar to/based off:

[Token-Based Authentication for AngularJS and Laravel Apps](https://scotch.io/tutorials/token-based-authentication-for-angularjs-and-laravel-app)
[Token-Based Authentication for AngularJS and Laravel Apps (continued)](http://ryanchenkie.com/token-based-authentication-for-angularjs-and-laravel-apps/)

@chenkie Thank you for the tutorials

One of the main issues I encountered when trying to incorporate the above, was leveraging the repo's folder structure/orientation with that of the stated instructions. I even tried reverting back to standard controllers however kept getting the following error when using the function:

```
//Use Satellizer's $auth service to login
            $auth.login(credentials).then(function(data) {
                // If login is successful, redirect to the users state
                $state.go('users', {});
            });
```

Error: data is defined but never used

Thank you for your time, any response will be greatly appreciated and sorry for a lengthy post.

Kind Regards

**Comment by chenkie** [comment]
You don't need to list `data` as param in the `then` method. If you leave it out and just have an anonymous function there, that error should go away.

**Comment by jadjoubran** [comment]
Hi @Mylo-92 
I'm glad that you found it useful
Thanks @chenkie for your contribution as well

1) Totally agree with @chenkie 
I'd just like to add that this is only a warning displayed by [eslint](http://eslint.org/).. it doesn't affect your js code compilation

2) in your `register.html` page template:
You just need to call the component, no need to write data inside it (they'll be removed since the component has a template)
`<register-form></register-form>`

3) {{vm.starter} is now showing: It seems that you have a javascript error..
Please run `gulp && gulp watch` and then show us the errors you see in the console

:smile:

**Comment by ghost** [comment]
@chenkie Thank you for your reply, that helped.

@jadjoubran I removed the data from the component in `register.html` however, now, all that is presented is the heading for the component i.e **Register Form**. Below is the output from my terminal, however no error occurs:

```
sudo gulp && gulp watch
[12:46:19] Using gulpfile ~/Desktop/Dev/laravel5-angular-material-starter-master/gulpfile.js
[12:46:19] Starting 'default'...
[12:46:19] Starting 'bower-js'...
[12:46:19] Finished 'default' after 105 ms
[12:46:22] gulp-notify: [Laravel Elixir]  
[12:46:22] gulp-notify: [Laravel Elixir]  
[12:46:22] Finished 'bower-js' after 3.32 s
[12:46:22] Starting 'bower-css'...
[12:46:23] gulp-notify: [Laravel Elixir]  
[12:46:23] gulp-notify: [Laravel Elixir]  
[12:46:23] Finished 'bower-css' after 1.32 s
[12:46:23] Starting 'angular in ./angular/'...
[12:46:31] Version: webpack 1.12.12
 Asset   Size  Chunks             Chunk Names
app.js  14 kB       0  [emitted]  main
[12:46:31] gulp-notify: [Laravel Elixir]  
[12:46:31] Finished 'angular in ./angular/' after 7.98 s
[12:46:31] Starting 'ngHtml2Js'...
[12:46:32] Finished 'ngHtml2Js' after 716 ms
[12:46:32] Starting 'less'...

Fetching Less Source Files...
   - ./angular/**/*.less


Saving To...
   - public/css/app.css

[12:46:40] gulp-notify: [Laravel Elixir] Less Compiled!
[12:46:40] Finished 'less' after 7.59 s
[12:46:53] Using gulpfile ~/Desktop/Dev/laravel5-angular-material-starter-master/gulpfile.js
[12:46:53] Starting 'watch'...
[12:46:53] Finished 'watch' after 121 ms
```

Thank you for the time and the help

**Comment by ghost** [comment]
@jadjoubran apologies confused the terminal with dev tools console. 

Output:

```
TypeError: angular.module(...).component is not a function
 app.js:360:2
"Error: [ng:areq] Argument 'RegisterFormController' is not a function, got undefined
http://errors.angularjs.org/1.4.9/ng/areq?p0=RegisterFormController&p1=not%20a                 nanunction%2C%20got%20undefined
minErr/<@http://localhost:8000/js/vendor.js:68:12
assertArg@http://localhost:8000/js/vendor.js:1816:1
assertArgFn@http://localhost:8000/js/vendor.js:1826:1
$ControllerProvider/this.$get</<@http://localhost:8000/js/vendor.js:9356:9
setupControllers@http://localhost:8000/js/vendor.js:8426:36
nodeLinkFn@http://localhost:8000/js/vendor.js:8468:32
compositeLinkFn@http://localhost:8000/js/vendor.js:7929:13
publicLinkFn@http://localhost:8000/js/vendor.js:7809:30
$ViewDirectiveFill/<.compile/<@http://localhost:8000/js/vendor.js:33735:9
invokeLinkFn@http://localhost:8000/js/vendor.js:9039:9
nodeLinkFn@http://localhost:8000/js/vendor.js:8533:1
compositeLinkFn@http://localhost:8000/js/vendor.js:7929:13
publicLinkFn@http://localhost:8000/js/vendor.js:7809:30
updateView@http://localhost:8000/js/vendor.js:33667:23
$ViewDirective/directive.compile/</<@http://localhost:8000/js/vendor.js:33605:11
$RootScopeProvider/this.$get</Scope.prototype.$broadcast@http://localhost:8000/js/vendor.js:16573:15
transitionTo/$state.transition<@http://localhost:8000/js/vendor.js:33015:11
processQueue@http://localhost:8000/js/vendor.js:14991:28
scheduleProcessQueue/<@http://localhost:8000/js/vendor.js:15007:27
$RootScopeProvider/this.$get</Scope.prototype.$eval@http://localhost:8000/js/vendor.js:16251:16
$RootScopeProvider/this.$get</Scope.prototype.$digest@http://localhost:8000/js/vendor.js:16069:15
$RootScopeProvider/this.$get</Scope.prototype.$apply@http://localhost:8000/js/vendor.js:16359:13
bootstrapApply@http://localhost:8000/js/vendor.js:1680:9
invoke@http://localhost:8000/js/vendor.js:4535:14
bootstrap/doBootstrap@http://localhost:8000/js/vendor.js:1678:1
bootstrap@http://localhost:8000/js/vendor.js:1698:1
angularInit@http://localhost:8000/js/vendor.js:1592:5
@http://localhost:8000/js/vendor.js:29652:5
trigger@http://localhost:8000/js/vendor.js:3069:7
defaultHandlerWrapper@http://localhost:8000/js/vendor.js:3358:3
createEventHandler/eventHandler@http://localhost:8000/js/vendor.js:3346:9
```

**Comment by jadjoubran** [comment]
@Mylo-92 No worries!
So the problem is that you're not using Angular 1.5 yet..
so you should use `.directive` instead of `.component`
And thank you for reminding me about this ;) #165 
Let me know if it solves your issue

**Comment by ghost** [comment]
@jadjoubran all is now resolved moreover, displaying as done in the screencasts. Had to remove the `ng-controller = "RegisterFormController as vm"` from `register.html` and put/define it in `RoutesConfig.js` under the relevant route. Once again, thank you for your help and time, greatly appreciated!

Kind Regards

**Comment by jadjoubran** [comment]
Great :smile:
Feel free to open a new issue if you have suggestions or comments
