### ISSUE TITLE
How to keep updates tracked while making my own changes?

### ISSUE THREAD

**Issue by ChadTaljaardt** [jadjoubran/laravel5-angular-material-starter#179]
Hello, 

I want to use this project, but how would i do it in terms of keeping updated with all the changes happening? Whats the best way to go around this?

What i mean is if you release an update that fixes a bug, if i used this in my own project i will probably have the same bug, is there a way to somehow keep updated with this?

Sorry i don't know if i'm making my questions quite clear enough, hard to explain. 

Thanks - Chad

**Comment by jadjoubran** [comment]
I think @GrahamCampbell campbell would have a great answer for that. I remember he mentioned something similar in #121

**Comment by ChadTaljaardt** [comment]
Okay yeah i see, i was just trying to figure out if there was a easier way to do this then manually going through everything and manually change everything.

**Comment by jadjoubran** [comment]
Yeah makes sense

Have you tried Graham's approach? (When I asked him how I can sync with the original laravel repo)

**Comment by ChadTaljaardt** [comment]
You mean where he gave you a link to all the diff's?

**Comment by jadjoubran** [comment]
Yeah.. I'm honestly not sure if there's a better way..
We can keep this issue open maybe someone has a suggestion

**Comment by shiruken1** [comment]
So, is my idea of having 2 repos dumb? I have the fork that I sync with Jad's, which I only use to make contributions to here from one branch, and personal modifications on another. Then I have another fork of my own fork, where I have all the development stuff for the company.

If I've overcomplicated things, I'd love your feedback! Thanks!

**Comment by jadjoubran** [comment]
I think it's fine!

**Comment by iannazzi** [comment]
I guess I am having the same issue, I am manually pulling in changes as I have branched off. I was pulling in JWT and Satellizer changes by looking through the commits to find our differences. I ignored updates like StyleCi updates. Now I am interested in just pulling in the new testing changes. In this case I am far behind. I am assuming I will clone again and then use two finder windows to move files around, just like we did in 1992. I am not awsome with git, but with such large diffences in projects git seems like not the right tool to merge changes.

**Comment by jadjoubran** [comment]
Here's how I would manage it:
After the installation steps, I'd link my new (work related) repository by running `git remote add origin` (as in just follow the installation steps to link your personal github/bitbucket repository)
then I'd add `git@github.com:jadjoubran/laravel5-angular-material-starter.git` as an `upstream`
by running `git remote add upstream git@github.com:jadjoubran/laravel5-angular-material-starter.git`

That way running `git pull origin master` would pull the changes for your own personal project
and then running `git pull upstream master` would pull the changes from this repo
This would probably cause conflicts that can be resolved manually, but then you'll be able to get the latest features, merged with your own changes.
However I doubt this would work if you've made a looot of changes to this repo.. such as changing the folder structure
I already use this technique with another kind of project so it should also work here

**Comment by shiruken1** [comment]
Yup. It does. On both my local copy of this repo, and the copy if my fork
of this repo I have a remote branch that pulls directly from this one. I
keep work and personal contributions in separate folders altogether just
for peace of mind.

The only thing I wish I knew how to do more efficiently is resolving those
merge conflicts, because indeed I have done a loooot of changes :P

Do you guys use any tools that could help me with that?

**Comment by jadjoubran** [comment]
I will mention this in the documentation for version 3.2
With this approach, you can easily pull in the changes for 3.2.x.. but it's never guaranteed that it'll work for 3.3.x
