### ISSUE TITLE
Changes to app not showing even after refresh.

### ISSUE THREAD

**Issue by yunus89** [jadjoubran/laravel5-angular-material-starter#180]
I am following screencast on getting started from laravel-angular.io. I followed exact steps but for some reasons whenever i change the code in my source code, the change is not reflected in browser even after refresh and 're-serving'.

When i try to use gulp && gulp watch, i get an error

```
module.js:85
throw e;
^

SyntaxError: Error parsing C:\xampp\htdocs\laravel5-angular-material-starter\nod
e_modules\gulp\node_modules\orchestrator\node_modules\end-of-stream\package.json
: Unexpected token
```

**Comment by jadjoubran** [comment]
Hi @yunus89 

I just tried the setup and I didn't have this error..
Could you try removing your `node_modules` folder and installing it again?

Let me know if that fixes it for you

**Comment by yunus89** [comment]
problem fixed
