### ISSUE TITLE
NotFoundHttpException

### ISSUE THREAD

**Issue by odyright** [jadjoubran/laravel5-angular-material-starter#181]
hi @jadjoubran following the tutorial V3.1, i got error: **Sorry, the page you are looking for could not be found.** 
![screen shot 2016-03-01 at 13 49 27](https://cloud.githubusercontent.com/assets/4316506/13428780/8a97a8f0-dfb4-11e5-8d2f-1c671774f201.png)

i checked my console and it shown: 
![screen shot 2016-03-01 at 13 53 39](https://cloud.githubusercontent.com/assets/4316506/13428881/25f8cd56-dfb5-11e5-84ba-205ebe53b95e.png)

Here is what my route.js => `angular/config/Routesconfig.js` looks like:

```
export function RoutesConfig($stateProvider, $urlRouterProvider) {
    'ngInject';

    var getView = function(viewName) {
        return './views/app/pages/' + viewName + '/' + viewName + '.html';
    };

    $urlRouterProvider.otherwise('/');

    $stateProvider
        .state('app', {
            abstract: true,
            views: {
                header: {
                    templateUrl: getView('header')
                },
                footer: {
                    templateUrl: getView('footer')
                },
                main: {}
            }
        })
        .state('app.landing', {
            url: '/',
            data: {},
            views: {
                'main@': {
                    templateUrl: getView('landing')
                }
            }
        })
        .state('app.create_post', {
            url: '/create-post',
            views: {
                'main@': {
                    templateUrl: getView('create_post')
                }
            }
      });
}

```

what should i do?

**Comment by jadjoubran** [comment]
Hi @odyright 
I think you just need to browse to `/#create-post` instead of `/create-post` because this is an angular route..
Let me know if it works for you so I can update the docs

Thanks!

**Comment by odyright** [comment]
yes, i tried with & without the `#` before i posted,  and nothing. but when i browse to `/#/create-post` it redirect me to the landing page

**Comment by jadjoubran** [comment]
I'm sorry I mistyped it.. could you try navigating to `/#/create-post` ?
Normally that's not an issue if you're using `ui-sref="app.create_post"` to link to a certain page

**Comment by odyright** [comment]
yes of course i thought of that,i tried it and retried, but same result. 

```
<md-content class="Page-Container DemoHeader">
    <div layout="row">
        <div flex="90" flex-offset="5" class="DemoHeader-container">
            <div layout="row" layout-align="space-between">
                <img src="img/icons/logo.svg" class="DemoHeader-logo" ui-sref="app.landing"/>
                <div layout="row" layout-align="center stretch" hide-xs>
                    <a class="DemoHeader-link md-subhead" href="">Docs</a>
                    <a class="DemoHeader-link md-subhead" ui-sref="app.create_post">Create Post</a>
                </div>
            </div>
        </div>
    </div>
</md-content>
```

and something strange i got on my terminal, an error with a comma
![screen shot 2016-03-02 at 09 34 30](https://cloud.githubusercontent.com/assets/4316506/13456256/390547e4-e05a-11e5-86f9-da694c889e02.png)

**Comment by jadjoubran** [comment]
Those warnings in the terminal are fine.. they're generated by `eslint`.. you can think o f them as tips to improve your code.

So there are no errors in your Chrome Console when you navigate to `/#/create-post`?

**Comment by odyright** [comment]
something's wrong with my code when I type the link `/#/create-post` it right back to its initial state `homestead.app/#/` so I can't analyse the Chrome Console

**Comment by jadjoubran** [comment]
yes even if it's redirecting, you can have the Chrome Console already open.. and just see if there are errors

**Comment by odyright** [comment]
hahhah i didn't know that i checked and here is what i get:
![screen shot 2016-03-02 at 10 50 23](https://cloud.githubusercontent.com/assets/4316506/13458475/57b24cd6-e065-11e5-870f-e4bd5168fb4d.png)

**Comment by jadjoubran** [comment]
So you can see that it wasn't able to find the template `app/pages/create_post/create_post.html`
Can you verify that it's there?
If not then maybe it's an issue with the generators.. so also please tell me which version you have for `laravelangular/generators` in your `composer.json`

And this assumes you've ran `gulp` of course

**Comment by odyright** [comment]
```
    "require": {
        "php": ">=5.5.9",
        "laravel/framework": "5.2.*",
        "tymon/jwt-auth": "0.5.*",
        "barryvdh/laravel-cors": "0.7.x",
        "laravelangular/generators": "~2.1",
        "dingo/api": "1.0.x@dev"
    },
```

**Comment by odyright** [comment]
i remember that i wasn't be able to run `php artisan make:controller CreatePostController --plain` instead of that i ran it without `--plain`. i don't think it had have an impact

**Comment by jadjoubran** [comment]
yeah `--plain` is now the default behavior in Laravel 5.2.. that's not the issue

Can you please do the following:

1) run `gulp` - nevermind the warnings from eslint
2) browser and verify that the following file exists: `angular/app/pages/create_post/create_post.html`.. if not try to find the path for this and let me know

**Comment by odyright** [comment]
i did `gulp` & yes the `create_post.html` file exists

**Comment by jadjoubran** [comment]
Maybe @jadsalhani has an idea?

**Comment by jadsalhani** [comment]
@odyright how did you create the create_post files? Through the generators or manually?

And can you show us their relative paths as well

**Comment by odyright** [comment]
hi @jadsalhani the create_post files has been created through the generator; here is the path: `laravel5-angular-material-starter/angular/app/pages/create_post/create_post.page.html`

**Comment by jadjoubran** [comment]
oh.. it's missing a `.page`

**Comment by odyright** [comment]
??? :anguished:  where??? pls

**Comment by jadjoubran** [comment]
so in your routes.js file, go to the `getView` function and change it to this:

```
var getView = function(viewName) {
    return './views/app/pages/' + viewName + '/' + viewName + '.page.html';
};
```

So it's a bug in v3.1 which hasn't been released yet.. I'm going to push a fix for that right now.
Thanks!

**Comment by jadjoubran** [comment]
@odyright let me know if that fixes it for you

**Comment by odyright** [comment]
ok

**Comment by odyright** [comment]
errors in my chrome console:
**GET http://homestead.app/views/app/pages/header/header.page.html 404 (Not Found)**
**GET http://homestead.app/views/app/pages/footer/footer.page.html 404 (Not Found)**

**Comment by jadjoubran** [comment]
I think you had a mix of both apps because you were working on the unstable version

Open your header.html and rename it to header.page.html
same thing for the footer

**Comment by odyright** [comment]
i already did it before, when u post the modif. in route.js but still not working.

**Comment by jadjoubran** [comment]
okay what errors do you see?

**Comment by odyright** [comment]
@jadjoubran the same i mentioned.

**Comment by jadjoubran** [comment]
so did you rename the files header.html to header.page.html?

**Comment by odyright** [comment]
yes and before i changed the header.html and renamed it to header.page.html it was no problem so my question may seem a little silly but the header & footer don't need component? like create.page.html

**Comment by jadjoubran** [comment]
you can do them with components.. but it's not necessary if they don't have any logic
so what's not working right now.. I can't understand

**Comment by odyright** [comment]
nothing appears now
![screen shot 2016-03-02 at 20 05 42](https://cloud.githubusercontent.com/assets/4316506/13473707/6d3f4516-e0b2-11e5-97a0-66c1c9d793cd.png)

**Comment by jadjoubran** [comment]
Show me the path for your `header.page.html`

**Comment by jadsalhani** [comment]
Hi @odyright 

Can you please show us the angular/app/ folder structure if it's no trouble?
As in what's inside the folders and how the pages and components are laid out

**Comment by odyright** [comment]
@jadjoubran the path is : `laravel5-angular-material-starter/angular/app/pages/header/header.page.html`

@jadsalhani here you are:
![screen shot 2016-03-02 at 20 27 39](https://cloud.githubusercontent.com/assets/4316506/13474324/6b197448-e0b5-11e5-9d0b-e86d0f544461.png)

**Comment by jadjoubran** [comment]
okay and did you run `gulp`?
For later on you could keep `gulp && gulp watch` running

**Comment by odyright** [comment]
ok thanks @jadjoubran & @jadsalhani i restarted laravel homestead & vagrant: everything is back in order with some errors: 
![screen shot 2016-03-02 at 20 50 40](https://cloud.githubusercontent.com/assets/4316506/13475017/88c1b980-e0b8-11e5-996a-07a28dde085c.png)

**Comment by odyright** [comment]
if i understand some value the assertion expected isn't defined. but i  don't know how to fix it!

**Comment by odyright** [comment]
solved, 
i just removed the directive `ng-controller="CreatePostController as vm"` I have written unintentionally in the `create_post_page.html` like that 

```
<md-content class="Page-container" ng-controller="CreatePostController as vm">

    <h1>Create Post</h1>

    <create-post-form></create-post-form>

</md-content>

```

Now all things are right, but in another step with the form "create post" i can't save the entries in database when i tried the form, could you help me?

**Comment by jadjoubran** [comment]
Just wait for the upcoming screencasts :smile:

**Comment by odyright** [comment]
ok i'm waiting :+1:

**Comment by odyright** [comment]
hi @jadjoubran with the form "create post" when i tried to post something in the form i get nothing in my database, could you help me? 
the Chrome console shows: `POST http://homestead.app/posts 404 (Not Found)`... 
I don't think that this is due to "Restangular".

**Comment by antonkomarev** [comment]
Because all the requests should be done to `/api/`if they are created using `$api` in routes file.

Try to make a call to `http://homestead.app/api/posts`

**Comment by jadjoubran** [comment]
Yes true, are you using a customPost method?
the `api` prefix has already been added in the restangular config..

**Comment by jadjoubran** [comment]
I think there was a mistake in the tutorial, if you're using `Restangular`, use `API` instead which is an instance of Restangular configured to work properly with this API.
I fixed it in the docs

**Comment by odyright** [comment]
ok thanks @a-komarev i'll try.

**Comment by jadjoubran** [comment]
@odyright the issue was in the tutorial
You can just use `API` instead of `restangular` and it'll fix it

**Comment by odyright** [comment]
thanks @jadjoubran i fixed it and now the console shows me : 
![screen shot 2016-03-07 at 11 12 46](https://cloud.githubusercontent.com/assets/4316506/13567875/d0ab8dc0-e455-11e5-8bee-77af048dde83.png)

**Comment by odyright** [comment]
i got : `POST http://homestead.app/api/posts 500 (Internal Server Error)`

**Comment by jadjoubran** [comment]
Yes it means there's an error with your backend code
If you copy pasted the code from the tutorial
You can see the errors if you click on the request in chrome

**Comment by odyright** [comment]
`message: "Type error: Argument 1 passed to App\Http\Controllers\Controller::validate() must be an instance of Dingo\Api\Http\Request, array given, called in /home/vagrant/Code/laravel5-angular-material-starter/app/Http/Controllers/CreatePostController.php on line 14"`

`status_code: 500`
but it seems that my CreatePostController.php is good

**Comment by jadjoubran** [comment]
please check #189
or try getting the updated code from the tutorial

**Comment by odyright** [comment]
ok thanks @jadjoubran i also commented the validation out and it works very well; great Tuts. 
:+1: But I want to know
1) if you've put this validation it's for a purpose. Why didn't you use the angular's validation?  
2) is this with Dingo api more secure or flexible?

**Comment by odyright** [comment]
good i see i think that you want to do things simply such as the Dingo Api's wiki said: 

> Dealing with errors when building an API can be a pain. Instead of manually building error responses you can simply throw an exception that extends from Symfony\Component\HttpKernel\Exception\HttpException and the API will automatically handle the response for you.

_that's great_ :+1:

**Comment by jadjoubran** [comment]
Actually no need to comment it out if you fix the imports

1) because validation needs to be enforced from the backend always. the front-end validation is just for the user experience

2)  It's not about security, it's about Content negotiation.. but this might be removed in the future :/ Check the content negotiation in the docs if you want to learn more

3) and yes this has already been taken care of :smile:

**Comment by odyright** [comment]
![image](https://cloud.githubusercontent.com/assets/4316506/13570562/e358ba68-e466-11e5-9668-f37b7a16f186.png)  ok I understand.

**Comment by odyright** [comment]
hi @jadjoubran 
you said: 

> Actually no need to comment it out if you fix the imports

but I have rather done a modification of the code in the `CreatePostController.php` by adding `$request` to `$this->validate();` like this: 

``` javascript
public function create(Request $request)
    {
      $this->validate(,[
        'name'  => 'required',
        'topic' => 'required',
      ]);

      $post = new Post;
      $post->name = $request->input('name');
      $post->topic = $request->input('topic');
      $post->save();

      return response()->success(compact('post'));
    }
```

to

``` javascript
public function create(Request $request)
    {
      $this->validate($request,[
        'name'  => 'required',
        'topic' => 'required',
      ]);

      $post = new Post;
      $post->name = $request->input('name');
      $post->topic = $request->input('topic');
      $post->save();

      return response()->success(compact('post'));
    }
```

what do you think ?

**Comment by jadjoubran** [comment]
That's right, thanks!
I fixed the documentation and then I noticed that someone had already suggested this edit :smile: 
But I never received a notification :/

**Comment by odyright** [comment]
u're welcome even if someone suggested it before me
sees thou not that I am progressing? :100:

**Comment by jadjoubran** [comment]
Yes you are :smile: :rocket:
