### ISSUE TITLE
Clean v3.1 displaying blank screen

### ISSUE THREAD

**Issue by antonkomarev** [jadjoubran/laravel5-angular-material-starter#184]
I've tried to install latest version. npm, bower, gulp and artisan hasn't returned any errors. Webserver started but I've got a blank screen instead of application :(

``` html
<!doctype html>
<html ng-app="app" ng-strict-di>
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="http://localhost:8000/css/vendor.css">
    <link rel="stylesheet" href="http://localhost:8000/css/app.css">
    <link href='https://fonts.googleapis.com/css?family=Lato:300,400,700' rel='stylesheet' type='text/css'>

    <title>Laravel Angular Material Starter</title>

    <!--[if lte IE 10]>
    <script type="text/javascript">document.location.href = '/unsupported-browser'</script>
    <![endif]-->
</head>
<body>

    <div ui-view="header"></div>
    <div ui-view="main"></div>
    <div ui-view="footer"></div>

    <script src="http://localhost:8000/js/vendor.js"></script>
    <script src="http://localhost:8000/js/partials.js"></script>
    <script src="http://localhost:8000/js/app.js"></script>

            <script type="text/javascript">
        document.write('<script src="'+ location.protocol + '//' + (location.host.split(':')[0] || 'localhost') +':35729/livereload.js?snipver=1" type="text/javascript"><\/script>')
    </script>
    </body>
</html>
```

And browser console:

> http://localhost:8000/views/app/pages/header/header.page.html Failed to load resource: the server responded with a status of 404 (Not Found)
> http://localhost:8000/views/app/pages/footer/footer.page.html Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by jadjoubran** [comment]
Hi @a-komarev 
Thank you so much for reporting this

Working on a fix

**Comment by jadjoubran** [comment]
Fixed in 3.1.1

**Comment by antonkomarev** [comment]
@jadjoubran Thank you! Upgraded from 3.0.x without any issues.

**Comment by jadjoubran** [comment]
@a-komarev oh cool! So you followed the upgrade guide? I'm glad to hear that

**Comment by antonkomarev** [comment]
@jadjoubran Yeah, it was useful.

Finally all the migration was done manually with cleaning up project code:
- branch of product app created;
- deleted all files in it;
- installed fresh app `v3.1` there;
- created components and pages with the names like they were named before;
- `copy + paste` required changes from `v3.0` to `v3.1` using diffs (angular + laravel).

**Comment by jadjoubran** [comment]
Sounds great :+1:
