### ISSUE TITLE
Error 500: "Method success does not exist."

### ISSUE THREAD

**Issue by yunus89** [jadjoubran/laravel5-angular-material-starter#189]
Hi @jadjoubran ,

In the docs, `CreatePostController` return `response()->success(compact('post'))` which causes internal server error. I changed it to `response()->json(compact('post'))` instead, and everything is good. 
If it's a mistake, i thing i should be corrected? Thanks.

**Comment by jadjoubran** [comment]
Hi @yunus89 
Thanks for reporting this issue

This was fixed after you started following the tutorial

You can apply the fix to your installation, check the commit that fixed it:
https://github.com/jadjoubran/laravel5-angular-material-starter/commit/8ab971aba8a874e457f86b67b62841b603e483b4

**Comment by jadjoubran** [comment]
So it has been fixed as of 3.1.2
I'm releasing 3.1.3 in a few after finalizing the remaining issues in #187

**Comment by yunus89** [comment]
Awesome!

**Comment by jadjoubran** [comment]
@yunus89 All issues fixed, if you have time I'd recommend you do the tutorial again. It should be a smooth process now.
Thanks for help and I'd love it if you can give me your feedback (here or in a new issue). If you think that there's anything that can be simplified
Thanks!

**Comment by yunus89** [comment]
Hi @jadjoubran ,

I just gone through docs, everything seems to be good.

Problems i encountered:
1. I get 500 error, message `"Argument 1 passed to App\Http\Controllers\Controller::validate() must be an instance of Dingo\Api\Http\Request, array given, called in C:\xampp\htdocs\v3.1\laravel5-angular-material-starter\app\Http\Controllers\CreatePostController.php on line 17 and defined"`

but once i comment the validation out, i get a Toast!
1. Not a problem though, just a typo or something - in the docs is written
   
   ```
   Open angular/app/components/create_post_form/create_post_form.html in your editor and add the relevant HTML form.
   ```

`create_post_form.html` should be changed to `create_post_form.component.html`

**Comment by jadjoubran** [comment]
@yunus89 hmm.. did you copy paste the controller code?
It probably happened because I didn't add the imports at the top.. so if you copy pasted that into your controller it wouldn't work as expected. I just fixed it in the docs though.

And yes thanks, I fixed that too!

Do you think the overall process can be made easier? One thing for sure is that the JWT authentication part can be made easier and will be (through #151) but what do you think regarding the rest?

**Comment by yunus89** [comment]
How easy/possible is it for one to change css framework from materialize to say twitter bootstrap. I so far haven't seen any docs explaining that?

I know some people might prefer to use one over another i.e either twitter bootstrap or angular materialize.

So my suggestion is to easy the process of transition, maybe include it in the docs as well.

**Comment by jadjoubran** [comment]
Materialize uses jQuery.
This is using Angular Material which plays nicely with Angular.

If you plan on using bootstrap, you could just remove angular-material from the dependencies and install bootstrap or angular-bootstrap.. it doesn't really matter

However if someone doesn't plan on using Angular, then it doesn't make sense for them to use this starter
