### ISSUE TITLE
How to add directives

### ISSUE THREAD

**Issue by yunus89** [jadjoubran/laravel5-angular-material-starter#194]
Hi @jadjoubran ,

In v3.1, how can one add custom directives?

**Comment by jadjoubran** [comment]
Hi @yunus89,

Directives have been migrated to components as explained the [upgrade guide](https://laravel-angular.readme.io/docs/upgrade-guide#section-angular-1-5)

If you were on 3.0, you shouldn't see any difference between components and directives
Just make sure to read all the upgrade guide and angular's documentation for components (also mentioned in the upgrade guide)
So the command would be `php artisan ng:component {name}`

Let me know if this solves your issue

**Comment by yunus89** [comment]
Hi @jadjoubran ,

Sorry, this question kinda dummy!

What's the difference between page and component in context of this starter?

**Comment by antonkomarev** [comment]
@yunus89 pages are containers for the static data and components. And components could have static or dynamic data and any kinds of application logic. You can [read about components in angular docs](https://docs.angularjs.org/guide/component).

So, page could be just 

> Hello world!

Or it could be contacts page where there will be a text:

> Our company motto is - be the best! Our contacts:

And after that you can place a component which will load a google map and display location of your office. Anything you need to use on the multiple pages could be isolated in component and attached in any moment you need this data.

**Comment by jadjoubran** [comment]
@a-komarev :smile:

**Comment by yunus89** [comment]
i will keep that in mind.

**Comment by jadjoubran** [comment]
@yunus89 Do you think it can be made clearer in the tutorial? If yes, how?

**Comment by yunus89** [comment]
Hi @jadjoubran , @a-komarev 
According to angular docs on components, link function is not available. In class defination that starter generate, how can i repalce link function in this for example

```
    angular.module('app')
          .directive('uiNav', ['$timeout', function($timeout) {
                return {
                       restrict: 'AC',
                        link: function(scope, el, attr) {
                                 el.find('a').bind('click', function(e) {
                                 var li = angular.element(this).parent();
                                 var active = li.parent()[0].querySelectorAll('.active');
                                 li.toggleClass('active');
                                 angular.element(active).removeClass('active');
                         });
                    }
            };
      }]);
```

How can i manipulate DOM using components

**Comment by jadjoubran** [comment]
I think in this scenario, you have to use directives..
You can create a directive using the same component generator.. just make sure to rename the file, controller, etc..
