### ISSUE TITLE
Angular / Laravel complete abstraction?

### ISSUE THREAD

**Issue by paulchill** [jadjoubran/laravel5-angular-material-starter#197]
Hey Guys, Quick question, i already have an angular client which talks to a Laravel sever.

Concidently i am using Angular Material so this package really caught my eye. Is there much refactoring or effort to separate them ? I wish to allow many clients to talk to the server.

Or would this be a waste using this framework due to my needs?

What do you guys think? Seems comprehensive. # @Bodom78

**Comment by jadjoubran** [comment]
Hi @paulchill 
More information on how you're doing it would make it possible for anyone here to advise whether there's a lot of refactoring involved or not (and whether it's worth it or not)

And if you have some free time, you can always try to port a few pages/controllers in a new project and see the benefits for your self

**Comment by paulchill** [comment]
@jadjoubran  Thanks for your reply.

I am using Laravel to serve simple json responses from query string parameters at the moment and an angular client is parsing and displaying this data. nothing to fancy but its quick and fast. 

This package seems to have a lot of good features.

I will what you said :)

**Comment by jadjoubran** [comment]
Sounds great!

Feel free to open a new issue if you have questions or comments :smile:
