### ISSUE TITLE
localization of laravel angular application

### ISSUE THREAD

**Issue by hunter686** [jadjoubran/laravel5-angular-material-starter#200]
@jadjoubran  hello jadjoubran.

could you telle me how do you resolve localization of the application. You will use localization of laravel or angular js (ex: ng-translate, ng-gettext). I am doing a projet using laravel5 and angular material. Your projet gives me great inspiration.  If your can make some efforts for localization, it would be really appreciated.

**Comment by jadjoubran** [comment]
Hi @hunter686 
You can use `ng-translate` or `ng-gettext` to do the localization or internationalization.. I don't really think there's anything else to be done

You just need to follow the installation instructions on their website
it's typically a bower install with a `--save` (of course you need to have `gulp watch` running) and then you can start using their filter/directive

if you find a missing component in this starter let me know.. we could always provide a recipe ( #149 ) but localization won't be provided out of the box since it won't be necessarily used by everyone

Let me know if it works for you :smile:

**Comment by hunter686** [comment]
@jadjoubran 
I have used ng-gettext and it works for me. But i have found a projet [laravel-js-lang-converter](https://github.com/micheleangioni/laravel-js-lang-converter). And then i am telling myself maybe it would be better to leave laravel to manage translation of application and use a tool to generate file .json which would be used by ng-translate in front-end. 

I would try this laravel js converter to see if i can make it.

**Comment by shiruken1** [comment]
@hunter686 What I did was use angular-translate, then created a quick method to parse the json files when outputting from the back end (emails, API responses, etc) and a CRUD that lets anyone in the team edit the text without me having to recode anything. 

Let me know if you're interested, and I'll share the code for the method I made, and how I use it.

**Comment by hunter686** [comment]
hi @shiruken1 

I am interested in it. I really want to know how you do output from backend and how your crud is made.
please share it with me

**Comment by jadjoubran** [comment]
@hunter686 Yes sounds great.. if that tool makes your life easier, it should be easy for you to set it up with this starter package

**Comment by shiruken1** [comment]
@hunter686 Here you go: [Localization](https://github.com/shiruken1/laravel5-angular-material-starter/tree/langular-localization)

The main components are:
- App/Helpers/Translations::translate()  The main code to convert the JSON's, and the function you'll need to call from any back-end method besides a controller
- App/Http/Controllers/Controller::d() the wrapper for controllers to use
- Angular/config/translate.config.js (What tells angular-translate to look for the json files as soon as you change states)
- public/lang/en/*.json (the json files)

@jadjoubran Let me know if this would be useful for a recipe! I'm still working on getting you the login recipes. Sorry for the length in delay.

Cheers!

**Comment by jadjoubran** [comment]
Hi @shiruken1 yeah sure let me know if you guys think there's some explanation that needs to go in a recipe.. something that other people could benefit from (not very specific to a particular scenario)
And don't worry about it, I should be shipping a new version with JWT and login, registration forms out of the box soon

**Comment by jadjoubran** [comment]
@hunter686 so far so good?
Please close the issue if there aren't any updates for the moment
Thanks!

**Comment by hunter686** [comment]
@jadjoubran 
yes, it's ok now!

**Comment by shiruken1** [comment]
@jadjoubran I forgot where the final destination for recipes is, but I wanted to let you know that I've added a json_lint task on my localization branch, since angular-translate is _very_ picky about the json files.

Cheers!

**Comment by bharatsoftpro** [comment]
@jadjoubran: Please help me I am also stuck in same. How to implement in angular end.

**Comment by jadjoubran** [comment]
Hi @bharatsoftpro you can follow the suggestions from @shiruken1
