### ISSUE TITLE
How to use another theme

### ISSUE THREAD

**Issue by bamboovn** [jadjoubran/laravel5-angular-material-starter#201]
Hi,
Laravel Angular is using Material theme as default. Can I use another theme (bootstrap) ?
Thanks

**Comment by ChadTaljaardt** [comment]
+1 for interest

**Comment by jadjoubran** [comment]
Yes sure, there's already a thread on that

Bootstrap alternative: #114

**Comment by bamboovn** [comment]
thank you :+1:
