### ISSUE TITLE
Out of the box JWT authentication using satellizer (Login & Registration)

### ISSUE THREAD

**Issue by jadjoubran** [jadjoubran/laravel5-angular-material-starter#202]
- [x] Setup satellizer
- [x] Configure satellizer to work with login API (sane defaults for this starter)
- [x] handle errors using ToastService
- [x] Login form using Angular Material
- [x] Register form using Angular Material
- [x] integration tests for AuthController
- [x] AuthController
- [x] Login functionality using satellizer
- [x] Register functionality using satellizer
- [x] fix expecting a token issue
- [x] **[Breaking]** update API service to use new token
- [x] test with sample protected route
- [x] Design fixes? cc/ @nicolesaidy
- [x] Demo: only local?

**Comment by shiruken1** [comment]
Let me know if I should upgrade my previous PR to 5.2 and make a new one from that, along with the Material UI for the front-end. I could pull in everything on your checklist, except for the Restangular interceptor.

All the best!

**Comment by jadjoubran** [comment]
Hi @shiruken1 
Thank you so much for your help!

I have a branch I've been working on.. it should be done by this weekend I'll share the result soon :smile:

**Comment by chojuanillo** [comment]
I look forward , as I have to implement my project . a million thanks

**Comment by ChadTaljaardt** [comment]
+1

**Comment by yunus89** [comment]
Hi @jadjoubran ,

I really need Satellizer integrated into this starter. Could you please estimate how much time will take you to complete the above tasks?

**Comment by jadjoubran** [comment]
Hi @yunus89 
I'm finally back home from a long trip :smile: 
It will be ready by the end of this week for sure

But keep in mind that you can also follow the installation guide provided by satellizer..I'll just try to polish some things to make it more accessible for everyone
Cheers

**Comment by ChadTaljaardt** [comment]
Thanks for this @jadjoubran It will be a great addition :smile:

**Comment by jadjoubran** [comment]
Halfway through :smile:

**Comment by shiruken1** [comment]
I know it's been forever, but I finally have the UI for this!

It's pretty nifty, is responsively designed, and includes landing page (which I can leave out), login with email/password, a dropdown to select a social network (with template interactivity and corresponding Angular functionality), and registration.

Do you still want it? How should I deliver it? Let me know!

**Comment by franklupo** [comment]
Great addition

**Comment by jadjoubran** [comment]
@shiruken1 Thanks for this! But don't worry the feature is almost over :smile: 
I am not doing social network login by default since this is an easy task, people would just need to follow satellizer's docs.. and not everyone would need it
I'll push the remaining fixes in the coming few days :smile:

**Comment by jadjoubran** [comment]
This is done :smile: 
I still need to design the 2 pages with @nicolesaidy
I'd love to get your feedback if anyone feels like testing it

If all goes well, I'll update the docs & record a screencast

Meanwhile, here are the steps to test:
- install latest unstable version
- php artisan migrate
- navigate to `/#/register` and create an account
- navigate to `/#/login` and login
  Mainly there are 2 pages, login & register and 2 components: login-form and register-form
  You can also take a look at the satellizer code in the components
  satellizer configuration is available in `angular/config/satellizer.config.js`

**Comment by jadjoubran** [comment]
Thanks @nicolesaidy for the design fixes :smile: 

![login screenshot](https://cloud.githubusercontent.com/assets/2265232/14049844/84d2325e-f2c0-11e5-91e9-14beee738250.png)
![register screenshot](https://cloud.githubusercontent.com/assets/2265232/14049846/84e41078-f2c0-11e5-8bec-1b30f3208b79.png)

**Comment by kujtimiihoxha** [comment]
@jadjoubran  I think #129 should be part of this implementation, what do you think ?

**Comment by jadjoubran** [comment]
Yes it will :smile: I've already updated the milestone to 3.2

**Comment by kujtimiihoxha** [comment]
@jadjoubran I think that the register form should have a confirm password field what do you think ?

**Comment by jadjoubran** [comment]
@kujtimiihoxha I've seen a lot of startups omit this field.. For the simple reason that in case a user writes a wrong one (which rarely happens, he can just reset his password) 
However it should be very straightforward if anyone wants it for his own project

**Comment by shiruken1** [comment]
Yup. The less fields the better.

We're actually omitting the password field entirely, and make them change
the password we generated for them, as soon as they finish registration.

**Comment by jadjoubran** [comment]
Documentation & screencast moved to trello board (when 3.2 becomes available)
