### ISSUE TITLE
 possible problem with autoscroll

### ISSUE THREAD

**Issue by chojuanillo** [jadjoubran/laravel5-angular-material-starter#203]
my problem is that I created two pages and move from one state to another page is overwritten at bottom for a moment. can you help me?.

I searched google and looks like it could be a problem autoscroll

**Comment by jadjoubran** [comment]
@chojuanillo I didn't quite get what the issue
Can you show a screenshot?

**Comment by chojuanillo** [comment]
thanks for your quick response. the problem is caused the transitions.less file. already resolved

**Comment by jadjoubran** [comment]
Okay great!
So do you suspect there's an issue in `transitions.less`?

**Comment by chojuanillo** [comment]
Yes I think so. my provoked me in every state change overprinting of the page at the bottom , for a few milliseconds , until it showed in its defined position, in this case at the top , but when his position was to the left, overprinting right , and so

**Comment by chojuanillo** [comment]
in all browsers . I removed the css and disappeared

**Comment by jadjoubran** [comment]
okay thanks, I'll take a look :smile:

**Comment by jadjoubran** [comment]
I couldn't reproduce it, so closing for now
