### ISSUE TITLE
Deprecated for npm

### ISSUE THREAD

**Issue by dehboris** [jadjoubran/laravel5-angular-material-starter#209]
gulp-minify-css@1.2.4: Please use gulp-clean-css
graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
graceful-fs@1.2.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.

**Comment by jadjoubran** [comment]
Hi @dehboris 
Thank you for opening an issue

Unfortunately all of these packages are not directly referenced in this starter.. as in they are a dependency for other packages that we are using
Thus we cannot fix these warnings

But they shouldn't be an issue.. almost all packages that you install using npm have warnings :laughing:
