### ISSUE TITLE
Commands

### ISSUE THREAD

**Issue by GrahamCampbell** [jadjoubran/laravel5-angular-material-starter#21]
You have a "Command" "listeners", but not a Command folder?

**Comment by GrahamCampbell** [comment]
Also, I'd recommend renaming listeners to handlers, a bit like I do in StyleCI.

**Comment by jadjoubran** [comment]
hmm I ended up with these folders when migrating from 5.0 to 5.1..
- So I'm missing a `Commands` folder? (I think you had a typo)
- and You're suggesting that I rename `listeners` to `handlers`

**Comment by jadjoubran** [comment]
@GrahamCampbell awaiting your feedback

**Comment by jadjoubran** [comment]
I can't see what's wrong here.. I even compared to Laravel's own architecture and fount out that they both match.

Feel free to reopen if you have more info
Thanks!

**Comment by GrahamCampbell** [comment]
Look at the StyleCI codebase.

**Comment by GrahamCampbell** [comment]
It makes no sense to have a handler for commands when there are no commands to handle.
