### ISSUE TITLE
Components not work

### ISSUE THREAD

**Issue by dehboris** [jadjoubran/laravel5-angular-material-starter#210]
Hi, 
I create a CreatePostFormComponents

angular/index.components.js
  2:9  error  "CreatePostFormComponent" is defined but never used  no-unused-vars

The any page don't work, after inspect i see

angular.js:68 Uncaught Error: [$injector:modulerr] Failed to instantiate module app due to:
Error: [$injector:modulerr] Failed to instantiate module app.components due to:
TypeError: key.charAt is not a function

**Comment by jadjoubran** [comment]
Hi @dehboris 

1) as mentioned in the screencasts and documentation, those errors are only meant for code quality and they're provided by [eslint](http://eslint.org/)

2) You have a regular javascript error in your code.. on the `key.charAt`

**Comment by dehboris** [comment]
No, I have not often that error. This is for the first time.
How can do? 
Because of this error any of my page is displayed. It's just white

**Comment by jadjoubran** [comment]
Look into your chrome console for the exact location of this error `TypeError: key.charAt is not a function`
You can often click on it on the right and it'll open the source of the error
