### ISSUE TITLE
Passing in data to views using ui-router example

### ISSUE THREAD

**Issue by iannazzi** [jadjoubran/laravel5-angular-material-starter#211]
Jab, I'm stuck passing data into the views. 

Following the ui-router guide as a side project worked fine, however implementing the ui-router examples in this project is not working out so well. I am having a hard time finding documentation on how you turned a router into a class, so I thought I would go for a basic example to get things working.

Breaking into a simple example.. If I wanted to pass data to the landing page

I would first add a controller to the landing page state

```
        .state('app.landing', {
            url: '/',
            views: {
                'main@': {
                    templateUrl: getView('landing')
                }
            },
            controller: function($scope) {
                $scope.items = ["A", "List", "Of", "Items"];
            }
        })

```

and then try to list them out in landing.page.html:

```
<div class="container">

    <h3>List of State 1 Items</h3>
    <ul>
        <li ng-repeat="item in items">{{ item }}</li>
    </ul>

</div>
```

I have no items printed in the list. Additionally no errors. Can you help?

**Comment by jadjoubran** [comment]
Hi @iannazzi 
You are right, if you try to follow ui-router's tutorial it won't work.. that's just because we're using named routes
so, you need to fix your code like this:

```
.state('app.landing', {
            url: '/',
            views: {
                'main@': {
                    templateUrl: getView('landing'),
                      controller: function($scope) {
                         $scope.items = ["A", "List", "Of", "Items"];
                     }
                }
            }
        })
```

Also, I'd recommend that you use the controllerAs syntax - but you probably pasted this to make the scenario easier - if not, let me know and I'll be glad to help :smile:

**Comment by iannazzi** [comment]
@jadjoubran 
Thank you, works like a charm.  Found the named routes docs here [https://github.com/angular-ui/ui-router/wiki/Multiple-Named-Views](https://github.com/angular-ui/ui-router/wiki/Multiple-Named-Views)

Onto the next issue!
