### ISSUE TITLE
Update Dialog generator

### ISSUE THREAD

**Issue by jadjoubran** [jadjoubran/laravel5-angular-material-starter#216]
They shouldn't generate controllers anymore
Dialogs would only use components

**Comment by jadsalhani** [comment]
@jadjoubran Shouldn't this be in the ng-generators repo?

**Comment by jadjoubran** [comment]
@jadsalhani yes it should.. but since planning for the 3.2 milestone is happening here and people are more active here, I usually open those issues on this repo and then close them with commit messages from the other one

**Comment by jadsalhani** [comment]
:+1:

**Comment by jadjoubran** [comment]
btw @jadsalhani I just remembered that the `DialogService.fromTemplate` needs to be changed as well

**Comment by jadjoubran** [comment]
@jadsalhani make sure to re-publish the config file from vendor before testing this. I've made a lot of updates

**Comment by jadjoubran** [comment]
Also @jadsalhani please check if angular-material has an updated dialog template as of 1.1.x

**Comment by jadjoubran** [comment]
After discussing with @jadsalhani, this doesn't seem feasible in the current version of Angular and Angular Material => as in without using controllers
If anyone needs to use it, I think you can pass your own controller via the `DialogService.fromTemplate` options argument
