### ISSUE TITLE
blank screen

### ISSUE THREAD

**Issue by teslaji** [jadjoubran/laravel5-angular-material-starter#220]
after all install and build, it throws blank screen. 
tried all troubleshooting and complete re-install.
but problem persists.
This is really embarrassing for me ! :(

**Comment by jadjoubran** [comment]
Hi @teslaji 
Did you run `gulp && gulp watch`?
Did you check your `Chrome console` for errors?

**Comment by teslaji** [comment]
Issue got resolved.
I had to delete node_module and redo npm install.
braceful-expansion module was throwing module not found error.

also coming from MEAN stack I thought server fires up just by  `gulp` which was not the case here.
Thanks.
