### ISSUE TITLE
Auto generate tests for components and services

### ISSUE THREAD

**Issue by jadjoubran** [jadjoubran/laravel5-angular-material-starter#221]
As suggested by @kujtimiihoxha it would be nice if `artisan ng:component` auto generated a test file that has a sample `ngDescribe` file..
Also we can do the same for services
I'd also add that this can be disabled by a flag in `config/generators.php`
- [x] generate tests for component with correct ngDescribe
- [x] add 2 flags to config for tests: components & services
- [x] only generate component test if flag is enabled in config
- [x] add `--no-spec` support
- [x] generate tests for services with correct ngDescribe
- [x] only generate service test if flag is enabled in config
- [x] add `--no-spec` text
- [x] test
- [x] tag new release after #224 
- [x] create remaining tests folder structure and add `.gitkeep` (after merging #219)
- [x] update dependency
- [x] publish new vendor

**Comment by shiruken1** [comment]
Awweeesome! I would really appreciate this, because I still can't make
heads or tails of Angular testing.

Thanks @kujtimiihoxha !
