### ISSUE TITLE
Rename RoutesConfig

### ISSUE THREAD

**Issue by kujtimiihoxha** [jadjoubran/laravel5-angular-material-starter#222]
I think we should rename `RoutresConfig.js` to `routes.config.js` so we maintain  the naming convention for all config files.

**Comment by jadjoubran** [comment]
Yes indeed, but first let's double check with @JadSalhani (author if this fike) if there is a reason behind this naming

**Comment by jadsalhani** [comment]
:+1: Must have missed it when adding the fix

**Comment by kujtimiihoxha** [comment]
@jadjoubran Don't forget to change [index.routes.js](https://github.com/jadjoubran/laravel5-angular-material-starter/blob/master/angular/index.routes.js), also I would suggest to completely remove `index.routes.js` and add the routes configuration to the `index.config.js` as all other config files.

**Comment by jadjoubran** [comment]
Woups you're right
And yes I totally I agree I'll fix it
