### ISSUE TITLE
Blank Page on fresh install

### ISSUE THREAD

**Issue by makokhavictor** [jadjoubran/laravel5-angular-material-starter#229]
I am getting a blank page after installing the starter, i dont know why.
This what i am getting on viewing the console
![6561e1e0-f5ad-11e5-8a16-487fa74b02e9](https://cloud.githubusercontent.com/assets/17508889/14104383/99081cbc-f5ad-11e5-8d28-1100af269a84.png)

I am a newbie in this, please help

**Comment by jadjoubran** [comment]
Hi @makokhavictor 
Did you run `gulp && gulp watch` after the installation?
If not give it a try.. it should fix the issue

**Comment by makokhavictor** [comment]
I have tried <code>gulp && gulp watch</code> and this is what i get on my cmd
![image](https://cloud.githubusercontent.com/assets/17508889/14104796/c237c39c-f5af-11e5-8ecb-3c3f5582b4d0.png)

Thanks for replying

**Comment by jadjoubran** [comment]
Your `npm install` might have failed.. try running `npm install` again and then run `gulp && gulp watch` again

**Comment by makokhavictor** [comment]
Alright @jadjoubran , Let me try it. Thank you once more

**Comment by jadjoubran** [comment]
Sure :smile: 
Let me know how it goes
Also have you checked the screencasts? I think they'll save you a lot of time debugging

**Comment by makokhavictor** [comment]
I sure will @jadjoubran 
I am Using the Screencasts as my guide

**Comment by makokhavictor** [comment]
This is what i get after doing a fresh <code>npm install</code>
![image](https://cloud.githubusercontent.com/assets/17508889/14105061/dfd03cac-f5b1-11e5-9ff5-bc5b8362d2d8.png)

I think there is a problem with how i am installing it. I am using the install guide on https://laravel-angular.readme.io/docs/install

**Comment by jadjoubran** [comment]
@makokhavictor these are warnings.. keep it running and show me a screenshot of the last thing it outputs

**Comment by makokhavictor** [comment]
this is the last section that was left out
![image](https://cloud.githubusercontent.com/assets/17508889/14105126/47422990-f5b2-11e5-9bee-ed0f52854658.png)

**Comment by jadjoubran** [comment]
Okay looks good.. just make sure to run `gulp` before `artisan serve` so that it can compile your assets

**Comment by makokhavictor** [comment]
Same problem when running `gulp` before `artisan serve`
Or i should try and do a fresh installation again

**Comment by makokhavictor** [comment]
Or there is something i am doing wrong?

**Comment by jadjoubran** [comment]
hmm.. try the following
remove your `node_modules` folder and then run `npm install` again
I'm trying to install it manually to see if I get the same issue

**Comment by makokhavictor** [comment]
Ok im on it, right away

**Comment by jadjoubran** [comment]
Also let me know which `node` and `npm` versions you have
by running `node -v` and `npm -v`

**Comment by makokhavictor** [comment]
my node version is `v4.4.0`
my npm version is `2.14.20`

**Comment by jadjoubran** [comment]
If the error persists, I'd recommend that you upgrade to `npm` 3
but let's see where this goes.. we might need to update the documentation accordingly

**Comment by makokhavictor** [comment]
Thank very much @jadjoubran lemmi wait till npm install finishes, if it does not work, i will upgrade to `npm` 3 and see how it goes. 
I really appreciate your help

**Comment by jadjoubran** [comment]
@makokhavictor everything went successful on my end
Keep me posted

**Comment by makokhavictor** [comment]
Alright @jadjoubran .I think the problem might be my `npm` version
Let me do the updates and then do a fresh install of the same
Thank you very much

**Comment by jadjoubran** [comment]
Sounds great!
Btw I guess you can update `npm` by just running `npm update -g npm` (sometimes you need to run it twice)
but if you have another tutorial/preferred way then nevermind this :smile:

**Comment by jadjoubran** [comment]
@makokhavictor any updates on this?

**Comment by makokhavictor** [comment]
Hey @jadjoubran , sorry i was caught up somewhere. Thank you for your help, the problem was that i had to update my `npm` to `version 3` and now it works perfectly as expected.
You are the best, and i give the starter a 10 out of 10

**Comment by jadjoubran** [comment]
I'm glad to hear that it works for you and that you're enjoying working with this starter :smile: 
Feel free to open a new issue if you have any comment or suggestion
Also make sure to star the repo
