### ISSUE TITLE
Suggestion for renaming partialsModule

### ISSUE THREAD

**Issue by kujtimiihoxha** [jadjoubran/laravel5-angular-material-starter#230]
@jadjoubran  I would suggest to rename the `partialsModule` to `app.partials`. If that is OK for you I could submit a pull request for that .

**Comment by jadjoubran** [comment]
Sounds great :+1: 
Don't forget the gulp task changes :smile: 
Thanks!

**Comment by kujtimiihoxha** [comment]
Done. :wink:
