### ISSUE TITLE
Fix failing tests

### ISSUE THREAD

**Issue by jadjoubran** [jadjoubran/laravel5-angular-material-starter#232]
travis is having issues installing node modules

**Comment by jadsalhani** [comment]
Maybe run a build removing the file that's causing the issue? From the looks of the error log we could try

> moving it away

and then seeing if it works

**Comment by jadjoubran** [comment]
@jadsalhani I didn't quite get what you mean
`-npm ERR! EEXIST, open '/home/travis/.npm/e2c9c17d-is-npm-lodash-3-10-1-package-tgz.lock'`
this is the error right?

**Comment by jadsalhani** [comment]
@jadjoubran yeah, so maybe we can add to the  `before_script` something like

`rm -rf /home/travis/.npm` or `rm /home/travis/.npm/e2c9c17d-is-npm-lodash-3-10-1-package-tgz.lock` and see if it clears it up

**Comment by jadjoubran** [comment]
but travis always starts on a fresh machine..

**Comment by jadjoubran** [comment]
no?

**Comment by jadjoubran** [comment]
According to [this issue](https://github.com/npm/npm/issues/6309) it seems that this is a lock file created during the installation

**Comment by jadsalhani** [comment]
Yeah..
Maybe after the last snapshot something went wrong and a file wasn't cleaned up properly?

**Comment by jadjoubran** [comment]
Let's give it a shot

**Comment by jadjoubran** [comment]
Woups

**Comment by jadjoubran** [comment]
maybe node needs to be updated?

**Comment by jadsalhani** [comment]
Yeah I noticed the node version is very low (0.10), maybe try running it on Node 4 or something like that?

**Comment by jadjoubran** [comment]
Yeah I guess that's the issue, someone reported a similar issue a few days ago
