### ISSUE TITLE
Pacakges big application

### ISSUE THREAD

**Issue by franklupo** [jadjoubran/laravel5-angular-material-starter#235]
Hello,
My application is divided into packages how can I integrate components pages and routes in angular?

Thank you
best regards

**Comment by jadjoubran** [comment]
Hi @franklupo 
Can you please elaborate more?

**Comment by franklupo** [comment]
Hi @jadjoubran 
For example, I created packages in laravel before I used the view with blade now I would like to use components and pages with angular material.

How can I do?

**Comment by jadjoubran** [comment]
I am sorry but this is still ambiguous..

**Comment by franklupo** [comment]
How can I publish the components inside a package in partialsModule?

**Comment by jadjoubran** [comment]
If I understand you correctly:
The components you write will be automatically added to partialsModule (which was recently renamed in to `app.partials`)
If you want to change the config for that, you can find it in `tasks/ngHtml2Js.task.js`

**Comment by franklupo** [comment]
ok thanks
