### ISSUE TITLE
Enhancement idea 

### ISSUE THREAD

**Issue by kujtimiihoxha** [jadjoubran/laravel5-angular-material-starter#243]
I think we could use Ecmascript 6 decorators to eliminate the need of registering the config files and components, routes etc.., also this would make it later easier for users to switch to angular 2. I have implemented this in [kujtimiihoxha/laravel-ng-ts](https://github.com/kujtimiihoxha/laravel-ng-ts.git) , my solution uses TypeScript but it can be easily implemented in JavaScript. 

Example:

``` javascript
    @Component({
            selector: "header",
            templateUrl: "./views/components/header/header.template.html"
        }
    )
    @Inject("App.Core.Services.AuthService", "$state")
    class HeaderComponent {
        constructor( authService,  $state) {
            this.user = authService.getCurrentUser();
        }
        private logout() {
            this.authService.logout().then(() => {
                this.$state.go("auth.login");
            });
        }
    }
```

If you want I could submit a pull request with my solution. 

BTW, If you have time take a look at the repository mentioned and tell me if you have any suggestions.(it is still a work in progress).

**Comment by jadjoubran** [comment]
Hi @kujtimiihoxha 
Thank you for the feature suggestion!
I don't think Decorators are available in EcmaScript 6.. if I remember correctly they were postponed to ES7

maybe can also get @jadsalhani's opinion on this?

I really love this.. I'm also very fond of decorators.. but my initial thought would be that it's better to keep it as is for 3.2.. which should be the last major version for Angular 1.5.. Since we should obviously start working on an Angular 2 version soon
What do you think?

**Comment by jadjoubran** [comment]
And btw sure, I'll send you my feedback in a few :smile:

**Comment by jadsalhani** [comment]
Hi @kujtimiihoxha 

This looks really great! I'm a hardcore TypeScript/ES6 fan (coming from a Java background :D) and the solution you did really embraces the awesomeness of TypeScript and ES6

I took a look at your starter as well, Kudos and awesomely written TypeScript code! :dancer: 

Now regarding the integration with Laravel-Angular, as @jadjoubran said, it's better to stick with the Angular 1.x syntax. Already for some who use this starter Angular is not very evident, and the starter is being used as a learning tool for both Angular and Laravel.

We added ES6 syntax to enable the use of the latest JavaScript features, but pushing it more would defeat a bit the purpose of AngularJS bootstrapping.

Once we start the Angular 2 version of the starter though, we'd love your contribution!

**Comment by kujtimiihoxha** [comment]
@jadjoubran Ok than , I just loved this solution that's why I proposed it, I really like angular 2 and how the syntax looks , but unfortunately it lacks the plugins that angular 1 has, that is the only reason I still use angular 1, and I wanted to make it look and feel more like angular 2. I would be very interested in contributing to the angular2 branch of this starter :wink: 

@jadsalhani  Thank you so much, I also come from a Java background  and I like my variables to be what I tell them to bee ahaahha :smile: that's why I love TypeScript, I look forward to helping with the angular 2  version :wink: , Also you are welcome to contribute and suggest ideas on laravel-ng-ts :wink: . 

Again thank you very much, I will close this issue.

**Comment by jadjoubran** [comment]
@kujtimiihoxha I just ran a fresh installation of your project
I don't have any comments for the moment since I haven't ventured a lot into typescript yet.. I'll let you know in case there's anything :smile:

**Comment by kujtimiihoxha** [comment]
@jadjoubran  Thank you very much, I am currently preparing a github page for the project that will host the docs, maybe it will help people that are not very familiar with TypeScript, I am searching for a front end designer that is willing to contribute in the design of the views and I hope this will bring new features to the project.

Again thank you very much for the time :wink:

**Comment by jadjoubran** [comment]
Sure, good luck :smile:
