### ISSUE TITLE
Looking for testimonials

### ISSUE THREAD

**Issue by jadjoubran** [jadjoubran/laravel5-angular-material-starter#244]
@nicolesaidy is working on a testimonials section design for the landing page

Is anyone interested in submitting a testimonial?

If yes, copy paste and fill this template

**name**: your full name
**picture** (head shot): link or github avatar link
**testimonial**: Maximum 30 words
**link to your github**: yes/no

**Comment by shiruken1** [comment]
Name: Andres M.

Picture:
https://media.licdn.com/mpr/mpr/shrinknp_400_400/AAEAAQAAAAAAAAaJAAAAJDVjMmMwNDFlLTdiMmUtNGJhMC04OWUwLWEwN2Y0Yjg0YmQxNg.jpg

Testimonial: The main reason I chose this for my current project was the
leadership. Not only have they created an amazing boilerplate, but it's
been super friendly and professional on all fronts!

**Comment by ChadTaljaardt** [comment]
Name : Chad Taljaardt
Picture: https://scontent.fman2-1.fna.fbcdn.net/hphotos-xpt1/v/t1.0-9/472_1234079933273774_6540061379692382293_n.jpg?oh=b832b6aaf9c6599ffaace4a176a3efd8&oe=577DDC88

Testimonial: One of the best Boilerplate for web developers out there, using both of the top technologies together seamlessly with very friendly and knowledgeable leadership

Link to Github : yes

**Comment by jadsalhani** [comment]
**name**: Jad Salhani
**picture** (head shot): https://www.facebook.com/photo.php?fbid=10151622826114721&l=d75ac2ff87
**testimonial**: One of the fastest ways to bootstrap an angular webapp with a dev-ready backend. I've used it in many projects, and contributing to it with the help of Jad really improved my development skills
**link to your github**: yes

**Comment by kujtimiihoxha** [comment]
**name**: Kujtim Hoxha
**picture**: https://scontent-fra3-1.xx.fbcdn.net/hphotos-xfp1/v/t1.0-9/12938342_1085182134878265_7120380148377366675_n.jpg?oh=ca29217cbec260b54ae4b92e35ea6a81&oe=577418B2
**testimonial**: I think this project is one of the best starting points for developers that are beginning to learn angular and laravel. Keep up the good work.

**link to you github**: yes

**Comment by jadjoubran** [comment]
Thanks everyone :D
