### ISSUE TITLE
Data between components

### ISSUE THREAD

**Issue by flick36** [jadjoubran/laravel5-angular-material-starter#247]
Hi, it might not be a starter issue, but im facing this problem, i've created 2 components, one it's a mdSidenav, and the other one it's a toolbar, the toolbar its my header and the sidenav it's in my main i'm creating an admins dashboard, so i want to be able to close the sidenav with a button on  the toolbar i can do that by cllaing the service $mdSidenav(component) but in the toolbar i need one variable to evaluate an expression in the sidenav so how can i achieve that? any idea?

heres a codepen of what i want ot achive: http://codepen.io/anon/pen/XbVyww click on the Toogle left,

but as i say i have 2 components, so i can't share a variable that way

**Comment by jadjoubran** [comment]
The cleanest solution for this would be to create a service. Services are ideal for communication between components in this kind of scenarios.

If the components were nested (not in this scenario) then angular 1.5's `require` can be used

Let me know if the service works for you :smile:

**Comment by flick36** [comment]
Hi, i've already tried to use a service but i need to bind the variable, and when i change the variable making click in the button on the toolbar, it doesnt update in the sidenav controller.

**Comment by jadjoubran** [comment]
I think this is the issue:
In your view, instead of using `ng-if="isOpen"` you need to bind it to the service value
`ng-if="SidebarService.isOpen` or `ng-if="SidebarService.getIsOpen()"`

**Comment by flick36** [comment]
I'm having some unexpected behavior, if i call the function in the controller it does show me de state, for exmaple if i click de button in the toolbar, and i change the state to true, and then console log the state it does change everytime, but if i use it in the DOM it doesnt work.

**Comment by flick36** [comment]
I might gonna need a factory but the angular generators doesnt have a generetor for this ones, any ide on how to implement factories?

**Comment by teodoriu** [comment]
I had the same problem a few days ago, This is what i did:
- created a service with the functions

`mdSidenav_isOpen, mdSidenav_toggleVisibility, mdSidenav_open, mdSidenav_close`
- added in .run 

`$rootScope.service= serviceService;`
- then in component construct added

`this.service= serviceService;`
- in template i have

`ng-click="vm.service.mdSidenav_toggleVisibility('left')"`

**Comment by flick36** [comment]
Yes @BTeodorWork  that did the trick, thank you! 

Edit: it depends on how you declare your variables and functions in the service, but there's no actual need on using the $rootScope, but thank you again for the tip!

**Comment by jadjoubran** [comment]
@flick36 there is a generator for services not factory
`artisan ng:service TimeDifference`
