### ISSUE TITLE
[Pull request] Create pages in subfolders

### ISSUE THREAD

**Issue by flick36** [jadjoubran/laravel5-angular-material-starter#249]
Hi this is just an enchance feature that i think it makes sense, it's about the angualr generators, they're awesome! but if we can create them into subfolders, like for example i have a page in page/page.html, but i have a ui view there, that calls a nested view that i only need in that page, i woul like to have something like page/views/view.html, insted of having that view in the same place i have my other important pages of the project, i've seen this folder structure in almost every theme i've tried and to me it makes sense but well i guess it's a matter of taste

**Comment by shiruken1** [comment]
What about making the nested view into a directive?

**Comment by flick36** [comment]
It's the same thing, we can't create directives with the php artisan generator, it was replaced with the component one, we can just rename the things that generators create but it's a tiny little more work, besides if we create them as directives that implies creating another sibling folder of the pages one, and when you are editing that view that has the nested view you have to go back to the directive folder, and find among every other directives you may have and find the one that it's required from the page view, instead we can just ok, i'll create this view inside this page cause it's where i used it not anywhere else

**Comment by jadjoubran** [comment]
Hi @flick36 
If I understand you correctly, you mean you want to support the following command?

`artisan ng:page accounts/login` right?
and same for components

If this is what you mean and you can send a Pull Request to https://github.com/jadjoubran/laravel-ng-artisan-generators it would be great :smile:

**Comment by flick36** [comment]
Sure give me a couple of days and i'll submit a PR

**Comment by jadjoubran** [comment]
Sounds great, thanks 😄

**Comment by flick36** [comment]
[Made a pull request](https://github.com/jadjoubran/laravel-ng-artisan-generators/pull/26#issue-150087791)

**Comment by jadjoubran** [comment]
Available with a `composer update laravelangular/generators` ;) thanks @flick36!
