### ISSUE TITLE
Error report when input data validation fails

### ISSUE THREAD

**Issue by vampire1306** [jadjoubran/laravel5-angular-material-starter#250]
I want to validate users' input data whether it's too short or too long, then alert them. Just like the demo [here](https://material.angularjs.org/latest/demo/input).
But the error message does not hide after I correct my test input.
My code is below:

```
<form name="registerForm">
    <md-input-container  class="md-icon-float md-block">
        <label>Username</label>
        <md-icon><i class="material-icons">person</i></md-icon>
        <input required md-maxlength="7"  ng-model="vm.username" name="username">
        <div ng-messages="registerForm.username.$error">
            <div ng-message="required">Name is required.</div>
            <div ng-message="md-maxlength">The name has to be less than 30 characters long.</div>
        </div>
    </md-input-container>
</form
```

I try to copy & paste the demo code for test, but it results the same.
[Here](http://2.pik.vn/201664cc5814-563f-4057-88ad-9a17a68afb7b.png)'s the test result:

**Comment by jadjoubran** [comment]
Hi @vampire1306 
Have you included `ng-messages`? (just double checking)
This is definitely related to `ng-messages`.. if you can provide a codepen, then re-open the issue so maybe someone can help!

Cheers
