### ISSUE TITLE
Moving from Laravel 5.2 to Laravel-Angular Material Starter

### ISSUE THREAD

**Issue by Akikev** [jadjoubran/laravel5-angular-material-starter#253]
Hello!

I have tried to upgrade my current project from Laravel 5.2 to Laravel-Angular Material Starter, but there is nothing in the docs related to this operation.

Is this as simple as adding the different dependencies and configuring them (Elixir, Angular, structure…), or are there other changes like in the Laravel core?

Thank you.

**Comment by jaredb7** [comment]
I recently did this this to one of my projects, fairly straight forward as my project is still in its infancy and I already had Dingo API integrated and had already had Laravel generate the User Auth.

_Need to marry up dependencies from_
bower
composer
node modules package

_You need to carry across configs (sitting in the root directory)_
karma
webpack
elixr
gulpfile (or merge your own changes into this)

_carry across folders_
public/img (for landing page images)
angular
tests
tasks (for gulp)

Follow instructions for the the DingoAPI package
Basically covers installing Providers and configuring a key

_Laravel Core changes, Inspect and merge across_
/app/config/app.php (check ordering of of ResponseMacro & API providers)
/app/config/generators.php
/app/config/auth.php
/app/config/cors.php
/app/Http/routes.php
/app/Http/Controllers/AnglarController.php
/app/Http/Controllers/Controller.php
/app/Http/Kernel.php
/app/providers/ResponseMacroServiceProvider.php
/app/Http/Controllers/Auth/AuthController.php 

_Carry over/merge_
/resources/views/unsupported_browser.blade.php
/resources/views/index.blade.php

also check the X_000000_create_users_table migration as the rememberToken was removed.

That's how I did it, 
You could also do it the other way, start with Laravel Anglar starter and move your controllers/models ect over into it.

I found it pretty easy to move across but then again my project is essentially a shell after deciding to restructure everything.

**Comment by jadjoubran** [comment]
Hi @Akikev 
You can follow @jaredb7's awesome answer!

If you can give more info regarding your own project (do you have an API, how many endpoints, do you want to migrate the view, is it written in angular, how many views, etc..) we might be able to give you a more in depth answer!

**Comment by jadjoubran** [comment]
Feel free to re-open if you have more info 😄
