### ISSUE TITLE
Changes to Angular Tests not taking effect in actual testing?

### ISSUE THREAD

**Issue by jaredb7** [jadjoubran/laravel5-angular-material-starter#254]
I'm not sure if this is bug or configuration issue... but if I change a test to fail or build my tests up, any changes or additional tests added aren't seen by jasmine/test runner.
gulp does see all the file modifications and reruns the tests over and over, except it seems to be running tests as they were at the time I did gulp && gulp watch.

So if I start out with 8 tests, add another 4, as I'm modifying the test, gulp is seeing the file change but the number of tests passing stays at 8/8

Example of not seeing test modification
**eg, check title to not be empty**
`it('check site title not empty', () => {
            var title = deps.element.find('h3');
            expect(title.text()).not.toBe('');
        });`

**if I change the test so it fails simply by removing not, it still passes**
`it('check site title not empty', () => {
            var title = deps.element.find('h3');
            expect(title.text()).toBe('');
        });`

It still passes, as if its still rerunning the original block.

I have to rerun gulp && gulp watch for it to refresh and then if I alter my component template or whatever the test now fails as expected, this is frustrating and slow.

I'm new to Angular and I'm also not sure if it maybe something in my dev environment (Homestead) or I'm doing something wrong?

Help/thoughts appreciated.

**Comment by jadjoubran** [comment]
Hi @jaredb7 
Thanks for reporting this. I'll check to see if I can reproduce it and then hopefully hunt it down

**Comment by jaredb7** [comment]
I did a bit of investigating, and found that the test bundle file (/tmp/<hash>.browserify) wasn't being updated with the tests (if I 'vi' the file I can see my navbar tests haven't changed). The file was being modified (file modify timestamp changes) though.

I had had a quick look at karma-browserfy and it mentioned to set watchify poll for finer change detection. I remember having to do this also when I was playing with VueJS, for some reason it wouldn't always see changes.

> Watchify Config
> 
> You can configure the underlying watchify instance via config.watchify. This is helpful if you need to fine tune the change detection used during autoWatch=true.
> 
> ```
>         watchify: {
>             poll: true
>         },
> ```

I think this may be just a edge case issue with Homestead or just that specific environment.

After adding those lines into karma.config.js test's refresh and reflect the changes expected.

**Comment by jadjoubran** [comment]
Actually you're right, I wasn't able to replicate your issue on my machine..
so if no one else bumps into this, let's keep it as is
Thanks!
