### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by flakerimi** [jadjoubran/laravel5-angular-material-starter#258]
Does it have a roadmap of what will be in. I was looking on trello cards but can't find the future, only the past :)

What I would like to have is a simple Acl Gui and A sidebar for custom modules. Since its starter, I should  jump and start prototyping my app. 

[Respond](http://respondcms.com/) has a great admin interface, It would be great to have something like that.

**Comment by flick36** [comment]
Thing is I belive, that this is, as you mention, a starter, and some users won't need an admin dashboard as @jadjoubran mention [here](https://github.com/jadjoubran/laravel5-angular-material-starter/issues/223#issuecomment-202921378)

**Comment by jadjoubran** [comment]
Hi @flakerimi 
Thanks for your question!

As @flick36 mentioned, this is a starter project not a CMS.. this is the main reason why there isn't any ready-made admin..

Github issues is where you can take a look at the roadmap, feature suggestions & discussions. Feel free to create a new issue for every feature you'd like to suggest!

I'm also planning on sending an anonymous survey as soon as 3.2 is released.. So make sure to `watch` the repo to get the notification when I post the survey

In case a lot of people are interested in an admin panel, it might come as a completely different service on top of this.. but unfortunately, this isn't in the near future :(

Let me know if you have other questions 😄

**Comment by flakerimi** [comment]
Yeah probably right.
