### ISSUE TITLE
How to invoke this.$auth.setToken() if the call is not triggered from Angularjs

### ISSUE THREAD

**Issue by AndrewLaBabies** [jadjoubran/laravel5-angular-material-starter#262]
Hi Everyone,

I got a case:
1. An application finished the authentication, and then send the openID to my Laravel application.
2. Laravel application using that openID to generate the token, and then send to index.blade.php
3. index.blade.php can get the token.

However, how could I set the token into Angularjs? like this.$auth.setToken(response.data.token) in login-form.component.js.

I spend quite a lot of time to try to resolve, but still failed…
Please help, thanks in advance.

Best Regards,
Andrew He

**Comment by jadjoubran** [comment]
Hi @AndrewLaBabies 
Isn't this all happening through an AJAX request?

For example, you call the API endpoint you wrote using restangular..
If that's the case, you can do something like this:

``` javascript
this.API.all('auth').post(data).then((response) => {
    this.$auth.setToken(response.data.token);
});
```

Let me know if this fixes your issue

**Comment by AndrewLaBabies** [comment]
Hi @jadjoubran ,

Thanks for your reply.
Looks like your case is: angularjs > laravel > angularjs, if so, that will work.
However, how about laravel > angularjs? No call is triggered by angularjs,  but need to pass the parameter to $auth.

Rgds,
Andrew

**Comment by jadjoubran** [comment]
is there a specific reason why Laravel is doing this without an Ajax call?
As in, is it happening inside a cronjob or a queue?

**Comment by AndrewLaBabies** [comment]
My application needs to integrate with WeChat (a popular product in China like Twitter/Facebook).
When user in WeChat accepts authorization to access my application, the user information from WeChat will be sent to my application (Laravel handling at this moment), then my application will use JWTAuth to generate the token.
I can send the token from Laravel’s controller to index.blade.php, however, how could I set token to $auth in angularjs?
Thanks.

Rgds,
Andrew

**Comment by jadjoubran** [comment]
I think you can either store it in a global variable or maybe in the database and then retrieve it again with an ajax call.. but I must admit both solutions are ugly

**Comment by AndrewLaBabies** [comment]
global variable? Do you mean save it in $rootScope?

**Comment by jadjoubran** [comment]
It's **really ugly hack**, but maybe storing it into a global javascript variable..
There must be a better way to do that.. but I couldn't understand what's going on under the hood

**Comment by jadjoubran** [comment]
I would say the database approach is a bit cleaner.. although the idea from a JWT is that you don't need the db
but maybe you can store it in the users table and then remove it once the user has fetched it? or just keep it?

**Comment by AndrewLaBabies** [comment]
but from my case, even though saving into database, but the client still need to know the token, set in @auth， or global javascript or local storage ---- no more information but just some come from laravel.

**Comment by jadjoubran** [comment]
Yes if you have it in your database, you could then always query for it from your front-end.. Until you have it
What do you think?

**Comment by AndrewLaBabies** [comment]
but how do I know the token belonging to me? I think that is the key.
still need to pass token to a globe variable (once, after set the $auth, we can delete?).

**Comment by jadjoubran** [comment]
Yeah.. sounds plausible I guess

**Comment by AndrewLaBabies** [comment]
I still can NOT set the token to $auth !!
After get the token from globe javascript variable, I call this.$auth.setToken(response.data.token) to set token, however, it doesn't work. Failed (401 unauthorized ) to call API inside $api->group(['middleware' => ['api', 'api.auth']], function ($api)

**Comment by jadjoubran** [comment]
Can you post some js code?
code for setting token
then add a console.log for ($localStorage)
and then the API call for the restricted endpoint

**Comment by AndrewLaBabies** [comment]
```
   loadData(){
        console.log('window weChatToken: ' + this.$window.weChatToken);

        if(this.$window.weChatToken!=null && this.$window.weChatToken!='') {


            //this.$auth.setToken(this.$window.weChatToken);

            var data = {
                weChatToken: this.$window.weChatToken
            };

            this.API.all('refreshWeChatToken').post(data)
                .then((response) => {
                        var token = response.data.token;

                        console.log('after refresh:');
                        console.log(token);
                        console.log('asss');
                        this.$auth.setToken(response.data.token);

                        this.$window.weChatToken = '';
                    })
                    .catch(this.ErrorHandling.bind(this));

                    console.log('xxx!');

                    //this.API.all('getUser').post(data)
                    //  .then((response) = > {
                    //      console.log('I got the token to access JWF protect API!');
                    //  })
                    //  .catch(this.ErrorHandling.bind(this));

            }
    }
```

**Comment by AndrewLaBabies** [comment]
and in Laravel, I have to transform the type to string, otherwise, token is null when return.
return response()->success(['token' => (string)$token]);

**Comment by AndrewLaBabies** [comment]
```
class WeChatController extends Controller
{
    public function refreshWeChatToken(Request $request){
        Log::debug("WeChatController.refreshWeChatToken():");
        $dataFactory = new WeChatUserToken();

        if($dataFactory->isWeChatTokenExist($request->input('weChatToken'))){
            // JWT Auth
            $customClaims = ['mobile' => 'aaa', 'temp' => 'abc'];

            $payload = JWTFactory::make($customClaims);

            $token = JWTAuth::encode($payload);

            Log::debug("WeChatController.refreshWeChatToken(): token refresh. ");

            //TODO: remove this debug for token
            Log::debug("WeChatController.refreshWeChatToken(): token: ". $token);

            return response()->success(['token' => (string)$token]);
        }else{
            Log::debug("WeChatController.refreshWeChatToken(): there is no existing WeChatToken.");
            return response()->error("系统不存在此用户Token.", 403);
        }

    }



}
```

**Comment by jadjoubran** [comment]
Please use "```" (3 backticks) followed by a new line to format your code

**Comment by AndrewLaBabies** [comment]
sorry, didn't notice, is it caused by? my PC is slow now, print the console log later.

```
class LandingFormController{
    constructor($stateParams,$state,API,$auth,$window){
        'ngInject';

        //
        this.$auth = $auth;
```

**Comment by AndrewLaBabies** [comment]
When invoke following, I got error in chrome.

```
	console.log('$ngStorage.localStorge:');
						console.log($ngStorage.localStorge);

```
angular.js:13550 Error: [$injector:unpr] Unknown provider: $ngStorageProvider <- $ngStorage
http://errors.angularjs.org/1.5.5/$injector/unpr?p0=%24ngStorageProvider%20%3C-%20%24ngStorage
    at angular.js:68
    at angular.js:4458
    at Object.getService [as get] (angular.js:4611)
    at angular.js:4463
    at getService (angular.js:4611)
    at injectionArgs (angular.js:4635)
    at Object.invoke (angular.js:4657)
    at $controllerInit (angular.js:10115)
    at nodeLinkFn (angular.js:9033)
    at angular.js:9433

**Comment by AndrewLaBabies** [comment]
update again:

![github_framework_issue3](https://cloud.githubusercontent.com/assets/8588393/14724236/6d7a8b8c-0847-11e6-83e7-3bdfad59dce5.png)

**Comment by jadjoubran** [comment]
`console.log(token);` is weird.. I can't see any token
This probably isn't the issue but your scenario is too big to be debugged manually

I'd recommend that you do it step by step.. you can even start from scratch

if it still doesn't work, I guess stackoverflow would be a better fit

Good luck!

**Comment by AndrewLaBabies** [comment]
finally, I saved the necessary login info in DB, and pass the key to angularjs to let it relogin.
It works now, thanks.
