### ISSUE TITLE
JWT Token refresh

### ISSUE THREAD

**Issue by shiruken1** [jadjoubran/laravel5-angular-material-starter#264]
Hey folks!

I'm having a really hard time with this one. I'm trying to get the tokens to refresh, by adding

```
.setFullResponse(true) //for token refresh below
.addResponseInterceptor(function (response, operation, what) {
    if(response.data.token !== $auth.getToken()) { //refresh the token
        var token = response.headers.Authorization.replace('Bearer ','');
        $auth.setToken(token);
    }
$log.debug(response.headers);
})
```

to API.service.js, however response.headers keeps coming back as undefined.

I've added 'exposedHeaders' => ['Authorization'] to config/cors.php and 'middleware' => 'cors' to my routes.

Any suggestions would be really appreciated. I've spent over 3 hours on this to no avail :(

Thanks!!

**Comment by jadjoubran** [comment]
Hi @shiruken1 
Could you send a screenshot of the headers from chrome or postman?
Or at least could you verify that they're returned correctly?

**Comment by shiruken1** [comment]
They're returning correctly, as far as I can tell: http://imgur.com/UTGZoCz
however the console still reports response.headers as undefined

**Comment by jadjoubran** [comment]
Can you see the `Access-Control-Expose-Headers`? I don't think it's being returned..
It might be an issue from
1) your config
2) the package you're using

looking for a quick fix?
You could implement your own middleware and modify the response

``` php
    public function handle($request, Closure $next)
    {
        $response = $next($request);

        $response->headers->set('Access-Control-Expose-Headers', 'list your headers here');

        return $response;
    }
```

**Comment by shiruken1** [comment]
I saw it only when I included header("Access-Control-Allow-Origin: *"); into public/index.php like the barryvdh/laravel-cors says to do for debugging, but I'm not using any packages other than what came with this one (Dingo and Laravel-CORS)

Cors.php has:

```
    'supportsCredentials' => false,
    'allowedOrigins' => ['*'],
    'allowedHeaders' => ['*'],
    'allowedMethods' => ['GET', 'POST', 'PUT',  'DELETE'],
    'exposedHeaders' => ['Authorization'],
    'maxAge' => 0,
    'hosts' => [],
```

**Comment by shiruken1** [comment]
I added Header set Access-Control-Expose-Headers "Authorization" to my .htaccess, and it now shows up in the response headers. Shouldn't the cors.php config made that happen, like the middleware you suggested? 

Regardless, Restangular still reports undefined for response.headers. I tried logging response.headers('Authorization') like I found somewhere, but Restangular states headers is not a function. 

:(

**Comment by jadjoubran** [comment]
It might be an issue from the plugin.. you can check their issues

And seems like a restangular problem :/ https://github.com/mgonto/restangular/issues/1263

**Comment by shiruken1** [comment]
Well this sucks... :( Thank you so much for the pointer. I can't believe I didn't come across that issue when I started Googling yesterday.

Any recommendations for me? I'm all ears!

Thanks again

**Comment by jadjoubran** [comment]
Yeah googling usually isn't enough.. I always search their issues

I'd recommend you take a look at restangular's implementation of this function.. and see if you can run it natively
Or maybe you could return the token in a field (I have no idea if it's a bad practice or if it has security concerns)

Good luck! 😄
