### ISSUE TITLE
[Support] Best practice to get data from the RESTful API

### ISSUE THREAD

**Issue by flick36** [jadjoubran/laravel5-angular-material-starter#266]
Restangular requires an array when using getList() but in the API i return the data with 
`return response()->success(compact('count', 'clients'));` that gives back a JSON

[Docs](https://laravel-angular.readme.io/docs/response-macros) says that 

> you can always expect the same response format for all success responses.

But it doesnt work with JSON so, should i use `addResponseInterceptor` from restangular to extract what a i need from the JSON? or should pass everything as an array?

**Comment by jadjoubran** [comment]
Hi @flick36 
Indeed this doesn't work with a `getList()` call. getList calls only work if your API call returns an array..
So it doesn't really make sense to use `getList` if you're expecting two objects: `count` & `clients`..

You could implement response interceptor to alter the response and make it work.. but I don't personally recommend it as it's a bit magical for some kind of responses

The main benefit of response macros is taking care of error responses automatically and consistently

**Comment by flick36** [comment]
So, what should i do then? cause even if i just return 1 object `getList()` won't work and restangular suggest using them for [CRUD operations](https://github.com/mgonto/restangular#how-do-i-handle-crud-operations-in-a-list-returned-by-restangular)

**Comment by jadjoubran** [comment]
You could return 1 array from your API which contains 2 arrays:

```
[
    'users' => [
           'clients' => ...,
           'count' => ...,
     ]
]
```

or simply append the count to the users

`$clients['count'] = $count;`
