### ISSUE TITLE
[support] how to set variabel global on angular?

### ISSUE THREAD

**Issue by yosmelvin** [jadjoubran/laravel5-angular-material-starter#267]

**Comment by jadsalhani** [comment]
If you mean having a variable in the global scope (i.e. [$rootScope](https://docs.angularjs.org/api/ng/service/$rootScope)), then it should be something like

```
$rootScope.test = "Test variable value";
```

of course after injecting `$rootScope` in your constructor.

I must say that using the $rootScope is a bad practice in most cases, if you'd like to have a variable globally available wrap it in a service to inject it and use it whenever you need.

Hope this helps
