### ISSUE TITLE
token too long,  it can't be passed to client

### ISSUE THREAD

**Issue by AndrewLaBabies** [jadjoubran/laravel5-angular-material-starter#268]
when token is too long, client always complain 'TypeError： Cannot read property 'data' of underfined.'
seems that it happens on JWTFactory only, JWTAuth::attempt works fine.

We have to fix it by following:(

**Laravel:**
$customClaims = ['mobile' => $mobile, 'password' => $password];
$payload = JWTFactory::make($customClaims);
$token = JWTAuth::encode($payload);
$token1 = substr($token,0,150 );
$token2 = substr($token,150);

**Angularjs:**
var token1 = response.data.token1;
var token2 = response.data.token2;
var tokenStr = token1+token2;
this.$auth.setToken(tokenStr);

**Comment by jadjoubran** [comment]
Hi @AndrewLaBabies 

From the error message you posted, `'TypeError： Cannot read property 'data' of underfined.'` it seems that there's another issue..
Could you send over a screenshot of a postman or chrome response?

**Comment by AndrewLaBabies** [comment]
here we go!

Rgds,
Andrew

**Comment by jadjoubran** [comment]
screenshot not showing

**Comment by AndrewLaBabies** [comment]
![github_framework_issue](https://cloud.githubusercontent.com/assets/8588393/14677935/5b5ece42-0746-11e6-801e-18ebb0e2a864.png)

sorry, sent by email just now.

**Comment by jadjoubran** [comment]
okay great, please send me a screenshot from the network tab > `response` or `preview` sub-tab

Also do you have some custom code in your responseInterceptor?

**Comment by AndrewLaBabies** [comment]
I see nothing in network tab, sources tab can help?
![github_framework_issue1](https://cloud.githubusercontent.com/assets/8588393/14678494/747a69b6-0748-11e6-8def-b9650b3becc8.png)

**Comment by jadjoubran** [comment]
If you can just `console.log(response)` and show me the response collapsed of course

**Comment by AndrewLaBabies** [comment]
come again

![github_framework_issue2](https://cloud.githubusercontent.com/assets/8588393/14679143/378a985c-074b-11e6-9171-a493ef3bf22a.png)

**Comment by jadjoubran** [comment]
sorry my bad, console.log(response.data)

**Comment by jadjoubran** [comment]
Feel free to re-open in case you have more info

Thanks 😄
