### ISSUE TITLE
Anonymous Survey

### ISSUE THREAD

**Issue by jadjoubran** [jadjoubran/laravel5-angular-material-starter#269]
Hi All,

3.2 stable has just been tagged.

I would love it if you can fill this [Anonymous survey](http://goo.gl/forms/0nPZ04sSIV) to let us know more how we can improve this starter. It will only take you 60 seconds.

❤️

**Comment by flick36** [comment]
May I ask, what are the beneifts/cons of dropping the dingo/api?

Awesome starter!

**Comment by jadjoubran** [comment]
In order for dingo/api to work properly, they had to rewrite a lot of routing functionality this leads to the below **benefits** (I've hit those issues in some apps I've built):
- dingo/api works by adding a middleware. So using the `WithoutMiddlewareTrait` from your tests is impossible.. Which makes testing a lot harder
- pattern methods don't work :( https://github.com/dingo/api/issues/741
- middleware issue https://github.com/dingo/api/issues/964

cons:
- if someone is relying on another feature from dingo/api, he'll have to manually install dingo/api. Luckily, it's trivial to setup.
- we'd have to reproduce "a lighter version" of some of the features (discussed below)

Also, since Laravel 5.2 has been introduced, most important features from dingo/api can be developed by writing a middleware.. For example `API versioning`, `content negotiation`.

Let me know what you think 😄

**Comment by flick36** [comment]
Those doesn't sound like **benefits** lol, and what would you replace it with? middlewares?

**Comment by jadjoubran** [comment]
haha yes I meant benefits of removing it
And yes, by custom middlewares that can be enabled/disabled depending on every user's preference

**Comment by flick36** [comment]
In that case it sounds like a good ide to remove it

**Comment by ChadTaljaardt** [comment]
Contributed ^^
