### ISSUE TITLE
[Support] How to resolve foreing keys Restangular

### ISSUE THREAD

**Issue by flick36** [jadjoubran/laravel5-angular-material-starter#273]
Hi, it's me again, i have this technical concern of how to solve the foreing keys with Restangular. I have for example this json that i get from my RESTful API

```
{
    id: 43,
    users_scheduler_id: 1,
    created_at: "2016-04-24 19:34:12",
    updated_at: "2016-04-24 19:34:12"
}
```

there are a lot  of them that i get from a getList(), but how can i show in angular the name of the **users_scheduler_id** instead of it's id

**Comment by jadjoubran** [comment]
Hi,

Can you please show a sample code.. I'm not sure I get it

**Comment by flick36** [comment]
sure, i'm using:

`this.appointments = this.API.all('apointments').getList().$object;`

to get an array of objects containing:

```
{
    id: 43,
    start_datetime: "2016-04-18 00:00:00",
    end_datetime: "2016-04-18 00:15:00",
    notes: "",
    users_scheduler_id: 1,
    is_urgent: 0,
    is_unavailable: 0,
    users_provider_id: 1,
    client_id: 2,
    id_services: 1,
    created_at: "2016-04-24 19:34:12",
    updated_at: "2016-04-24 19:34:12"
}
```

and the values that have an **id** in the name like: `users_providers_id` and `id_services` are foreing keys from other tables.

`users_scheduler_id` and `users_providers_id` are from the `Users` table
`client_id` is from the `Clients` table
and `id_services` is from the `Services` table

and in my angular app when i get the array of objects, i want to show the name of the 3 above instead of the foreing key, cause when i click a card for example i need those details, like for the name of the client, and what service is

**Comment by jadjoubran** [comment]
If I understand correctly,  this is something that needs to be fixed from the API

[Official docs tutorial](https://laravel.com/docs/5.2/quickstart-intermediate#eloquent-relationships)

**Comment by flick36** [comment]
Thanks!
