### ISSUE TITLE
[support] Custom claims in JWT?

### ISSUE THREAD

**Issue by ryantate13** [jadjoubran/laravel5-angular-material-starter#274]
I'd like to add custom user profile data to the JWT claims. How is this accomplished?

**Comment by jadjoubran** [comment]
Hi @ryantate13 
Have you checked the [official documentation for jwt-auth](https://github.com/tymondesigns/jwt-auth/wiki)?
So of course you have access to `config/jwt.php` and you need to fix the `AuthController`

let me know if this helps

**Comment by ryantate13** [comment]
Thanks for the step in the right direction. I was able to find more info here:

http://stackoverflow.com/questions/29014681/add-the-user-role-to-the-jwt-laravel-5-jwt-auth

**Comment by jadjoubran** [comment]
Sounds great!

It would be great if you can post an example of your findings which will help the community 😄

**Comment by jadjoubran** [comment]
Hi @ryantate13 
Any update on this?

**Comment by ryantate13** [comment]
Definitely, here is how I am handling the custom claim today. I also ready on the jwt-auth page that in a future version there may be built-in solution that will not require two queries but for now I believe this is the best way to go about it.

```
public function login(Request $request)
    {
        $this->validate($request, [
            'email'    => 'required|email',
            'password' => 'required|min:8',
        ]);

        $credentials = $request->only('email', 'password');

        $user = User::where('email', '=', $credentials['email'])->first();

        if ($user) {
            $customClaims = ['cid' => $user->client_id];
        }
        else{
            $customClaims = [];
        }



        try {
            // verify the credentials and create a token for the user
            if (! $token = JWTAuth::attempt($credentials, $customClaims)) {
                return response()->error('Invalid credentials', 401);
            }
        } catch (\JWTException $e) {
            return response()->error('Could not create token', 500);
        }

        $user = Auth::user();

        return response()->success(compact('user', 'token'));
    }
```

**Comment by jadjoubran** [comment]
Sounds great, thanks for the example! 😄
