### ISSUE TITLE
Getting view data from backend to angular controller

### ISSUE THREAD

**Issue by baj84** [jadjoubran/laravel5-angular-material-starter#278]
Hey,

I need to have some pages that aren't part of the single page app, but it still uses angular.
I'm trying to pass data from the backend to an angular controller like so:
     return view('search_results', array('origin' => $fromLocationObject, 'destination' => $toLocationObject));

What is the best way to do this?

Thanks

**Comment by flick36** [comment]
What kind of data are you triying to pass?
Where do you get `$fromLocationObject` and `$toLocationObject` from?

You are triyin to send an array so you can get that from a REST Api, and in the angular controllers retrieve that info with Restangular, but i really don't know what those variables are or where do they come from, or what you triyin to do, maybe you can provide more info?

**Comment by elemes1** [comment]
Hi, how can  one easily use angular controller without the use components and the ng:create page, for example i want to create a factory service which access http  get request on laravel controller and then send to angular controller and pass to the landing page, what would be the easiest approach. thanks

**Comment by flick36** [comment]
Hi @elemes1 you could open a new issue asking that for a better control, that way if someone else is looking the same thing you are looking, it'll be easier to find anyway, here's one approach,

https://github.com/jadjoubran/laravel5-angular-material-starter/issues/245#issuecomment-207478783

**Comment by elemes1** [comment]
thanks, i would try it then get back to you
