### ISSUE TITLE
Directives are broken

### ISSUE THREAD

**Issue by flick36** [jadjoubran/laravel5-angular-material-starter#279]
They don't work even when using as created without a function or variables or anything it always get `Argument 'fn' is not a function, got Object`

**Comment by jadjoubran** [comment]
Hi @flick36 
Thanks for reporting the bug.
Directives need to return a function rather than an object
I will fix and bump the generators

**Comment by jadjoubran** [comment]
Available in generators `2.4.2`
You can update by running `composer update laravelangular/generators`

**Comment by flick36** [comment]
Thanks!
