### ISSUE TITLE
Use API in dialog response 

### ISSUE THREAD

**Issue by Neo-89** [jadjoubran/laravel5-angular-material-starter#280]
Hi,

I'm trying to send data from mdDialog prompt but when I call 'this.API', I see in console 'Cannot read property 'API' of undefined'. But when I create other variable before dialog service - it works. Is this correct? It looks strange to me...

```
class CreateProductFormController {
    constructor(API, ToastService, $timeout, DialogService) {
        'ngInject';

        this.API = API;
        this.timeout = $timeout;
        this.DialogService = DialogService;
        this.ToastService = ToastService;
        this.product_name = '';

        this.API.all('products').get('')
            .then((response) => {
                this.products = response.data.products;
            });
}
add() {
        var data = {
            product_name: this.product_name
        };
        var api = this.API;
        var toast = this.ToastService;

        this.DialogService.prompt('New product','Add new product','Product name')
            .then(function(result){
                data.product_name = result;
                api.all('products').post(data).then((response) => {     // this.API.all... doesn't work
                toast.show('Product added successfully');
                });
            }, function() {
                console.log('canceled');
            });
    }
```

I'm new in Angular so maybe my solution is senseless. Thanks for any help.

**Comment by jadsalhani** [comment]
Hi @Neo-89 

As explained in the [Arrow functions](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Functions/Arrow_functions) definition:

> Until arrow functions, every new function defined its own this value (a new object in case of a constructor, undefined in strict mode function calls, the context object if the function is called as an "object method", etc.). This proved to be annoying with an object-oriented style of programming.

So since you have `.then(function(result){` calling the api, then the `api` variable you are using is bound to the `this` of the callback function and not the parent function

As mentioned: 

> An arrow function expression has a shorter syntax compared to function expressions and lexically binds the this value (does not bind its own this, arguments, super, or new.target). Arrow functions are always anonymous.

So in short to fix it you should use an arrow function as your callback, so it would be

```
 this.DialogService.prompt('New product','Add new product','Product name')
            .then((result) => {
                data.product_name = result;
                api.all('products').post(data).then((response) => {     // this.API.all... doesn't work
...
```

Happy coding!
