### ISSUE TITLE
Redirect after login

### ISSUE THREAD

**Issue by ianzitow** [jadjoubran/laravel5-angular-material-starter#282]
Guys,

After login through `/#/login`, why aren't users redirected to, let's say, `/#/home`? Right now, it just triggers a successful toast, but remains on the same page.

**Comment by flick36** [comment]
That's up to you, this is a starter, it only has a landing page wich everyone can access in, a login page, a register page, and a reset password page you have to add the functionality, cause not everyone has the same pages, for example you want your users to go to `/#/home` but i want mine to go to `/#/agenda` you should be able to redirect them by simpy adding in the `login-form.component.js` on the succesfull response in line `21` the state you want your users to go after a succesfull login

**Comment by jadjoubran** [comment]
Yes indeed, as @flick36 mentioned.

It's relatively easy. You just need to inject `$state` and add `this.$state = $state` in your constructor.
And then you'll be able to navigate to your own state right below the toast message:

``` javascript
this.$state.go('app.landing');
```

Feel free to re-open if there's anything else
