### ISSUE TITLE
passing data  from laravel backend to landing page  using controller only

### ISSUE THREAD

**Issue by elemes1** [jadjoubran/laravel5-angular-material-starter#285]
Hi would like to pass data from laravel controller to angular controller using API and then send to landing page as md-select option.  i would like to do this : 

`````` ///////////services

(function () {
    'use strict';
    angular
        .module('boons')
        .factory('locationsFactory', function($http){
            function getLocations(){
                return $http.get('http://freeboons.dev/api/states');
            }

            return{
                getLocations: getLocations
            }
        });
})();

///controller 

    'use strict';
    angular
        .module('boons')
        .controller('boonsCtrl', function ($scope, $http,locationsFactory) {
            $scope.message= "# classsifieds";
            locationsFactory.getLocations().then(function(locations){
                $scope.locations = locations.data;

                console.log(locations);
            });


/////landing page : 

<md-input-container flex-gt-sm="25" flex="50">
                    <md-select ng-model="locationFilter" placeholder="Location">
                        <md-option ng-value="location" ng-repeat="location in locations">{{location.name}}</md-option>
                    </md-select>
                </md-input-container>



        });
})();```

any help please. 
``````

**Comment by jadjoubran** [comment]
Hi @elemes1 
Please use 3 backticks and a new line to format your code  ```

**Comment by flick36** [comment]
I think there's no need to create a factory for that, you can just create a controller using this approach: https://github.com/jadjoubran/laravel5-angular-material-starter/issues/245#issuecomment-207478783 and in your landing page set the `ng-controller="YourControllerName as vm"` and in that controller inject the API Service to have something like this:

```
export class YourControllerName {
    constructor(API) {
        'ngInject';

        this.API = API;

        this.locations = this.API.all('locations').getList().$object;
        this.selectedLocation;
    }
}
```

and in the `md-select` of your landing page:

```
<md-select name="locations" ng-model="vm.selectedLocation">
    <md-optgroup label="Locations">
        <md-option ng-value="location" ng-repeat="location in vm.locations">
            {{location.name}}
        </md-option>
    </md-optgroup>
</md-select>
```

of course this is assuming in your Locations Controller on Laravel you are responding with a JSON object like:

`return response()->json($locations , 200);`

There are millions (maybe exagerating) ways to do it, as you wanna do that on the landing page wich i won't recommend cause there's no need to have controllesr in pages i found this to be the easieast way but, you should use a `component` instead, that way you won't need to create controllers.

**Comment by elemes1** [comment]
thank you so much, would try both approach 
and get back to you.

**Comment by elemes1** [comment]
@flick36 Thank you. worked like charm. didn't know it could be this easy

**Comment by flick36** [comment]
You're welcome @elemes1 i'm glad it helped

**Comment by elemes1** [comment]
@flick36 hi one more thing, using the component option, i get nothing on the landing page, but works if i use it on the components page itself. this is what my console shows 
Error: [ng:areq] Argument 'CreateStateViewController' is not a function, got undefined
and i already specified CreateStateViewController as vm.  thanks for the help

**Comment by jadjoubran** [comment]
If you're using a component, you shouldn't explicitly have an `ng-controller=..`
Can you show some code?

**Comment by elemes1** [comment]
Thank you, : 

the Component code section. : 

```
class CreateStateViewController {
    constructor(ToastService, API) {
        'ngInject';

        //

        this.message="#1 Free Market Place in Nigeria.";
        this.API = API;
        this.Toast=ToastService;
        this.locations =  this.API.all('states').getList().$object;
        this.selectedLocation;

    }

    onInit() {

          }

export const CreateStateViewComponent = {
    templateUrl: './views/app/components/create_state_view/create_state_view.component.html',
    controller: CreateStateViewController,
    controllerAs: 'vm',
    bindings: {}
}


```

The landing page : 

```
    <section id="banner" layout-padding ng-controller="CreateStateViewController as vm">
        <boons-project class="md-title no-padding">{{vm.message}}</boons-project>
        <p align="center">connecting the rich and poor within nigeria</p>
        <div class="filters" layout="column">
            <div class="select-filter" layout="row" layout-align="center" layout-wrap>
                <md-input-container flex-gt-sm="25" flex="50">
                    <md-select ng-model="vm.selectedLocation" placeholder="Location">
                        <md-option ng-value="item" ng-repeat="item in vm.locations">
                            {{item.name}}
                        </md-option>
                    </md-select>
                </md-input-container>

                <md-button class="all" flex>all boons</md-button>
            </div>
            <div class="input-filter" layout="row" layout-align="center" >
                <md-input-container flex>
                    <input type="text" placeholder="I'm looking for..." ng-model="boonsFilter">
                </md-input-container>
                <md-button class="md-flat cta-btn"><md-icon class="mdi mdi-magnify"></md-icon>Search</md-button>
            </div>
        </div>

    </section>      <!--end banner -->

```

**Comment by flick36** [comment]
I don't think you get how `components` work, take a look at the [Angular Documentation](https://docs.angularjs.org/guide/component)

Components are like templates, Pages are like containers of components, so in you landing page you sure can have text and everything but for a md-slect for example i assume it does something when you select an item, so it's a form, a tiny little form. so for example i have this landing page:

```
  <section id="banner" layout-padding>

  </section>      <!--end banner -->
```

i''m gonna use a component for a a select so i create my component, in this case with the artisan command `php artisan ng:component CreateStateView` and my landing page will turn into this

```
    <section id="banner" layout-padding>
        <create-state-view></create-state-view>
    </section>      <!--end banner -->
```

And as you can see in the component controller it's already especified where it's template is in this case: `templateUrl: './views/app/components/create_state_view/create_state_view.component.html',` so i open that template and i'll put in there the rest of your code having this:

```
<boons-project class="md-title no-padding">{{vm.message}}</boons-project>
        <p align="center">connecting the rich and poor within nigeria</p>
        <div class="filters" layout="column">
            <div class="select-filter" layout="row" layout-align="center" layout-wrap>
                <md-input-container flex-gt-sm="25" flex="50">
                    <md-select ng-model="vm.selectedLocation" placeholder="Location">
                        <md-option ng-value="item" ng-repeat="item in vm.locations">
                            {{item.name}}
                        </md-option>
                    </md-select>
                </md-input-container>

                <md-button class="all" flex>all boons</md-button>
            </div>
            <div class="input-filter" layout="row" layout-align="center" >
                <md-input-container flex>
                    <input type="text" placeholder="I'm looking for..." ng-model="boonsFilter">
                </md-input-container>
                <md-button class="md-flat cta-btn"><md-icon class="mdi mdi-magnify"></md-icon>Search</md-button>
            </div>
        </div>
```

and the logic remains the same on your controller

**Comment by elemes1** [comment]
wow, thanks once again. i understand now, by the way,  do write blog posts for tutorials, This explanation is really cool and concise.  would love to subscribe to your blog if you do

**Comment by flick36** [comment]
@elemes1 i'm glad to help, you can watch the [screencast](https://www.youtube.com/channel/UCTiRXlOapSWfu02rtOdaGvA) of this starter that @jadjoubran do from time to time, they're awesome

**Comment by elemes1** [comment]
Thanks would do that
