### ISSUE TITLE
How to load loggedIn user credentials in each page Header

### ISSUE THREAD

**Issue by rcadhikari** [jadjoubran/laravel5-angular-material-starter#286]
Hi there,

I am trying to use your package, however I am bit struggling to find out a way to load the logged in user's credentials on each page's header.

Also, could you please guide me to declare the custom JavaScript global function at the very first before begin to load anything, so that I should be able to call it anywhere within the project JavaScript code.

Many thanks
RC

**Comment by jadjoubran** [comment]
Hi,

Are you using UI-router's nested routing just like in this starter?

```
.state('app', {
            abstract: true,
            views: {
                header: {
                    templateUrl: getView('header')
                },
                footer: {
                    templateUrl: getView('footer')
                },
                main: {}
            }
        })
```

if so, then you don't need to set the header for every page which means as soon as you fetch the user data.. they remain there
Now what you need to solve is, how to get the user data when the user refreshes.
I'd recommend that you store them in localstorage using `$localStorage` if you want
And then create a service that reads them.. Something like: `UserService` where you have methods for `.set(user)` and `.get()`.. they save and read from localStorage using $localStorage (this is how I do it).

I am not sure what you mean by that.. Normally you could have code run in the `app.run` phase of the angular app..
http://stackoverflow.com/questions/20663076/angularjs-app-run-documentation
