### ISSUE TITLE
Need Custom Dialog Sample

### ISSUE THREAD

**Issue by muhyiddins** [jadjoubran/laravel5-angular-material-starter#287]
is there someone who can give me an example of using a custom dialog. I have tried to create a form, but the save button does not execute the function save () in the dialog controller
Thanks.

**Comment by flick36** [comment]
The template

```
<md-dialog>
    <form ng-submit="vm.save()">

        <md-toolbar>
          <div class="md-toolbar-tools">
            <h2>Title</h2>
          </div>
        </md-toolbar>

        <md-dialog-content>

            You put your inputs and everything else in here, or up there in the md-toolbar

        </md-dialog-content>

        <md-dialog-actions>
            <md-button type="button" ng-click="vm.cancel()">Cancel</md-button>
            <md-button class="md-primary md-raised" type="submit">Save</md-button>
        </md-dialog-actions>
    </form>
</md-dialog>
```

The controller

```
export class YourControllerName{
    constructor(DialogService){
        'ngInject';

        this.DialogService = DialogService;
    }

    save(){
        //Logic here
        this.DialogService.hide();
    }

    cancel(){
        this.DialogService.cancel();
    }
}
```

**Comment by muhyiddins** [comment]
Thanks @flick36, I had made it, but it still doesn't work.

I attach below a few snippet of my code

Template :

```
<md-dialog>
    <form ng-submit="vm.save()">

        <md-toolbar>
          <div class="md-toolbar-tools">
            <h2>Add-post</h2>
          </div>
        </md-toolbar>

        <md-dialog-content>
            <div class="md-dialog-content">
                <md-input-container flex>
                    <label>Name</label>
                    <input type="text" ng-model="vm.name">
                </md-input-container>
                <md-input-container flex>
                    <label>Topic</label>
                    <input type="text" ng-model="vm.topic">
                </md-input-container>
             </div>
        </md-dialog-content>

        <md-dialog-actions>
            <md-button type="button" ng-click="vm.cancel()">Cancel</md-button>
            <md-button class="md-primary md-raised" type="submit">Save</md-button>
        </md-dialog-actions>
    </form>
</md-dialog>

```

Controller :

```
export class AddPostController{
    constructor(DialogService, API, ToastService){
        'ngInject';

        this.DialogService = DialogService;

        this.API = API;
        this.ToastService = ToastService
    }

    save(){
        //
        var data = {
            name: this.name,
            topic: this.topic,
        };

        this.API.all('posts').post(data).then(() => {
            this.ToastService.show('Post added successfully');
        });
        console.log('Save Button Pressed');
        this.DialogService.hide();
    }

    cancel(){
        console.log('Close Button Pressed')
        this.DialogService.cancel();

    }
}

```

And i have call by `ng-click="vm.add()"` with button  and function in component controller :

```


    add(){
        this.DialogService.fromTemplate('add-post');

    }


```

but the save and close button does not works.
What's wrong with my code? Is there someone who has the experience to make it work.
Thanks

**Comment by flick36** [comment]
You have to import the Dialog controller, in the component controller from where you are calling the Dialog, like this:

```
import { AddPostController } from '../../../dialogs/add_post/add_post.dialog.js';

export class ControllerWhereAddFunctionIs{
 ...
```

and in your `add()`function add this:

```
 add() {
        let options = {
            controller: AddPostController,
            controllerAs: 'vm'
        }
        this.DialogService.fromTemplate('add-post', options);
    }
```

I've gotta tell you, i felt ofended by your 

> someone who has the experience

 comment

**Comment by muhyiddins** [comment]
@flick36 thank you so much, it's worked like charm.

**Comment by flick36** [comment]
@middink you're welcome, glad to help.

**Comment by jadjoubran** [comment]
Thanks @flick36! 😄

**Comment by arifulhb** [comment]
Thanks @flick36 your solution is :dart:

**Comment by muhyiddins** [comment]
How to pass variable to Dialog.

i have call function `edit(data)` and I  expecting the parameter 'data' can be sent to the dialog and display the text input. Thanks

```
edit(data) {
        let options = {
            controller: EditPostController,
            controllerAs: 'vm'
        }
        this.DialogService.fromTemplate('edit-post', options);
    }

```

**Comment by jadjoubran** [comment]
You can use `locals`
They're available in [Angular material's documentations](https://material.angularjs.org/latest/api/service/$mdDialog)

**Comment by confeccionar** [comment]
Hi, 
I put within the function 

```
modal()
{
        let options = {
           controller: EmpresasController,
           controllerAs: 'vm'          
        }
        this.DialogService.fromTemplate('empresas', options);
}
```

but I get the following error: 

angular.js:13920 ReferenceError: EmpresasController is not defined
at AfiliacionNuevaController.nuevaEmpresaModal (app-40718f4821.js:641).

I put in index.components.js 

import {EmpresasController} from '../../../dialogs/empresas/empresas.dialog.js';

use laravel-angular 3.2

**Comment by jadjoubran** [comment]
Hi @confeccionar 
You need to `import EmpresasController`  at the  top of the file
check your `index.modules.js` for a sample

**Comment by confeccionar** [comment]
Thanks. @jadjoubran .

help me please,  the modal save new data in the database , what I want is to close the modal data is update. my main controllador I have a function that calls the data from the database. when the modal is closed this function is called.

sorry for the English , I use google translate.

**Comment by flick36** [comment]
Yeah amm @confeccionar no offense but that english is bad (google translate doesn't translate very well programming stuffs 😆) i believe you speak spanish? if so you can email me, or private chat me on gitter :)
