### ISSUE TITLE
Dialogs not working propertly

### ISSUE THREAD

**Issue by vafl-brut** [jadjoubran/laravel5-angular-material-starter#289]
After generating the dialog with ng:dialog it does show using service's fromTemplate function, but the controller is not assigned it seems and buttons dont get bound to functions. The only way to close the dialog is by hitting Esc.
Am I doing something wrong ? Thanks for this fantastic repo, Jad!

**Comment by flick36** [comment]
Look this: https://github.com/jadjoubran/laravel5-angular-material-starter/issues/287#issuecomment-216327964

**Comment by vafl-brut** [comment]
Thank you, sire!
