### ISSUE TITLE
[Enhancement] Replace livereload with browserSync()

### ISSUE THREAD

**Issue by flick36** [jadjoubran/laravel5-angular-material-starter#290]
Since elixir version 5.1 we have the `browserSync()` task by default, that it's a replacement for the `livereload` plugin in this starter, the most awesome thing that `livereload` does it's the `soft CSS reload` but that seems broken now because of the use of the task `versions()` and it brokes every single time you made a save too fast for example you modify a typo in 2 files and you save them almost instantly it will brake because it's lock, this doesn't happens with `browserSync()` the only tiny problem it's that in order to `browserSync()` to work we have to initialize `artisan serve` like: `artisan serve --host=0.0.0.0` and the task would look like this: `.browserSync({  proxy: 'localhost:8000' })`

**Comment by jadjoubran** [comment]
Yes indeed live reload broke because of the versioning task..
This wouldn't be fixed in browserSync though since we'll have the same issue

But I still see the benefit of removing `laravel-elixir-reload` and relying on elixir..
So yeah why not 😄 
In case you decide to work on it, please let me know so that we don't work on it at the same time

**Comment by flick36** [comment]
Well it's really simply, by just removing the livereload and putting `.browserSync({ proxy: 'localhost:8000' })` instead, you are ready to go

i can create a PR if you want

**Comment by jadjoubran** [comment]
Actually aren't we missing a script for browser sync to work? It's not working right now

**Comment by flick36** [comment]
I've downloaded a clean starter, replace what i changed and it worked, the script in the browser is set automatically by `browserSync()` and you have to start `artisan seve` with a `--host=0.0.0.0` argument

![Example](http://i.imgur.com/FnHLTfz.gif)

**Comment by jadjoubran** [comment]
ah.. I missed the host argument
Thanks for giving it a try
I'll keep this open until I update the docs and release 3.2.1

**Comment by flick36** [comment]
There's a workaround to make `artisan serve` starts by default in `0.0.0.0` host by creating a task inside gulp, and that way with just `gulp && gulp watch` the server will start automtically, but it's not a general solution because it implies the user to set the location to the php path and it's different for every user and SO. but maybe with the implement of #149 or maybe writing in the docs a how-to for those who might  want to do that?

**Comment by jadjoubran** [comment]
Yeah it would be a bit overcomplicated..
I was thinking of creating a `gulp serve` task that runs `gulp` and then 2 parallel processes: `gulp watch` and `artisan serve`
But I'll just update the docs for now

**Comment by jadjoubran** [comment]
This has become a bit redundant now that Laravel valet exists.. What do you think?
I'm personally just using valet since it makes more sense to just go to the url rather than having to run `artisan serve --host=0.0.0.0`

**Comment by flick36** [comment]
thing is that 

> Valet requires the Mac operating system and Homebrew. 

and not everyone develops on Mac, me included (i don't like anything from the apple)

**Comment by jadjoubran** [comment]
Oh that's true.. I forgot about that

**Comment by flick36** [comment]
@jadjoubran Ok so, Mac users have [Laravel Valet](https://laravel.com/docs/5.2/valet) and if you really want to delete this functionality i don't find it useful neither since as you say we have Valet... then Windows users (like me) can use [Laragon](https://laragon.org/) wich i totally recommend. Then you will have to have this very well documented somehow what do you think?

Laragon has some nice built-in utilities like:

> Cmder
> Git
> Node.js
> npm
> SSH
> Putty
> PHP 7 & 5.6 (Easily switchable with one click)
> Activate/deactivate PHP extensions on the fly
> xDebug
> Composer
> Apache
> MariaDB/MySQL
> phpMyAdmin
> Full Lumen and Laravel support
> Auto create virtual hosts
> Mail Catcher - Laragon will show a small window on the bottom right of your screen and help you quickly view content of the generated email
> Mail Sender - You can use mail() function to send mail to Internet easily and effortlessly
> Mail Analyzer: Analyze what happens when email is sent behind the scene and show helpful information to make sure that your email configurations are correct.
> ngrok - allows connections from the Internet to the local server

But what really makes it awesome (beside all of the mention above) is the posibility to Auto create virtual hosts therefore you just make `composer install` in the root folder of laragon and whatever name you use to that folder it will automatically turn in into a domain for example:

`C:\laragon\www\starter` here we install the starter... then laragon automatically creates a `starter.dev` domain how awesome is that?

Here are some nice [tutorials](https://laravelista.com/series/laravel-on-windows-with-laragon)

We will just have to deal with linux users xD but i guess if they're on linux they've probably know how to do things hahaha... but some tutorials as well will be harmless

**Comment by jadjoubran** [comment]
That's great.. so it seems they're have some kind of parity with Laravel valet
This is also what Valet does for the virtual hosts, but it might be missing a lot of features
Anyway thanks for the suggestions, I will revert this and update the docs 👍

**Comment by hackur** [comment]
Very cool. This is a total must-have for windows.
