### ISSUE TITLE
Test seeInDatabase

### ISSUE THREAD

**Issue by dkat101** [jadjoubran/laravel5-angular-material-starter#291]
I found #132 but I just don't understand it. I have followed the starter tutorial and this is my test. 
$project = factory(App\Project::class)->create();

```
    $this->post('/api/project', [
        'user_id' => $project->user_id,
        'name' => $project->name,
        'description' => $project->description
    ])->seeApiSuccess()
        ->seeJsonObject('project')
        ->seeJsonKeyValueString('user_id', $project->user_id)
        ->seeJsonKeyValueString('name', $project->name)
        ->seeJsonKeyValueString('description', $project->description);

    $this->seeInDatabase('projects', [
        'user_id' => $project->user_id,
        'name' => $project->name,
        'description' => $project->description
    ]);
```

this is the response i get after running it.
Failed asserting that '{"errors":false,"data":{"project":{"user_id":2,"name":"Marian Doyle","description":"Animi quis sit culpa eum quam voluptatem voluptate.","updated_at":"2016-05-04 13:17:55","created_at":"2016-05-04 13:17:55","id":24}}}' matches PCRE pattern "/("user_id":"2"|&quot;user_id&quot;:&quot;2&quot;)/i".

**Comment by jadjoubran** [comment]
Hi,

Actually you can now use `->seeJson` instead of the seeJsonKeyValue and seeJsonKeyValueString which have been deprecated

Replace your assertion with this:

```
->seeJson(['user_id' => $project->user_id])
->seeJson(['name' => $project->name])
->seeJson(['description' => $project->description]);
```

and it should work.

Btw your the seeJsonKeyValueString is failing, not your seeInDatabase

Let me know if it fixes it for you 😄

**Comment by dkat101** [comment]
Thanks a bunch. That worked. And thanks for the quick response.
