### ISSUE TITLE
intercept error 401 unauthorized from restangular response and redirect to login page

### ISSUE THREAD

**Issue by chojuanillo** [jadjoubran/laravel5-angular-material-starter#293]
Hi. first of all, to thank the wonderful work you have done with this package, it has helped me a lot as a starting point for my projects and as a base structure for not getting lost in such convergence.
Like my question is a little silly, but do not know how to trap the error 401 unauthorized, when I make a request from restangunlar, after the token has expired, and then redirected to the login page. you could tell me how to do it ?.
thank you very much.

**Comment by flick36** [comment]
assuming you are using the [`Response Macros`](https://laravel-angular.readme.io/docs/response-macros) that are included in this starter you may have something like this: 

``` php
if ( !\Auth::user()->is_verified ){
      return response()->error('Not Authorized', 401);
}
```

that'll return an error so in your method where you are calling Restangular you may have something like this:

``` javascript
this.API.all('clients').post(this.client).then(()=>{
    this.ToastService.show('Succesfull post');
},(response)=>{
    this.ToastService.show('Unsuccessful post');
    if(response.error == 401){
        this.$state.go('app.login');
    }
})
```

Haven't tried the code, but i think that should work, if not, please post some code you have to guide you

**Comment by chojuanillo** [comment]
Thank you very much for the reply. but there would be some way to implement an interceptor, to avoid having to put on each call restangular

**Comment by flick36** [comment]
in the `API.service.js` add:

```
if (response.status === 401) {
    return $state.go('app.login');
}
```

and remove the `|| response.status === 401` from the first `if` at line `15`

of course add the `$state` service to the constructor

**Comment by chojuanillo** [comment]
thank you very much

**Comment by jadjoubran** [comment]
Thanks @flick36 for the amazing help 😄
