### ISSUE TITLE
Third party modules can't able to include 

### ISSUE THREAD

**Issue by aliceopti** [jadjoubran/laravel5-angular-material-starter#301]
I have used **'kendo.directives'** module in index.module.js file , It's always returning

 Module **'kendo.directives'** is not available! You either misspelled the module name or forgot to load it.

But i have added  <script src="http://cdn.kendostatic.com/2014.1.318/js/kendo.all.min.js"></script>

Into my index.blade.php

There's no option to include third party modules for anugular

**Comment by jadjoubran** [comment]
Hi @aliceopti 
How did you install it?
You should be using `bower install` with the `--save` flag

Let me know if it works!

**Comment by aliceopti** [comment]
I have modified my index.modules.js as below 

```
angular.module('app', 
    'kendo.directives'
]);

angular.module('kendo.directives', []);
```

Now that error gone.. but i dont't know how to call gridOptions from component to my view , because am new to angular but well know about laravel

`<select kendo-drop-down-list k-options="vm.phoneOptions" ng-init="vm.activate()"></select>`

The phoneOptions are like

```
vm.phoneOptions = {
            dataSource: {
               data:
                  [
                    {name: "iPhone", id: 1},
                    {name: "Droid", id: 2},
                    {name: "Windows", id: 3}                  
                  ]
            },
            dataTextField: "name",
            dataValueField: "id",
            optionLabel: "Select a phone..."
         }
      }
```

But nothing display in the dropdown

**Comment by pooniv** [comment]
@aliceopti I have also tried the way u have defined here. The kendo options not working in angular components. 

@jadjoubran  : Can you please tell me how to create controllers for the page.I didn't find any folders for controllers..

I'm very new to angular.

**Comment by flick36** [comment]
@aliceopti changue `vm.phoneOptions` in your controller to `this.phoneOptions` <- just in the controller in your view, let it as `vm.phoneOptions`

@pooniv https://github.com/jadjoubran/laravel5-angular-material-starter/issues/245#issuecomment-207478783

**Comment by aliceopti** [comment]
@flick36 @jadjoubran 
**get_all_post.component.js**

```
class GetAllPostController{ 
    constructor(API){
        'ngInject';   
        this.user = { 'name':'Angular component'};
        this.phoneOptions = {
                dataSource: {
                   data:
                      [
                        {name: "iPhone", id: 1},
                        {name: "Droid", id: 2},
                        {name: "Windows", id: 3}                  
                      ]

             }
        }
        this.API = API;

    }

}
export const GetAllPostComponent = {
    templateUrl: './views/app/components/get_all_post/get_all_post.component.html',
    controller: GetAllPostController,
    controllerAs: '$vm',
    bindings: {}

}

```

**get_all_post.component.html**
`<select kendo-drop-down-list k-data-text-field="'id'"  k-data-value-field="'name'" k-options="{{$vm.phoneOptions}}"></select>`

If i defind`controllerAs: 'vm'` , then in my component view 
`<span>Name: {{ vm.user.name }}</span>` Not working .

so i defined like `controllerAs: '$vm',`
and accessing in my view component `<span>Name: {{ $vm.user.name }}</span>`

**index.modules.js**

```
angular.module('app', [
    'app.run',
    'app.filters',
    'app.services',
    'app.components',
    'app.directives',
    'app.routes',
    'app.config',
    'app.partials',
    'kendo.directives',
    'app.controllers'
]);

angular.module('app.run', []);
angular.module('app.routes', []);
angular.module('app.filters', []);
angular.module('app.services', []);
angular.module('app.config', []);
angular.module('app.directives', []);
angular.module('kendo.directives', []);
angular.module('app.components', [
    'ui.router', 'ngMaterial', 'angular-loading-bar',
    'restangular', 'ngStorage', 'satellizer'
]);
angular.module('app.controllers', [
    'ui.router', 'ngMaterial', 'angular-loading-bar',
    'restangular', 'ngStorage', 'satellizer','kendo.directives'
]);

```

This is whole code for creating kendo drop down , this code not at all working for me .. 

Please help me to use kendo in my angular view

**Comment by aarukarthiga** [comment]
@aliceopti ....
in your index.modules.js

Inject your kendo directives 
```
angular.module('app.components', ['kendo.directives',
	'ui.router', 'ngMaterial', 'angular-loading-bar',
	'restangular', 'ngStorage', 'satellizer'
]);
```

And call the kendo inputs in your component file.Hope it will works :-)

**Comment by aarukarthiga** [comment]
@pooniv 
[Refer here](https://github.com/jadjoubran/laravel5-angular-material-starter/commit/ee51d242b037e9c301ec684cef2e20650673aa43)

**Comment by flick36** [comment]
@aliceopti why are you saying that if you dont use the `$` the binding wont work? it should.. if it works with the dollar sign .-. 

and delete this line `angular.module('kendo.directives', []);` and this one `'kendo.directives',` and all the 

```
angular.module('app.controllers', [
    'ui.router', 'ngMaterial', 'angular-loading-bar',
    'restangular', 'ngStorage', 'satellizer','kendo.directives'
]);
```

you don't need those :S

just add `'kendo.directives'` to the `components module`

**Comment by flick36** [comment]
Just delete all those line i've told you and every other change you have made, or if you can start again, with a fresh starter, and open your console on the root directory of the starter and use: `bower install kendo-ui-core -save` wait until it finish, and add the `'kendo.directives'` to your `components module` and you thats it here is a gif for you to see its workig: ![](http://i.imgur.com/KEAJC7v.gif) (sorry for the mess, im playing xD)

**Comment by aliceopti** [comment]
@flick36  @aarukarthiga  

Thanks .. It's working perfectly :+1:

**Comment by jadjoubran** [comment]
Thanks @flick36 for the amazing support!
