### ISSUE TITLE
vendor.js file not created in public folder during Gulp task

### ISSUE THREAD

**Issue by Kirtan-dnp** [jadjoubran/laravel5-angular-material-starter#302]
Hello  I am following your tutorials on this link  ww.sitepoint.com/flexible-and-easily-maintainable-laravel-angular-material-apps/ and it's very helpful but at the time of running gulp task angular was not combine with laravel5.2

If you have any possible solution please reply me.

**Comment by jadjoubran** [comment]
Hi @Kirtan-dnp 
Unfortunately that guide is a big outdated 
I need to add a note to the readme
Can you paste your gulpfile and also show me if you have some errors in your terminal?

**Comment by Kirtan-dnp** [comment]
Hello 
Thanks for your support I past my gulfile.js and I terminal screenshot & console screenshot.

gulfile.js:
var elixir = require('laravel-elixir');

/*
 |--------------------------------------------------------------------------
 | Elixir Asset Management
 |--------------------------------------------------------------------------
 |
 | Elixir provides a clean, fluent API for defining some basic Gulp tasks
 | for your Laravel application. By default, we are compiling the Sass
 | file for our application, as well as publishing vendor resources.
 |
 */

/_elixir(function(mix) {
    mix.sass('app.scss');
});_/

var elixir = require('laravel-elixir');
require('./tasks/angular.task.js');
require('./tasks/bower.task.js');
require('laravel-elixir-livereload');

elixir(function(mix){
    mix
        .bower()
        .angular('./angular/')
        .copy('./angular/app/**/*.html', 'public/views/app/')
        .copy('./angular/directives/**/_.html', 'public/views/directives/')
        .copy('./angular/dialogs/__/_.html', 'public/views/dialogs/')
        .livereload([
            'public/js/vendor.js',
            'public/js/app.js',
            'public/css/vendor.css',
            'public/css/app.css',
            'public/views/*_/_.html'
        ], {liveCSS: true});
});

![terminal](https://cloud.githubusercontent.com/assets/17508958/15204464/3f41a252-182b-11e6-9fd0-d4c4fb7750e6.png)
![console](https://cloud.githubusercontent.com/assets/17508958/15204471/48dc42d6-182b-11e6-94de-6874b05621ab.png)

**Comment by flick36** [comment]
Hi @Kirtan-dnp first of all if you could please use 3 backticks and a new line to format your code ```

You shouldn't copy the angular folder to anywhere, so you can delete all those copy on the `gulpfile.js` can you please post the `./tasks/angular.task.js` too?

**Comment by jadjoubran** [comment]
@Kirtan-dnp Any updates on this?

**Comment by Kirtan-dnp** [comment]
Hi Jad,

Thanx for your support ! I was trying to create compiled version of angular app file using gulptask but it was giving me error like described above. Now i solved it but seriously i would love to have your updated guide about this article. Thanx again ! 
ww.sitepoint.com/flexible-and-easily-maintainable-laravel-angular-material-apps/

**Comment by jadjoubran** [comment]
Thanks @Kirtan-dnp!
The reason why it will be so hard to update that post, is that the package has evolved a lot since I wrote the article.. so many changes & contributions went into it
