### ISSUE TITLE
Help me to save logged In user credentials

### ISSUE THREAD

**Issue by aarukarthiga** [jadjoubran/laravel5-angular-material-starter#304]
Any one please tell me how to store the user details like php session. in angular ?

To check whether user logged in or not to show log out

**Comment by flick36** [comment]
There are millions way to do that

https://github.com/jadjoubran/laravel5-angular-material-starter/issues/286#issuecomment-216123792

**Comment by jadjoubran** [comment]
@aarukarthiga was your issue solved?

**Comment by aarukarthiga** [comment]
@jadjoubran ..am trying to save my logged user details using ngstroage and trying to write a service for  authenticate . if the user logged in only open the page  , otherwise ask them to login.

Still trying to write a service. Am beginner of angular.

Any idea?

**Comment by flick36** [comment]
@aarukarthiga i think this will work for you https://github.com/jadjoubran/laravel5-angular-material-starter/pull/297

**Comment by aarukarthiga** [comment]
@flick36  I have saved the logged user details in my $localstorage. That's works..perfectly..

I'm trying to write a service like API,Toast ,..etc.. AUTHSERVICE  to use my  profile page ..to check the user is logged or not ?

Any idea about ?

**Comment by aarukarthiga** [comment]
```
console.log(this.StorageService.set({userid: "shivraj", lname: "rath"})); -- Return TRUE
         console.log(this.StorageService.get("userid")); -- Always return undefined
```
I have attached my storageservice
[storage.service.txt](https://github.com/jadjoubran/laravel5-angular-material-starter/files/274427/storage.service.txt)

**Comment by aarukarthiga** [comment]
Getting 

`ReferenceError: angular is not defined`

How to solve this .. i duknw why is coming

**Comment by flick36** [comment]
@aarukarthiga but why would you want to create something that already exists? just inject `$auth` in any controller and `this.$auth.isAuthenticated()` return a boolean `true` if the user is logged and false if it's not

**Comment by aarukarthiga** [comment]
@flick36  Thanks. But how can i get auth user details like user name , email , user_id ? Is there any default stroage in $auth class? 

I didn't used $auth..

**Comment by aarukarthiga** [comment]
@jadjoubran .. My issue solved..:)

**Comment by jadjoubran** [comment]
Great 👍 😄
