### ISSUE TITLE
Unable to authenticate with invalid token. status_code:401

### ISSUE THREAD

**Issue by dkat101** [jadjoubran/laravel5-angular-material-starter#305]
My test for saving a new user is

```
$this->authUserPost('/api/user/new', [
            'u_id' => $faker->u_id,
            'f_name' => $faker->f_name,
            'l_name' => $faker->l_name,
            'email' => $faker->email,
            'password' => $faker->password,
            'remember_token' => $faker->remember_token
        ])->seeApiSuccess()
            ->seeJson(['data' => true])
            ->seeJson(['errors' => false]);
```

and it's returning

> Unable to find JSON fragment ["errors":false] within [{"message":"Unable to authenticate with invalid token.","status_code":401}]

**Comment by jadjoubran** [comment]
Hi @dkat101 
could you show your routes file?

**Comment by dkat101** [comment]
```
<?php

Route::get('/', 'AngularController@serveApp');
Route::get('/unsupported-browser', 'AngularController@unsupported');

Route::group(['middleware' => ['web']], function () {
});

$api->group([], function ($api) {
    $api->post('users/login', 'LoginController@login');
});

//protected routes with JWT (must be logged in to access any of these routes)
$api->group(['middleware' => 'api.auth'], function ($api) {
    $api->get('user/single/{u_id}', 'UserController@getSingle')
        ->where('u_id', '[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}');
    $api->get('user/list', 'UserController@getList');
    $api->post('user/new', 'UserController@create');
    $api->post('user/edit/{u_id}', 'UserController@update');
    $api->post('user/delete/{u_id}', 'UserController@delete');
});
```

**Comment by jadjoubran** [comment]
hmm I don't see anything wrong here..
are you doing any auth check in your method `@create`?

**Comment by dkat101** [comment]
This is my UserController create method

```
public function create(Request $request) {
        $this->validate($request, [
            'f_name' => 'required|string',
            'l_name' => 'required|string',
            'email' => 'required|email',
            'password' => 'required|string'
        ]);

        $user = new User();
        if($request->input('u_id') != '') {
            $user->u_id = $request->input('u_id');
        } else {
            $user->u_id = Uuid::uuid();
        }
        $user->f_name = $request->input('f_name');
        $user->l_name = $request->input('l_name');
        $user->email = $request->input('email');
        $user->password = $request->input('password');

        return response()->success($user->save());
    }
```

**Comment by jadjoubran** [comment]
I couldn't find anything wrong with your code :/
do you still have this issue?

**Comment by dkat101** [comment]
yes, am still having that problem. Below is the response.

> There was 1 failure:
> 
> 1) UserTests::testUserCRUD
> Unable to find JSON fragment ["errors":false] within [{"message":"Unable to authenticate with invalid token.","status_code":401}].
> Failed asserting that false is true.
> 
> /home/vagrant/laravel/mockup/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/MakesHttpRequests.php:300
> /home/vagrant/laravel/mockup/tests/TestCase.php:52
> /home/vagrant/laravel/mockup/tests/UserTests.php:26
> 
> FAILURES!
> Tests: 1, Assertions: 1, Failures: 1.

**Comment by flick36** [comment]
I don't really know anything about tests (i really have to get started with those so any good tutorials will do me great) but, i think maybe, the error is because you have the route in a protected route on wich you have to be logged in, in order to create a new user and when you are doing your test with `$this->authUserPost('/api/user/new', [` you need to have a real token? .-.

**Comment by dkat101** [comment]
Laravel comes with authentication functionality out of the box. This also includes a user class used for registration. Now i wrote my own user class so i think functionality is conflicting.

**Comment by dkat101** [comment]
the whole aim of this issue is to test the CRUD methods on the user controller. Does anyone know how to test these CRUD methods?

**Comment by jadjoubran** [comment]
You would just add a `$this->seeInDatabase()` at the end
https://laravel.com/docs/5.2/testing#working-with-databases

**Comment by dkat101** [comment]
@jadjoubran am creating my custom user.

```
$this->authUserPost('user/new', [
            'u_id' => 'a20e0620-353d-36b1-9c87-0d985c2a8162',
            'f_name' => 'admin',
            'l_name' => 'admin',
            'email' => 'admin@local.test',
            'password' => bcrypt(1234),
            'remember_token' => str_random(10)
        ])
```

but that is not the user that is created and instead another user is created.

**Comment by jadjoubran** [comment]
Hi @dkat101 
You shouldn't pass the bcrypted password here.. 
If you can show me 2 pastebins/gists of your code I can probably make it work 😄

**Comment by dkat101** [comment]
I have uploaded the code to this repo

https://github.com/dkat101/mockup.git

**Comment by jadjoubran** [comment]
@dkat101 I just cloned it, setup the database and ran the migrations
but it seems you deleted the users' table migration..
maybe that's the issue?

**Comment by dkat101** [comment]
i deleted the initial user migration file and and created another.

**Comment by jadjoubran** [comment]
but it doesn't seem to be checked in.. can you please double check?

**Comment by dkat101** [comment]
Sorry, I was not tracking it. But i have added it now.

**Comment by jadjoubran** [comment]
okay so I'm finding a couple of issues, I will let you know as I go through them
1. The file and class name must be UserTest (rather than UserTests) for them to be pickedup by phpunit
2. You should add the prefix `/api/` to your route:
   `$this->authUserPost('api/user/new',`
   (it was missing from this route)
3. You can add `->dump()` to get the output of the endpoint

**Comment by jadjoubran** [comment]
1. the reason why it's failing, is because you've changed the primary key from `id` to `u_id` and only mentioned it in the model. You need to also update your `config/jwt.php` file. If you update it, there and set

``` php
    'identifier' => 'u_id',
```

it will work.
However you will get other issues that the `User` needs to be imported

Good luck and let me know if it works for you
