### ISSUE TITLE
Do not to use nghtml2js

### ISSUE THREAD

**Issue by lsosa3** [jadjoubran/laravel5-angular-material-starter#306]
Hi Jad, I am using your project for a personal project , is there any way to not use nghtml2js ? since the vendor.js and vendor.js.map file grows very large and takes a while to load the site .

By the way, awsome project.

**Comment by flick36** [comment]
Just delete the `.ngHtml2Js('./angular/**/*.html')` line in the `gulpfile.js` file if you don't want to use it

**Comment by jadjoubran** [comment]
True lazy loading the views makes sense in a lot of scenarios
As @flick36 mentioned you'd just have to remove that line and remove the partial scripts from your `index.blade.php`
