### ISSUE TITLE
Updating project

### ISSUE THREAD

**Issue by ShamarKellman** [jadjoubran/laravel5-angular-material-starter#308]
Hi, I am using this for a project and I would like to know the method for updating the project to the newest version

**Comment by Neo-89** [comment]
https://laravel-angular.readme.io/docs/upgrade-guide
Have you read it?

**Comment by jadjoubran** [comment]
Thanks @Neo-89 
@ShamarKellman if you're upgrading from 3.0 to 3.1, you need to go into the docs for 3.1 and look for the upgrade guide from 3.0
