### ISSUE TITLE
File not found in apache web server

### ISSUE THREAD

**Issue by num3r06** [jadjoubran/laravel5-angular-material-starter#309]
Hi, I try this installation and all work fine.
If i use php artisan serve localhost:8000 respond correctly.
If i use normal address of my bitnami wampstack http://localhost:8080/laravel_angular/public the chrome's console respond with:
http://localhost:8080/build/css/vendor-0c77a86012.css Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:8080/build/css/app-1c059c744c.css Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:8080/build/js/vendor-82b01a1c34.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:8080/build/js/partials-7ef26a69d1.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:8080/build/js/app-f82b347911.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:35729/livereload.js?snipver=1 Failed to load resource: net::ERR_CONNECTION_REFUSED
http://localhost:8080/build/css/vendor-0c77a86012.css Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:8080/build/css/app-1c059c744c.css Failed to load resource: the server responded with a status of 404 (Not Found)
Seems failed to find correct resources (the path seems to be wrong, misses installation folder).
I don't know if is a issue of elixir/gulp
Regards
num3r06

**Comment by jadjoubran** [comment]
Hi @num3r06 
Did you run `gulp`?
You can find the detailed [installation instructions](https://laravel-angular.readme.io/docs/install#beginner-friendly-installation)

**Comment by num3r06** [comment]
I ran gulp and work fine. The build folder is full of necessary file but the reference in the code go to wrong folder (at the web server's root and not at the installation folder)

Salvatore Morante
Il 17/05/2016 11:21:50, Jad Joubran notifications@github.com ha scritto:
Hi @num3r06 [https://github.com/num3r06]
Did you run gulp?
You can find the detailed installation instructions [https://laravel-angular.readme.io/docs/install#beginner-friendly-installation]

**Comment by jadjoubran** [comment]
hmm I didn't get what you mean..

**Comment by num3r06** [comment]
I follow the installation instruction and all work fine (also gulp && gulp watch). If i use php artisan serve the app works.
The installation folder is in htdocs/l5_ang of the apache web server.
If i use http://localhost:8080/l5_ang/public (how i ever make with the other laravel app) the browser remain in blank page and in console i have the errors not found css and js

**Comment by num3r06** [comment]
this is the blank page with error of browser
![error](https://cloud.githubusercontent.com/assets/7809704/15318695/89f6e366-1c27-11e6-9edc-0312b1aa1ae4.png)

**Comment by jadjoubran** [comment]
Ah okay well that makes sense because it needs to be served from within the `public` app.. just like any other Laravel app
Not to mention the security risk of exposing the whole application as the webroot

**Comment by num3r06** [comment]
Tthe app is conteined in a folder within webroot but the resouces path (css and js) seems to be in the webroot

**Comment by num3r06** [comment]
i've fix it replacing {!! elixir('css/vendor.css') !!} with {!! asset('css/vendor.css') !!} and all others in the index.blade.php after viewing #2 screencast
thx

**Comment by num3r06** [comment]
Sorry but doesn't works.... :(
When i try login feature i've got an error not found http://localhost:8000/api/auth/login.
Another time going to resource in webroot while the app is in subfolder

**Comment by num3r06** [comment]
Sorry for long conversation. I've learned elixir concept in the laravel doc and i've understand where i mistake.
I believe the only solution it's using apache's virtual host for using absolute path of asset
thx for the support
