### ISSUE TITLE
Redirect state issue

### ISSUE THREAD

**Issue by pooniv** [jadjoubran/laravel5-angular-material-starter#310]
After login i would like to redirect my page to profile page..so i have used 

`this.$state.go('profile');`

But throwing error 

`Error: _this.$state is undefined`

Why it's happening and also for $localstorage 

`$localStorage.username = user.name;`

Please help

**Comment by aarukarthiga** [comment]
@pooniv  Try 

`this.$state.go('app.profile');`

`this.$localStorage.username = user.name;`

It will works !

**Comment by jadjoubran** [comment]
@pooniv I think you're using a `function()` instead of an arrow function (`() => {}`) which doesn't have access to the same `this` scope..
If you use an arrow function, it should work
