### ISSUE TITLE
Gulp & browserSync issue

### ISSUE THREAD

**Issue by aliceopti** [jadjoubran/laravel5-angular-material-starter#312]
I'm using browserSync instead of livereload. But the browserSync not working as per the expectation.

And if i change any thing in my controller or view file every time i need to run gulp after that only i can able to view my changes.. If i refresh the page the changes are not reflected, only gulp run only reflecting my changes..

Without gulp i cant see my changes? Why it's happening?

**Comment by flick36** [comment]
How are you serving the page? you have to use `artisan serve --host=0.0.0.0`

**Comment by aliceopti** [comment]
@flick36 ..its works perfect ...Great man !..It was work in local good..how it will be act in liver server...can u explain?

**Comment by jadjoubran** [comment]
@aliceopti on a live server you would have a virtual host pointing to `/public` which will make it work

**Comment by flick36** [comment]
@aliceopti it really depends on your server bro, you might be using, a VPS, or a shared hosting, and if you are using a VPS or a dedicated server you might have nginx or Apache and depending on your hosting provider, you can do certain things or not, and there are a lot of ways to serve the app, i can recommend you something but maybe it doesnt fit your needs, or maybe there's a better way to do it, but yeah basically as @jadjoubran said 

> you would have a virtual host pointing to `/public` which will make it work
