### ISSUE TITLE
Laravel Routes Test Error

### ISSUE THREAD

**Issue by RVidal111** [jadjoubran/laravel5-angular-material-starter#313]
I have the original document for the v. 3.2 and i don't edit anything. When i do the Step following the youtube's tutorial that i have to insert in the console phpunit, this declare that i have a Fail. And is this:

LaravelRoutesTest::testLandingResponseCode Failed asserting that 500 matches expected 200

C:\xampp\htdocs\ECOMotoAPI\API\test\LaravelRoutesTest.php:15
C:\xampp\php\pear\PHPUnit\TextUI\Command.php:176
C:\xampp\php\pear\PHPUnit\TextUI\Command.php:129

The original code from teh project is:

``` php
<?php


class LaravelRoutesTest extends TestCase
{
    /**
     * A basic functional test example.
     *
     * @return void
     */
    public function testLandingResponseCode()
    {
        $response = $this->call('GET', '/');

        $this->assertEquals(200, $response->status());
    }

    public function testUnsupportedBrowserPage()
    {
        $this->visit('/unsupported-browser')
             ->see('update your browser')
             ->see('Internet Explorer');
    }
}
```

I have to change this line: 

`$this->assertEquals(200, $response->status());`

for this?

`$this->assertEquals(500, $response->status());`

If i do this the Fail don't appear, but i don't know if is the correct solution.

**Comment by jadjoubran** [comment]
Hi @RVidal111 
If you  run `php artisan serve` and browser to `localhost:8000` does the site load?
Also have you finished all installation steps?
