### ISSUE TITLE
API Routes 404

### ISSUE THREAD

**Issue by followtheart** [jadjoubran/laravel5-angular-material-starter#316]
Default  routes;
When user register ,get error 404;
and dingo/api routes `php artisan api:routes` not included in `php artisan route:list`?
![image](https://cloud.githubusercontent.com/assets/7168292/15456560/ecbc9062-20a6-11e6-9937-8bdb6b031057.png)

Any help,thx

**Comment by flick36** [comment]
Can you post the error please?

The api routes won't show up in the regular routes command as they're not registered alongside Laravel routes.

**Comment by jadjoubran** [comment]
Yes please
The registration url in satellizer.conf.js is `/api/auth/register` which shows up here
then maybe there's another issue

**Comment by followtheart** [comment]
After many tests;
Found that API works with `php artisan serve --host=0.0.0.0`,but not working with 
`php artisan serve` nor apache server

**Comment by flick36** [comment]
No, and it's not starter fault, `elixir` doesn't work with default serve using  `browsersync` you have to use the `--host =0.0.0.0`flag don't know why :V maybe an `elixir` bug as i explain here, when propose the change https://github.com/jadjoubran/laravel5-angular-material-starter/issues/290

**Comment by followtheart** [comment]
Well ,It seems work now...................
