### ISSUE TITLE
ng:directive for resposive tabs

### ISSUE THREAD

**Issue by aliceopti** [jadjoubran/laravel5-angular-material-starter#317]
I have created directive for responsive tabs referrence followed in  
[http://codepen.io/alisuarez/pen/qOvjLa](http://codepen.io/alisuarez/pen/qOvjLa)

Any created directive as like below 

```
class ReponsiveTabsController{
    constructor(){
        'ngInject';

        //
    }
}

export const ReponsiveTabsDirective = {
    controller: ReponsiveTabsController,
    restrict: 'A',
    link: function(scope, element, attrs, controllers){
         element.responsiveTabs({
        startCollapsed: false
      });
    }
}
```

How can i access it in view ???  and how it will be work please any one help me

**Comment by jadjoubran** [comment]
Hi @aliceopti 
What do you mean by access it in the view?

**Comment by aliceopti** [comment]
@jadjoubran  ..like component we are using in pages like

`<create-post-form></create-post-form>`

How to use directive and i want responsive tabs ..in my page ..help me

**Comment by flick36** [comment]
This starter uses `angular material` wich already have [tabs](https://material.angularjs.org/latest/demo/tabs) any particulary reason you need a directive that for what i can see uses jquery? :confused:

**Comment by aliceopti** [comment]
@flick36 ...Angular default tab on responsive it's shows like regular scroll able tabs...But i want on responsive the tabs act like accordion ...as per the example link i mentioned [http://codepen.io/alisuarez/pen/qOvjLa](http://codepen.io/alisuarez/pen/qOvjLa)

My requirement is responsive tab accordion ..that's why i want the directive as per the example..but i'm beginner of this angular material ..so i need a help from you guys.. 

If anyone helped me...tats great for me to work on directives.

Advance thanks

**Comment by flick36** [comment]
@aliceopti it's really hard to read(understand) you bro :S what's your native language?(maybe we speak the same and can understand you better) the directive you post, works? have you tried it? I don't know if it works and i don't have a way to try it by myself, because i don't use the modules you use since they're not in the starter, and to be honest... the issues here are for this repository, and your issue here, doesn't seems to be a `laravel5-angular-material-starter` issue, it sounds more like a problem you have... there are sites like [Codementor](https://www.codementor.io/jadjoubran) (notice @jadjoubran it's actually there) where you can hire people to help you to do something, i mean i don't have any problem on helping you but..come one.. so, to answer the question you ask in the post...

`How can i access it in view ???` 

well you have your component `<create-post-form></create-post-form>` that has it's html template, in the `angular/app/component/create-post-form/create-post-form.html` file, wich im gonna assume it's the same as you codepen.

```
<div class="container" ng-app="myApp">
  <div class="row">
    <div class="col-lg-12">
      <div id="responsiveTabs" responsive-tabs>
        <ul>
          <li><a href="#tab-1"> Tab 1 </a></li>
          <li><a href="#tab-2"> Tab 2 </a></li>
          <li><a href="#tab-3"> Tab3 </a></li>
        </ul>

        <div id="tab-1"> Content tab 1 </div>
        <div id="tab-2"> Content tab 2 </div>
        <div id="tab-3"> Content tab 3 </div>
      </div>
    </div>
  </div>
</div>
```

there... that's how you access it on the view, the same you way you do on your codepen

**Comment by aliceopti** [comment]
@flick36 ..Sorry for my English. My native language not English.

My question is very simple only. I would like to use directive in that angular material.

I have created my test directive using ng:directive responsive_tabs , now i have responsivetabs controller function in my responsive_tabe directive folder.

```
class ReponsiveTabsController{
    constructor(){
        'ngInject';

        //
    }


}

export const ReponsiveTabsDirective = {
    controller: ReponsiveTabsController,
    restrict: 'A',
    link: function(scope, element, attrs, controllers){
         element.responsiveTabs({
            startCollapsed: false
          });
    }
}
```

In my component controller class i try to use my directive (responsive )

```
export const FilePostComponent = {
    templateUrl: './views/app/components/file_post/file_post.component.html',
    controller: FilePostController,
    controllerAs: 'vm',
    bindings: {},
    directives: 'ReponsiveTabsDirective'
}
```

In that component html file I have call the directive 

```
<div id="responsiveTabs" responsive-tabs>
        <ul>
          <li><a href="#tab-1"> Tab 1 </a></li>
          <li><a href="#tab-2"> Tab 2 </a></li>
          <li><a href="#tab-3"> Tab3 </a></li>
        </ul>

        <div id="tab-1"> Content tab 1 </div>
        <div id="tab-2"> Content tab 2 </div>
        <div id="tab-3"> Content tab 3 </div>
      </div>
```

It's not working ... .

**Comment by flick36** [comment]
update the generatoros with `composer update laravelangular/generators` the directives returns a function not an object https://github.com/jadjoubran/laravel5-angular-material-starter/issues/279

your directive should look like this:

```
class ResponsiveController{
    constructor(){
        'ngInject';
    }
}

export function ResponsiveTabsDirective(){
    return {
        controller: RedirectTabsController,
        restrict: 'A',
        link: function(scope, element, attrs, controllers){
         element.responsiveTabs({
            startCollapsed: false
          });
        }
    }
}
```

As i say i don't use your modules so i don't know if your function works but here's an example showing just console messages:

![](http://i.imgur.com/E28Tzwg.gif)

and you don't need `directives: 'ReponsiveTabsDirective'`

**Comment by aliceopti** [comment]
@flick36 ..Thanks.. Now it's working for me.. 

When we can use controller and link in the directives ?

 `responsive-tabs` is means to `'ResponsiveTabsDirective`

**Comment by flick36** [comment]
Cool, you're welcome, well it really depends on when you want your code to run here, read [this](http://jasonmore.net/angular-js-directives-difference-controller-link/)

> Angular directives can be a black hole of thoughts, and one of those being, “where do I put code, in ‘controller’ or ‘link’?”
> 
> The **short short** answer: **‘link’**.
> 
> The **longer short** answer: Ask yourself “when do I want my code to run?”
> 
> Before compilation? – **Controller**
> After compilation? – **Link**

**Comment by pooniv** [comment]
@flick36 if i have a function inside directive controller... how could i call ?

```
class ResponsiveTabsController{
    constructor(){
        'ngInject';
    }

    show(){
        console.log('alert');
    }
}

export function ResponsiveTabsDirective(){
    return {
        controller: ResponsiveTabsController,
        link: function(scope, element, attrs, controllers){

            console.log("I'm link");
        }
    }
}
```

I want call show() alone ?

**Comment by aarukarthiga** [comment]
@pooniv  You can call your function in link like 

`controllers.show()`

**Comment by flick36** [comment]
The link functions receives 4 params, that in order, they're generated as, `scope, element, attributes and a controller` you can name them as you want actually, you can have for example `s, e, a, c` it does'nt really matter, and how you named the 4th attibute it's how you gonna call the controller, if you left them as default, then as @aarukarthiga said, you'll access it as `controllers.show()` in your example

**Comment by jadjoubran** [comment]
Feel free to re-open if you still have issues 😄

**Comment by bhagu31** [comment]
i want to load a content when i click on tab .. do anybody has any idea ?

```
<div id="responsiveTabs" responsive-tabs>
        <ul>
          <li><a href="#tab-1"> Tab 1 </a></li>
          <li><a href="#tab-2"> Tab 2 </a></li>
          <li><a href="#tab-3"> Tab3 </a></li>
        </ul>

        <div id="tab-1"> Content tab 1 </div>
        <div id="tab-2"> Content tab 2 </div>
        <div id="tab-3"> Content tab 3 </div>
      </div>

function ResponsiveTabsDirective(){
    return {
        controller: RedirectTabsController,
        restrict: 'A',
        link: function(scope, element, attrs, controllers){
         element.responsiveTabs({
            startCollapsed: false
          });
        }
    }
}
```
