### ISSUE TITLE
Login: "Remember me"

### ISSUE THREAD

**Issue by clementbirkle** [jadjoubran/laravel5-angular-material-starter#318]
Hi,

I want to give my users the option "Remember me" to check when they log in.

Is it possible technically ? Could you please tell me what files i should modify?

Thank you in advance ! :)

**Comment by aarukarthiga** [comment]
@Clem01 

```
if (Auth::attempt(['email' => $email, 'password' => $password], $remember))
{
    // The user is being remembered...
}
```

`$remember` is Boolean `true or false.`

**Comment by clementbirkle** [comment]
Thank you @aarukarthiga for this solution.

The login uses other class / method of the original Laravel Auth. In AuthController.php, we can see the following: 

```
        try {
            // verify the credentials and create a token for the user
            if (! $token = JWTAuth::attempt($credentials)) {
                return response()->error('Invalid credentials', 401);
            }
        } catch (\JWTException $e) {
            return response()->error('Could not create token', 500);
        }
```

Apparently, the method JWTAuth::attempt() doesn't have a third argument.

--- EDIT ---

```
    /**
     * Attempt to authenticate the user and return the token.
     *
     * @param array $credentials
     * @param array $customClaims
     *
     * @return false|string
     */
    public function attempt(array $credentials = [], array $customClaims = [])
    {
        if (! $this->auth->byCredentials($credentials)) {
            return false;
        }

        return $this->fromUser($this->auth->user(), $customClaims);
    }
```

**Comment by flick36** [comment]
See this: https://github.com/tymondesigns/jwt-auth/issues/570

You'll have to save the token in `localStorage`here's one [example](http://stackoverflow.com/a/35891353)

**Comment by clementbirkle** [comment]
Thank you @flick36, this allowed me to find the solution => just this:

```
if ($request->rememberMe) {
    config(['jwt.ttl' => (60*24*60)]);
}
```

It works well !

**Comment by flick36** [comment]
@Clem01 that won't 'remember' the user, it'll just make the token valid for 60 days. wich may have the sensation of remember me functionality but it's not the nice thing to do i believe. Once #149 are ready, i'll make a 'remember me' functionallity recipe using localStorage

**Comment by clementbirkle** [comment]
Thank you very much @flick36. It's great news, i'm looking forward to your solution!
