### ISSUE TITLE
SEO considerations (e.g. prerender.io server)?

### ISSUE THREAD

**Issue by dyial** [jadjoubran/laravel5-angular-material-starter#32]
I know this is slightly tangential, but a few of my AngularJS sites have been hit with an SEO penalty a couple of months back since I assumed Google could crawl big JavaScript apps fine (turns out it cannot). 

To be on the safe side do you think it's possible to use a package such as @JeroenNoten's https://github.com/JeroenNoten/Laravel-Prerender (this hasn't been updated to 5.1 unfortunately) and a simple deploy script to set up our own prerender.io server on Forge? Just thought I'd ask, I think a safe fallback for SEO should play a part in this amazing project :smile:

**Comment by jadjoubran** [comment]
Hey!

Thanks for the feature suggestion!
I just got back from travel, so I'll take a look at this tomorrow and I'll let you know :D

Make sure to star the repository in the meantime

**Comment by jadjoubran** [comment]
Hey @dyial 
Now that the upstream library has been fixed fro 5.1
Have you ever worked with it before?
Do you have some recommendations?

**Comment by dyial** [comment]
Hi @jadjoubran, sorry I've been really busy the last couple of weeks but I'll try and set up a prerender server on Forge soon. Keep up the great work :smile:

**Comment by jadjoubran** [comment]
Awesome great!
I'll wait for your feedback
Do you think you'll be able to provide a PR?

And I guess we only need to pretend just the main route `/`. Is that true?

**Comment by jadjoubran** [comment]
According to [this](https://googlewebmastercentral.blogspot.com/2015/10/deprecating-our-ajax-crawling-scheme.html) and many other resources, it doesn't seem to me that a solution such as prerender is useful.. no?

Feel free to re-open
