### ISSUE TITLE
Laravel Angular Material with firebase database

### ISSUE THREAD

**Issue by aarukarthiga** [jadjoubran/laravel5-angular-material-starter#322]
Hi @jadjoubran 

Is this possible to create chat application using (Laravel Angular Material + Firebase) 

I think fire base is a temporary data base to sync data. But i don't know about depth knowledge about firebase database.

Thanks in advance

**Comment by jadjoubran** [comment]
Hi @aarukarthiga 
Yes you should be able to use it.. but if you're completely relying on firebase then I don't think you'd need Laravel no?

**Comment by aliceopti** [comment]
@jadjoubran @flick36 

I have one doubt... I want to use this laravel angular material web application in offline mode .ie ..without internet also this application need to work ..for like upload a file in offline mode..one's internet connected automatically my script will have to detect that uploaded file and update to server and database..

Is quite difficult using this ?? Or which one is possible to achieve?

**Comment by flick36** [comment]
That's imposible, how would make it work offline and then online? you have to have the project files in a server wich is accesible via internet if you are on production or locally if you are on deployment, but you cant have in both, explain to me how are you serving the app? or how are you planning to do so?

**Comment by jadjoubran** [comment]
You could probably still do that with Service Workers..
I was actually planning on releasing version 3.3 which has a Progressive Web App setup 😄 
But I won't be able to do that before the next few weeks
so @aliceopti research how you can make your app work offline with service workers, it has nothing to do with the setup that we have

**Comment by jadjoubran** [comment]
Feel free to re-open if you still need help 😄
