### ISSUE TITLE
Angular Config: add settings

### ISSUE THREAD

**Issue by clementbirkle** [jadjoubran/laravel5-angular-material-starter#324]
Hello,

I would like to add a configuration file (settings) to recover some variables that I could reuse in: controllers, components, services, etc. Example: public key of reCaptcha.

I think we should add a file in the config directory but I do not understand how it works.

Does someone could give me a small example please? Thank you very much in advance!

**Comment by aarukarthiga** [comment]
Create file under config folder `settings.php`

inside 
```

return [

    'captcha_key' => 'ABCDEF',

];  
```

Then call your controller like` Config:get('settings.captcha_key')`

**Comment by jadjoubran** [comment]
yep, just like @aarukarthiga said
And then you could add the key in your `.env` so that you don't commit it inside your git repo
so instead of 'ABCDEF' you can do `env('captcha_key', 'optional default value');`
and add

```
captcha_key=ABCDEF
```

to your `.env`

**Comment by clementbirkle** [comment]
Houps, i am confused but i wanted to speak about Angular JS not about Laravel^^

**Comment by flick36** [comment]
You can add in you `index.modules.js` file at the very end or at the begging or anyway you like after any  `module` for example:

`angular.module('app.run', []);`

```
angular.module('app.run', []).constant('config', {
        PUBLIC_CAPTCHA_KEY: 'your_captcha_key',
        SOME_OTHER_CONSTANT: 'your_other_constant'
    });
```

and you can now inject it in any controller in this example:

in any constructor you just inject `config` (wich is the constant name)

```
class ExampleController {
    constructor(config){
        this.config = config;
    }
    $onInit(){
        console.log(this.config.PUBLIC_CAPTCHA_KEY);
    }
}
export const ExampleComponent = {
    templateUrl: './views/app/components/example/example.component.html',
    controller: ExamplerController,
    controllerAs: 'vm',
    bindings: {}
}

```

that's the easy way, of course you can create a new file named `index.constants.js` with a module inside named

```
angular.module('app.constants', []).constant('config', {
        PUBLIC_CAPTCHA_KEY: 'your_captcha_key',
        SOME_ODER_CONSTANT: 'your_other_constant'
    });
```

import it in the `index.main.js` as: `import './index.constants';` and a think that's it if i'm not missing something :stuck_out_tongue_winking_eye:

**Comment by clementbirkle** [comment]
Wahouu, it's amazing !! Thank you very much for your example, i implemented it and it works very well. ;)
