### ISSUE TITLE
missing .bowerrc for custom bower_components directory

### ISSUE THREAD

**Issue by eelco2k** [jadjoubran/laravel5-angular-material-starter#328]
After trying to install laravel5-angular-material-starter project i noticed that the bower_components were in the app folder. This is which is strange... 

so I added a .bowerrc to overwrite the location to the root folder, i'm not sure if this is default behaviour or only in my situation.

so i added the following in root folder into .bowerrc file:

`{
  "directory" : "bower_components"
}`

**Comment by syzygyinteractivemedia** [comment]
found it, was my problem. Had .bowerrc in my home directory.
