### ISSUE TITLE
Dependency issue with npm v2.14

### ISSUE THREAD

**Issue by applecrusher** [jadjoubran/laravel5-angular-material-starter#33]
root@karl:/var/www/html/laravel5-angular-material-starter# npm install -g gulp bower
^Croot@karl:/var/www/html/laravel5-angular-material-starter# npm install
npm WARN package.json @ No repository field.
npm WARN package.json @ No license field.
npm WARN unmet dependency /var/www/html/laravel5-angular-material-starter/node_modules/laravel-elixir requires gulp-minify-css@'^1.2.0' but will load
npm WARN unmet dependency /var/www/html/laravel5-angular-material-starter/node_modules/gulp-minify-css,
npm WARN unmet dependency which is version 0.3.13

**Comment by jadjoubran** [comment]
Hi @applecrusher 
Thanks for reporting this.
Did your `npm install` command crash? or these were simple warnings that were thrown out on the screen?

Because it's fine to get warnings when running `npm install`.

**Comment by jadjoubran** [comment]
Feel free to re-open if this if it's still having issues
Thanks!
