### ISSUE TITLE
Not able to see create-post page  in "Posts" Tutorial

### ISSUE THREAD

**Issue by sjanakir2015** [jadjoubran/laravel5-angular-material-starter#330]
I'm submitting a 
- [x] support request.

Hello,

I am new to js and angular. I have followed your tutorial in
https://laravel-angular.readme.io/docs/tutorial-overview and tried to get the application which adds posts (name,topic) to a database, running.

I am working in Windows 10.  
For brevity, in the following comment,
L5AMS = "laravel5-angular-material-starter"
(Folder created by "composer create-project ..." command)

File: L5AMS/angular/config/routes.config.js:

```
let getView = (viewName) =>
{
return ./views/app/pages/${viewName}/${viewName}.page.html; // Line #getView
};

$stateProvider
                       .state('app.create_post', {
                                  url: '/create-post',
                                  views: {
                                  'main@': { templateUrl: getView('create_post' }
                                   }
})
.state('app', { abstract: true, data: {},                           //{auth: true} would require JWT auth
                      views: { header: { templateUrl: getView('header') },     // Line #header
                                   footer: { templateUrl: getView('footer') },                      // Line #footer
                                   main: {}
                                 }
})
```

File: L5AMS/app/Http/routes.php:

```
//public API routes
$api->post('posts','CreatePostController@create');          // Line 1
$api->post('create-post','CreatePostController@create'); // Line 2
// Line 1 added by me to add a route for "/create-post"
```

Issue # 1. URL typed in browser:
http://localhost:8000/
The content of File:"L5AMS/resources/views/index.blade.php"  is displayed in the browser and in the console (in browser), I see the following error messages. 

http://localhost:8000/views/app/pages/header/header.page.html 404 (Not Found)
http://localhost:8000/views/app/pages/footer/footer.page.html 404 (Not Found)

I tried changing the path in "Line #getView" but no success.

Question: what should the path be in Line #getView?
Or, should the prefix in file: L5AMS/tasks/ngHtml2Js.task.js be some other prefix?

```
elixir.extend('ngHtml2Js', function(src, output, options) {
                                            var defaultOptions = { moduleName: 'app.partials',
                                                                                  prefix: './views' };
```

Issue # 2. URL typed in browser:
http://localhost:8000/#/create-post
I get the same error messages (header and footer file not found) in the console and the same content of index.blade.php is displayed in the browser.

What is the link I am missing? How does the content in index.blade.php get displayed?
What should I do to get "create-post" page?

Thanks,
SJ
- **Laravel & Angular version:** 5.2.22

**Comment by flick36** [comment]
When you use the artisan commando `php artisan ng:page some-name` it creates a folder in the `L5AMS/angular/app/pages` folder with the `some-name` you have defined in the previous command so in this example it would create a folder that looks like this: `L5AMS/angular/app/pages/some-name` and inside that folder it would create 2 files, `some-name.less` and `some-name.page.html` so what the `getView` function does it's returning the html file you have on whatever you especified, in your example:

`'main@': { templateUrl: getView('create_post' }`

you should have a folder in the path i mention before so you can see the html content of that file (`create_post.html`), now it's weird that the header and the footer are not found, since they're there by default unless you have delete them, can you confirm they exist in `L5AMS/angular/app/pages` there you should have 2 fodlers named `header` and `footer`

**Comment by sjanakir2015** [comment]
The following files do exist:
L5AMS/angular/app/pages/create_post/create_post.less and create_post.page.html
L5AMS/angular/app/pages/header/header.less and header.page.html
L5AMS/angular/app/pages/footer/footer.less and footer.page.html

That is why I doubt whether the getView function should prefix "/views/app/pages/" because, in the directory structure,  there is no path which has "/views/app/pages/" as a substring, particularly note the folder "views".  
i.e. the path "angular/app/pages/..." exists;  but the path "views/apps/pages/..." does not exist.

**Comment by flick36** [comment]
That's because the `ngHtml2Js` generates a module that pre-load all the HTML files into the `$templateCache` you read more about the library [here](https://github.com/martinssipenko/laravel-elixir-ngHtml2Js)

Anyway so from the beggining, how are you serving the app? are you using `gulp and gulp watch` and `php artisan serve --host=0.0.0.0` ?

**Comment by sjanakir2015** [comment]
I referred to ngHtml2Js because it prefixes 'views/' to the filenames. I will read the doc for my further learning. Thanks. 

Yes,  I am serving the app using 
gulp && gulp watch
 php artisan serve 

(I am not using --host 0.0.0.0)

Sent from Samsung Galaxy Note

-------- Original message --------

**Comment by flick36** [comment]
Open your `L5AMS/public/js/partials.js` file and with your favorite editor Search for `header.page.html` does it throws any results?

**Comment by sjanakir2015** [comment]
Response inline. 
Thanks,Sowmya

```
  From: Allan Alvarez Ortiz <notifications@github.com>
```

 To: jadjoubran/laravel5-angular-material-starter laravel5-angular-material-starter@noreply.github.com 
Cc: sjanakir2015 sjanakir@yahoo.com; Author author@noreply.github.com
 Sent: Tuesday, June 7, 2016 2:00 AM
 Subject: Re: [jadjoubran/laravel5-angular-material-starter] Not able to see create-post page in "Posts" Tutorial (#330)

Open your L5AMS/public/js/partials.js file and with your favorite editor Search for header.page.html does it throws any results?
<Sowmya>
Line in which header.page.html was found:   `  $templateCache.put('./views/app/pages/header/header.page.html',`
Similarly, for "create_post_form" `$templateCache.put('./views/app/components/create_post_form/create_post_form.component.html',`
and similar lines for footer.page.html, forgot-password,login-form,register-form, etc.—

**Comment by flick36** [comment]
ok to be honest, it's a weird error this one you are getting, is there any chance you can send me vía email or github repositorie your code so i can look at it with more detail? but before doind that try to download the app again, but this time with

`composer create-project jadjoubran/laravel5-angular-material-starter:dev-master` 

and everything else the same:

```
cd laravel5-angular-material-starter
npm install -g gulp bower
npm install
bower install
#fix database credentials in .env
php artisan migrate
gulp
```

**Comment by jadjoubran** [comment]
Yes I think it's better to check if you can replicate this issue with a fresh install (3.2.0 or dev-master)

**Comment by sjanakir2015** [comment]
Hello Jad,
I created a fresh install and I dont see this issue.  
In the earlier install, I had modified the file:index.blade.php; particularly, altered the following line:`   <div ui-view="main"></div> `(I now understand the significance of this line ! :-) )My guess is that this was one of the reasons for the problem.  I replaced it with the original line and still the issue ("create-post" page not seen) was not resolved. 
Since I am not able to replicate the issue in the fresh install, shall I close this issue?
@Jad and Allan Alvarez Ortiz,
Thanks for your prompt response towards resolving the issue,Sowmya

```
  From: Jad Joubran <notifications@github.com>
```

 To: jadjoubran/laravel5-angular-material-starter laravel5-angular-material-starter@noreply.github.com 
Cc: sjanakir2015 sjanakir@yahoo.com; Author author@noreply.github.com
 Sent: Tuesday, June 7, 2016 7:13 AM
 Subject: Re: [jadjoubran/laravel5-angular-material-starter] Not able to see create-post page in "Posts" Tutorial (#330)

Yes I think it's better to check if you can replicate this issue with a fresh install (3.2.0 or dev-master)—

**Comment by flick36** [comment]
If you want to use the 1st install we can try to solve it, but if you can stick the fresh install then feel free to close this issue.
