### ISSUE TITLE
Controller in page

### ISSUE THREAD

**Issue by macalimosa** [jadjoubran/laravel5-angular-material-starter#331]
Hello Sir,

I would like to ask how can i manage controller in page that i created.

the component controllers are works fine but the page itself don't have controller.

Sorry for noob question newbie here.

Thanks and Advance.

**Comment by flick36** [comment]
https://github.com/jadjoubran/laravel5-angular-material-starter/issues/285#issuecomment-216257436

**Comment by macalimosa** [comment]
Thank you verry much sir @flick36... but how can i control or pass data from one component to other components..

Example: I want hide first the other component while the first component not yet filled out.
and i want to hide  a component by their roles.

Sorry for noob question.

Thanks!.

**Comment by flick36** [comment]
Well that's easy, you create a service [read this](https://thinkster.io/a-better-way-to-learn-angularjs/services) althoug that tutorial it's on ES5 syntax it's realtively easy witht this starter to create a service all you have to do it's in your console `php artisan ng:service ServiceName` and your service will be created at `RootFolder/angular/services/ServiceName.service.js` with this example you get this in that `js`file:

```
export class ServiceNameService{
    constructor() {
        'ngInject';

        this.exampleVariable = 'I'm an example variable';
    }

    exampleFunction(){
        return this.exampleVariable;
    }
}
```

in there you can create `variables, functions, constants, etc..` or whatever you want (in this example i manually create the `exampleFunction()` and the `this.exampleVariable`)

all you have to do now it's to inject that service in any controller you want to share the data, for example Let's say you have this 2 components controllers

```
class FirstController {
    constructor() {
        'ngInject';
    }

    $onInit(){
    }
}

export const FirstComponent = {
    templateUrl: './views/app/components/first/first.component.html',
    controller: FirstController,
    controllerAs: 'vm',
    bindings: {returnTo: '<'}
}
```

and

```
class SecondController {
    constructor() {
        'ngInject';
    }

    $onInit(){
    }
}

export const SecondComponent = {
    templateUrl: './views/app/components/second/second.component.html',
    controller: SecondController,
    controllerAs: 'vm',
    bindings: {returnTo: '<'}
}
```

Then in both contructors you'll inject our newly created `Service` named `ServiceNameService` so you'll end having something like this:

```
class FirstController {
    constructor(ServiceNameService) {
        'ngInject';

        this.ServiceNameService = ServiceNameService;
    }

    $onInit(){
        console.log(this.ServiceNameService.exampleVariable); //This will print the variable
    }
}

export const FirstComponent = {
    templateUrl: './views/app/components/first/first.component.html',
    controller: FirstController,
    controllerAs: 'vm',
    bindings: {returnTo: '<'}
}
```

and

```
class SecondController {
    constructor(ServiceNameService) {
        'ngInject';

        this.ServiceNameService = ServiceNameService;
    }

    $onInit(){
        console.log(this.ServiceNameService.exampleFunction()); //This will also print the variable fucntion but calling the function there.
    }
}

export const SecondComponent = {
    templateUrl: './views/app/components/second/second.component.html',
    controller: SecondController,
    controllerAs: 'vm',
    bindings: {returnTo: '<'}
}
```

And that's basically it, if you change the service variable, it will changue in every component controller.

**Comment by macalimosa** [comment]
Thank you very much sir @flick36 . it's a big help for a newbie like me.

**Comment by flick36** [comment]
I'm 24 bro, don't call me sir, i feel old hahahaha xD, anytime dude, we are here to help :) we were all newbies once, and we're all newbies at some subject
