### ISSUE TITLE
User test creating 2 users instead of 1 and user token not created

### ISSUE THREAD

**Issue by dkat101** [jadjoubran/laravel5-angular-material-starter#333]
Following #305 

When I run the test, this is the response

```
{#380
  +"errors": false
  +"data": true
}
```

But 2 users are created in the database instead of 1 user. This is my repo https://github.com/dkat101/mockup.git

**Comment by jadjoubran** [comment]
Hi @dkat101 
What do you mean you're getting 2 users?
Can you check after which test it's creating 2 users?
And then show me the code for this particular test (maybe it's not updated on your repo)

**Comment by jadjoubran** [comment]
Please re-open if you've got additional info
