### ISSUE TITLE
Issue setting up production app

### ISSUE THREAD

**Issue by harryy2510** [jadjoubran/laravel5-angular-material-starter#335]
[Support Request]

Please help me out in setting up my app for production environment
1. Even if i do `gulp --production` , neither my js nor my css is getting minified
2. How do i completely remove tests from my app before building it for production?
3. How do i remove versioning from prodcution app?
- **Laravel & Angular version:** 3.2.0

**Comment by jadjoubran** [comment]
Hi @harryy2510 
1. I cannot reproduce it.. I just ran `gulp --production` and `public/js/app.js` was minified. Can you try on a fresh install?
2. PHP or JS tests? js tests aren't bundled into your app.js, they are just ran when you run `gulp watch` or `gulp karma`
3. Can you provide more information?

**Comment by jadjoubran** [comment]
Please re-open if you've got more info
