### ISSUE TITLE
vm.hide() in dialog service won't work

### ISSUE THREAD

**Issue by ghost** [jadjoubran/laravel5-angular-material-starter#336]
- **I'm submitting a ...**
- [ ] bug report
- [ ] feature request
- [ ] support request
- [ ] other (Please specify)
- **Provide information & explanation**
- **Got code samples?**
  Make sure to use 3 backticks (and javascript or php after it to show your code) [More info](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code)
  Also make sure to click on the _Preview_ button to double check your code formatting
- **Laravel & Angular version:** 3.2.0

**Comment by flick36** [comment]
amm some info?

**Comment by jadjoubran** [comment]
Yes please provide some info

**Comment by jadjoubran** [comment]
I think this is a duplicate of https://github.com/jadjoubran/laravel5-angular-material-starter/issues/289
Feel free to re-open if you have another issue 😄
