### ISSUE TITLE
Elixir in production server

### ISSUE THREAD

**Issue by num3r06** [jadjoubran/laravel5-angular-material-starter#337]
- **I'm submitting a ...**
- [ ] bug report
- [ ] feature request
- [x] support request
- [ ] other (Please specify)  

I need explanation about elixir function.
I resolve startup issue using apache's virtualHost because this function search minified version of css and js in web server's root folder.
But in production i have a server with multiple app in various folder of web server.
It's a way for resolve this?
How works gulp --production?
thx
- **Provide information & explanation**
- **Got code samples?**
  Make sure to use 3 backticks (and javascript or php after it to show your code) [More info](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code)
  Also make sure to click on the _Preview_ button to double check your code formatting
- **Laravel & Angular version:** 3.2.0

**Comment by jadjoubran** [comment]
Hi @num3r06 
Your question is not very clear
If you're looking for the official elixir documentation, you can find them [here](http://laravel.com/docs/5.2/elixir)
If you're looking for laravel-angular's elixir methods, you can find the docs [here](http://laravel-angular.readme.io/docs/elixir)

**Comment by num3r06** [comment]
I try to explain better:
the app is in the subfolder of apache's server. 
if i call http://localhost:8080/laravel5-angular-material-starter/public/
 from browser i receive this error in chrome console:

```
Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:8080/build/css/material-design-iconic-font-612a746cc7.css Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:8080/build/js/app-e27888b3ae.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:8080/build/css/app-fb87f3b896.css Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:8080/build/js/vendor-1f3d200734.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:8080/build/js/partials-1b9dd183d9.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:8080/build/js/app-e27888b3ae.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:8080/build/css/vendor-221b044de3.css Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:8080/build/css/app-fb87f3b896.css Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:8080/build/css/material-design-iconic-font-612a746cc7.css Failed to load resource: the server responded with a status of 404 (Not Found)
```

if i using a virtualHost (from the same folder) all works fine.

**Comment by flick36** [comment]
Problem it's not elixir, but the fact that laravel is not designed to work on shared hosting providers nor Apache servers or at least not in easy way if you dont have access to a ssh, because as you can see in your error, it is expecting the file on `RootFolder/build` but they're on `RootFolder/public/build` so you have to create a `Rewrite Rule` with `.htaccess` and maybe hack the framework a little bit cause you'll probably have to change some routes in the `index.php` as well

**Comment by num3r06** [comment]
ok thx for support i try for write rule in .htaccess file

**Comment by num3r06** [comment]
I fix this in my local development enviroment using virtualHost but in production server (where are many web app in various apache subfolder) i don't know how make this.
I found this tutorial
http://blog.kongnir.com/2015/09/25/setting-up-laravel-5-on-shared-hosting-server/
is useful for this case?
P.S A fresh installation of laravel app work regular in another subfolder in the same server

**Comment by jadjoubran** [comment]
@num3r06 is there an error that you're seeing?

**Comment by num3r06** [comment]
the error is the same of my previous try.
I want to use a subfolder of apache for this application. I know the problem is elixir in the asset of index page function in conjunction with .version() of gulp.
I can force in any mode the path of elixir version?

**Comment by num3r06** [comment]
the same problem i've in the restangular configuration. If i use a virtualHost works. If i try to use subfolder path of apache the route it's not found because pointing at the apache's DocumentRoot

**Comment by jadjoubran** [comment]
@num3r06 can you show the exact error, it'll help figure out what the issue is
Also please show the URL you are using
maybe it's better if you can send a screenshot showing the URL & the error in the browser console

**Comment by num3r06** [comment]
This is the situation:
the physical folder of my develop machine is c:\www\lalaravel5-angular-material-starter which is mapped in a apache root subfolder
I try to use a virtual host http://portale.local:8080 and all works fine.
If i try to use http://localhost:8080/laravel5-angular-material-starter/public/
This is the result
![img1](https://cloud.githubusercontent.com/assets/7809704/16902380/4de1af62-4c5d-11e6-9612-749f56cf7dad.png)
The css and js resources are searched in DocumentRoot folder and not in the correct sub folder. If i substitute elixr helper in index with asset helper the page are loaded correctly but i believe not with the versioned resources making from gulp. 
When i try, after use asset instead of elixir and with the working index,  to use api routes (which woks correctly with virtual host i have an error of not routes found. this is the img:
![img2](https://cloud.githubusercontent.com/assets/7809704/16902427/699d1272-4c5e-11e6-9418-9c7d2d5f14a1.png)
I correct the restangular config setBaseUrl removing / from url /api and all seems to works except auht route wihich not work
Sorry for the complex request but solution with virtual host can't work on production server (lan server for internal application) which have only static IP and not domain or subdomain.
thx in advance for great support

**Comment by jadjoubran** [comment]
well I think you'd need to fix your `index.blade.php` to remove absolute paths
and then you also need to fix every component to remove the leading slash
but then nghtml2js won't work but if you need it you can just disable it

**Comment by num3r06** [comment]
I try this solution and i give you feedback as soon as possible.
At this moment using a tutorial on deploy laravel app on a shared hosting i partially resolved with shell script which copy build and other folder in apache DocumentRoot.
For now all seems to work correctly
Thanks for support and for great job on this starter pack

**Comment by flick36** [comment]
I've just install an app of mine in a shared hosting (BlueHost) all you have to do it's to point your domain to the public folder not the root directory it's easir if you use a subdomain for this, but nothing a good .htaccess can't do.

**Comment by num3r06** [comment]
if i do this another app on the server isn't accessible.
My server is a lan server with static ip and not domain/subdomain is provided

**Comment by jeslomo** [comment]
Hi @num3r06 ,

I've use apache for serve the app (and have more apps in the apache folder (htdocs)) and i've no problem.

My solution for you can do this is use "asset" function of laravel in index.blade.js for load js/css files.

Example:

```
<!doctype html>
<html ng-app="app" ng-strict-di>
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="{!! asset(elixir('css/vendor.css')) !!}">
    <link rel="stylesheet" href="{!! asset(elixir('css/app.css')) !!}">
    <link href='https://fonts.googleapis.com/css?family=Lato:300,400,700' rel='stylesheet' type='text/css'>

    <title>Laravel Angular Material Starter</title>

    <!--[if lte IE 10]>
    <script type="text/javascript">document.location.href = '/unsupported-browser'</script>
    <![endif]-->
</head>
<body>

    <div ui-view="header"></div>
    <div ui-view="main"></div>
    <div ui-view="footer"></div>

    <script src="{!! asset(elixir('js/vendor.js')) !!}"></script>
    <script src="{!! asset(elixir('js/partials.js')) !!}"></script>
    <script src="{!! asset(elixir('js/app.js')) !!}"></script>

    {{--livereload--}}
    @if ( env('APP_ENV') === 'local' )
    <script type="text/javascript">
        document.write('<script src="'+ location.protocol + '//' + (location.host.split(':')[0] || 'localhost') +':35729/livereload.js?snipver=1" type="text/javascript"><\/script>')
    </script>
    @endif
</body>
</html>

```

Important, use "elixir" before "asset" function.

If you hace a IP then the result is:
--> http:// < your_ip > / < project_name (if have more projects) >/public/#/

Later, if you want quit "public" in the route, with .htaccess not must have problems.

Regards

**Comment by num3r06** [comment]
thx for support. i have tried a solution like this but after the problem was in the api routes which have ever a absolute root path.
I try to change restangular config but nothing change. In your project the auth routes and dingo api routes are working?

**Comment by jeslomo** [comment]
In /angular/index.config.js i've created a constant: base_url.

```
import {RoutesConfig} from "./config/routes.config";
import {LoadingBarConfig} from "./config/loading_bar.config";
import {ThemeConfig} from "./config/theme.config";
import {SatellizerConfig} from "./config/satellizer.config";

angular.module('app.config')
    .constant('base_url', 'http://localhost/apc/public/')
    .config(RoutesConfig)
    .config(LoadingBarConfig)
    .config(ThemeConfig)
    .config(SatellizerConfig);

```

And in /angular/config/satellizer.config.js use this constant for user/api.

```
export function SatellizerConfig($authProvider, base_url) {
    'ngInject';

    $authProvider.httpInterceptor = function() {
        return true;
    };

    $authProvider.loginUrl = base_url + 'api/auth/login';
    $authProvider.signupUrl = base_url + 'api/auth/register';
    $authProvider.tokenRoot = 'data';//compensates success response macro
}
```

And finall, in API.service.js use "base_url" to configure Restangular:

```
return Restangular.withConfig(function (RestangularConfigurer) {
            RestangularConfigurer
                .setBaseUrl(base_url + '/api/')
                .setDefaultHeaders(headers)
                .setErrorInterceptor(function (response) {
                    if (response.status === 422 || response.status === 401) {
                        for (let error in response.data.errors) {
                            return ToastService.error(response.data.errors[error][0]);
                        }
                    }
                    if (response.status === 500) {
                        return ToastService.error(response.statusText)
                    }
                })
                .addFullRequestInterceptor(function (element, operation, what, url, headers) {
                    let token = $window.localStorage.satellizer_token;
                    if (token) {
                        headers.Authorization = 'Bearer ' + token;
                    }
                });
        });
```

**Comment by num3r06** [comment]
Great job!!!! 
I try this and i'll feedback as soon as possible

**Comment by num3r06** [comment]
All works fine.
