### ISSUE TITLE
$watch

### ISSUE THREAD

**Issue by macalimosa** [jadjoubran/laravel5-angular-material-starter#338]
Hello Guys,

Can you give me example how to use $watch and $watchCollection in latest version of laravel-angular using ecmascipt 6.

Thanks in advance!.

**Comment by jadjoubran** [comment]
Hi, 

Normally you'd have to inject $scope to use it but because of the way components work, you probably don't need $watch..  You can use lifecycle events available as of Angular 1.5

If you can show me what you're trying to do, I can show you a sample :D

**Comment by macalimosa** [comment]
hi @jadjoubran,

What i'm trying to do is detect  when the value of vm.selectedItem is changed, 

here is my sample code: 

``` javascript
class ShowhidebuttonController{
    constructor($scope,$log){
        'ngInject';
        this.$scope = $scope;
        this.$log = $log;
        this.selectedItem = [];
    }

    $onInit(){
    }

    this.$scope.$watch(this.selectedItem,(newVal,OldVal) =>{
        this.$log.info(oldVal);
        this.$log.info(newVal);
    });
} 
```

Actually im using `daniel-nagy/md-data-table` my problem is i don't know how ng-show other content when row is selected.

I already tried ng-click from row it's working but not in checkbox and last i decided to use watch for watching changed value.

**Comment by jadjoubran** [comment]
I don't think you need the watch.. can you show me the HTML as well?
Please use the backticks to show your code (```)

**Comment by milocosmopolitan** [comment]
I think you can use ng-change and ng-options

```
 <select ng-change="updateValue(selectedItem, '{{item.id}}')"
    ng-model="selectedItem" ng-options="item.id as item.name for item in data" multiple>
 </select>


class ShowhidebuttonController{
  constructor($scope, $log){
    'ngInject';
    $scope.selectedItem = [];
    $scope.data = {
      {id:1, name:'apple'},
      {id:2, name:'lime'},
      {id:3, name:'banana'},
    };
    $scope.updateValue = function(oldVal, newVal){
      $log.log(oldVal);
      $log.log(newVal);
    }
  }
} 
```
