### ISSUE TITLE
Demo not responsive on mobile

### ISSUE THREAD

**Issue by jadjoubran** [jadjoubran/laravel5-angular-material-starter#34]
After @Bodom78's PR, we still have these issues:
- [x] Show menu icon not aligned properly.
- [x] Restructure brings back the content jump issue when animating from page to page.
- [x] Content/Pages needs to be made consistant and working in the responsive layout (Use Cards?, Max Width so content not too wide on larger screens, 100% after breakpoint for smaller screens) .

**Comment by Bodom78** [comment]
I've been tweaking/restructuring locally in what little spare time I have to try and improve the layout so it can be responsive with minimal markup/styles workarounds. Will keep you posted.

Notes:
Material components work well to form app layouts but when you wrap them in elements like a div used to inject the ui-view into they break the components default flow . Better to add ui-view directives onto the components directly.

Should use md-cards for the "Page" area content, will allow graying backround color if preferred. Constrain to max width and transform to 100% on breakpoint.

Small issues to resolve:
![styling-issues](https://cloud.githubusercontent.com/assets/139152/9697326/ca4a0b1a-53cc-11e5-84d5-4b46cbd40a61.jpg)

**Comment by jadjoubran** [comment]
Oh okay, noted!

Thanks a lot!
If you have this in your own fork maybe I can contribute to that as well
Cheers!

**Comment by Bodom78** [comment]
Sure, help is appreciated. Here you can find my forked branch:
https://github.com/Bodom78/laravel5-angular-material-starter/tree/responsive-restructure

The branch has a restructured layout, is responsive and the sidenav hide/show is present.

Some issues off the top of my head that are currently present:
- Show menu icon not aligned properly.
- Restructure brings back the content jump issue when animating from page to page.
- Content/Pages needs to be made consistant and working in the responsive layout (Use Cards?, Max Width so content not too wide on larger screens, 100% after breakpoint for smaller screens) .

**Comment by jadjoubran** [comment]
Wow that's great, thanks!

But those are weird errors indeed

I'll take a look again at error number 2 and 3.

But regarding the menu icon I don't think we have a solution other than a `margin-top` no?

**Comment by Bodom78** [comment]
Yep, just some margin tweaking would do the trick as it's a fixed size. Had hoped to get more done but work always gets in the way.

**Comment by jadjoubran** [comment]
No worries man, it's actually great that you're helping.
I'm working on a fix right now

**Comment by jadjoubran** [comment]
@Bodom78 Can you add me as a contributor to your fork? so push my code fixes - I should've forked but I guess it's too late

**Comment by jadjoubran** [comment]
You know what.. I just realized that I introduced lots of new issues...
even some of the issues (like the sidebar shows twice) when you first open the page.
Not sure if we need to start over or maybe change the layout completely..

**Comment by Bodom78** [comment]
I've added you as a contributor.

Hopefully I can look into the layout today/tomorrow, we don't seem to have these issues on the project I'm working on in the office.

The fade between page transitions, is that something that was added and not part of angular material?

I might strip all the css and work from there. I figure we should require minimal styling since the starter pretty much follows a generic material layout (but that's usually never the case).

**Comment by Bodom78** [comment]
I think I've sorted the jumping issue, for the sidenav at least, just need to apply it when I get some time.

Originally we had:
`<element ui-view="...">[Injected Material Component]</element>`
Which caused issues with how material components flowed.

Currently I have:
`<material component ui-view="...">[Injected Content]</material component>`
Which causes the ugly jump shift caused by the animating in effect (disabling animations fixes the issue but also removes the cool slide in/out effect in the menu)

What should work is:
`<material component><element ui-view="...">[Injected Content]</element></material component>`
because the material components are still at the root level, they will layout nicely and the content can fade in without effecting them.

**Comment by jadjoubran** [comment]
oh okay that's cool!
Thanks again for your contribution

**Comment by Bodom78** [comment]
Hey @jadjoubran, No problem.

Please check out the latest commit on the fork and let me know your thoughts when you have a chance:
- Responsive working for the most part (See below).
- Aligned menu icon.
- Jumping issues fixed for material components and page when transitioning in/out.
- Content pages updated to use md-cards, they are pretty consistant in structure now.
- Removed redundant CSS that was no  longer required.

Only remaining issue that I could not sort out is making the Prisim code highlighting blocks scale down with the cards for smaller screens. The should scroll the overflow content but I just couldnt get it to work. Let me know if you have any ideas on this.

**Comment by jadjoubran** [comment]
@Bodom78 Hats off!
I can't tell you how excited I am to have this on the master branch. Seriously great job and thanks again!
I honestly don't see the issue with the Prism code.. because when someone clones this repository, 90% of the time they don't really care about Prism, they just need to remove it (I want to add this to the Docs so that people don't keep Prism when they don't need it)..
What do you think? I mean it's also readable on mobile

**Comment by Bodom78** [comment]
@jadjoubran No problem, always happy to contribute where I can.

Yep I agree, the Prisim code blocks do not really need to be responsive as their really just instructions that will be removed anyway by those using this starter project.

Branch has now been merged into master.

**Comment by jadjoubran** [comment]
Awesome - just released 2.9.1
For future reference, this is available as of [2.9.1](https://github.com/jadjoubran/laravel5-angular-material-starter/releases/tag/2.9.1)

Btw on a side note, are you originally from Lebanon?

**Comment by Bodom78** [comment]
Great stuff. 

Ha, my name gives it away. My father is originally from Lebanon, Halba I believe. I've never been there myself tough, but I can speak Lebanese quite poorly.

**Comment by jadjoubran** [comment]
oh nice! Indeed your appearance and name gave it away.
I've been to Brisbane, Gold coast, Sydney and Tasmania last year

**Comment by jadjoubran** [comment]
I just noticed that I still haven't pushed this to AWS elastic beanstalk to update the demo. 
I'll push it tomorrow morning

**Comment by Bodom78** [comment]
No problem. I'm from Melbourne and been here most of my life. it's a decent state. If you ever visit do it in the summer because the weather here sucks for the most part.

**Comment by jadjoubran** [comment]
Noted :D
New demo deployed!
