### ISSUE TITLE
Redirecting the angular login after api authentication

### ISSUE THREAD

**Issue by ghost** [jadjoubran/laravel5-angular-material-starter#341]
Hi, I am quite new with Angular, however am quite fluent in Laravel. Your framework is a breath of fresh air and i find it amazingly easy to use and fluent.

Having said that, could you please give me insight into how to redirect the angular app/views to a different page after a authentication request is successfull through the api?

I have followed your docs and tutorials, and get the toast popups validating authentication, however, I would like to extend this to allow for a redirect to a different angular route.

I hope I made the question clear enough.

Please let me know if you need more information
- **Laravel & Angular version:** 3.2.0

**Comment by jadjoubran** [comment]
I'm glad you enjoy developing using this starter 😄 
Seems like this question is resolved, feel free to open a new issue if you more questions
