### ISSUE TITLE
Production apps built with this starter?

### ISSUE THREAD

**Issue by jadjoubran** [jadjoubran/laravel5-angular-material-starter#345]
If anyone has a production app built with this starter it would be great to share!
Thanks 😄

**Comment by antonkomarev** [comment]
We have only 1 live product using it right now and couple still in sandbox state. Will post them if they will go our from incubator :D

http://cybercog.ru/

**Comment by flick36** [comment]
https://material-appointments.io although its still on development and still has a lot of missing features

**Comment by jadjoubran** [comment]
Oh that's awesome 😄 
Thanks for sharing!

**Comment by daem0ndev** [comment]
I've been working on a new progressive web app for a client recently and wanted to try out your starter. It's still not close to done, and is definitely not yet released to public, but I wanted to share it with you @jadjoubran 

My goal is to make one of the best examples of your starter as well as best practices in laravel+angular in general. Please check it out, and mind the fact that its still not done. I have only started development on this 3 weeks ago. 

[http://beta.pintradingonline.com](http://beta.pintradingonline.com)

Its fully responsive and uses satellizer for facebook/google based login/registration among other things. It's really leveraging almost every feature in laravel and angular even in this early / incomplete stage :)

**Comment by jadjoubran** [comment]
Wow that's awesome @daem0ndev 
I'm glad you were able to achieve this in just 3 weeks 😄 
My only comment would be that you need SSL (https) in order for PWA features to work (service workers)
I'm releasing the first tutorial on PWA with this starter tonight, make sure to check the youtube channel (or subscribe) :D

**Comment by daem0ndev** [comment]
Yep, its still in dev mode only and not publicly available. Hoping to go live in 2 weeks and will be on SSL in that time.

**Comment by jadjoubran** [comment]
@daem0ndev awesome!
Btw I just published (1 minute ago!) this [new screencast](https://www.youtube.com/watch?v=qe5dJdPYvfA), I hope it helps!

**Comment by shiruken1** [comment]
Our app is called Empowrd and is on the Play, App and Windows stores.

We haven't opened up the web portal to the public yet, but it'll be on
Empowrd.com

**Comment by kiro64** [comment]
https://www.ticketdee.com

This is my personal project integrate to NodeJS for  Chat and Realtime Notification feature 
also add Facebook Notification for Member who's register using their Facebook account. 
and HTML5 Notification

i've been waiting for angular 2 version. 
@jadjoubran Do you have milestone or plan to start or complete a change to Angular 2 version

**Comment by jadjoubran** [comment]
That's awesome @kiro64
I haven't started working on a version with Angular 2, but with the availability of the official `angular-cli`, it would be a bad decision to re-invent the wheel and have features like the `ng generators` in version 2.. so there's a big chance that for Angular 2, this repo will be a package or something similar..
I need to brainstorm on this and then share it here or on gittr

**Comment by jadjoubran** [comment]
Also Angular 2 has been changing a lot, even between release candidates

**Comment by hackur** [comment]
@jadjoubran can I suggest that we start a new repository for the new Angular 2 and Laravel 5.3 implementation? I'd like to include a better formatted SASS / Material directory structure with stubs that include the default material variables and a single main.scss and/or critical.scss file that imports all of the other dependent SCSS stylesheets.

I've been thinking about how to create a pull request to handle this with the existing L5.2 and Angular 1 configuration... but haven't had to time to perfect it.

A more consolidated SASS directory structure will give us better control over the order our scss files are processed and will not require us to modify the elixir task every time we include new SCSS styles for new components, pages, etc. Also, we can separate our critical and main scss files while still importing any custom partials with custom material variables and/or mixins to both files.

See these documents regarding better sass project structure:
http://sass-guidelin.es/#main-file
https://github.com/HugoGiraudel/sass-boilerplate
http://thesassway.com/beginner/how-to-structure-a-sass-project

**Comment by jadjoubran** [comment]
Hi @hackur 
Thanks for this suggestion!
Have you seen the official [Angular CLI](http://cli.angular.io/) ?
After using it for a while it makes it feel that if we try to do all of these stuff (including the generators), we'll be reinventing the wheel and it won't be as good as what they've done
They even have progressive web apps support (with a `--mobile` flag)

**Comment by chihab** [comment]
Awesome work everybody and thanks again @jadjoubran and all commiters for this project !

A better architecture maybe would be to separate client side code from server side code. Client side would only need node in its environment  (so maybe no more laravel generators but just something like angular-cli or yo based generators would do the stuff) while server side code would need php and node of course as it is based on laravel. The client side code would be, ideally, not dependent to Laravel but just do api calls. It would be then preferably be on a separate repo without laravel name on it so js community could use it independently.

By the way, I've just shared a minimilastic [sample app](https://github.com/chihab/angular-styleguide-sample) that follows [Angular/es2015 styleguide](https://github.com/toddmotto/angular-styleguide) by todd motto who kindly added it to the styleguide resources. Don't know if it could be good to follow todd styleguide on our angular code @jadjoubran ?

**Comment by jadjoubran** [comment]
@chihab yes I was also thinking in that direction..
Laravel & Angular 2 might be just a package
This allows for easier updates & migrations (from an older version to a newer one)
And I agree that we shouldn't have the generators baked in anymore since they are provided by `angular-cli`
I do agree on Todd Motto's styleguide, but isn't this for Angular 1.5?
Since the next release will have to be for Angular 2..

**Comment by chihab** [comment]
Okay @jadjoubran.  Are you planning to keep an up to date version for Angular 1.5 on a branch or something when Angular 2's one will be here ? If so, the idea was to make a js repo for the app along with its generators OTB.

**Comment by jadjoubran** [comment]
@chihab okay so I originally thought you were talking about Angular 2
Does it make sense to keep on radically improving the Angular 1 version?
I'm planning on keeping the Angular 1 version and updating its dependencies, bringing small features, etc.. but since this is a starter, I assume most people would like to start with the latest & greatest
Let me know what you think - especially that I just got what you mean 😄

**Comment by gradosevic** [comment]
@jadjoubran I see this is a quite popular repository, and it would be a really good to have Angular 2 based version. I've been working with NG2 a lot for past month and it's quite stable now. Material design support is still in active development, but the main features are completed and work well https://github.com/angular/material2

Is there any way we can have a new branch or repository to work on? I believe the time is just right, and someone will start making it anyway, I would like to see you guys start it first since you already know the stuff. I would like to contribute if there's a repository like that. Thanks!

**Comment by jadjoubran** [comment]
Hi @gradosevic 
Thanks a lot for the initiative. You are absolutely right, but I was extremely busy for the last few weeks.. I will start having more free time in about 4 weeks.
However I'll set something up (a new repo/branch) during the weekend for sure
Thanks!

**Comment by gradosevic** [comment]
That sounds great! I really appreciate your time and effort for this. Thanks!

**Comment by jadjoubran** [comment]
Hi @gradosevic 
I've opened 2 new repos:
- [laravel-angular](https://github.com/jadjoubran/laravel-angular) Laravel package
- [angular-laravel](https://github.com/jadjoubran/angular-laravel) Angular package

and created 1 new "brainstorming" issue in every one
Any help would be greatly appreciated 😄

**Comment by gradosevic** [comment]
Hi @jadjoubran 
Thank you so much for the repositories! I'll think about the comments for the packages.
I'm curious why these packages are separated, and how can we make them work together? I will not spam on this thread anymore since it's closed now, but it would be great if you could provide just a brief description how these two can work together, just to wrap up this conversation. Thank you!

**Comment by jadjoubran** [comment]
Hi @gradosevic 
No worries, I don't mind re-opening this issue

What I was thinking was: having 1 Laravel package that can be installed with a composer require and then `artisan vendor:publish` - Benefits:
- Can be installed on any Laravel application
- Lumen support can be added easily
- Upgrading Laravel applications becomes independent from the package

There will be also 1 Angular package which can be installed on an angular-cli generated app or any other Angular 2 app

The only downside that I see, is that there isn't any "boilerplate" anymore.. However we can still work on a boilerplate that uses those 2 packages
Let me know what you think

**Comment by jadjoubran** [comment]
Also don't forget that `angular-cli` takes away half of the features that were available in this version
Also Laravel 5.3 is more and more embracing APIs

**Comment by gradosevic** [comment]
@jadjoubran 

Thanks for the answers, it's now more clear to me. 
I totally agree with you regarding the Laravel package. That approach would be more flexible and easy to maintain. I see, you want to support also non-Laravel apps with that Angular package. I guess it can be re-used in Laravel package without too much effort, right? 

Did you have a chance to look at the [Laravel passport](https://laravel.com/docs/5.3/passport) introduced in 5.3? There was a similar challenge to support both back-end and front-end passport components that are optional by default, and Taylor solved it by creating a custom "passport" artisan command for installation. Front-end Vue.js components can be published with vendor:publish command. Maybe this approach could be used to publish Angular 2 components and optional boilerplate code as well? 

I know, a lot of features are missing, but at least we would have something to start with and improve with time.

Thanks

**Comment by jadjoubran** [comment]
Thanks for your feedback @gradosevic!

The main goal is not to make it work with non-Laravel apps.. but I guess that's also something that you'd get.. But in case along the way, we had to make something Laravel-specific, then we will do it.. Because this is mainly targeting Laravel & Angular

I thought exactly about this.. by publishing views.. but then your angular app doesn't live inside your Laravel project anymore.. So that is something that I'm not sure how we can solve.. any ideas?

Can you suggest other features? I'm not sure what could be there.. of course features that will be useful for everyone

**Comment by gradosevic** [comment]
@jadjoubran 

I think that the main goal should be to make it integrated with Laravel as much as possible so we can eventually replace Vue.js completely with Angular, so people can have a choice to choose at least between these two frameworks. I would say that the initial version should be very simple, just a hello world page with a new page layout and support for Material UI,  support for typescript compiling, preferably with Elixir, support for routing that works well with both Angular and Laravel routes, etc. In general, code should be organized in a "Laravel way", if possible. This would be a blank starter for a new Angular/Material/Laravel projects.

Later we could create more useful components like contact form, login form, maybe page with some sample Material UI snippets (like the Twitter Bootstrap snippets page), support for REST etc. These could be optional features and maybe a user could choose to install them only when they're needed.

I think that the first part that is integrated with Laravel would be hard to separate from it, so this should be integrated in the Laravel package, but the additional front end components can be stored in a separate project. I think that Angular repository shouldn't have any dependencies to Laravel repository if it's intended to be used by other apps.

In my opinion, it would be good to start with the Laravel package first and see how it goes. Later, we could try to isolate Angular components to a separate project, if it's possible. At least, we could have those re-usable Angular components stored there, that can be used by non-Laravel apps.

This is just an idea from consumer's perspective, you probably know better what's doable and what's not, so what do you think?

**Comment by jadjoubran** [comment]
Okay so I agree with you on the Laravel package but there are a few problems with having Angular inside the Laravel repository:
- We'd have to reproduce all the work done in the official `angular-cli`. Which means it'll never be as good as the angular-cli
- Some users would like to use `angular-cli`, others would like to use the `angular-seed`, etc.. 

So by completely separating the Laravel package from the Angular one, you could have separate teams working on every project, and you could choose either Laravel or Lumen, and whichever boilerplate/generator you need for Angular 2

I also think it's nice to have some ready made components later on
And potentially have 1 new repo which acts as a boilerplate with Laravel & Angular-cli.. which uses both of these packages.. for users looking to use Laravel & the angular-cli

thoughts? 😄

**Comment by gradosevic** [comment]
That sounds like a perfect idea to have these projects completely decoupled from each other, and still achieve the same. Maintaining would be much easier. From your experience with the previous project, do you think that boilerplate generator can be flexible enough to give us freedom to create/change everything that's needed in the Laravel/Lumen project? If it is, that would be just perfect.

**Comment by jadjoubran** [comment]
Well the third repo which may come later needs to combine these two.. so I guess it's still early to talk about it
but yeah basically if you're using Laravel & angular-cli it shouldn't be a problem to do whatever you want inside of it (but that's all theoretical for now)

**Comment by gradosevic** [comment]
Sounds good to me. Maybe we could wrap up this conversation into some bullet points for the repositories? Thanks a lot for the explanation!

**Comment by temoctzin** [comment]
Hello, i would like to share a sample app using this starter,

I hope the example helps someone.

[https://github.com/Cuauhtemoc-tzin/ejercicioCRUD](https://github.com/Cuauhtemoc-tzin/ejercicioCRUD)
