### ISSUE TITLE
Custom url-prefix of ui-routes

### ISSUE THREAD

**Issue by followtheart** [jadjoubran/laravel5-angular-material-starter#347]
- **I'm submitting a ...**
- [ ] bug report
- [ ] feature request
- [X] support request
- [ ] other (Please specify)

How can I change url-prefix `/#` to sth else ?

```
http://www.laravel-angular.io/#/login
```
- **Laravel & Angular version:** 3.2.0

**Comment by milocosmopolitan** [comment]
$locationProvider.html5Mode(true);

https://scotch.io/tutorials/pretty-urls-in-angularjs-removing-the-hashtag

**Comment by followtheart** [comment]
thx
