### ISSUE TITLE
vertical / horizontal stepper form

### ISSUE THREAD

**Issue by odyright** [jadjoubran/laravel5-angular-material-starter#348]
- **I'm submitting a ...**
- [ ] bug report
- [ ] feature request
- [x] support request
- [ ] other (Please specify)

Is there an exemple of Material design stepper form? If i want to produce an registration form with more than 2 steps how should i proceed?
Concerning vertical stepper form, i saw that [Material Design Lite Stepper (Polyfill)](http://ahlechandre.github.io/mdl-stepper/) could be a good example of Material Design Stepper implementation and there are demonstrations with Css & Javascript file. But their Stepper component was based on Material Design Lite (MDL) library not suitable for an "angular material" project, i think 

So could you please inspire me a way to implement vertical / horizontal stepper form? it's for a live project!

**Comment by flick36** [comment]
https://github.com/eberlitz/material-steppers

https://github.com/ipiz/md-steppers

https://github.com/mgonto/angular-wizard

https://scotch.io/tutorials/angularjs-multi-step-form-using-ui-router

**Comment by odyright** [comment]
Thank you, the 2 first seem following the Material design spec.

**Comment by flick36** [comment]
The last 2 can follow Material design spec since they're well just that, design specs... just a little bit of css and they're materialized

**Comment by hackur** [comment]
I like the first one (eberlitz/material-steppers). It also seems to have been updated more frequently / recently.

**Comment by odyright** [comment]
thanks to all of you; i did it. But if someone could build or propose something else too beautifull...i'm open!

**Comment by flick36** [comment]
that's trivial since what you might found beautiful i might think it's aweful :stuck_out_tongue_winking_eye:  like i say better way it's to css style your form here are some examples:

[Fuse](http://fuse-angular-material.withinpixels.com/ui/forms)
[Triangular](http://triangular.oxygenna.com/#/forms/wizard)
[INSPINIA](http://webapplayers.com/inspinia_admin-v2.5/form_wizard.html)
[Material Admin](http://www.codecovers.eu/materialadmin/forms/wizard)

CSS is the key :wink:

**Comment by odyright** [comment]
Fuse for me. Thks @flick36.

**Comment by odyright** [comment]
Sorry i closed it too early; i need support in ths starter i made a vertical stepper form/Registration form and I am inspired "Fuse". but  When we move to the next step, the icon isn't change. I notice it espacially for optional step, even if we remove `option-step`. 
I tried to modify directives but nothing. 

how could i solve it? plz

**Comment by flick36** [comment]
Didn't get what you wanna do :confused:  :S

**Comment by odyright** [comment]
when a step is complete, his icon change to show that fields are filled completely. So Icons only change if the steps are complete. But in my case is not working like that and i want to fix it!

**Comment by flick36** [comment]
Yeah, I and i think "we" can't help you with that, cause that's your own logic, you should ask in the directive project page :/ i do not know what `option-step` is or what it does since it's not part of this project

**Comment by odyright** [comment]
yes, you right!
