### ISSUE TITLE
Development Collaboration

### ISSUE THREAD

**Issue by proxnoob06** [jadjoubran/laravel5-angular-material-starter#349]
- **I'm submitting a ...**
- [ ] bug report
- [ ] feature request
- [x] support request
- [ ] other (Please specify)
- **Provide information & explanation**

Hello guys,

We are planning to use laravel5-angular-material-starter in our project.

The configuration is done but we had problem in development environment 

we are three (3) in the team but we don't know how to collaborate in project every time we have to save or update the files ,the page is refresh over and over again.

and while there's a error in codes the watcher is stop

Question 1: How we can config port/folder/module for specific dev that every time he changed file only his/her browser is refresh.

Quenstion 2: How can other team run artisan command by network?

Thank you in advance
# Newbiew

**Comment by flick36** [comment]
Git, maybe?

**Comment by jadjoubran** [comment]
Are you all working on the same folder on the network? :/

**Comment by proxnoob06** [comment]
yes sir @jadjoubran same folder..

**Comment by jadjoubran** [comment]
Yeah then as @flick36 mentioned, you should be using Git to manage all of this 
There's nothing special about Laravel & Angular with git.. So you can look for any Laravel Git tutorial

**Comment by fusedtechresource** [comment]
thank you verry much sir @jadjoubran @flick36  and sorry po noob question hehe.
