### ISSUE TITLE
Deploy on port 80

### ISSUE THREAD

**Issue by applecrusher** [jadjoubran/laravel5-angular-material-starter#35]
What is the easiest way to configure this so that it goes to port 80 rather than 8000?

**Comment by jadjoubran** [comment]
`artisan serve --port=80`

**Comment by jadjoubran** [comment]
Let me know if this works for you :D

**Comment by GrahamCampbell** [comment]
That should definitely work.

**Comment by jadjoubran** [comment]
Feel free to re-open this if you're having more issues
Thanks!
