### ISSUE TITLE
CI : Branch 3.2.1's build is not passing

### ISSUE THREAD

**Issue by chihab** [jadjoubran/laravel5-angular-material-starter#356]
- **I'm submitting a ...**
- [x] bug report
- [ ] feature request
- [ ] support request
- [x] build not passing on 3.2.1

branch 3.2.1's build is not passing on travis-ci since last commit.

I tried to figure out what is happening, maybe related to .env file not present but can't understand why it would work before and also for default branch (master) then...

What is your ci/build workflow ? Do you create new branch for each fix then push it to github to activate the ci ?

Thanks
- **Laravel & Angular version:** 3.2.1

**Comment by jadjoubran** [comment]
Hi @chihab 
Thanks for contributing!
It's failing that `critical.css` is not found, which is introduced in branch `feature-pwa` that was recently merged into master.. I don't exactly know why this is happening

I normally have them as tags.. so when there was an issue in tag 3.2.0, I checkouted to tags/3.2.0, made a fix and tagged 3.2.1
Maybe this line needs to be fixed?
https://github.com/jadjoubran/laravel5-angular-material-starter/blob/3.2.1/.travis.yml#L25

**Comment by chihab** [comment]
Indeed, on Travis build steps, we're telling Travis to get a fresh install from dev-master which is not the branch we'd really like to test.

**Here what happens:**

First Travis clones our branch 3.2.1:
`git clone --depth=50 --branch=3.2.1 https://github.com/jadjoubran/laravel5-angular-material-starter.git`

Then in the same folder, we do a 
`composer create-project jadjoubran/laravel5-angular-material-starter=dev-master`

and then go into that latter to do the build and testings. This one is the master branch, not the stable 3.2.1. Hence the critical.css not supposed to be here.

**The way we should probably do it is**
To launch the build inside the cloned repo which matches the exact version we're willing to test. The composer create-project is redundant and probably unwanted here (as explained). Btw, create-project is a git clone + composer install, so it is better imo to do pre-install and post-install steps rather than pre-create-project and post-create-project, the former applies to both.

It would also be better to have: 
- on the Travis install step:  all the install dependencies stuff
- on the Travis script step:  only the actual build commands (gulp and why not unit tests)

Something like:

```
install:
  - composer install && npm install -g gulp bower && npm install && bower install

script:  
  - php artisan migrate --force && gulp && vendor/bin/phpunit
```

If we follow this steps, we'll have an issue on build due to key and jwt generation not done because it is supposed to be done on composer create-project, it should be moved to post-install phase on composer.json

Here are the proposed fixed files:
https://github.com/chihab/laravel5-angular-material-starter/blob/branch-3.2.1/.travis.yml
https://github.com/chihab/laravel5-angular-material-starter/blob/branch-3.2.1/composer.json

Shouldn't we specify (in composer.json I suppose) the project's current version. I didn't find a way to know which version is my current project folder.

**Comment by jadjoubran** [comment]
Okay now it makes sense, thanks for the explanation!
Could you send a PR with the fixes to 3.2.1? And then after testing it and making sure it works, we can port it to master
Btw regarding the version, most packages don't have it because of the reasons stated in the [docs](https://getcomposer.org/doc/04-schema.md#version)

**Comment by chihab** [comment]
Olay @jadjoubran, I'll send a PR asap.

**Comment by chihab** [comment]
@jadjoubran 
I'll send a PR once #358 is fixed and phpunit tests pass successfully on master branch.

**Comment by jadjoubran** [comment]
@chihab I will fix this, because I guess it's easier from my side
I'm traveling tonight though so I'll try as soon as possible 😄

**Comment by chihab** [comment]
Okay @jadjoubran. Have a nice trip. :)

**Comment by jadjoubran** [comment]
@chihab I just discovered an issue with this approach.. running composer install locally would delete the files that we were deleting on composer create-project..

**Comment by jadjoubran** [comment]
Another issue would be that `.env` is being copied everytime you run `composer install`..

**Comment by chihab** [comment]
Ok @jadjoubran, I see.

So when doing composer create-project, these two commands are done automatically
- .env copy
- key/jwt generation with php artisan
  This would be described on composer.json

When doing git clone: 
- If it's a human, he'll have to run the above commands manually
- If it Travis CI we will tell him to do it via its conf file

I'll submit a PR

Two nice things to have:
- One single script that runs the .env copy and key/jwt generation and that is called from travis conf and composer.json files.
- Continous build on composer create-project along with the branch specific builds.

**Comment by jadjoubran** [comment]
Thanks for the PR!
I guess the duplication is no big deal for now.. especially that travis would complain if we miss something, but it might be useful for the future, I agree 👍 
And what do you mean by Continuous build on composer create-project?

**Comment by chihab** [comment]
With our new travis configuration, composer create-project and (specially its related scripts specified on composer.json) is never tested. I don't really know how but it would be nice to have it tested automatically on each stable release.

We would have another travis Job (not the current one) that does: composer create-project and exactly the same commands on the documentation. It is like the end-to-end testing of the project (since we don't do a "git clone" on the docs).

Really a nice to have cause travis conf and composer.json would be rarely modified so no risk to introduce an issue (due to a delta).

**Comment by jadjoubran** [comment]
okay yeah makes sense.. I just added it to the [trello board](https://trello.com/b/tZ997reo/laravel-angular-material-starter) thanks!

**Comment by jadjoubran** [comment]
I still need to fix it for 3.2.1

**Comment by jadjoubran** [comment]
actually how are we supposed to fix it for 3.2.1 now? 😛

**Comment by chihab** [comment]
We need to merge only travis and composer files, without gulp modifications related to critical.scss...

I propose to do it without a merge, I mean by doing the same modifications on composer.json and travis.yml on 3.2.1 branch. Afterwards the merge would be conflictual with master branch and we would have to resolve it manually, which is pretty straightforward.

How would I be able to send a PR on that ? Should I create a branch (local-3.2.2) from 3.2.1 tag on my repo then create a pull request from my repo's local-3.2.2. Then, to which branch on your repo should I submit it ? Don't we need a "stable" branch on your repo (not the master beta one :)) ?

**Comment by jadjoubran** [comment]
hmm actually if you want you can target that tag against `tags/3.2.1` (although it doesn't show up in the list)
I've never done it before but I guess it would be cool to learn it 😄 
but yeah I guess for the next releases I'll keep the master as stable and do all the new stuff on develop

**Comment by chihab** [comment]
I don't think I can do it that way. I have to target a branch on my PR.

@jadjoubran, could you please create a branch 3.2.2 or stable (from 3.2.1) that I would target on my PR ? Changes are ready on my repo's 3.2.2 branch. Travis build is OK on my side too.

**Comment by jadjoubran** [comment]
Hi @chihab `stable-3.2.1` is up!

**Comment by chihab** [comment]
Hi @jadjoubran. PR submitted.

Thanks !

**Comment by jadjoubran** [comment]
Great, thanks a lot 😄

**Comment by mvpasarel** [comment]
@jadjoubran One quick question, I want to start a project using this package but I am not sure what version to use. Master or 3.2.1?

**Comment by jadjoubran** [comment]
@mvpasarel that will be cleared out in the docs once 3.3 is released!
But yeah if you're looking to build a Progressive web app, then you can use Master
If you're not interested in building a progressive web app, then 3.2.x is the way to go

**Comment by mvpasarel** [comment]
@jadjoubran Gotcha. Will go with master then and will wait for 3.3 before going to production. Also, thanks for the package, at first sight, it seems exactly what I was looking for.

**Comment by jadjoubran** [comment]
@mvpasarel great! Btw according to the [trello board](https://trello.com/b/tZ997reo/laravel-angular-material-starter) 3.3.0 will probably be identical to the `rc` that you're going to use right now (except for a minor bug fix maybe)
So the only thing that would be helpful for you when 3.3.0 is released is actually the documentation and screencast 😄 
Since there isn't any documentation at the moment, I'd recommend reading through #340 so that you can see what features you can use
Also, it would be great if you open a new issue and let me know if something needs to be fixed

**Comment by mvpasarel** [comment]
@jadjoubran For sure. I will let you know if I find any issues and try some PR as well once I figure it out what I can do to help. Cheers!
