### ISSUE TITLE
Fresh install and angular error

### ISSUE THREAD

**Issue by jeslomo** [jadjoubran/laravel5-angular-material-starter#359]
- **I'm submitting a ...**
- [x] bug report
- **Provide information & explanation**

Hi, I followed step by step installation that there on the web and boot up with "php artisan serve" I get this error:

Error: [$injector:strictdi] function($provide) is not using explicit annotation and cannot be invoked in strict mode laravel angular material
- **Got code samples?**

I've run this code:

composer create-project jadjoubran/laravel5-angular-material-starter --prefer-dist
cd laravel5-angular-material-starter
npm install -g gulp bower
npm install
bower install
# fix database credentials in .env --> YES

php artisan migrate
gulp && gulp watch
php artisan serve
- **Laravel & Angular version:** 3.2.0

**Comment by jeslomo** [comment]
If download versión 3.3.0-beta works correctly, but master brach crash with the error previously mentioned.

**Comment by jadjoubran** [comment]
Hi @jeslomo 
I just followed your steps and installed 3.2.1 but it's working fine..
are you sure you didn't modify any file?
Would you be able to try it again in a new folder?
Thanks!

**Comment by MrDracknes** [comment]
Hi!, i'm trying in another Mac and it works.

Sorry for the "non-issue".

**Comment by jeslomo** [comment]
Hi! I've tried in another Mac and it's works.

Sorry for the "non-issue".

Thanks!
