### ISSUE TITLE
How to get back to dev mode

### ISSUE THREAD

**Issue by ghost** [jadjoubran/laravel5-angular-material-starter#36]
I ran "sh deploy.sh" and it compiled and optimised app in public folder but now the Debugbar, for instance, is gone. How to compile back to dev environmet again? I tried clearing cache and changing the deploy.sh but I cannot find documentation where to set it.

**Comment by ghost** [comment]
nevermind got it back

**Comment by jadjoubran** [comment]
Awesome.

So in case someone has the same issue, you should just run

```
artisan cache:clear
artisan route:clear
```

**Comment by ghost** [comment]
yea, that is exactly what I did. At first I though I need to change the flag to dev or remove no-dev and delete the rest. Thanks. :)

**Comment by jadjoubran** [comment]
No worries!
Make sure to star the project :smile:
