### ISSUE TITLE
critical.css issues

### ISSUE THREAD

**Issue by jadjoubran** [jadjoubran/laravel5-angular-material-starter#362]
- [x] !angular/critical.scss <-- Not Found (thrown by gulp)
- [x] double check that critical.css is not being included in the final.css

btw @chihab another benefit that we got from processing critical.css with `sass()` is that when you run `gulp --production` it'll minify the critical.css 😄

**Comment by chihab** [comment]
@jadjoubran how did you get these issues ?

On master branch, there is no more critical.css, we now have critical.scss. That latter had been submitted on the PR.

Do we still have theses issues ?

**Comment by jadjoubran** [comment]
yeah actually you can just run `gulp` and you'll see the error.. it's from the suggestion I gave you
We do have a critical.css at the end which is getting processed
but no worries I'll fix it, I just needed to write them down

**Comment by jadjoubran** [comment]
@chihab I think critical.css was working fine for you when running gulp..
but it was failing for me, and after digging, I found this [issue](https://github.com/laravel/elixir/issues/429)
So running npm update fixed it 👍
