### ISSUE TITLE
TypeError: $auth.isAuthenticated is not a function at redirectToLogin

### ISSUE THREAD

**Issue by jeslomo** [jadjoubran/laravel5-angular-material-starter#363]
- **I'm submitting a ...**
- [X] bug report
- **Provide information & explanation**

Hi, i'm trying the framework and i have found a bug in the **routes.run.js** file.

If implements: "data: {auth: true}" in the routes.config.js in theory the event "redirectToLogin" must be fired, but when arrive to the funcion "$auth.isAuthenticated()" it crashed.

Attach a IMG: https://s32.postimg.org/s9gmn42th/Captura_de_pantalla_2016_07_12_a_las_16_25_27.png

I've change this code:

```
export function RoutesRun($state, $transitions) {
    'ngInject';

    let requiresAuthCriteria = {
        to: ($state) => $state.data && $state.data.auth
    };

    let redirectToLogin = ($auth) => {
        'ngInject';
        if (!$auth.isAuthenticated()) {
            return $state.target('app.login', undefined, {location: false});
        }
    };

    $transitions.onBefore(requiresAuthCriteria, redirectToLogin, {priority:10});

}
```

By this:

```
export function RoutesRun($state, $auth, $transitions) {
    'ngInject';

    let requiresAuthCriteria = {
        to: ($state) => $state.data && $state.data.auth
    };

    let redirectToLogin = () => {
        'ngInject';
        if (!$auth.isAuthenticated()) {
            return $state.target('app.login', undefined, {location: false});
        }
    };

    $transitions.onBefore(requiresAuthCriteria, redirectToLogin, {priority:10});

}
```

I've change the $auth var to inject instead the "redirectToLogin".

And now (with my modifications) **it works perfectly**.
- **Laravel & Angular version:** 3.2.1

**Comment by jadjoubran** [comment]
Thanks @jeslomo 
I'll fix it soon

**Comment by proxnoob06** [comment]
Hi @jeslomo  when i'm trying your code i got this error. 

`angular.js:68Uncaught Error: [$injector:unpr] Unknown provider: $transitionsProvider <- $transitions`

**Comment by jeslomo** [comment]
Hi @proxnoob06 

This error is the unique error in javascript console?

I think you should have more errors or problems in the code that are preventing you inject this library

Could you give us more information?

**Comment by proxnoob06** [comment]
Hello @jeslomo,

in my index.modules config
 `angular.module('app.run', ['ui.router'])`

my  Routerun config
I tried to inject $transitions
`RoutesRun($rootScope, $state, $auth, $transitions)`

and i got this error 
`angular.js:68Uncaught Error: [$injector:unpr] Unknown provider: $transitionsProvider <- $transition`
[https://s31.postimg.org/6rnfrs9qj/transitions.png](url)

**Comment by jeslomo** [comment]
Hi, 

I see the problem.

In my index.modules.js i've this:

```
angular.module('app', [
    'app.run',
    'app.filters',
    'app.services',
    'app.components',
    'app.directives',
    'app.routes',
    'app.config',
    'app.partials'
]);

angular.module('app.run', []);
angular.module('app.routes', []);
angular.module('app.filters', []);
angular.module('app.services', []);
angular.module('app.config', []);
angular.module('app.directives', []);
angular.module('app.components', [
    'ui.router', 'ngMaterial', 'angular-loading-bar',
    'restangular', 'ngStorage', 'satellizer'
]);

```

And in my run:

```
import {RoutesRun} from './run/routes.run';

angular.module('app.run')
    .run(RoutesRun);

```

Witch version are using?

**Comment by proxnoob06** [comment]
the second one..

angular.module('app.run', []);
angular.module('app.routes', []);
angular.module('app.filters', []);
angular.module('app.services', []);
angular.module('app.config', []);
angular.module('app.directives', []);
angular.module('app.components', [
'ui.router', 'ngMaterial', 'angular-loading-bar',
'restangular', 'ngStorage', 'satellizer'
]);

**Comment by proxnoob06** [comment]
version of laravel angular or ui router?

laravel angular: lastest version 3.2
ui router: ~0.2.15 already tried ~0.3.1 same error

**Comment by jeslomo** [comment]
Version of laravel angular, and witch branch has use?

**Comment by flick36** [comment]
That's cause we are Using Ui-Router 1.0.0-alpha3 

https://github.com/jadjoubran/laravel5-angular-material-starter/pull/283

https://github.com/jadjoubran/laravel5-angular-material-starter/pull/296

Although a new beta came out 20 days ago, there were some breaking changes, and i haven't exactly look at the code to see if we can safely update to the beta, but i believe we can't, cause of the breaking changues i mentioned, anyway i'll take a look soon, and made a PR in case we need to update some code with the new beta one.

**Comment by proxnoob06** [comment]
Hello @flick36 ,

Thank you very much.

i already updated into 1.0.0-alpha3 version but i got several issues into $state with params and notify.

code:
`this.$state.go('dashboard.test',{param1:param1},{notify:false})`

in my example above my current state become disabled and unclickable but when i use the old version '0.2.15' it works fine.

**Comment by flick36** [comment]
That's because `notify` will broadcast `$stateChangeStart` and `$stateChangeSuccess` events. And those events `stateChange*` as you can read on https://github.com/angular-ui/ui-router/releases/tag/1.0.0alpha0

> All state events, (i.e. $stateChange\* and friends) are deprecated and disabled by default; re-enable them by including the ng1/stateEvents.js file, and depend on the ui.router.state.events angular module in your application.

So, notify won't work, altough i encourage you to update to the new beta you might have a hard time triyin yo figure out how to make things work, because there's no documentation yet, but it will be a must-have changue when the it reaches stable version. So if you don't want to learn all over again, you can just rollback the changues in https://github.com/jadjoubran/laravel5-angular-material-starter/pull/283 and use the `0.2.15` version that you are most used to...

BTW [here's the documentation](http://angular-ui.github.io/ui-router/1.0.0-alpha.3) for `1.0.0-alpha3` but like i said, it's in a very early WIP state so you might not understand everything in there.

**Comment by jadjoubran** [comment]
@jeslomo thanks again for reporting this
I wanted to fix it in 3.3.0 but I just noticed that it has already been fixed before
@flick36 thanks as well for your help 😄

**Comment by cyberkiko** [comment]
Original issue is happening on fresh install. 

This happends once I set auth:true

```
.state('app', {
   abstract: true,
   data: {auth: true},
   views: {
     header: {
        templateUrl: getView('header')
    },
...
```

![screen shot 2016-08-09 at 1 14 27 pm](https://cloud.githubusercontent.com/assets/888793/17525989/3f4fa7fa-5e33-11e6-8995-de48085e8bce.png)

**Comment by flick36** [comment]
@cyberkiko That's because you don't put `auth:true` on the abstract state... you put `auth` in any child state for example the landing page

https://github.com/jadjoubran/laravel5-angular-material-starter/issues/346#issuecomment-228129322

**Comment by jadjoubran** [comment]
@cyberkiko updated comment in routes.config.js, because it used to be in the abstract state

**Comment by cyberkiko** [comment]
@jadjoubran & @flick36 thanks that works, but also I did update the routes.run.js file as was suggested in the first comment, else wouldn't work.

**Comment by jadjoubran** [comment]
Yes that's because this has been probably merged after you installed your version of this starter

**Comment by mikemillers** [comment]
I am getting this error because for the most obvious of reasons: $auth.isAuthenticated is not a function.

I changed routes.run.js on line 10 to:

`if (!$auth.isAuthenticated) { .. } `

And all good after that,

Thanks Jad btw!
