### ISSUE TITLE
Need Custom Dialog Sample with pass $scope parent

### ISSUE THREAD

**Issue by chojuanillo** [jadjoubran/laravel5-angular-material-starter#365]
- **Provide information & explanation**

Hi. could someone help me with an example to move the scope parent to custom dialog

thank you very much

**Comment by jadjoubran** [comment]
Hi @chojuanillo 
I think one of those 2 issues would help
#287 and #336 
Let me know!

**Comment by chojuanillo** [comment]
hello, for me this example not work :

in the dialog 

```
 save(){
        //Logic here
        this.DialogService.hide();
    }

    cancel(){
        this.DialogService.cancel();
    }
```

cancel not work ... error: `TypeError: this.DialogService.cancel is not a function`

in a controller that call dialog:

```
modificarreserva() {
        let options = {
            controller: Entradalibros1Controller,
            controllerAs: 'vm',
            scope: this //(this? or which $scope ... in example angular material use $scope, which is used here?)
        };
        this.DialogService.fromTemplate('entradalibros1', options);
    }
```

I have also imported the controller

`import { Entradalibros1Controller } from '../../../dialogs/entradalibros1/entradalibros1.dialog.js';`

sorry my english and sorry 
apology is a Newbie in angular programing.

thanks in advance

**Comment by flick36** [comment]
Why you wanna pass scope? usually there's no need to do that, can you post the all code please? Also, if you want to speak in spanish we can private chat in [Gitter](https://gitter.im/jadjoubran/laravel5-angular-material-starter)

**Comment by jadjoubran** [comment]
@chojuanillo resolved?

**Comment by daem0ndev** [comment]
@chojuanillo you should not pass the parent scope to the dialog, instead use the `locals` key when passing options to your dialog to send down any relevant bits from your parent scope to the dialog's scope. They will be available in your dialog's controller under this.locals

**Comment by flick36** [comment]
This is solved @jadjoubran

**Comment by lahirudb** [comment]
Hi, I need to open a dialog service template from another dialog service..

**Comment by lahirudb** [comment]
@chojuanillo  you need to add the following in the constructor
constructor(DialogService){
this.DialogService = DialogService;
}
use this.DialogService ....
