### ISSUE TITLE
DialogService fromTemplate does not reference dialog controller js

### ISSUE THREAD

**Issue by daem0ndev** [jadjoubran/laravel5-angular-material-starter#371]
- **I'm submitting a ...**
- [x] bug report
- [x] feature request
- [ ] support request
- [ ] other (Please specify)
- **Provide information & explanation**
  When using the ng:dialog generator, its nice that you get the dialog html and controller stubs, however, when using the DialogService.fromTemplate() method, it does not include the controller js by default. This is confusing and feels like its not really working "out of the box".

Let me know if you plan on fixing this, or if you intended that we should pass the controller manually in the options whenever calling DialogService.fromTemplate() 

I am guessing the issue is referencing the controller dynamically via imports at run time?
- **Laravel & Angular version:** 3.2.0

**Comment by jadjoubran** [comment]
Hi @daem0ndev 
Thanks for this!
Would you be able to submit a PR with your suggestions? And then we can discuss what's the ideal fix

**Comment by jeslomo** [comment]
Hi, 

I've the same problem. How can use a controller in custom dialog?

And i've found a problem:

I've change this:
options.templateUrl = './views/dialogs/' + template + '/' + template + '.dialog.html'

By this:
options.templateUrl = '../angular/dialogs/' + template + '/' + template + '.dialog.html';

**Comment by jeslomo** [comment]
Any solution for this?

**Comment by flick36** [comment]
https://github.com/jadjoubran/laravel5-angular-material-starter/issues/287#issuecomment-216327964
