### ISSUE TITLE
Need an example of logout functionality

### ISSUE THREAD

**Issue by avastamin** [jadjoubran/laravel5-angular-material-starter#372]
Sorry, I new and I am looking for an example of logout functionality. How I can add a simple logout button and redirect to login page after logout out.

Thanks in advance.

**Comment by jadjoubran** [comment]
Hi @avastamin 
You can just have a regular logout method like this:

``` javascript
  logout() {
    this.$localStorage.$reset();
    this.$state.go('app.landing');
  }
```

In this example, I chose to clear out the localstorage values but that might not be ideal for your application

Let me know if it works for you

**Comment by avastamin** [comment]
Thanks.  I want to integrate ui calendar but not sure how to add custom angular code like this: https://github.com/angular-ui/ui-calendar/blob/master/demo/calendarDemo.js

Your support would really help a lot.

**Comment by jadjoubran** [comment]
For package specific help that are not part of this starter, I'd recommend the [gittr chat room](https://gitter.im/jadjoubran/laravel5-angular-material-starter)
