### ISSUE TITLE
Theme Change

### ISSUE THREAD

**Issue by MohamedQabbani** [jadjoubran/laravel5-angular-material-starter#374]
- **I'm submitting a ...**
- [x] support request

Can i replace current theme with metronic material theme?
And if i replace is i will rewrite all components in this theme as angularjs

**Comment by jadjoubran** [comment]
Most components are agnostic from Angular Material, except for the ToastSerice which you can get rid of
I'd recommend getting rid of Angular material first, and then following the steps of the theme you have
