### ISSUE TITLE
Angular 2 converting

### ISSUE THREAD

**Issue by filipveschool** [jadjoubran/laravel5-angular-material-starter#377]
- **I'm submitting a ...**
- [ ] bug report
- [ ] feature request
- [ ] support request
- [ ] other (Please specify)
- **Provide information & explanation**
- **Got code samples?**
  Make sure to use 3 backticks (and javascript or php after it to show your code) [More info](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code)
  Also make sure to click on the _Preview_ button to double check your code formatting
- **Laravel & Angular version:** 3.2.0

**Comment by filipveschool** [comment]
Hi, Will you convert your project soon to angular 2?

**Comment by jadjoubran** [comment]
Hi @filipveschool 
You can follow the discussion here #345
