### ISSUE TITLE
how to write code in restangular?))

### ISSUE THREAD

**Issue by varrek1** [jadjoubran/laravel5-angular-material-starter#379]
how to write code in restangular? For example, in angular, I wrote in the html
ng-click="paginateBack()" 
and
$scope.paginateBack = function () {}
in controller,
 how to implement it here? The video in YouTube is explained only form, but how do other things not shown dynamic.Sorry for my english , it is google translate.

**Comment by jadjoubran** [comment]
@normann1993 there's no difference, you can use it just like we used it in the screencasts
Make sure to check the [official documentation for Restangular](https://github.com/mgonto/restangular)
