### ISSUE TITLE
The online demo doesn't work

### ISSUE THREAD

**Issue by llstarscreamll** [jadjoubran/laravel5-angular-material-starter#382]
- **I'm submitting a ...**
- [x] bug report
- **Provide information & explanation**
  The online demo only show the welcome page, trying to register and gives a "Internal Server Error" and there is no example data to login (is just missing) can't test the login form

**Comment by jadjoubran** [comment]
Yes indeed, the docs don't have a database that's why..
but normally people don't know the urls for login and register, and they're not linked from the landing page
