### ISSUE TITLE
No 'Access-Control-Allow-Origin'

### ISSUE THREAD

**Issue by proxnoob06** [jadjoubran/laravel5-angular-material-starter#383]
- **I'm submitting a ...**
- [ ] bug report
- [ ] feature request
- [x] support request
- [ ] other (Please specify)

Hello,

I would to ask how to fix this  error `XMLHttpRequest cannot load http://v0.postcodeapi.com.au/states.json. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access.`?

I tried to get data from the api `http://v0.postcodeapi.com` but im getting errors, when i used plugins by Google Chrome (Allow-Control-Allow-Origin)  it works fine.  

this is my code
    `states(){
        let state = this.Restangular.allUrl('states','http://v0.postcodeapi.com.au/states.json').getList();
        return state;   
    }`

**Comment by flick36** [comment]
Can you try in another browser? i think chrome doesn't allow CORS on localhost, you should use a domain like `example.dev`

**Comment by proxnoob06** [comment]
thank you @flick36 , i will try it later :+1:

**Comment by fusedtechresource** [comment]
@flick36 , bro i already updated in hosting but i got same error.

**Comment by jadjoubran** [comment]
Hi @proxnoob06 
Has this been resolved?

**Comment by proxnoob06** [comment]
hello @jadjoubran ,
Yes this is already resolved by using laracurl from backend.

Thanks!
