### ISSUE TITLE
Adding angular-aria dependency to the application [Support]

### ISSUE THREAD

**Issue by harishsn** [jadjoubran/laravel5-angular-material-starter#384]
- **I'm submitting a ...**
- [x] support request
- **Provide information & explanation**
  Need support in adding angular-aria dependency for tab-index functionality
  **Angular-aria installation from NPM
  I'm getting this error
  Error: [$injector:unpr] Unknown provider: ngAriaProvider <- ngAria
- **Laravel & Angular version:** 3.2.0

**Comment by jadjoubran** [comment]
Hi @harishsn 
I think ng-aria is already a dependency of Angular Material..
However if you need to set it as a dependency, you need to do that using bower
