### ISSUE TITLE
Laravel Auth::user() returns null when logged in? How Does Middleware Work?

### ISSUE THREAD

**Issue by admcfajn** [jadjoubran/laravel5-angular-material-starter#386]
- **I'm submitting a ...**
- [ ] bug report
- [ ] feature request
- [x] support request
- [ ] other (Please specify)
- **Provide information & explanation**
  After login Auth::user() returns null. 

Laravel Auth::user() returns null when logged in?

How do I access Authenticated User Data? 

How should I be passing user-data in to Angular? 
- Can I do this from several places throughout the build?
- Or should I store it all in Angular at login?

I guess my question comes down to: How does middleware work between the angular ui and the laravel api. I can pass data from one side to another. Users seem to be logged in to angular but not the api (wether called from angular or anonymously). I'm guessing I need to call the api in another way, or edit a permissions configuration.

Thanks!

```
class AuthController extends Controller
{
    public function getUser(){
        $user = Auth::user();
        return response()->success(compact('user'));
    }
}
$api->any('getuser', 'Auth\AuthController@getUser');

localhost:8000/api/auth/getuser
[null]
```
- **Laravel & Angular version:** 3.2.0
  Unsure where to find that info in the project. Pretty sure it's recent (the project is 2 months old)

**Comment by jadjoubran** [comment]
Hi @dabzo 

I'm assuming you're using JWT authentication right?
If yes then you need to make sure to send the token according to the docs [here](https://github.com/tymondesigns/jwt-auth/wiki)

**Comment by admcfajn** [comment]
Thanks very much @jadjoubran 

That's the case, yes. I'll dig in to that documentation. Thank you.
- Update: Here's the code I used:

**Laravel Controller**

```

namespace App\Http\Controllers\Auth;

use Auth;
use JWTAuth;
use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

// use Session;

class AuthController extends Controller
{
    public function getUser(Request $request){
        $user = JWTAuth::parseToken()->authenticate();
        return $user;
        // return response()->success(compact('user'));
    }
}

```

**Angular API Call**

```
    $onInit(){

        console.log('this is the token:');
        console.log(this.$auth.getToken());

        let token = this.$auth.getToken();

        this.API.all('auth/getuser').post({token: token})
        .then((user)=>{

            console.log( 'this is the user: ', user.user );

            this.user = user.user;

            this.name = user.user.firstName;
            this.lname = user.user.lastName;

        });
    }

```

The satellizer api-reference was also handy when learning this: https://github.com/sahat/satellizer#api-reference

**Comment by jadjoubran** [comment]
Great! 😄
