### ISSUE TITLE
401 (Unauthorized)

### ISSUE THREAD

**Issue by proxnoob06** [jadjoubran/laravel5-angular-material-starter#387]
- **I'm submitting a ...**
- [ ] bug report
- [ ] feature request
- [x] support request
- [ ] other (Please specify)

Hello Guys,

I would like to ask why i can always get this error 

`401 (Unauthorized)`

`{"message":"Wrong number of segments","status_code":401}`

using port 3000, (browser-sync as recommended)
when i trying to repeat my request or refresh  the page  sometimes it works

i also tried in 8000 port i can get this error rarely.
- **Laravel & Angular version:** 3.2.0

**Comment by jadjoubran** [comment]
Hi @proxnoob06 
This might have to do with the `token` you're sending

This [issue](https://github.com/tymondesigns/jwt-auth/issues/35) might help

**Comment by proxnoob06** [comment]
oh thank jadjouban, maybe the reason is my custom token.
