### ISSUE TITLE
Upgrade to Laravel 5.3

### ISSUE THREAD

**Issue by jadjoubran** [jadjoubran/laravel5-angular-material-starter#388]
This is going to be an ongoing effort as we are waiting for vendor library to support 5.3:
- [x] jwt-auth
- [x] dingo/api (will be removed from the starter)

However, now that Laravel has a dedicated API routes file and middleware groups.. I'm doubting dingo/api will be useful to everyone
I'm thinking of removing dingo/api for the next version, and people who are upgrading and depend on it, can just simply install it (takes 2 minutes)

I also predict the below features:
- [x] Replace default vue components with Angular equivalent
- [x] JWT setup for API
- [x] Use elixir's webpack
- [x] Use mix.combine instead of custom elixir task
- [x] all the previous awesomeness (unless it's not needed anymore)

It's great to see with every release, that Laravel is adapting more & more of the core features that we used to rely on.. (API routes, etc..) which allows us to make it even neater in the starter
Also angular-cli is making all the boilerplate work vanish!

As usual, feedback is more than welcome 😄

**Comment by dameety** [comment]
@jadjoubran Really looking forward to that. Well done. I have a question, please, if possible, how would you say is the best way to make an admin dashboard with this package.

**Comment by jadjoubran** [comment]
Thanks @dameety 
Someone has already done that, and has documented it in the [recipes](https://github.com/jadjoubran/laravel-angular-recipes)

**Comment by dameety** [comment]
Mega thanks @jadjoubran. Very grateful

**Comment by daem0ndev** [comment]
Looking forward to this! If you want help testing out the upgrade path, Im interested in assisting. Till then it looks like I should just stick to 5.2 on my project.

**Comment by jadjoubran** [comment]
@daem0ndev Thanks! I will post updated on this issue

**Comment by abebars** [comment]
Looking forward to this!

**Comment by jadjoubran** [comment]
Elixir now has webpack support 🎉 
This is another step that we don't have to worry about in 5.3

**Comment by nueko** [comment]
Hi, have you started this, which branch?

**Comment by rusowyler** [comment]
👍

**Comment by jadjoubran** [comment]
Hi @nueko I'm starting soon
The branch will be called `version-3.4`

**Comment by jadjoubran** [comment]
I started working on it 😄 You can follow the process [here](https://trello.com/c/yFT9yZCv/139-laravel-5-3-support)

**Comment by jadjoubran** [comment]
Almost done with this

**Comment by jadjoubran** [comment]
Beta tagged! `3.4.0-beta` Please report any issues you find
I will work on the docs and publish it soon 😄

**Comment by jadjoubran** [comment]
3.4 is released 🎉 
Thanks for all the help
