### ISSUE TITLE
Help State Roles

### ISSUE THREAD

**Issue by proxnoob06** [jadjoubran/laravel5-angular-material-starter#389]
- **I'm submitting a ...**
- [ ] bug report
- [ ] feature request
- [x] support request
- [ ] other (Please specify)

Hello Guys,

Can you give me a help  regards in user roles,

i already research about this and i found that i need create some login ni routes.run , is that possible?

ex.

```
.state('dashboard', {
           abstract: true,
            data: {
                auth:true,
           },
            views: {
               main: {}
}

state('dashboard.home', {
           url: '/dashboard/home',    
           data: {
               auth:['admin','agent']
              }

}
```

**Comment by jadjoubran** [comment]
Hi @proxnoob06 
There was some discussion about this [here](https://github.com/jadjoubran/laravel5-angular-material-starter/issues/223)

**Comment by proxnoob06** [comment]
Hello @jadjoubran ,

I already tried base on that discussion but i am failed from getting value of roles

`data: {roles: ['admin'] }`

when i logged $state service  i got an several objects like `current` that contains object that i need.
however i got different object while logging $state.current.

what i'm trying to do is compare base on role of user and redirect to not found page if not user role is valid 

<img width="216" alt="state" src="https://cloud.githubusercontent.com/assets/20083187/18076284/2b5d9a4a-6eaf-11e6-9a9e-15db39de7284.png">
<img width="412" alt="state current" src="https://cloud.githubusercontent.com/assets/20083187/18076283/2b5494b8-6eaf-11e6-8d55-70158fa6fa43.png">

here's my codes

```

let redirectToNotFound = ($transition$) => {
        'ngInject';

        $log.log('$state',$state);
        $log.log('$state.current',$state.current);


        /*   
            angular.forEach($state.current.data.roles,function (value,key) {

                if (!value == $auth.getPayload().role.name);
                    return $state.target('app.not-found', undefined, {location: false});
                }
            })
      */

};

```

**Comment by proxnoob06** [comment]
Opss Sorry Guys for noob question. i already solve this by this code
```
let requireRole =  {
        to: ($state) => $state.data.except && $state.data.except == $auth.getPayload().roles.role
    };
let redirectToNotFound = ()=>{
        return $state.target('dashboard.not-found', undefined, {location: false});
    }
```

**Comment by jadjoubran** [comment]
I'd use `$state.data` to get the auth
