### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Unstinted** [jadjoubran/laravel5-angular-material-starter#390]
FatalErrorException in a9fa41c0c46628eebba0db4ad37742bda7130626.php line 17: Illuminate\View\Engines\PhpEngine::main(): Failed opening required '/home/wpc/Desktop/Projects/laravel5-angular-material-starter/public/css/critical.css' (include_path='/home/wpc/Desktop/Projects/laravel5-angular-material-starter/vendor/phpseclib/phpseclib/phpseclib:.:')

```
in a9fa41c0c46628eebba0db4ad37742bda7130626.php line 17
```

The above shore the error when i ran php artisan serve

**Comment by jadjoubran** [comment]
Hi @Unstinted 
Is this on a fresh install?

**Comment by CptChaos** [comment]
I am having the same issue, using a fresh install. Tried a reinstall (as I had packages updated), but didn't  help.
