### ISSUE TITLE
Global Variables Assignment 

### ISSUE THREAD

**Issue by abebars** [jadjoubran/laravel5-angular-material-starter#391]
- **I'm submitting a ...**
- [ ] bug report
- [ ] feature request
- [x] support request
- [ ] other (Please specify)

Better description I am trying to achieve something like this
so i can call the settings from any controller or view 
`App.factory('settings', ['$rootScope', function($rootScope) {
    // supported languages
    var settings = {
        layout: {
            pageSidebarClosed: false, // sidebar menu state
            pageContentWhite: true, // set page content layout
            pageBodySolid: false, // solid body color state
            pageAutoScrollOnLoad: 1000 // auto scroll to top on page load
        },
        assetsPath: '../assets',
        globalPath: '../assets/global',
        layoutPath: '../assets/layouts/layout2',
    };
    $rootScope.settings = settings;
    return settings;
}]);`
- **Laravel & Angular version:** 3.3.0

@jadjoubran

**Comment by flick36** [comment]
First of all that would never work. Are you new to angular or coding in general? have you work with classes before? are you familiar with OOP?

You have 2 classes there, the `AppViewController` and the `LoginFormController` each class has it's own scope, wich means they don't share variables, i mean just think about it, it's like you have to refrigerators, each one has it's own fruits, of course you can change their fruits inside the fridge but theres no way one fridge know what inside another fridge...

That said, if you don't want to show the header or footer in one view just in your `angular\config\
routes.config.js` look for the `app.login` state and just delete the header and footer view so you end up having something like:

```
.state('app.login', {
    url: '/login',
    views: {
        'main@': {
        templateUrl: getView('login')
    }
    }
})
```

**Comment by abebars** [comment]
@flick36  Yeah , I am really new here thanks for your advice but you answer will not fix the problem I have I can override the header to be empty template HTML , but I am  looking to initialize global settings which could be changed from any controller are you familiar with that !!!

**Comment by flick36** [comment]
That wasn't what your original post said, i did solve what you asked first ¬¬

Create a service https://github.com/jadjoubran/laravel5-angular-material-starter/issues/331#issuecomment-224471442

**Comment by abebars** [comment]
@flick36 you didn't solve it as i need but anyway i found the way to do it.
Thanks for nothing :) lol

**Comment by flick36** [comment]
```
I'm submitting a ...
 bug report
 feature request
 support request
 other (Please specify)
I am just new to Angluar JS and had rough time to do what i am thinking to do in this way.
I want to hide the Header on Specific Page through ng-show and variables to be assigned in AppComponet and cahnge those values in the LoginFormComponent 
here is the code

`class AppViewController {
constructor($mdToast, ToastService, $window) {
'ngInject';

    this.$window = $window;
    this.$mdToast = $mdToast;
    this.ToastService = ToastService;
    this.headerShow = true;
    this.footerShow = true;

}`
"class LoginFormController {
constructor($auth, ToastService) {
'ngInject';

    this.$auth = $auth;
    this.ToastService = ToastService;
    this.headerShow = false;
    this.footerShow = false;
}"
`div ui-view="header" ng-show="vm.headerShow">

div ui-view="footer" ng-show="vm.footerShow">`

Laravel & Angular version: 3.3.0
@jadjoubran
```

I did solve what you asked, you should elaborate better next time if you want people to solve your problems as you 'need them' to be solved

You're welcome (:

**Comment by abebars** [comment]
@flick36  Just Personal Advice Take or Ignore it , If you want to be appreciated for helping anybody **Don't be offensive** :) Always remember experience come from mistakes , Wish you best luck
