### ISSUE TITLE
StyleCI Turned Off?

### ISSUE THREAD

**Issue by GrahamCampbell** [jadjoubran/laravel5-angular-material-starter#395]

**Comment by jadjoubran** [comment]
I wanted to ping you about it but forgot 😄 
I had to temporarily turn it off because it was removing unused imports which are kept on purpose in Laravel to make it easier in some files
I used to have the `present: laravel`
what other changes should I make? Thanks!

**Comment by GrahamCampbell** [comment]
The laravel/laravel repo just turns off the unused imports fixer.

**Comment by GrahamCampbell** [comment]
``` yaml
preset: laravel

disabled:
  - unused_use
```

**Comment by jadjoubran** [comment]
Great thanks!
I've also got this issue: https://styleci.io/analyses/qoLBQb
 any idea?

**Comment by GrahamCampbell** [comment]
Looks ok to apply the changes. laravel/laravel excludes those files. I'll probably talk to Taylor about getting those defaults changes at somepoint.

**Comment by GrahamCampbell** [comment]
Alternatively, just remove those comments. That's probably what I'll recommend for the core.

**Comment by jadjoubran** [comment]
Okay, thanks @GrahamCampbell
