### ISSUE TITLE
No final.js file

### ISSUE THREAD

**Issue by blackotruck** [jadjoubran/laravel5-angular-material-starter#398]
- **I'm submitting a ...**
- [x] bug report
- [ ] feature request
- [ ] support request
- [ ] other (Please specify)
- **Provide information & explanation**
  `mix.version()` is not creating public\js\final.js causing `File js/final.js not defined in asset manifest. (View: C:\wamp\www\laravel-api\resources\views\index.blade.php)`
- **Got code samples?**
  Make sure to use 3 backticks (and javascript or php after it to show your code) [More info](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code)
  Also make sure to click on the _Preview_ button to double check your code formatting
- **Laravel & Angular version:** 3.2.0

**Comment by jadjoubran** [comment]
Related to #397
