### ISSUE TITLE
No seeJsonKeyValueString() function

### ISSUE THREAD

**Issue by monkeyWzr** [jadjoubran/laravel5-angular-material-starter#399]
Hi, I'm a new learner. When I was trying the tutorial using the **master** branch, I found there's no `seeJsonKeyValueString()` in `TestCase` class (no `seeJsonKeyValue()` either). So phpunit can't run successfully as the video shows.
 I wonder if it is because this function is deprecated and the tutorial should be updated:D.

**Comment by jadjoubran** [comment]
Hi @monkeyWzr 
Thanks for reporting this
Yes indeed, those functions have been deprecated. Just to make sure, are you watching the tutorial in the screencast? or going through the text documentation?

**Comment by monkeyWzr** [comment]
The text documentation [TDD](https://laravel-angular.readme.io/docs/tdd)(v3.3). And I think the same codes shows up in the screencast, too.(at about 3:50 in the video [
Laravel Angular Material Starter #3 - Tutorial](https://youtu.be/_ZWV9KBK2N8))

**Comment by Banjerr** [comment]
I also just ran across this, watching the screen cast. Whats the alternative function to use here? @jadjoubran thanks!

_edit_ figured it out through some trial and error.
`->seeJson(['name' => $post->name, 'topic' => $post->topic])`
instead of
`->seeJsonKeyValueString('name', $post->name)
      ->seeJsonKeyValueString('topic', $post->topic);`

**Comment by jadjoubran** [comment]
Yes true, the reason why those helpers were deprecated was that Laravel started providing the `seeJson` helper
I will update the docs & tutorial soon
Thanks!

**Comment by yazfield** [comment]
@jadjoubran suggested an edit to the docs. Just add a YouTube annotation to the videos :)

**Comment by jadjoubran** [comment]
@yazfield on it, thanks 😄 
I was off the grid for the past month (small surgery, conferences & overloaded with work)
Will try to release 3.4 tonight

**Comment by jadjoubran** [comment]
Fixed in both places!

**Comment by yazfield** [comment]
@jadjoubran oh I hope you're doing well!

**Comment by jadjoubran** [comment]
@yazfield yep I fully recovered, cheers!
