### ISSUE TITLE
Generator for AngularJS

### ISSUE THREAD

**Issue by palpalani** [jadjoubran/laravel5-angular-material-starter#4]
Can you implement generator for AngularJS with GulpJS https://github.com/Swiip/generator-gulp-angular with a helper generator for generator-gulp-angular to create sub tasks: https://github.com/doronsever/generator-gulp-angular-subtask

**Comment by jadjoubran** [comment]
Well I already have a yeoman generator for laravel 5 which also has an option for AngularJS
https://github.com/jadjoubran/laravel5-generator
Take a look and if you still can't find what you want, let's discuss it there. Open a new issue on the generator's repository
Thanks!
