### ISSUE TITLE
Livereload doesn't work

### ISSUE THREAD

**Issue by enzonotario** [jadjoubran/laravel5-angular-material-starter#400]
- **I'm submitting a ...**
- [ ] bug report
- [ ] feature request
- [x] support request
- [ ] other (Please specify)
- **Provide information & explanation**
  Hi!, I run `gulp && gulp watch`. When I save a changes, the `gulp watch` works (I can see in the terminal), but the browser doesn't refresh automatically. I have to refresh it manualli twice or three times to see the changes.

I run `php artisan serve --host=0.0.0.0` and doesn't work fine too.
- **Laravel & Angular version:** 3.3

Thanks! and sorry for my english!

**Comment by jadjoubran** [comment]
Hi @enzonotario 
This is actually a missing feature in 3.3 because service workers require SSL, I wasn't able to run a local version with https://
I will take a look soon and see if there's an update on it, if yes I'll release 3.3.1

**Comment by enzonotario** [comment]
Sorry! I realise that you remove livereload and put browserSync... browserSync doesn't work too, I have to put 

```
.browserSync({
            reloadDelay: 0,
            proxy: 'localhost:8000'
         });
```

in gulpfile.js.

It works fine in firefox. In chrome it reloads, and a few seconds later, the page shows me a message with something like "a newer version available - REFRESH"

Have you idea how fix this problem in chrome?

Thanks!

**Comment by jadjoubran** [comment]
oh so this works on https?
You can bypass the `a newer version available` from the `Applications` tab on chrome dev tools ([screencast](https://www.youtube.com/watch?v=qe5dJdPYvfA))

**Comment by enzonotario** [comment]
Thanks so much!!! :)

**Comment by jadjoubran** [comment]
@enzonotario does it work for you on HTTPS? https://localhohst:8000? with the setup you had

**Comment by nueko** [comment]
chrome's webworker just work on localhost and not any other domains eg project.dev.
just look [here](https://developers.google.com/web/fundamentals/getting-started/push-notifications/step-03#create-indexhtml)  _the p tag_

**Comment by jadjoubran** [comment]
that is true.. I wonder why I was striving for https support
Thanks for this! Would you be able to send a pull request targeting `develop` branch?

**Comment by nueko** [comment]
not, yet. i have a busy  month..

**Comment by enzonotario** [comment]
It works for me on localhost without https... and I do the "bypass" in chrome, and sometimes it works fine, and sometimes not...
