### ISSUE TITLE
Production/Testing Environments Configuration

### ISSUE THREAD

**Issue by hottehead** [jadjoubran/laravel5-angular-material-starter#403]
- **I'm submitting a ...**
- [ ] bug report
- [ ] feature request
- [x] support request
- [ ] other (Please specify)
- **Provide information & explanation**

I just deployed the first version to the testing environment. The application is now missing the critical.css. I noticed that the folder with this file is excluded via .gitignore. Am I supposed to install and run frontend preprocessing tools (npm, gulp, bower) on my production/testing environments, too? I'd prefer deploying a finished version of source code.

> main(): Failed opening required '/public/css/critical.css' (include_path='/vendor/phpseclib/phpseclib/phpseclib:.:/usr/share/php:/usr/share/pear') in 
> /storage/framework/views/14b87bc39f1dd9b28ace968557d2c4ce0f871497.php on line 19

**Comment by jadjoubran** [comment]
Hi @hottehead 
You can avoid running those tools by checking in this file into your source control... so yeah updating the gitignore would fix it

this is fine if you're the only one working on this project, but might become problematic if there are multiple developers working on it

**Comment by hottehead** [comment]
Hey @jadjoubran,

I now removed them from gitignore and it works. I dont see any other solutions too, except for a real build and deployment server.

Thanks so far.
