### ISSUE TITLE
remove hashtag # in url by angularjs 

### ISSUE THREAD

**Issue by puahyan** [jadjoubran/laravel5-angular-material-starter#407]
hi, i haved use this stack for some time, the only most problem i faced is the url #,
First , in index.blade.php as html file  i added <base href="/">  
Second, in the config file i add add 
 $locationProvider.html5Mode({
        enabled: true,
        requireBase: true
    });
then i reload, the url working well from http:8000/#/home -> http:8000/home, 
However, when I copy the link to new tab, it show page not found by laravel, display laravel path not found error,  it is because it detect the route by laravel in laravel routes, 

if you refresh the page/reload again, it show page not found, i get annoyed by the # in url, so how to fix this , thanks

**Comment by puahyan** [comment]
pls provide technical answer how to , thanks

**Comment by jadjoubran** [comment]
Here's how to fix your issue:
http://stackoverflow.com/questions/29484665/pretty-urls-in-angularjs-and-laravel-not-working

**Comment by puahyan** [comment]
YES SOLVE, the answer is change the return 404view to index view in handler.php, THANKS!!!!

**Comment by puahyan** [comment]
the only disadvantages is the console.log and network will display file not found error message

**Comment by jadjoubran** [comment]
You shouldn't show a 404, you should return the `view('index');`

**Comment by puahyan** [comment]
ya, thanks.
