### ISSUE TITLE
I can not add a module in app.components  - [support  request] 

### ISSUE THREAD

**Issue by confeccionar** [jadjoubran/laravel5-angular-material-starter#409]
index.modules.js

```
angular.module('app.components', [
    'ui.router', 'ngMaterial', 'angular-loading-bar',
    'restangular', 'ngStorage', 'satellizer', 'ui.utils.masks'
]);

```

bower.json

```
{
  "name": "laravel5-angular-material-starter",
  "authors": [
    "Jad Joubran <jad@jadjoubran.com>"
  ],
  "ignore": [
    "**/.*",
    "node_modules",
    "bower_components",
    "test",
    "tests"
  ],
  "dependencies": {
    "angular": "~1.5",
    "angular-ui-router": "~0.2.15",
    "ngstorage": "~0.3.3",
    "angular-material": "~1.1",
    "restangular": "~1.5.2",
    "angular-loading-bar": "~0.8.0",
    "satellizer": "^0.14.0",
    "angular-input-masks": "^2.4.0"
  }
}

```

show errors:

angular.js:68Uncaught Error: [$injector:modulerr] Failed to instantiate module app due to:
Error: [$injector:modulerr] Failed to instantiate module app.components due to:
Error: [$injector:modulerr] Failed to instantiate module ui.utils.masks due to:
Error: [$injector:nomod] Module 'ui.utils.masks' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.

**Comment by flick36** [comment]
Did you run `bower install --save angular-input-masks` and then `gulp` ?

**Comment by confeccionar** [comment]
thank you very much, i am noob :D
