### ISSUE TITLE
Out of the box JWT authentication

### ISSUE THREAD

**Issue by jadjoubran** [jadjoubran/laravel5-angular-material-starter#41]
- demo should show how JWT works, how the auth token is being generated, saved in localstorage and sent
- also show how it works with dingo/api
- also add note that if you don't plan on using JWT, then you should uncomment the CSRF token middleware

Or maybe "choose between JWT (disable CSRF) or not (enable CSRF) (or just add it to installation)"?

**Comment by jadjoubran** [comment]
Almost done with this :rocket:

**Comment by jadjoubran** [comment]
@Bodom78 @rooferz @masterpowers @palpalani
If you have time, just clone the repository and run it in the browser then open the JWT Auth page.

I added an interactive tutorial that explains demos how JWT works. I'd love to get your feedback on this.

**Comment by Bodom78** [comment]
@jadjoubran Nice, can't wait to check it out.

Will do my best to give it a shot either this or next weekend, doing crunch at the office till the end of the year so under the pump at the moment :(

**Comment by jadjoubran** [comment]
Will fix the design with the new website
