### ISSUE TITLE
decode token

### ISSUE THREAD

**Issue by proxnoob06** [jadjoubran/laravel5-angular-material-starter#411]
- **I'm submitting a ...**
- [ ] bug report
- [ ] feature request
- [x] support request
- [ ] other (Please specify)

Hello Guys, I would like to ask how can i decode a token?

I already tried JwtAuth::decode($token) but i got this error : 

```
{"message":"Argument 1 passed to Tymon\\JWTAuth\\JWTManager::decode() must be an instance of Tymon\\JWTAuth\\Token, string given","status_code":500}
```

my objective are:
1.I want to  a post token from other Apps(which we are also developed) and login using token.
2. Decode token to get payload information for queering  user if valid.
- **Laravel & Angular version:** 3.2.0

**Comment by jadjoubran** [comment]
Can you show a sample code?
