### ISSUE TITLE
Error while running gulp in v3.4

### ISSUE THREAD

**Issue by harishsn** [jadjoubran/laravel5-angular-material-starter#412]
- **I'm submitting a ...**
- [ ] bug report
- [ ] feature request
- [x] support request
- [ ] other (Please specify)
- **Provide information & explanation**
  Error while running gulp in v3.4
  [Error: Entry module not found: Error: Can't resolve 'babel?presets[]=es2015' in '/var/www/la_beta_test'
- **Laravel & Angular version:** 3.4

**Comment by jadjoubran** [comment]
It seems it's missing from package.json
You can temporarily fix by manually installing 
https://www.npmjs.com/package/babel-preset-es2015
Will release a fix soon, thanks!

**Comment by jadjoubran** [comment]
It turns out I was missing a bunch of them, thanks again @harishsn 
You can grab the updated package.json from the commit above
