### ISSUE TITLE
Authenticating with Facebook and Satellizer

### ISSUE THREAD

**Issue by CaptainChainsaw** [jadjoubran/laravel5-angular-material-starter#413]
- **I'm submitting a ...**
- [ ] bug report
- [ ] feature request
- [x] support request
- [ ] other (Please specify)
- **Provide information & explanation**

I am trying to authenticate and login using satellizer.  I'm new to Laravel and have some angular experience so please bear with me.  I created an app on Facebook to authenticate with and followed the instructions as best as I could.  I have a "sign in with facebook" button on my login page, clicking it does nothing and there are no errors in the console.  I expect I've not configured this correctly.  Could you please help me set this up?

Also how can I determine which routes should only be available to authenticated users?

On the facebook app I've set:

Valid OAuth redirect URIs: http://locahost:8000
Site URL: http://locahost:8000
- **Got code samples?**
  Make sure to use 3 backticks (and javascript or php after it to show your code) [More info](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code)
  Also make sure to click on the _Preview_ button to double check your code formatting

My login page:

```
    <md-content class="Page-container">
        <div class="Login-formContainer" layout="column" layout-align="center center">

           <h1 class="md-headline">Log in to your account</h1>

         <login-form></login-form>
        <button ng-click="authenticate('facebook')">Sign in with Facebook</button>
     </div>
  </md-content>
```

`    

```
 export function SatellizerConfig($authProvider) {
'ngInject';

$authProvider.httpInterceptor = function() {
    return true;
}

$authProvider.loginUrl = '/api/auth/login';
$authProvider.signupUrl = '/api/auth/register';
$authProvider.tokenRoot = 'data';//compensates success response macro

$authProvider.facebook({
  clientId: '317593668600609',   // app id
  responseType: 'token',
  name: 'facebook',
  url: '/auth/facebook',
  authorizationEndpoint: 'https://www.facebook.com/v2.5/dialog/oauth',
  redirectUri: window.location.origin + '/',
  requiredUrlParams: ['display', 'scope'],
  scope: ['email'],
  scopeDelimiter: ',',
  display: 'popup',
  oauthType: '2.0',
  popupOptions: { width: 580, height: 400 }
});
 }
```
- **Laravel & Angular version:** 3.2.0
  3.3

**Comment by jadjoubran** [comment]
Hi @CaptainChainsaw 
The `$authProvider.facebook` needs to be in your `login-form` component

**Comment by CaptainChainsaw** [comment]
Hi @jadjoubran 

I've had a look in login-form.component.js.  Please forgive my ignorance, if I want to use multiple authproviders is it a case of passing $authProvider to the constructor?  I'm not really sure what I'm meant to do with this file.  If there's any tutorials you can direct me to I'll happily take a look.

Thank you.

**Comment by jadjoubran** [comment]
Hi @CaptainChainsaw 
I haven't used satellizer recently.. you can find tutorials [here](https://www.google.bg/search?q=satellizer+tutorial&gws_rd=cr,ssl&ei=rF73V677Osj6aYDho_gK) especially the toptal article
