### ISSUE TITLE
Newly created html files are not copied when running gulp (v 3.4)

### ISSUE THREAD

**Issue by yazfield** [jadjoubran/laravel5-angular-material-starter#414]
Hi, first time testing this and it looks great!
- **I'm submitting a ...**
- [x] bug report
- [ ] feature request
- [x] support request
- [ ] other (Please specify)
### Information & explanation

I've been following the "create post" tutorial but I found that newly created html files (create_post.html) don't get copied to public folder after re-executing `gulp && gulp watch`.

I tested deleting `public/views/pages/footer` folder on a fresh install then re-executed `gulp && gulp watch` and got the same result.
Note that running `gulp && gulp watch` the first time after a fresh install copies the files correctly

Thanks for your help.
- **Laravel & Angular version:** 3.4.0
- **npm version:** 3.10.8
- **gulp version:** 3.9.1

**Comment by jadjoubran** [comment]
Hi @yazfield 
Will test this after we fix the other issue
Thanks!

**Comment by puahyan** [comment]
hi, how can i download 3.4 version? laravel 5.3 right?

**Comment by yazfield** [comment]
@puahyan if you're using git, just change your working branch after cloning with: `git checkout -b version-3.4`
you can list all branchs with this command: `git branch -a`

Otherwise, change the branch from github's web application and download the zipfile. Check the attached photo.
![attachment](https://cloud.githubusercontent.com/assets/9166171/19191711/d749d8ca-8ca3-11e6-8045-47a7a7005f65.png)

**Comment by puahyan** [comment]
Failed opening required '/Applications/AMPPS/www/angular-material/public/css/critical.css, its the gulp problem, in package .json why it is different from previous one, the  "dependencies": {... gone. i having a lot problme to installing this.
is the issue fix yet?

**Comment by puahyan** [comment]
and the elixir, issue, npm install have problem for exlir, due to version 
peerinvalid The package laravel-elixir@6.0.0-11 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer laravel-elixir-eslint@3.0.0 wants laravel-elixir@>=3.0.0

**Comment by puahyan** [comment]
hi, version 3.3 everything works fine, but in laravel 5.2, nvm i just wait a stable 3.4. which is larael 5.3
thanks

**Comment by yazfield** [comment]
still have some troubles, trying to fix.

**Comment by jadjoubran** [comment]
After @yazfield, it seems that it's working
Thanks again @yazfield 
Feel free to re-open if the issue persists

**Comment by gultomic** [comment]
Hi @jadjoubran 

I have an issue for fresh install version 3.4 stable using `create-project`
it's fine when running gulp but got error on gulp watch

``` javascript
stream.js:74
     throw er; // Unhandled stream error in pipe.
     ^
Error: ENOENT: no such file or directory, stat 'C:\lams34\public\build\js\final-f5bfbdcd52.js'
    at error (native)
```

I'm running on:
- windows
- gulp
  - _CLI version 3.9.1_
  - _Local version 3.9.1_
- npm version: 3.10.8
- bower version: 1.7.9
