### ISSUE TITLE
wierd problem i  face

### ISSUE THREAD

**Issue by puahyan** [jadjoubran/laravel5-angular-material-starter#416]
- **I'm submitting a ...**
- [ ] bug report
- [ ] feature request
- [x] support request
- [ ] other (Please specify)

hi, i did install version 3.4 in window, everything works fine, but i try to install in my current macbook,
i faced this issue,
 laravel-elixir-eslint@3.0.0 requires a peer of laravel-elixir@>=3.0.0 but none was installed, 
hence i cant update my html file whenever i changed,  but only able to update the js files during the gulp watch ...
my node version is v4.4.5, npm version is 3.10.8, bower version is 1.7.9, may i know is the reason? thanks

**Comment by jadjoubran** [comment]
Hi @puahyan 
Those are warnings when running `npm install`.. it shouldn't be an issue
Are you running `gulp && gulp watch`?

**Comment by puahyan** [comment]
hi, at first, i clone https://github.com/jadjoubran/laravel5-angular-material-starter.git, then done all the setup,  i did php artisan serve and gulp && gulp watch, next i change some data in the loginform.component.html , edit some css in login.scss, and edit some in the login.js, the gulp will automatically update it/changed, and it works fine.

then i do it for laravel5-angular-material-starter-version-3.4, as i did for above for setup and make some changes on component html,scss and js files, only js and scss file get updated, not the html page.

this is the problem i face. thanks u may take a try and check in this way
- the setup need include composer install , composer update as well for vendor

**Comment by jadjoubran** [comment]
Ah okay that's actually the same issue here #414 
If you want something stable, I'd recommend you install it using composer create-project as mentioned in the [docs](https://laravel-angular.readme.io/v3.3/docs/install)
