### ISSUE TITLE
How to use another theme ?

### ISSUE THREAD

**Issue by birkansava** [jadjoubran/laravel5-angular-material-starter#419]
I want to use my own custom css files and not material . How can I use? what should i remove ? I don't want to destroy everything :)

**Comment by flick36** [comment]
https://github.com/silverbux/laravel-angular-admin This is a fork of this repo, that removes angular material and uses angular bootstrap, clone both repos and use a folder/file compare app to see what's different

**Comment by jadjoubran** [comment]
You can also easily uninstall angular material and remove all the dependencies used in the code (they aren't a many)

**Comment by birkansava** [comment]
I've just used that:
`.constant("$MD_THEME_CSS","");`

thanks for helping :)
