### ISSUE TITLE
hi, about the .yml file

### ISSUE THREAD

**Issue by puahyan** [jadjoubran/laravel5-angular-material-starter#420]
- **I'm submitting a ...**
- [ ] bug report
- [ ] feature request
- [ ] support request
- [x] other (Please specify)
  
  hi, first of all, great works !
  about the .yml file, when i download the zip, version 3.4, i cant see it my my folder, i using mac.
  and  you just remove dingo api, may i know how to customize the error exception handling, instead of displaying in the console.log, i wish to display to web, like alert the error message . thanks

**Comment by jadjoubran** [comment]
Hi @puahyan 
Which yml file? The one for travis?
The default error handling should show a toast.. is it not working for you?

**Comment by jadjoubran** [comment]
Feel free to re-open with more information!
