### ISSUE TITLE
Should return 404 not 500

### ISSUE THREAD

**Issue by nueko** [jadjoubran/laravel5-angular-material-starter#421]
- **I'm submitting a ...**
- [x] bug report
- [ ] feature request
- [ ] support request
- [ ] other (Please specify)
- **Provide information & explanation**
  Hi, on [Handler.php#L49](https://github.com/jadjoubran/laravel5-angular-material-starter/blob/master/app/Exceptions/Handler.php#L49) and [#65](https://github.com/jadjoubran/laravel5-angular-material-starter/blob/master/app/Exceptions/Handler.php#L65)

``` php
Route::current();
```

returns null on invalid route, so it will call getPrefix() on null that throws 500 instead 404.
also, what if the api has no prefix, but subdomain based api?

I think it should check for the middlewares existance, like follows (You can do it better than me)

``` php

    /**
     * Check for api routes.
     *
     * @param Request $request
     * @return bool
     */
    protected function isApiRoute($request)
    {
        return $request->route() && in_array('api', (array) $request->route()->middleware());
    }
```
- **Laravel & Angular version:** 3.4.0

**Comment by jadjoubran** [comment]
Fixed
