### ISSUE TITLE
Laravel 5.2

### ISSUE THREAD

**Issue by warmjaijai** [jadjoubran/laravel5-angular-material-starter#424]
- **I'm submitting a ...**
- [ ] bug report
- [ ] feature request
- [x] support request
- [ ] other (Please specify)
- **Provide information & explanation**

Hi developers, does v3.4 also support Laravel 5.2?

**Comment by Fiodor94** [comment]
Version 3.4 is based on Laravel 5.3
Version 3.2 is based on Laravel 5.2
