### ISSUE TITLE
class tymon do not exist for any route require token login

### ISSUE THREAD

**Issue by puahyan** [jadjoubran/laravel5-angular-material-starter#425]
- **I'm submitting a ...**
- [x] bug report
- [ ] feature request
- [ ] support request
- [ ] other (Please specify)

hi, i face this error, may take a look thanks.

``` php
Route::get('auth/user', function (Request $request) {
    return 'yo';
})->middleware('auth:api');
```

http://localhost:8000/api/auth/user  --> display error

**Comment by puahyan** [comment]
hi  i just add in kernal.php,  

```
protected $routeMiddleware = [ 
  'auth.api' => \Tymon\JWTAuth\Middleware\GetUserFromToken::class,
```

then it works,
, but why other version do not need it ? or my solution is wrong ?

**Comment by jadjoubran** [comment]
Hi @puahyan 
Thanks for the bug report
I can confirm that there's an issue, I'll work on a fix and deploy
Your fix didn't work for me, but the reason why this is required now is because dingo/api has been removed from the starter

**Comment by puahyan** [comment]
Route::get('auth/user', function (Request $request) {
    return 'yo';
})->middleware('auth.api');

protected $routeMiddleware = [ 
  'auth.api' => \Tymon\JWTAuth\Middleware\GetUserFromToken::class,

**Comment by puahyan** [comment]
auth.api, not auth:api

**Comment by jadjoubran** [comment]
yeah true, this is a way of fixing it
However `auth:api` is supposed to use the `api` config on the default `auth` provider (check the config/auth.php)
I will try to solve the issue while keeping `auth:api` if not then I will use your fix
Thanks!

**Comment by jadjoubran** [comment]
Fixed 😄
