### ISSUE TITLE
dialogs folder must be copy to public views

### ISSUE THREAD

**Issue by yosmelvin** [jadjoubran/laravel5-angular-material-starter#426]
- **I'm submitting a ...**
- [ ] bug report
- [ ] feature request
- [x] support request
- [ ] other (Please specify)
- **Provide information & explanation**

add this to gulp.js for copy html for dialogs
`.copy('angular/dialogs/**/*.html', 'public/views/dialogs/')`
- **Laravel & Angular version:** 3.4.0

**Comment by jadjoubran** [comment]
Great, thanks @yosmelvin 
Would you be able to send a PR against `master`?

**Comment by jadjoubran** [comment]
Fixed in #431
