### ISSUE TITLE
File css/final.css not defined in asset manifest.

### ISSUE THREAD

**Issue by markib** [jadjoubran/laravel5-angular-material-starter#428]
File css/final.css not defined in asset manifest. (View: C:\xampp\htdocs\laravel5-angular-material-starter\resources\views\index.blade.php)
- **I'm submitting a ...**
- [ ] bug report
- [ ] feature request
- [ ] support request
- [ ] other (Please specify)
- **Provide information & explanation**
- **Got code samples?**
  Make sure to use 3 backticks (and javascript or php after it to show your code) [More info](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code)
  Also make sure to click on the _Preview_ button to double check your code formatting
- **Laravel & Angular version:** 3.2.0

**Comment by jadjoubran** [comment]
Hi @markib 
Thanks for creating an issue
Can you elaborate more on what the problem is?

**Comment by jadjoubran** [comment]
Feel free to re-open with more information!
