### ISSUE TITLE
Try install on centos 6.7

### ISSUE THREAD

**Issue by harmon1ca** [jadjoubran/laravel5-angular-material-starter#433]
* **I'm submitting a ...**
- [ ] bug report
- [ ] feature request
- [ ] support request
- [x] other (Please specify)

I try to install you package on centos and get problem. I get 500 error on home page. In logs i have: 

> local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to a member function getPrefix() on null' in /www/domen/app/Exceptions/Handler.php:49

file httpd.conf

`<Directory /var/www/admen/data/www/domen>
        Options -ExecCGI -Includes
        php_admin_value open_basedir "/var/www/admin/data:.:/usr/lib/php:/usr/local/lib/php:/tmp"
        php_admin_flag engine on
        AllowOverride All
</Directory>
<VirtualHost *:81 >
        ServerName domen
        CustomLog /var/www/httpd-logs/domen.access.log combined
        DocumentRoot /var/www/admin/data/www/domen/public
        ErrorLog /var/www/httpd-logs/domen.error.log
        ServerAdmin mail
        ServerAlias www.domen
        SuexecUserGroup admin admin
        AddType application/x-httpd-php .php .php3 .php4 .php5 .phtml
        AddType application/x-httpd-php-source .phps
        php_admin_value open_basedir "/var/www/admin/data:.:/usr/lib/php:/usr/local/lib/php:/tmp"
        php_admin_value sendmail_path "/usr/sbin/sendmail -t -i -f mail"
        php_admin_value upload_tmp_dir "/var/www/admin/data/mod-tmp"
        php_admin_value session.save_path "/var/www/admin/data/mod-tmp"
        DirectoryIndex index.php
</VirtualHost>`

permissions on files 755, and 'storage', 'bootstrap/cache'  1777

host:
- PHP 5.6.22
- Centos 6.7

**Comment by nueko** [comment]
Just quick shot, `getPrefix` method stands on [Controller.php](https://github.com/jadjoubran/laravel5-angular-material-starter/blob/master/app/Http/Controllers/Controller.php) and 
[Handler.php](https://github.com/jadjoubran/laravel5-angular-material-starter/blob/3.4.0/app/Exceptions/Handler.php)
try to remove or tweak this method on the Controller.php

``` php
/*fixes unwanted redirects when validation fails*/
    public function validate(Request $request, array $rules, array $messages = [], array $customAttributes = [])
    {
        $validator = $this->getValidationFactory()->make($request->all(), $rules, $messages, $customAttributes);
        if ($validator->fails()) {
            if (Route::current()->getPrefix() === 'api') {
                $message = $validator->errors()->first();
                throw new ValidationException($message);
            } else {
                throw new ValidationException($this);
            }
        }
    }
```

and see #421 and #423

**Comment by harmon1ca** [comment]
I remove getPrefix from Controller.php and use Handler.php #423 request. And it work, thanks.
