### ISSUE TITLE
Not working together with admin packages like Voyager?

### ISSUE THREAD

**Issue by mgvd** [jadjoubran/laravel5-angular-material-starter#434]
* **I'm submitting a ...**
- [ ] bug report
- [ ] feature request
- [x] support request
- [ ] other (Please specify)

* **Provide information & explanation**
I'm trying to use the Voyager admin package with a laravel5-angular-material project but besides the first dashboard screen it doesn't work. I get errors in the log: getPrefix() on null. This originates in the RoutesProvider (line 49). This suggests Route::getCurrentRoute() is null and something is wrong with the route config. It's not seeing the routes.php from Voyager?

All works fine when I use a vanilla laravel application with Voyager.

Iḿ new to Laravel and Laravel-material; maybe there is an obvious sollution. Please let me know.

* **Laravel & Angular version:** 3.2.0

**Comment by mgvd** [comment]
Hold on. Will try again using --save

**Comment by jadjoubran** [comment]
Hi @mgvd 
Any update on this issue?

**Comment by mgvd** [comment]
No, I gave up to be honest. If someone confirms that either Voyager should or should not work together with ang-matr., that would be useful

**Comment by jadjoubran** [comment]
Could you try going to `app\Http\Controllers\Controller.php` and try making the function look like this:

```php
        if ($validator->fails()) {
               throw new ValidationException($this); 
        }
```

Basically I just removed this check: `Route::current()->getPrefix() === 'api'`

Let me know if it fixes the issue

**Comment by followtheart** [comment]
Voyager works with this starter without any modification of this project 😄 
But in my case,my user table conflicts with voyager's default user table;your may have some problem like that too

**Comment by mgvd** [comment]
@jadjoubran this doesn't work. same behaviour.

@followtheart I'm very curious how your install is different. After initiating a new laravel-material-starter application, fixing the .env I do the stuff mentioned here: https://github.com/the-control-group/voyager

**Comment by followtheart** [comment]
# laravel5-angular-material-starter-voyager 
you can use this https://github.com/followtheart/laravel5-angular-material-starter-voyager.git  directly,
Or you can do it yourself, just follow steps below:

# Step 1, laravel5-starter
Also see here :https://laravel-angular.readme.io/docs
```bash
git clone https://github.com/jadjoubran/laravel5-angular-material-starter.git
cd laravel5-angular-material-starter
npm install -g gulp bower
npm install
bower install
#fix database credentials in .env
php artisan migrate
gulp
```
# Step 2, voyager
#Also see here: https://github.com/the-control-group/voyager
```bash
composer require tcg/voyager
```

Next make sure to create a new database and add your database credentials to your .env file:

```
DB_HOST=localhost
DB_DATABASE=homestead
DB_USERNAME=homestead
DB_PASSWORD=secret
```

Add the Voyager service provider to the `config/app.php` file in the `providers` array:

```php
'providers' => [
    // Laravel Framework Service Providers...
    //...
    
    // Package Service Providers
    TCG\Voyager\VoyagerServiceProvider::class,
    // ...
    
    // Application Service Providers
    // ...
],
```

Lastly, we can install voyager by running

```bash
php artisan voyager:install
```

# extra steps:
```php
##(ONLY IN STARTER!!)  
php artisan migrate:refresh
php artisan db:seed --class=VoyagerDatabaseSeeder
```
# run server
```php
php artisan serve 
```

**Comment by jadjoubran** [comment]
@mgvd any updates?
@followtheart thank you so much for your contributions 😄
