### ISSUE TITLE
Angular Filters Not Working 

### ISSUE THREAD

**Issue by developcreativo** [jadjoubran/laravel5-angular-material-starter#438]
* **I'm submitting a ...**
- [x] bug report
- [ ] feature request
- [ ] support request
- [ ] other (Please specify)
En el ejemplo anterior {{ 'contact_us' | humanReadable }}  la salida deberia ser  output: Contact Us pues esta no funciona deja el DOM en blanco

TrustHtmlFilter is not using explicit annotation and cannot be invoked in strict mode

* **Laravel & Angular version:** 3.4.0

**Comment by developcreativo** [comment]
```
export function TrustHtmlFilter($sce) {
    return function(html) {
        return $sce.trustAsHtml(html);
    };
}
TrustHtmlFilter.$inject = ['$sce'];

```

Fix

**Comment by jadjoubran** [comment]
H @vdjkelly 
Thanks for reporting this bug.

I just fixed it by adding the missing `'ngInject'` which takes care of annotating dependency injection

```javascript
export function TrustHtmlFilter($sce) {
    'ngInject';
	return function(html) {
		return $sce.trustAsHtml(html);
	};
}
```
