### ISSUE TITLE
gulp build

### ISSUE THREAD

**Issue by markib** [jadjoubran/laravel5-angular-material-starter#439]
Error: ENOENT: no such file or directory, stat 'C:\xampp\htdocs\myAngularLaravel\laravel5-angular-material-starter\public\build\css\final-3b08b8dd72.css'
    at Error (native)

**Comment by kumarravisingh** [comment]
Similar Error occurred on my application too, I am using windows OS
It seems like Elixer and Windows OS dependent Issue, my bug is marked as [Upstream Fix ](https://github.com/jadjoubran/laravel5-angular-material-starter/issues/430)
in the meantime, you can try [This fix ](https://github.com/laravel/elixir/issues/626)  provided by [Albertgultom](https://github.com/albertgultom) on that thread. I haven't tried it, I do not have need of Progressive Web App so I switched to stable [Version 3.2.x](http://laravel-angular.readme.io/v3.2/docs/) which is working fine without any issue.
