### ISSUE TITLE
Modulerr: app.directives

### ISSUE THREAD

**Issue by LoganLehman** [jadjoubran/laravel5-angular-material-starter#443]
Hello,

I am getting the following error after creating a directive using the artisan creation script. I have been using components up until now (need the link fn). Any idea why this is occurring?

final-401ba20b18.js:68Uncaught Error: [$injector:modulerr] Failed to instantiate module app due to:
Error: [$injector:modulerr] Failed to instantiate module app.directives due to:
Error: [ng:areq] Argument 'directiveFactory' is required
http://errors.angularjs.org/1.5.9/ng/areq?p0=directiveFactory&p1=required
    at http://localhost:8000/build/js/final-401ba20b18.js:68:12
    at assertArg (http://localhost:8000/build/js/final-401ba20b18.js:1937:11)
    at $CompileProvider.registerDirective [as directive]

**Comment by flick36** [comment]
Is your directive added in `angular/index.directives.js` ? and did you run `gulp`? Also in the controller you are using your directive, have you imported it? like: `import { directiveFactory } from '../../../directives/likeif/directivefactory.js';`
