### ISSUE TITLE
 error  '$auth

### ISSUE THREAD

**Issue by ghost** [jadjoubran/laravel5-angular-material-starter#448]
E:\webdir\project_mrp\angular\run\routes.run.js
  2:49  error  '$auth' is defined but never used  no-unused-vars

â 1 problem (1 error, 0 warnings)

{ [ESLintError: Failed with 1 error]
  name: 'ESLintError',
  message: 'Failed with 1 error',
  showStack: false,
  showProperties: true,
  plugin: 'gulp-eslint',
  __safety: { toString: [Function: bound ] } }
[17:57:05] Finished 'eslint' after 843 ms
[17:57:05] Starting 'combine'...
[17:57:05] Finished 'combine' after 516 ms
[17:57:05] Starting 'version'...
[17:57:06] Finished 'version' after 552 ms
[17:57:06] Starting 'generate-service-worker'...
Total precache size is about 325.15 kB for 15 resources.
[17:57:06] Finished 'generate-service-worker' after 48 ms
[17:57:06] Finished 'all' after 5.51 s
[17:57:06] Starting 'default'...

**Comment by jadjoubran** [comment]
Hi @intrepidtr 
That's not an issue, only a warning to remove an unused variable
I'll get rid of it anyway, thanks!

**Comment by ghost** [comment]
Thank you for your interest

**Comment by johndoe2509** [comment]
@jadjoubran ,
in my installation ,
'$auth' seems cannot be injected correctly  and 
![2017-02-12 10 42 57](https://cloud.githubusercontent.com/assets/15901445/22863042/ada5780e-f174-11e6-899e-a6a09c20bd1d.png)

![2017-02-12 10 41 41](https://cloud.githubusercontent.com/assets/15901445/22863037/83e5b5ce-f174-11e6-86bb-0dc4c77a85ae.png)

do you know why?

**Comment by jadjoubran** [comment]
Hi @johndoe2509 
Can you please check this [issue](https://github.com/jadjoubran/laravel5-angular-material-starter/issues/435)?

**Comment by fajrinase** [comment]
I have same probleme with@ghost...

What solution? Any idea?

**Comment by jadjoubran** [comment]
Have you tried the solution posted [here](https://github.com/jadjoubran/laravel5-angular-material-starter/issues/435#issuecomment-259835245)?
