### ISSUE TITLE
How to change title and meta data base on page? (Best Practice)

### ISSUE THREAD

**Issue by yosmelvin** [jadjoubran/laravel5-angular-material-starter#449]
* **I'm submitting a ...**
- [ ] bug report
- [ ] feature request
- [x] support request
- [ ] other (Please specify)

* **Provide information & explanation**
How to change title and meta data base on page? (Best Practice)

* **Got code samples?**
Make sure to use 3 backticks (and javascript or php after it to show your code) [More info](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code)
Also make sure to click on the *Preview* button to double check your code formatting

* **Laravel & Angular version:** 3.4.0

**Comment by saade** [comment]
Hi @yosmelvin did you get it? I'm trying too :(

**Comment by jadjoubran** [comment]
Other users have suggested using the `ngMeta` package in another issue! 👍
