### ISSUE TITLE
Angular Build Project Sass

### ISSUE THREAD

**Issue by ghost** [jadjoubran/laravel5-angular-material-starter#451]
- [ ] bug report
- [ ] feature request
- [x] support request
- [] other (Please specify)

**/

Angular Build Project ?

Error: Undefined variable: "$layout-breakpoint-xs".
        on line 52 of angular/theme/quick-panel/quick-panel.scss
>> @media screen and (max-width: $layout-breakpoint-xs) {
   ------------------------------^

    at options.error (E:\webdir\project6\node_modules\node-sass\lib\index.js:286:26)
  status: 1,
  file: 'E:/webdir/project6/angular/theme/quick-panel/quick-panel.scss',
  line: 52,
  column: 31,

**Comment by flick36** [comment]
Are you sure your `$layout-breakpoint-xs` exists in that file?
