### ISSUE TITLE
Getting Error in bower install

### ISSUE THREAD

**Issue by kingvish** [jadjoubran/laravel5-angular-material-starter#452]
Getting error in bower install.
![error](https://cloud.githubusercontent.com/assets/6886053/21404322/a7f06246-c7e6-11e6-9997-c10261065228.png)

**Comment by flick36** [comment]
That's not an error .-.. It's just a bower resolution.

> When you specify dependencies(in this case Angular) for you app via Bower, some of the packages might rely on different versions of the same library. You will have to resolve what version of libraries your app actually wants. In other words, you break the tie. [Read More](http://jaketrent.com/post/bower-resolutions/)

In other words just select a number on wich angular dependency you want, probably you'll want the most newer in this case, number 2: `angular#1.6.0`

**Comment by kingvish** [comment]
Got it, Thank you!

**Comment by hezll** [comment]
add --force   (when conflict)
bower install --force angular-xxx
