### ISSUE TITLE
DevTools failed to parse SourceMap

### ISSUE THREAD

**Issue by yosmelvin** [jadjoubran/laravel5-angular-material-starter#454]
* **I'm submitting a ...**
- [x] bug report
- [ ] feature request
- [ ] support request
- [ ] other (Please specify)

* **Provide information & explanation**
I got warning on console like this
`DevTools failed to parse SourceMap: http://localhost/build/public/js/vendor.js.map`
`DevTools failed to parse SourceMap: http://localhost/critical.css.map`

because wrong path to vendor.js.map and critical.css.map
because when gulp the critical.css.map go to 'public/css/critical.css.map' 
and vendor.js.map go to public/js/vendor.js.map

Note To Remember: this issue on Development Environment not production 

* **Got code samples?**
bower.task.js

* **Laravel & Angular version:** 3.4.0

**Comment by jadjoubran** [comment]
Is this still an issue?

critical.css doesn't have sourcemaps though
