### ISSUE TITLE
How to integrate TinyMCE Text Editor

### ISSUE THREAD

**Issue by dinesh2017** [jadjoubran/laravel5-angular-material-starter#455]
* **I'm submitting a ...**
- [x] support request

* **Provide information & explanation**
Hi, 
Recently, I was installed TinyMCE (Text Editor) module in my project. But i'm confusing to implement and display the text editor in html page.  please guide us how to integrate new module like tinyMCE.

* **Laravel & Angular version:** 3.2.0

Thank you,

**Comment by flick36** [comment]
[Follow instructions](https://github.com/angular-ui/ui-tinymce), excepts the one that says you add the scripts to your applications, elixir already does that fro you, and convert to ES6

**Comment by dinesh2017** [comment]
already seen these instruction but little confusing. can you please provide little code for this. 

Thank you

**Comment by flick36** [comment]
No, i won't do the work for you, can you provide code for this? what is confusing you? what have you tried?

Edit: @dinesh2017 apparently it's hard to use with elixir https://github.com/tinymce/tinymce/issues/2914#issuecomment-221187804 you can try https://github.com/fraywing/textAngular
