### ISSUE TITLE
FatalErrorException due to the command gulp && gulp watch

### ISSUE THREAD

**Issue by akinolu52** [jadjoubran/laravel5-angular-material-starter#456]
* **I'm submitting a ...**
- [x] bug report
got this error on my git bash while running gulp && gulph watch
i have gulp installed on my system
- [x] support request
 'bower-js' errored after 9.18 ms
[06:46:31] Error: Bower components directory does not exist at C:\xampp\htdocs\laravel5-angular-material-starter\bower_components
    at Error (native)
    at module.exports (C:\xampp\htdocs\laravel5-angular-material-starter\node_modules\main-bower-files\lib\index.js:76:17)
    at Task.gulpTask (C:\xampp\htdocs\laravel5-angular-material-starter\tasks\bower.task.js:38:25)
    at Task.run (C:\xampp\htdocs\laravel5-angular-material-starter\node_modules\laravel-elixir\dist\tasks\Task.js:138:31)
    at Gulp.<anonymous> (C:\xampp\htdocs\laravel5-angular-material-starter\node_modules\laravel-elixir\dist\tasks\GulpBuilder.js:65:67)
    at module.exports (C:\xampp\htdocs\laravel5-angular-material-starter\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (C:\xampp\htdocs\laravel5-angular-material-starter\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (C:\xampp\htdocs\laravel5-angular-material-starter\node_modules\orchestrator\index.js:214:10)
    at Gulp.Orchestrator.start (C:\xampp\htdocs\laravel5-angular-material-starter\node_modules\orchestrator\index.js:134:8)
    at runNextSet (C:\xampp\htdocs\laravel5-angular-material-starter\node_modules\run-sequence\index.js:86:16)
[06:46:31] 'all' errored after 22 ms
[06:46:31] Error in plugin 'run-sequence(bower-js)'
Message:
    Bower components directory does not exist at C:\xampp\htdocs\laravel5-angular-material-starter\bower_components

- [x] other (Please specify)

* **Provide information & explanation**
Error when i run php artisan serve

$ php artisan serve
←[32mLaravel development server started on http://localhost:8000/←[39m
[Wed Jan  4 06:34:11 2017] PHP Warning:  Uncaught ErrorException: require(C:\xampp\htdocs\laravel5-angular-material-starter\public\css/critical.css): failed to open stream: No such
 file or directory in C:\xampp\htdocs\laravel5-angular-material-starter\storage\framework\views\000c94a4c473ad0b4efede1bf538ca6b3f09e6d3.php:17
Stack trace:
#0 C:\xampp\htdocs\laravel5-angular-material-starter\storage\framework\views\000c94a4c473ad0b4efede1bf538ca6b3f09e6d3.php(17): Illuminate\Foundation\Bootstrap\HandleExceptions->han
dleError(2, 'require(C:\\xamp...', 'C:\\xampp\\htdocs...', 17, Array)
#1 C:\xampp\htdocs\laravel5-angular-material-starter\storage\framework\views\000c94a4c473ad0b4efede1bf538ca6b3f09e6d3.php(17): require()
#2 C:\xampp\htdocs\laravel5-angular-material-starter\vendor\laravel\framework\src\Illuminate\View\Engines\PhpEngine.php(42): include('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\laravel5-angular-material-starter\vendor\laravel\framework\src\Illuminate\View\Engines\CompilerEngine.php(59): Illuminate\View\Engines\PhpEngine->evaluatePath('C
:\\x in C:\xampp\htdocs\laravel5-angular-material-starter\storage\framework\views\000c94a4c473ad0b4efede1bf538ca6b3f09e6d3.php on line 17
[Wed Jan  4 06:34:11 2017] PHP Fatal error:  Illuminate\View\Engines\PhpEngine::main(): Failed opening required 'C:\xampp\htdocs\laravel5-angular-material-starter\public\css/critic
al.css' (include_path='C:\xampp\php\PEAR') in C:\xampp\htdocs\laravel5-angular-material-starter\storage\framework\views\000c94a4c473ad0b4efede1bf538ca6b3f09e6d3.php on line 17
[Wed Jan  4 06:34:12 2017] 127.0.0.1:52681 Invalid request (Unexpected EOF)

and when i view the page i got:

FatalErrorException in 000c94a4c473ad0b4efede1bf538ca6b3f09e6d3.php line 17:
Illuminate\View\Engines\PhpEngine::main(): Failed opening required 'C:\xampp\htdocs\laravel5-angular-material-starter\public\css/critical.css' (include_path='C:\xampp\php\PEAR')

* **Got code samples?**
Make sure to use 3 backticks (and javascript or php after it to show your code) [More info](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code)
Also make sure to click on the *Preview* button to double check your code formatting

* **Laravel & Angular version:** 3.2.0

**Comment by flick36** [comment]
did you run `bower install`?

**Comment by akinolu52** [comment]
yes i have tried that and the only error i got after running bower install is:
ECONFLICT Unable to find suitable version for angular


and after trying to start the laravel server i got this on the cmd:
$ php artisan serve
←[32mLaravel development server started on http://localhost:8000/←[39m
[Thu Jan  5 22:17:42 2017] PHP Warning:  Uncaught ErrorException: require(C:\xampp\htdocs\laravel5-angular-material-starter\public\css/critical.css): failed to open stream: No such
 file or directory in C:\xampp\htdocs\laravel5-angular-material-starter\storage\framework\views\000c94a4c473ad0b4efede1bf538ca6b3f09e6d3.php:17
Stack trace:
#0 C:\xampp\htdocs\laravel5-angular-material-starter\storage\framework\views\000c94a4c473ad0b4efede1bf538ca6b3f09e6d3.php(17): Illuminate\Foundation\Bootstrap\HandleExceptions->han
dleError(2, 'require(C:\\xamp...', 'C:\\xampp\\htdocs...', 17, Array)
#1 C:\xampp\htdocs\laravel5-angular-material-starter\storage\framework\views\000c94a4c473ad0b4efede1bf538ca6b3f09e6d3.php(17): require()
#2 C:\xampp\htdocs\laravel5-angular-material-starter\vendor\laravel\framework\src\Illuminate\View\Engines\PhpEngine.php(42): include('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\laravel5-angular-material-starter\vendor\laravel\framework\src\Illuminate\View\Engines\CompilerEngine.php(59): Illuminate\View\Engines\PhpEngine->evaluatePath('C
:\\x in C:\xampp\htdocs\laravel5-angular-material-starter\storage\framework\views\000c94a4c473ad0b4efede1bf538ca6b3f09e6d3.php on line 17
[Thu Jan  5 22:17:42 2017] PHP Fatal error:  Illuminate\View\Engines\PhpEngine::main(): Failed opening required 'C:\xampp\htdocs\laravel5-angular-material-starter\public\css/critic
al.css' (include_path='C:\xampp\php\PEAR') in C:\xampp\htdocs\laravel5-angular-material-starter\storage\framework\views\000c94a4c473ad0b4efede1bf538ca6b3f09e6d3.php on line 17
[Thu Jan  5 22:17:43 2017] 127.0.0.1:55111 [200]: /favicon.ico
[Thu Jan  5 22:17:43 2017] 127.0.0.1:55112 Invalid request (Unexpected EOF)
[Thu Jan  5 22:17:43 2017] 127.0.0.1:55113 Invalid request (Unexpected EOF)
[Thu Jan  5 22:17:43 2017] 127.0.0.1:55114 Invalid request (Unexpected EOF)
[Thu Jan  5 22:17:43 2017] 127.0.0.1:55115 Invalid request (Unexpected EOF)


and the page error is:
FatalErrorException in 000c94a4c473ad0b4efede1bf538ca6b3f09e6d3.php line 17:
Illuminate\View\Engines\PhpEngine::main(): Failed opening required 'C:\xampp\htdocs\laravel5-angular-material-starter\public\css/critical.css' (include_path='C:\xampp\php\PEAR')

**Comment by akinolu52** [comment]
pls can someone show me how his/her bower.json file looks like 

and what version of angular is this laravel5-angular-material-starter using?

**Comment by flick36** [comment]
You show yours, i'm pretty sure you are not letting bower install finish, therefore gulp can't compile propertly...

**Comment by akinolu52** [comment]
bower.json

```
{
  "name": "laravel5-angular-material-starter",
  "authors": [
    "Jad Joubran <jad@jadjoubran.com>"
  ],
  "ignore": [
    "**/.*",
    "node_modules",
    "bower_components",
    "test",
    "tests"
  ],
  "dependencies": {
    "angular": "~1.5",
    "angular-ui-router": "~1.0.0-alpha.3",
    "ngstorage": "~0.3.10",
    "angular-material": "~1.0.8",
    "restangular": "~1.5.2",
    "angular-loading-bar": "~0.9.0",
    "satellizer": "^0.14.0"
  }
}
```

**Comment by flick36** [comment]
Oops, sorry somehow i miss your response, can you post a screenshot of the error? is it something like this? https://github.com/jadjoubran/laravel5-angular-material-starter/issues/452

**Comment by jadjoubran** [comment]
Hi @akinolu52 
When you're asked about a resolution, did you choose a specific version of Angular?
You should choose one that makes sense and prefix it with `!` to persist that in your `bower.json`

**Comment by Blair2004** [comment]
Well this issue hasn't been fixed ?
