### ISSUE TITLE
Cant Create Users In The Specified Table

### ISSUE THREAD

**Issue by agent2020** [jadjoubran/laravel5-angular-material-starter#457]
* **I'm submitting a ...**
- [ ] bug report
- [ ] feature request
- [x] support request
- [ ] other (Please specify)

i cant have the new user created in the table created, it keeps using User Table Instead of Admin Table, please how do i fix this

when i run 
php artisan voyager:admin user@mymail.com --create

* **Provide information & explanation**

    'user' => [
        'add_default_role_on_register' => true,
        'default_role'                 => 'user',
        'admin_permission'             => 'browse_admin',
        'namespace'                    => App\Admin::class,

**Comment by flick36** [comment]
Wrong repo, you should ask here: https://github.com/the-control-group/voyager

**Comment by jadjoubran** [comment]
Hi @agent2020 
Yes indeed, as @flick36 mentioned this is better asked on voyager's repository
Cheers!
