### ISSUE TITLE
how do i add text editor. I tried couple of existing angular and bootstrap editor but non of them are working with this module

### ISSUE THREAD

**Issue by mahenn** [jadjoubran/laravel5-angular-material-starter#461]
* **I'm submitting a ...**
- [x] support request

how do i add text editor. I tried couple of existing angular and bootstrap editor but non of them are working with this module

* **Laravel & Angular version:** 3.2.0

**Comment by flick36** [comment]
What have you tried?

**Comment by mahenn** [comment]
I tried with angular-wysiwyg,  angular-ckeditor,  ui-tinymce,  summer note
and couple of more.  Tried to use with angular directive as well but no
luck.  Could you please help me step by step configuration?

**Comment by flick36** [comment]
Nop, sorry i won't do the job for you =/ i can try to help on whatever you're struggling, but i won't do the job for you

**Comment by mahenn** [comment]
Not sure what you understood.  I was seeking help as I am using this module
for one of my project and did not find any help available.

I have figured it out.  Thanks

**Comment by mahenn** [comment]
I wanted steps to be followed for integrating third party scripts.  If you
have any documentation and not write code in my system.  Anyway thanks.  I
have fixed issue.

**Comment by flick36** [comment]
You wanted step by step configuration, that's me doing the work for you to copy paste ;)
