### ISSUE TITLE
application loading takes too much time (final.js - 1mb)

### ISSUE THREAD

**Issue by dinesh2017** [jadjoubran/laravel5-angular-material-starter#463]
- [ ] support request

Hi, Right now  i'm facing browser loading issue. final.js is taking too much time for loading because of the file size.  Original file (final.js) size is 4MB because of depended bower_components. After gulp with --production command it is compressed and get file with 1mb. But browser taking much of time for this file loading. Here, I'm showing my bower_components depended files. please guide me how to split this file into 2 or 3 files or else any solution for file compress/browser loading

* **Brower_component (bower.json)**

 "dependencies": {
    "jquery": "2.2.4",
    "angular": "angularjs#1.5.9",
    "angular-ui-router": "~1.0.0-alpha.3",
    "ngstorage": "~0.3.10",
    "angular-material": "^1.1.1",
    "restangular": "~1.5.2",
    "angular-loading-bar": "~0.9.0",
    "satellizer": "^0.14.0",
    "angular-animate": "^1.6.0",
    "angular-ui-tinymce": "^0.0.18",
    "lf-ng-md-file-input": "^1.5.1",
    "ng-file-upload": "^12.2.13",
    "ng-file-upload-shim": "^12.2.13",
    "angular-sanitize": "^1.6.1",
    "angular-slick-carousel": "^3.1.7"
  }

* **Laravel & Angular version:** 3.2.0

Thank you,

**Comment by jadjoubran** [comment]
Hi @dinesh2017 
Unfortunately that's a known problem with AngularJS (Angular 1)
You can't really split your angular code into multiple bundles, unless you create multiple modules

However, if I were you, I would try to get rid of `jQuery` as a dependency if it's not used elsewhere
