### ISSUE TITLE
Error: ENOENT: no such file or directory, stat '...\laravel5-angular-material-starter\public\build\css\final-812dd1b431.css'

### ISSUE THREAD

**Issue by viniciusfreitasmg** [jadjoubran/laravel5-angular-material-starter#464]
I had a problem executing "Gulp & Gulp Watch", the error generated was _**"Error: ENOENT: no such file or directory, stat 'C: \ wamp64 \ www \ laravel5-angular-material-starter \ public \ build \ css \ End-812dd1b431.css'"**_, I do not know how to solve. Can anyone help me?

**Comment by jadjoubran** [comment]
Hello @viniciusfreitasmg 
Do you have write permissions in that directory?

**Comment by tchoule84** [comment]
Are you on a Windows machine ? I had the same problem until i decided to desactivate Windows defender... Since, it's works perfectly :)

**Comment by pl4yradam** [comment]
+1 I have full permissions for the directory

**Comment by flick36** [comment]
Did you run `npm install` before running `gulp & gulp watch` ?

**Comment by pl4yradam** [comment]
Yes I did. I have followed the guide that was provided.

**Comment by flick36** [comment]
What version are you using?

**Comment by pl4yradam** [comment]
I tried the most recent version and the one prior

On 8 Mar 2017 2:50 a.m., "Allan Alvarez Ortiz" <notifications@github.com>
wrote:

What version are you using?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/jadjoubran/laravel5-angular-material-starter/issues/464#issuecomment-284930674>,
or mute the thread

**Comment by jadjoubran** [comment]
I'm not sure what could be causing it..
Can you try re-installing the project in a new folder?

**Comment by ArrayZoneYour** [comment]
@viniciusfreitasmg @pl4yradam 
I have meet the problem today,and the content below is my solution,hope it can help you
1. run the gulp watch 
![image](https://cloud.githubusercontent.com/assets/21001457/24829723/ce33cf52-1ca9-11e7-9631-7835b5420b7b.png)
2. compare to the gulp(I can gulp successfully but gulp watch failed)
![image](https://cloud.githubusercontent.com/assets/21001457/24829734/0bb5240c-1caa-11e7-8819-738b098c4a55.png)
3.compare the file in public/css/, public/js, public/build, public/manifest.json(*important)
![image](https://cloud.githubusercontent.com/assets/21001457/24829752/652cdf2a-1caa-11e7-838c-b175ed5cc9f7.png)
when gulp watch, this file doesn't change and the public/build, public/js will be empty, it must be a premission problem.
4.show the premission and change it
![image](http://github-10040048.cos.myqcloud.com/images/201704082237.png)
5.gulp watch again(lucky, I succeed)
 @![image](http://github-10040048.cos.myqcloud.com/images/201704082238.png)
Maybe your problem's reason is different,but I think you can find it finally : )

**Comment by hezll** [comment]
it works. i do it in git bash under win10
i also try chmod 777  * under the main path
