### ISSUE TITLE
folder 'public/css/' is missing

### ISSUE THREAD

**Issue by mangya** [jadjoubran/laravel5-angular-material-starter#466]
I tried to install this following the steps mentioned in the installation documentation but found that the folder 'public/css/' is missing and hence was not able to check further.

**Comment by jadjoubran** [comment]
Hi @mangya 
Did you make sure to run all the steps? as highlighted in the [docs](https://laravel-angular.readme.io/docs)
The `public/css` folder should be created when you run `gulp`

**Comment by mangya** [comment]
Ohh... Yes.. I think I missed the step. Sorry..
