### ISSUE TITLE
Directive [$compile] injection, how to?

### ISSUE THREAD

**Issue by saade** [jadjoubran/laravel5-angular-material-starter#467]
- [x] support request

I need to use $compile inside a directive. But it says: `$compile is not defined`.

How do i inject $compile?

Code example:

```
class VppDoPostController {
    constructor($compile) {
        'ngInject';
    }
}

export function VppDoPostDirective() {
    return {
        controller: VppDoPostController,
        scope: {
            model: '='
        },
        replace: true,
        link: function(scope, element, attrs, controllers) {
            var el = angular.element('<medium-editor/>');
            $compile(el)(scope);
            element.append(el);
        }
    }
}
```

* **Laravel & Angular version:** 3.2.0

**Comment by mikemillers** [comment]
I think you need to assign it to a variable on the controller class constructor (eg `this.$compile = $compile`) then it should be accessible in the link function by doing `controllers.$compile`

**Comment by saade** [comment]
@mikemillers you're right! Thanks BRO!!
