### ISSUE TITLE
Missing Dependencies on Package.json

### ISSUE THREAD

**Issue by saade** [jadjoubran/laravel5-angular-material-starter#468]
- [x] bug report

Just letting you know, these dependencies are missing in package.json, so gulp throws an error:
`
gulp-notify, gulp-uglify, gulp-concat, gulp-if, buble, buble-loader, 
`

and, we need to install `npm install laravel-elixir-eslint@beta --save-dev` in order to get rid of npm error:

`
npm ERR! peerinvalid The package laravel-elixir@6.0.0-15 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer laravel-elixir-eslint@3.0.2 wants laravel-elixir@>=3.0.0-0 <6.0.0-0
`

* **Laravel & Angular version:** 3.4.x

**Comment by jadjoubran** [comment]
Thanks @SaadeMotion for spotting these!
Would you be able to send a Pull Request against master please?

**Comment by saade** [comment]
Sure! Did!

**Comment by jadjoubran** [comment]
Thanks!
