### ISSUE TITLE
remove hashtag # in url by angularjs

### ISSUE THREAD

**Issue by saade** [jadjoubran/laravel5-angular-material-starter#469]
* **I'm submitting a ...**
- [x] support request

I'm trying to remove the # from url, if i try to access:
`http://localhost:8000`
my app works, but if i need to navigate to other page like:
`http://localhost:8000/home`
the page becomes blank.

i have done:

In my angular routes:
```
$locationProvider.html5Mode({
        enabled: true,
        requireBase: true
    });
```

on index.blade.php:
```
<base href="/">
```

and finally, after reading this thread: #407  in my handler.php:

```
public function render($request, Exception $e)
    {
        return view('index');
    }
```

but the page becomes blank.

* **Laravel & Angular version:** 3.4.x

**Comment by saade** [comment]
I had success with:

`return response()->view('index', [], 404);`


is this correct and safe to use?

**Comment by jadjoubran** [comment]
Hi @SaadeMotion 
Please take a look at this [thread](https://github.com/jadjoubran/laravel5-angular-material-starter/issues/118)

**Comment by jadjoubran** [comment]
I don't think it's a good idea to return 404s

**Comment by saade** [comment]
Just `return response()->view('index');` ??

**Comment by jadjoubran** [comment]
As noted [here](https://github.com/angular-ui/ui-router/wiki/Frequently-Asked-Questions#how-to-configure-your-server-to-work-with-html5mode), you can enable HTML5 mode in ui-router by writing:
`$locationProvider.html5Mode(true)`
and then in Laravel you need a [Catch all route](http://stackoverflow.com/questions/34831175/how-do-i-make-a-catch-all-route-in-laravel-5-2)
