### ISSUE TITLE
laravelangular/generators incompatible for laravel 5.4.*

### ISSUE THREAD

**Issue by Punksolid** [jadjoubran/laravel5-angular-material-starter#470]
* **I'm submitting a ...**
- [ ] support request

* **Provide information & explanation**
Is it there some upgrade guide to laravel 5.4, any plans to make laravelangular support it?

* **Got code samples?**
  Problem 1
    - Conclusion: don't install laravel/framework v5.4.10
    - Conclusion: don't install laravel/framework v5.4.9
    - Conclusion: don't install laravel/framework v5.4.8
    - Conclusion: don't install laravel/framework v5.4.7
    - Conclusion: don't install laravel/framework v5.4.6
    - Conclusion: don't install laravel/framework v5.4.5
    - Conclusion: don't install laravel/framework v5.4.4
    - Conclusion: don't install laravel/framework v5.4.3
    - Conclusion: don't install laravel/framework v5.4.2
    - Conclusion: don't install laravel/framework v5.4.1
    - laravelangular/generators 2.7.3 requires illuminate/console 5.1.* || 5.2.* || 5.3.* -> satisfiable by laravel/framework[v5.3.30], illuminate/console[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8, v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7, v5.3.0, v5.3.16, v5.3.23, v5.3.4].
    - laravelangular/generators 2.7.2 requires illuminate/console 5.1.* || 5.2.* || 5.3.* -> satisfiable by laravel/framework[v5.3.30], illuminate/console[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8, v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7, v5.3.0, v5.3.16, v5.3.23, v5.3.4].
    - laravelangular/generators 2.7.3 requires illuminate/console 5.1.* || 5.2.* || 5.3.* -> satisfiable by laravel/framework[v5.3.30], illuminate/console[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8, v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7, v5.3.0, v5.3.16, v5.3.23, v5.3.4].
    - laravelangular/generators 2.7.0 requires illuminate/console 5.1.* || 5.2.* -> satisfiable by illuminate/console[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8, v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7].
    - laravelangular/generators 2.7.1 requires illuminate/console 5.1.* || 5.2.* || 5.2.* -> satisfiable by illuminate/console[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8, v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7].
    - Can only install one of: laravel/framework[v5.4.0, v5.3.30].
    - don't install illuminate/console v5.1.1|don't install laravel/framework v5.4.0
    - don't install illuminate/console v5.1.13|don't install laravel/framework v5.4.0
    - don't install illuminate/console v5.1.16|don't install laravel/framework v5.4.0
    - don't install illuminate/console v5.1.2|don't install laravel/framework v5.4.0
    - don't install illuminate/console v5.1.20|don't install laravel/framework v5.4.0
    - don't install illuminate/console v5.1.22|don't install laravel/framework v5.4.0
    - don't install illuminate/console v5.1.25|don't install laravel/framework v5.4.0
    - don't install illuminate/console v5.1.28|don't install laravel/framework v5.4.0
    - don't install illuminate/console v5.1.30|don't install laravel/framework v5.4.0
    - don't install illuminate/console v5.1.31|don't install laravel/framework v5.4.0
    - don't install illuminate/console v5.1.41|don't install laravel/framework v5.4.0
    - don't install illuminate/console v5.1.6|don't install laravel/framework v5.4.0
    - don't install illuminate/console v5.1.8|don't install laravel/framework v5.4.0
    - don't install illuminate/console v5.2.0|don't install laravel/framework v5.4.0
    - don't install illuminate/console v5.2.19|don't install laravel/framework v5.4.0
    - don't install illuminate/console v5.2.21|don't install laravel/framework v5.4.0
    - don't install illuminate/console v5.2.24|don't install laravel/framework v5.4.0
    - don't install illuminate/console v5.2.25|don't install laravel/framework v5.4.0
    - don't install illuminate/console v5.2.26|don't install laravel/framework v5.4.0
    - don't install illuminate/console v5.2.27|don't install laravel/framework v5.4.0
    - don't install illuminate/console v5.2.28|don't install laravel/framework v5.4.0
    - don't install illuminate/console v5.2.31|don't install laravel/framework v5.4.0
    - don't install illuminate/console v5.2.32|don't install laravel/framework v5.4.0
    - don't install illuminate/console v5.2.37|don't install laravel/framework v5.4.0
    - don't install illuminate/console v5.2.43|don't install laravel/framework v5.4.0
    - don't install illuminate/console v5.2.45|don't install laravel/framework v5.4.0
    - don't install illuminate/console v5.2.6|don't install laravel/framework v5.4.0
    - don't install illuminate/console v5.2.7|don't install laravel/framework v5.4.0
    - don't install illuminate/console v5.3.0|don't install laravel/framework v5.4.0
    - don't install illuminate/console v5.3.16|don't install laravel/framework v5.4.0
    - don't install illuminate/console v5.3.23|don't install laravel/framework v5.4.0
    - don't install illuminate/console v5.3.4|don't install laravel/framework v5.4.0
    - Installation request for laravel/framework 5.4.* -> satisfiable by laravel/framework[v5.4.0, v5.4.1, v5.4.10, v5.4.2, v5.4.3, v5.4.4, v5.4.5, v5.4.6, v5.4.7, v5.4.8, v5.4.9].
    - Installation request for laravelangular/generators 2.7.* -> satisfiable by laravelangular/generators[2.7.0, 2.7.1, 2.7.2, 2.7.3].

**Comment by jadjoubran** [comment]
Hi @Punksolid Thanks a lot for mentiong this
Would you be able to send a Pull Request against [laravel-ng-artisan-generators](https://github.com/jadjoubran/laravel-ng-artisan-generators)?
It can be fixed by allowing 5.4 in `composer.json` alongside 5.1, 5.2 and 5.3

**Comment by jadjoubran** [comment]
This is fixed now in version `2.7.4`
Cheers!
