### ISSUE TITLE
Importing module to the controller

### ISSUE THREAD

**Issue by ryvan-js** [jadjoubran/laravel5-angular-material-starter#471]
hello there the documentation is quiet limited and vague in certain areas, i would like to use a module to generate tables http://iamisti.github.io/mdDataTable/. and i have no idea how to implement that into the controller, can you please help me out, google din't help much and stuck there for quiet long.

especially this line 

    angular.module('exampleApp', ['ngMaterial', 'mdDataTable']);

in this case exampleApp is the controller's name.and i believe laravel angular starter doesn't requires controller name to be defined actively,which means there is no ng-controller='' attribute.
thanks.

* **Laravel & Angular version:** 3.2.0

**Comment by jadjoubran** [comment]
Hi @ryvan-js 
You should go to `index.module.js` and register `'mdDataTable'` there under `angular.module`. 
`ngMaterial` is already registered so you don't need to worry about that.
And then you will be able to use md-data-table

**Comment by ryvan-js** [comment]
Hi there i did all i can but still having trouble loading the module.i am stuck in few places,same goes to controller defining.
 angular.module('exampleApp2').controller('ExampleController2', function($scope, $mdToast){

   ```
     $scope.nutritionList = [
            {
                id: 601,
                name: 'Frozen joghurt',
                calories: 159,
                fat: 6.0,
                carbs: 24,
                protein: 4.0,
                sodium: 87,
                calcium: '14%',
                iron: '1%'
            },
```
i just have no idea how to translate this into angular material starter style.and also i did played "bower install md-data-table" and then selected the option one which is 

  1) angular#~1.5.8 which resolved to 1.5.11 and is required by md-data-table#2.2.0, md-data-table#2.2.0

but i am getting errors as if the module was missing.please i really need your guidance ,thanks.

**Comment by ryvan-js** [comment]
Hello there, fairly made it. but i gotha reinstall the framework and fresh bower with md-data-table included.thanks for the support.

**Comment by ryvan-js** [comment]
i am also having issues with defining  $mdToast from the code below.

```
 angular.module('exampleApp19').controller('ExampleController19', function($scope, $mdToast){
        $scope.selectedRowCallback = function(rows){
            $mdToast.show(
                $mdToast.simple()
                    .content('Selected row id(s): '+rows)
                    .hideDelay(3000)
            );
        };
```

i have tried declaring it inside the constructor as this.$mdToast = $mdToast,but doesn't seems to work.

**Comment by jadjoubran** [comment]
The issue is that `$mdToast` is undefined, there's a descriptive explanation for that in this [issue](https://github.com/jadjoubran/laravel5-angular-material-starter/issues/280)
Cheers!
