### ISSUE TITLE
angular '$auth' cannot be injected correctly in the run block

### ISSUE THREAD

**Issue by johndoe2509** [jadjoubran/laravel5-angular-material-starter#472]
* **I'm submitting a ...**
- [ ] bug report
- [ ] feature request
- [* ] support request
- [ ] other (Please specify)

* **Provide information & explanation**

$auth is undefined in angular/run/routes.run.js , cannot set 'data: {auth: true}' for route

![2017-02-12 10 42 57](https://cloud.githubusercontent.com/assets/15901445/22863042/ada5780e-f174-11e6-899e-a6a09c20bd1d.png)

![2017-02-12 10 41 41](https://cloud.githubusercontent.com/assets/15901445/22863037/83e5b5ce-f174-11e6-86bb-0dc4c77a85ae.png)

* **Laravel & Angular version:** 3.4.0

**Comment by X-Anonymous-Y** [comment]
same here....:

[14:11:11]
...\xampp\htdocs\laravel5-angular-material\angular\run\routes.run.js
  1:49  error  '$auth' is defined but never used  no-unused-vars

✖ 1 problem (1 error, 0 warnings)

{ [ESLintError: Failed with 1 error]
  name: 'ESLintError',
  message: 'Failed with 1 error',
  showStack: false,
  showProperties: true,
  plugin: 'gulp-eslint',
  __safety: { toString: [Function: bound ] } }

**Comment by X-Anonymous-Y** [comment]
#435
Helps me ;)

works fine!
