### ISSUE TITLE
How to get ui-router resolved values in controller

### ISSUE THREAD

**Issue by dinesh2017** [jadjoubran/laravel5-angular-material-starter#474]
* **I'm submitting a ...**
- [ ] bug report

* **Provide information & explanation**
Hi, I'm struggling with get resolved value from ui-routed into the component controller. Many times i was tried. but always it is showing value is undefined. Here, i'm giving bit of my code. 

* **Got code samples?**

router.config.js

      $stateProvider.state('app.user-datshboard', {
            url: '/dashboard/:user',
            views: {
                'header@':{
                    templateUrl : getView('user-navbar')
                },
                'main@': {
                    templateUrl: getView('user-dashboard')
                },
                'footer':{}
            },
            params: {
                user : null
            },
            resolve: {
                OurUser : (UserServicesService)=>{
                    return UserServicesService.checkUser();
                }
            }
        })

UserServices.service.js

      export class UserServicesService{
       constructor(API,$auth,$log){
          'ngInject';
        this.API = API;
        this.$log = $log;
        this.$auth = $auth;
        this.user = null;
      }
       checkUser()
      {
        if(this.$auth.isAuthenticated()) {
            this.API.one('isProfile').get().then((response)=>{
                if(response.data.user == null)
                    this.user = response.data.user;
            });
            return this.user;
         }
      }
     }

    user-dashboard.component.js 
     
    class UserDashboardController{
    constructor(DialogService,API,$log,$timeout,$state,$stateParams,$auth,$scope){
        'ngInject';
        //
        this.$log = $log;
        this.$log.log(this.OurUser);
    }
   }

     export const UserDashboardComponent = {
      templateUrl: './views/app/components/user-dashboard/user-dashboard.component.html',
      controller: UserDashboardController,
       controllerAs: 'vm',
       binding : {'OurUser: '='}
     }
 
   Now, i'm getting undefined with "OurUser" variable. 

* **Laravel & Angular version:** 3.2.0

**Comment by 0xGeegZ** [comment]
HI, 

Did you try with a promise in your service?

**Comment by dinesh2017** [comment]
Yes i tried. But i'm getting always undefined...

**Comment by yuri-novikov** [comment]
You got typo datshboard in 1 line
`  $stateProvider.state('app.user-datshboard', {`

maybe that is the point?

**Comment by DedSec49** [comment]
In your file <UserServices.service.js>
There is a typo on a line: 12
It should be re-written as:

`this.API.one('isProfile').get('').then((response)=>{`

Hope this helps.
