### ISSUE TITLE
SEO for angular?

### ISSUE THREAD

**Issue by DennisOng** [jadjoubran/laravel5-angular-material-starter#475]
Been using this starter for a while now, would anybody have insights on how to get the site to be indexed by google?

I've tried the "fetch as google" option in google search console, but it's showing just the index.blade.php part, without any angular code being rendered. Is anyone facing this as well?

Thanks in advanced

**Comment by 0xGeegZ** [comment]
Hi,

I can't help you on this purpose but i'm looking for a good way to index this kind of project :)

**Comment by jadjoubran** [comment]
Hi @DennisOng and @tchoule84  
You will probably need to do "pre-rendering"
I've never done it for AngularJS before but I know there's a service for that: [prerender.io](https://prerender.io/)

**Comment by DennisOng** [comment]
Hi @jadjoubran thanks for that, just started trying out prerender.io, will see how it goes
