### ISSUE TITLE
I can't update my controller variable values after execute dialog service function

### ISSUE THREAD

**Issue by dinesh2017** [jadjoubran/laravel5-angular-material-starter#476]
* **I'm submitting a ...**
- [ ] bug report
- [ ] support request

* **Problem**
Hi, Why i can't update my variable values after dialog service function.Below code when i'm click addGender Button dialog window shown after click save button it is saved successfully. But Update my local variable (controller variable) it is not updating.  please guide me how to do this. 

* ** UserGenderDialog Service  **
          
            <md-dialog>
           <form ng-submit="vm.updateGender()">
            <md-dialog-content>
            <div class="md-dialog-content">
             <md-input-container class="RegisterForm-inputContainer">
              <label>I am</label>
                    <md-select ng-model="vm.gender" required md-no-asterisk="false">
                        <md-option value="1">Male</md-option>
                        <md-option value="2">Female</md-option>
                    </md-select>
                </md-input-container>
             </div>
            </md-dialog-content>

        <md-dialog-actions>
            <md-button type="button" ng-click="vm.cancel()">Cancel</md-button>
            <md-button class="md-primary md-raised" type="submit">Update</md-button>
        </md-dialog-actions>
       </form>
     </md-dialog>

* **UserProfile component.html.**

                <div layout="row" class="user-profile-fileds" layout-align="space-between">
                 <div class="user-profile-key">Gender</div>
                <div class="user-profile-button">
                 <a ng-click="vm.addGender($event)" class="RegisterForm-submit md-raised"><i class="zmdi zmdi-plus"></i> Add Gender</a>
                </div>
                <div class="user-profile-value">{{ vm.genderContain }}</div>
               </div>

* **UserProfile Controller**

                  class UserProfileController{
           constructor($log,$auth,API,$state,$stateParams,DialogService,$scope){
           'ngInject';
                   this.$auth = $auth;
                   this.$scope = $scope;
                   this.$log = $log;
                   this.API = API;
                   this.$stateParams = $stateParams;
                   this.DialogService = DialogService;
                   this.genderContain = "";;
         }
                addGender($event){
                   let options = {
                       controller: UserProfileController,
                       controllerAs: 'vm',
                       escapeToClose:true
                   }
                   this.DialogService.fromTemplate("UserGender",options);
               }
                updateGender(){
                   let user ={
                       gender : this.gender,
                       updateTo : 'gender'
                   }
                   this.API.all('updateprofile').post(user).then((response)=>{
                       this.genderContain = response.data.returnUser.gender;
                       this.DialogService.hide();
                   });

               }
          }

                   export const UserProfileComponent = {
                   templateUrl: './views/app/components/user-profile/user-profile.component.html',
                   controller: UserProfileController,
                   controllerAs: 'vm',
                   bindings: {}
                }

* **Laravel & Angular version:** 3.2.0

**Comment by flick36** [comment]
Post your Dialog controller, you should return something if you want to update some UserProfileController variable, to have something like this:
```
this.DialogService.fromTemplate("UserGender",options).then((returnedValue) => {
    this.variableInUserProfileController = returnedValue;
});
```

**Comment by jadjoubran** [comment]
@flick36's solution works 👍 
Feel free to re-open if it doesn't work
Cheers
