### ISSUE TITLE
Implementing factory codes for angular

### ISSUE THREAD

**Issue by ryvan-js** [jadjoubran/laravel5-angular-material-starter#477]
Hello there ,
where and how to implement factory codes for modules?

For example:
```
angular.module('nutritionApp').factory('$nutrition', ['$resource', function ($resource) {
  'use strict';

  return {
    desserts: $resource('https://infinite-earth-4803.herokuapp.com/nutrition/desserts/:id')
  };
}]);
```
thanks
* **Laravel & Angular version:** 3.2.0

**Comment by jadjoubran** [comment]
Hi @ryvan-js 
Using this starter, you could generate a service, which is very similar to a factory
Feel free to replace all the services you find here with a factory and rename the folder and fix the `index.module.js`
