### ISSUE TITLE
have a problem with authecation

### ISSUE THREAD

**Issue by harmon1ca** [jadjoubran/laravel5-angular-material-starter#479]
* **I'm submitting a ...**
- [ ] bug report
- [ ] feature request
- [x] support request
- [ ] other (Please specify)

I have a problem with login form. Got a 500 error on enter(api/auth/login 500 error(anonymous function)).But if i use wrong password i get 401
AuthController.php i get 401 error(anonymous function).
```
public function login(Request $request)
    {
        $this->validate($request, [
            'email'    => 'required|email',
            'password' => 'required|min:8',
        ]);

        $credentials = $request->only('email', 'password');

        try {
            // verify the credentials and create a token for the user
            if (! $token = JWTAuth::attempt($credentials)) {
                return response()->error('Invalid credentials', 401);
            }
        } catch (\JWTException $e) {
            return response()->error('Could not create token', 500);
        }

        $user = Auth::user();

        return response()->success(compact('user', 'token'));
```
i update composer.json to "tymon/jwt-auth": "1.0.*@dev" and it not helped
Centos 6.7

* **Laravel & Angular version:** 3.4.0

**Comment by jadjoubran** [comment]
Hi @harmon1ca 
Do you have `use Auth;`
at the top of your file?

**Comment by harmon1ca** [comment]
I have this in AuthController.php
```
namespace App\Http\Controllers\Auth;

use Auth;
use JWTAuth;
use Tymon\JWTAuth\Providers\JWT;
use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

```
but i commented "try catch" in  AuthController.php

```
$credentials = $request->only('email', 'password');

        /*try {
            // verify the credentials and create a token for the user
            if (! $token = JWTAuth::attempt($credentials)) {
                return response()->error('Invalid credentials', 401);
            }
        } catch (\JWTException $e) {
            return response()->error('Could not create token', 500);
        }*/

        $user = Auth::user();
```
and get warning "Expecting a token named "data.token".
In network tab i saw
![233](https://cloud.githubusercontent.com/assets/11133385/24151537/21c81b2c-0e5a-11e7-8247-c7ca6d9c6214.png)

**Comment by jadjoubran** [comment]
Alright then you need to check the logs in this file:
`storage/logs/laravel.log`
It will give you a pointer on why it's returning a 500

**Comment by harmon1ca** [comment]
I check log, last notice was "2017-03-10 08:26:28"
```
[2017-03-10 08:26:28] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Tymon\JWTAuth\Providers\LaravelServiceProvider' not found' in /vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php:146
Stack trace:
#0 {main}  
```
and i corected it

**Comment by harmon1ca** [comment]
i have progress with this problem. I change /app/User.php add "implements JWTSubject" and getJWTIdentifier(),getJWTCustomClaims() And it work(request 200 without errors) 
![scree](https://cloud.githubusercontent.com/assets/11133385/24603041/f5d3edc6-1867-11e7-8cbc-3aab8ba91246.png)
But after logged not redirect to my auth page

**Comment by asinan007** [comment]
Hi, 
little new to this. I just pulled the latest, and was reading the docs. On JWT Auth Section under Overview it does say there will be an auto generated LoginController.php but unfortunately it is not there. Am i missing something here??
