### ISSUE TITLE
Call component function from another component

### ISSUE THREAD

**Issue by num3r06** [jadjoubran/laravel5-angular-material-starter#480]
* **I'm submitting a ...**
- [ ] bug report
- [ ] feature request
- [x] support request
- [ ] other (Please specify)

* **Provide information & explanation**
Hi. i've create a angular view with an header and an central view.
Into the header i have a component and into the central view i have another component.
It's possible call a component header function from other component?
This feature it's important because a lot of header variable are updating from central view component action
Thx

* **Got code samples?**
Make sure to use 3 backticks (and javascript or php after it to show your code) [More info](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code)
Also make sure to click on the *Preview* button to double check your code formatting

* **Laravel & Angular version:** 3.2.0

**Comment by followtheart** [comment]
Maybe，what your need is a Service,and share the service in that two component(head/central)

**Comment by num3r06** [comment]
Ok i've investigate this possibility. But how can i refresh header variable value on an event in central view?
The central view refresh every 10 sec and if a value change in central variable a corrispondent value must be changed

**Comment by followtheart** [comment]
https://docs.angularjs.org/guide/component
