### ISSUE TITLE
Is this just old cruft?

### ISSUE THREAD

**Issue by james-coder** [jadjoubran/laravel5-angular-material-starter#481]
* **I'm submitting a ...**
- [ ] bug report
- [ ] feature request
- [x] support request
- [ ] other (Please specify)

* **Provide information & explanation**

Is this just old cruft? `'Accept': 'application/x.laravel.v1+json'`
https://github.com/jadjoubran/laravel5-angular-material-starter/blob/master/angular/services/API.service.js#L7

I see references to it in old documentation, but it seems to be removed in newer documentation and has no other reference in branch master code. Does this do anything right now or is it just left-over cruft?

Thanks in advance.

* **Laravel & Angular version:** 3.2.0

**Comment by jadjoubran** [comment]
Hi @jamesalton 
Thanks for posting here!
This is called Content negotiation between the front-end and the API
It allows you to specify a specific version of the API without altering the URLs
You can also configure it to return data in other formats than json
[Dingo API Documentation](https://github.com/dingo/api/wiki/Configuration#strict-mode)
