### ISSUE TITLE
Updating to Laravel 5.4 and Webpack

### ISSUE THREAD

**Issue by mikimaine** [jadjoubran/laravel5-angular-material-starter#482]
Is there any plan to update to Laravel 5.4 and use Laravel Mix with Webpack instead of Gulp.

**Comment by jadjoubran** [comment]
Hi @mikimaine 
Thanks for posting here!
Honestly I thought not a lot of people would be still using AngularJs now that Angular (angular 2) has been released so I was thinking that Laravel 5.3 would be the last release for AngularJS version and that I should start working on [Laravel-Angular](http://github.com/jadjoubran/laravel-angular)
However I didn't have much time in the past few months..

If the community actually needs a 5.4 version with Webpack support, I'll definitely do it!

( 👍  below if you'd need a 5.4 version )

**Comment by codex-corp** [comment]
@mikimaine if you just interested in webpack .. take a look here (https://github.com/JeffreyWay/laravel-elixir-webpack-official)

**Comment by newkillerbeast2017** [comment]
I would prefer a Lumen 5.4 with Angular 2.x since we mostly use Laravel as API, it would slim down and increase the performance. Just my 2 cents.

**Comment by wishborn** [comment]
Laravel 5.4 with Angular 2 would be awesome. I've been using Angular 2 in an Ionic project and I can see being able to extend it farther with this project.

**Comment by jadjoubran** [comment]
Hi @mikimaine 
As I've learned about mobile performance in the past year, I've added a 2017 update to the [readme](https://github.com/jadjoubran/laravel5-angular-material-starter/#2017-update)

I don't think it's a good idea to start new apps using AngularJS if you're planning on having decent mobile User Experience because javascript bundles have very large sizes

**Comment by mikimaine** [comment]
@jadjoubran  so will Angular 2 will be a better choice.

**Comment by RodWizard** [comment]
@jadjoubran so when will it be released? As Laravel 5.4 have many better feature like mailable, Laravel Dusk, Real-time facades, blade's slots, etc.

> Don't wan't to start a new project without this starter, so eagerly waiting for the latest release.

**Comment by jadjoubran** [comment]
I actually started working on the upcoming version for Angular (2+) 🎉 

It's still Work in progress but it works as a package on Laravel & Lumen
http://github.com/jadjoubran/laravel-angular

**Comment by jadjoubran** [comment]
Hi everyone!
You can already get started with the new Laravel & Angular package.
[Repo](https://github.com/jadjoubran/laravel-angular)
[Website & documentation](http://laravel-angular.io/)
🎉
