### ISSUE TITLE
error in fresh install 3.4

### ISSUE THREAD

**Issue by ahmedraafat200** [jadjoubran/laravel5-angular-material-starter#485]
* **I'm submitting a ...**
- [x] support request

it's a fresh install and i'm  getting this error after php artisan serve 

[Sat Mar 18 17:15:36 2017] PHP Warning:  Uncaught exception 'ErrorException' wit
h message 'require(C:\xampp\htdocs\laravel5-angular-material-starter\public\css/
critical.css): failed to open stream: No such file or directory' in C:\xampp\htd
ocs\laravel5-angular-material-starter\storage\framework\views\000c94a4c473ad0b4e
fede1bf538ca6b3f09e6d3.php:17
Stack trace:
#0 C:\xampp\htdocs\laravel5-angular-material-starter\storage\framework\views\000
c94a4c473ad0b4efede1bf538ca6b3f09e6d3.php(17): Illuminate\Foundation\Bootstrap\H
andleExceptions->handleError(2, 'require(C:\\xamp...', 'C:\\xampp\\htdocs...', 1
7, Array)
#1 C:\xampp\htdocs\laravel5-angular-material-starter\storage\framework\views\000
c94a4c473ad0b4efede1bf538ca6b3f09e6d3.php(17): require()
#2 C:\xampp\htdocs\laravel5-angular-material-starter\vendor\laravel\framework\sr
c\Illuminate\View\Engines\PhpEngine.php(42): include('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\laravel5-angular-material-starter\vendor\laravel\framework\sr
c\Illuminate\View\Engines\CompilerEngine.php(59): Illuminate\View\Engines\PhpE i
n C:\xampp\htdocs\laravel5-angular-material-starter\storage\framework\views\000c
94a4c473ad0b4efede1bf538ca6b3f09e6d3.php on line 17
[Sat Mar 18 17:15:36 2017] PHP Fatal error:  main(): Failed opening required 'C:
\xampp\htdocs\laravel5-angular-material-starter\public\css/critical.css' (includ
e_path='C:\xampp\php\PEAR') in C:\xampp\htdocs\laravel5-angular-material-starter
\storage\framework\views\000c94a4c473ad0b4efede1bf538ca6b3f09e6d3.php on line 17

* **Laravel & Angular version:** 3.4.0

**Comment by jadjoubran** [comment]
Hi @ahmedraafat200 
I think you forgot to run `gulp` before running `php artisan serve`
Let me know if it works for you!

**Comment by mtshikomba** [comment]
thanks @jadjoubran , it worked!
