### ISSUE TITLE
Laravel-Angular-Material-Doc-Chinese

### ISSUE THREAD

**Issue by ArrayZoneYour** [jadjoubran/laravel5-angular-material-starter#487]
* **I'm submitting a ...**
- [ ] bug report
- [ ] feature request
- [ ] support request
-  other (Chinese Doc Support)

* **Provide information & explanation**

In the last few months, I searching a good framework to provide the API for the App we want to make. Finally I found your project and I think it's really beautiful to work on.To show my thanks,I tanslate the doc of 3.2 into Chinese, 
[Laravel-Angular-Material-Doc-Chinese](https://github.com/ArrayZoneYour/Laravel-Angular-Material-Doc-Chinese)

* **Laravel & Angular version:** 3.2.0

**Comment by ArrayZoneYour** [comment]
Oh,It's for 3.4 version.I am wrong~

**Comment by jadjoubran** [comment]
Thanks a lot for that @ArrayZoneYour!
I've added it under `Community translations` in the readme
Cheers!\
