### ISSUE TITLE
How to use prerender service

### ISSUE THREAD

**Issue by dinesh2017** [jadjoubran/laravel5-angular-material-starter#488]
Anyone tell me how to use prerender service? i'm trying to install that but i don't how to configure that. please guide me?

- [ ] bug report
- [ ] support request

* **Provide information & explanation**
I'm using prerender service from https://github.com/prerender/prerender-node. But i'm confusing while implementation. please guide me how to?

Thank you,

* **Laravel & Angular version:** 3.2.0

**Comment by dinesh2017** [comment]
anyone please help me...

**Comment by dinesh2017** [comment]
is there any solution? please help me...

**Comment by jadjoubran** [comment]
Hi @dinesh2017 
Please check this issue https://github.com/jadjoubran/laravel5-angular-material-starter/issues/475
