### ISSUE TITLE
Add getting started guide

### ISSUE THREAD

**Issue by jadjoubran** [jadjoubran/laravel5-angular-material-starter#49]
How to get started after installation by doing a sample functionality:

covering the following:
- API routes
- controller
- artisan ng:feature generator
- ui-router
- angular controller
- restangular

**Comment by skattabrain** [comment]
This would be great! I just installed it, this looks like it will be awesome but a guide would be great. Having a complete working authentication out of the box would be great too.

This is definitely going to be a project to watch!

**Comment by jadjoubran** [comment]
hi @skattabrain thanks!
the out of the box authentication will be available in #41 
I would love it if you can star the repo, to show some support :smile: 

I still haven't drafted the getting started guide, but I'll write the first draft here:

1) after installation make sure to familiarize yourself with the underlying technologies - because in most scenarios, Laravel5-angular-material-starter is just a wrapper on top of these technologies:
angular
angular material
ui-router
restangular

2) The package's documentation is written using Laravel5-angular-material-starter. It allows you to use the sample code to start learning.

The most notable use case, is creating a new page called `reviews` on the front end:
3) Make sure to run `gulp watch` to compile all our changes.

4) First of all, we need to create a new feature so we run the following command:
`php artisan ng:feature reviews`
this will create the following directory structure:
`angular/app/reviews/`
`angular/app/reviews/reviews.html`
`angular/app/reviews/reviews.js`
`angular/app/reviews/reviews.less`

The JS file is the controller used for the view (reviews.html). `reviews.less` is used for styling the view.
This structure allows your project to scale with the number of developers using it and with the business complexity behind it - for more info check this article on [sitepoint](www.sitepoint.com/flexible-and-easily-maintainable-laravel-angular-material-apps/)

5) Next we need to add it to our ui-router's routes. So open the `routes.js` file and add a new entry for the route: `/reviews`. This should be straightforward because you have the previous routes serving as an example.

6) We need to add a new link to the sidebar, so we open the `sidebar.html` and add a new entry and fix the `ui-sref` directive so that it opens this page when we click on it.

7) Your browser should've automatically refreshed and now clicking on the `Reviews` link in the sidebar would open a blank page which calls the Angular `ReviewsCtrl`.
So feel free to open the `reviews.html` file and add some content and you can have the logic that you want inside `reviews.js`

8) Now let's say this page needs to call an API, you have to open the `routes.php` and register a new route, use the same syntax that's used above (this is `dingo/api`)

9) create your laravel controller and execute your logic

10) call this route using `$http` or `Restangular` (I'd recommend `Restangular`)
The base url has been already setup for you, so you just need to call the route (you can check this [file](https://github.com/jadjoubran/laravel5-angular-material-starter/blob/645952d9250724b6ae1cba1107b9a71bca40e776/angular/app/jwt_auth/jwt_auth.js#L19) as an example)

11) Enjoy!

Let me know if there's something that I missed
cheers

**Comment by mechanicux** [comment]
Thanks a lot for your efforts @jadjoubran this an awesome project.

**Comment by jadjoubran** [comment]
@mechanicux thanks :D Glad to hear that
Would you be interested in giving your opinion for [Version 3](https://github.com/jadjoubran/laravel5-angular-material-starter/issues/88)?

**Comment by mechanicux** [comment]
That would be a great pleasure anyway I'll try to write something if it crosses my mind,  I am just familiarizing with the code. Thanks @jadjoubran

**Comment by jadjoubran** [comment]
@mechanicux great! If you want to join the trello board and get a sneak peek feel free to send me your email.
If you have questions, feel free to open a new issue, it'll serve as documentation for other people
Cheers

**Comment by mechanicux** [comment]
Happy to follow along with you guys. here is my email ouad87@hotmail.com 
Cheers

**Comment by jadjoubran** [comment]
@mechanicux done!

**Comment by mechanicux** [comment]
@jadjoubran Thanks man :+1:

**Comment by jadjoubran** [comment]
@mechanicux @skattabrain docs for the newer version are online
https://laravel-angular.readme.io/
I would love to get your feedback
