### ISSUE TITLE
CSS isolation for every component

### ISSUE THREAD

**Issue by tarkant** [jadjoubran/laravel5-angular-material-starter#490]
* **I'm submitting a ...**
- [ ] bug report
- [ x] feature request
- [ ] support request
- [ ] other (Please specify)

* **Provide information & explanation**

Hello everyone, I know I've ticked that this is a feature request but it's mostly because I don't see it on the current version of the boilerplate, I may have missed a point, in that case, please excuse me.
That said, I would like to know if there is something about CSS isolation, if it's planned and if someone knows something about this specific feature in this boilerplate. (or a workaround, anything)
For now I'm setting a specific CSS class for every page but as you might guess, sometimes some elements get affected even though I'm using rather complex CSS selectors.

Thank you in advance.

* **Laravel & Angular version:** 3.2.0

**Comment by daem0ndev** [comment]
You can use css modules in your project, https://github.com/css-modules/css-modules
