### ISSUE TITLE
integration of a new angular template

### ISSUE THREAD

**Issue by norabouhssis** [jadjoubran/laravel5-angular-material-starter#491]
Hello @jadjoubran ,@Bodom78 , i hope you're doing great.
i really thank you, i'm progressing a lot in my project, i just want to use an admin template that i downloaded, but i don't know how to integrate it to the repository. can you help me please
thank you, 

hello @MohamedQabbani , how are you? did you managed to integrate your template?

this is the template that i want to integrate:http://akveo.com/blur-admin-mint/#/dashboard

**Comment by radiumrasheed** [comment]
Hi @norabouhssis,

This really is not an issue but I could help as I'm also in your shoes

The real deal here is, you have to do it manually. There is no **1 solution fits all** for all templates.

**Comment by norabouhssis** [comment]
hey @Ra1da35ma,

thank you for the answer! Can i know the solution please? i'm stuck here.

**Comment by radiumrasheed** [comment]
do you have the source code to the template yet ?

If yes, share the repo and your code lets have a see
