### ISSUE TITLE
error on running php artisan migrate

### ISSUE THREAD

**Issue by nwaughachukwuma** [jadjoubran/laravel5-angular-material-starter#492]
Am having the following error when I run php artisan migrate:

PHP Warning:  require(C:\xampp\htdocs\Web_Programming\PHP\Laravel\projects\jadjoubran\laravel5-angular-material-starter\bootstrap/./vendor/autoload.php): failed to open stream: No such file or directory in C:\xampp\htdocs\Web_Programming\PHP\Laravel\projects\jadjoubran\laravel5-angular-material-starter\bootstrap\autoload.php on line 17

Warning: require(C:\xampp\htdocs\Web_Programming\PHP\Laravel\projects\jadjoubran\laravel5-angular-material-starter\bootstrap/./vendor/autoload.php): failed to open stream: No such file or directory in C:\xampp\htdocs\Web_Programming\PHP\Laravel\projects\jadjoubran\laravel5-angular-material-starter\bootstrap\autoload.php on line 17
PHP Fatal error:  require(): Failed opening required 'C:\xampp\htdocs\Web_Programming\PHP\Laravel\projects\jadjoubran\laravel5-angular-material-starter\bootstrap/./vendor/autoload.php' (include_path='C:\xampp\php\PEAR') in C:\xampp\htdocs\Web_Programming\PHP\Laravel\projects\jadjoubran\laravel5-angular-material-starter\bootstrap\autoload.php on line 17

Fatal error: require(): Failed opening required 'C:\xampp\htdocs\Web_Programming\PHP\Laravel\projects\jadjoubran\laravel5-angular-material-starter\bootstrap/./vendor/autoload.php' (include_path='C:\xampp\php\PEAR') in C:\xampp\htdocs\Web_Programming\PHP\Laravel\projects\jadjoubran\laravel5-angular-material-starter\bootstrap\autoload.php on line 17

**Comment by radiumrasheed** [comment]
Hello, have you resolved this ?

It doesn't seem to be an issue with the project.

Something is wrong in your `local` environment.

Are you sure you ran `composer install` correctly ?
