### ISSUE TITLE
How to setting this project to passive event?

### ISSUE THREAD

**Issue by yosmelvin** [jadjoubran/laravel5-angular-material-starter#493]
* **I'm submitting a ...**
- [ ] bug report
- [ ] feature request
- [x] support request
- [ ] other (Please specify)

* **Provide information & explanation**
for default this project dosent passive event
like this link below
https://developers.google.com/web/updates/2016/06/passive-event-listeners

How to setting this project to passive event?

* **Laravel & Angular version:** 3.4.0

**Comment by jadjoubran** [comment]
Hi @yosmelvin 

you can simply add `{passive: true}` as the 3rd argument when using touch events in `addEventListener`
