### ISSUE TITLE
Uncaught ReferenceError: module is not defined  while trying to import laravel-echo

### ISSUE THREAD

**Issue by cran208** [jadjoubran/laravel5-angular-material-starter#494]
* **I'm submitting a ...**
- [ ] support request

* **Provide information & explanation**
I started a laravel-echo-server on my server and included laravel-echo into gulpfile.

As what I learned from laravel documentation:
`Import Echo from 'laravel-echo';` is all I need to do.

It works fine since I can console.log(Echo) in the browser except there is an "Uncaught ReferenceError: module is not defined" in console.

I looked up the echo.js file and found `module.exports = Echo`, which cause the error.

Am I doing anything wrong?

* **Laravel & Angular version:** 3.4.0

**Comment by jadjoubran** [comment]
Hi @cran208 
There isn't any module setup in this repository which is why your import statement is not working
