### ISSUE TITLE
how to implement pagination with restangular?

### ISSUE THREAD

**Issue by 0xd5dc** [jadjoubran/laravel5-angular-material-starter#497]
* **I'm submitting a ...**
- [ ] bug report
- [ ] feature request
- [x] support request
- [ ] other (Please specify)

* **Provide information & explanation**
how do I get with a param for pagination?
I want to use restangular to get "api/posts?page=2", but got type error "...getList is not a function"

* **Got code samples?**
in the controller
this.API.getList("posts", {page: params}).then(function(posts) {})

* **Laravel & Angular version:** 3.2.0

**Comment by jadjoubran** [comment]
Hi @summermick 
Try the below:

```javascript
this.API.all('').get('posts', {page: params})
```

**Comment by 0xd5dc** [comment]
I have been used this one, `API.all("post?page="+page).get('')`, instead, but my OCD just wont let me move one.
thanks a million!
