### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by jaesung2061** [jadjoubran/laravel5-angular-material-starter#499]
* **I'm submitting a ...**
- [ ] bug report
- [ ] feature request
- [ ] support request
- [X] other (Please specify)

* **Provide information & explanation**
Will there be support for Laravel 5.5?

**Comment by jadjoubran** [comment]
Hi @jaesung2061 
As mentioned in the readme, it's advised to move to Angular (2+) rather than relying on AngularJs, mainly because of the bundle size
That's covered in [laravel-angular](http://github.com/jadjoubran/laravel-angular)
