### ISSUE TITLE
Blank starter

### ISSUE THREAD

**Issue by maiziheimei** [jadjoubran/laravel5-angular-material-starter#501]
* **I'm submitting a ...**
- [ x] bug report
- [ ] feature request
- [ ] support request
- [ ] other (Please specify)

* **Provide information & explanation**
I have a problem, after installation by exactly following, https://laravel-angular.readme.io/docs,
I got a blank webpage at localhost:8000, just with a logo.

I tried to find the problems, I saw the following error when I ran "gulp && gulp watch"
"
.../laravel5-angular-material-starter/angular/run/routes.run.js
  1:49  error  '$auth' is defined but never used  no-unused-vars
✖ 1 problem (1 error, 0 warnings)
"
I went to check the "routers.run.js", there is "$auth" being used.

Please help me to get it starter! Thank you very much!

* **Got code samples?**
Make sure to use 3 backticks (and javascript or php after it to show your code) [More info](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code)
Also make sure to click on the *Preview* button to double check your code formatting

* **Laravel & Angular version:** 3.2.0

**Comment by jadjoubran** [comment]
Hello @maiziheimei 
Thanks for opening an issue.
can you please try the steps in this [issue](https://github.com/jadjoubran/laravel5-angular-material-starter/issues/500)

Please let me know if it works, thanks!
