### ISSUE TITLE
problems with a blank starter after installation!

### ISSUE THREAD

**Issue by maiziheimei** [jadjoubran/laravel5-angular-material-starter#502]
* **I'm submitting a ...**
- [ ] bug report
- [ ] feature request
- [ x] support request
- [ ] other (Please specify)

* **Provide information & explanation**
Dear jadjoubran, its me again.
when I edit ".env" file, by using database name as "laravel_angular", it gives queryException,

" [Illuminate\Database\QueryException]                                         
  SQLSTATE[HY000] [1049] Unknown database 'laravel_angular' (SQL: select * fr  
  om information_schema.tables where table_schema = laravel_angular and table  
  _name = migrations)" and 

 "[PDOException]                                             
  SQLSTATE[HY000] [1049] Unknown database 'laravel_angular'"

Could you help me with the installation? Thank you very much!

Bests

* **Got code samples?**
Make sure to use 3 backticks (and javascript or php after it to show your code) [More info](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code)
Also make sure to click on the *Preview* button to double check your code formatting

* **Laravel & Angular version:** 3.4.0

**Comment by jadjoubran** [comment]
It seems because you haven't created a database called `laravel_angular`, make sure to double check that and try again!

**Comment by maiziheimei** [comment]
Thanks! all installation problems have been solved.


Have a nice weekend!


________________________________

**Comment by jadjoubran** [comment]
Sounds great!
