### ISSUE TITLE
Update generators to match Demo Layout

### ISSUE THREAD

**Issue by jadsalhani** [jadjoubran/laravel5-angular-material-starter#54]
Since you changed the layout to be more responsive and that that Material Design components are responsive, I thought it would be a good idea to change the HTML generator stub  (used by ng\* generators) to match the skeleton of the Demo pages (Changes available here https://github.com/jadjoubran/laravel5-angular-material-starter/commit/fc81dddebd1a68900c67ca2706be54c906541546#diff-54e5be94b4fc1d6f374146c1cad4e758R1)

**Comment by jadjoubran** [comment]
Thanks!

Working on a fix

**Comment by jadjoubran** [comment]
Will be available as of [2.10.0](https://github.com/jadjoubran/laravel5-angular-material-starter/releases/tag/2.10.0)
