### ISSUE TITLE
Create screencast for getting started

### ISSUE THREAD

**Issue by jadjoubran** [jadjoubran/laravel5-angular-material-starter#62]
A 3-5 minutes screencast that quickly goes through installation and the process of creating a new page that connects to an API endpoint

**Comment by masterpowers** [comment]
where is the link of the screencast, anyway i already installed it and it is working

**Comment by jadjoubran** [comment]
hi @masterpowers 
I still haven't recorded the screencast, but I post all the new ideas/features on issues to get other people's opinion
I'll post here as soon as I do it but honestly I don't think it'll be in the coming 2 weeks.
Meanwhile, you can check issue #49

**Comment by coxw** [comment]
Agreed. It would be really useful to demonstrate how to get started. It's easy to spool up, but pointers on adding new features, routing examples, migrations, and JWT authentication would be really helpful to spur adoption. If I can figure it out, I will try to create some documentation.

**Comment by jadjoubran** [comment]
Hi @coxw 
The screencast will be released with Version 3.
I'm working on finishing all the features in Version 3 before I start recording the screencast.

Feel free to ask about one or more specific scenarios and I'd be happy to provide you with a step by step tutorial

Cheers

**Comment by jadjoubran** [comment]
With the release of version 3, screencasts are coming soon :smile:

**Comment by ChadTaljaardt** [comment]
:+1:

**Comment by jadjoubran** [comment]
Getting started screencast is now available on http://www.laravel-angular.io/
:smile: :rocket: 
More screencasts coming soon

Feel free to send requests for specific topics

**Comment by odyright** [comment]
:clap:

**Comment by jadjoubran** [comment]
New screencast is live :smile:

**Comment by ChadTaljaardt** [comment]
I just watched this, looks really good. 

Cant wait to see more :+1:

**Comment by jadjoubran** [comment]
awesome I'm glad you liked it :smile:
