### ISSUE TITLE
Suggestion: add ACL

### ISSUE THREAD

**Issue by ptondereau** [jadjoubran/laravel5-angular-material-starter#65]
This starter pack is great but I wonder if you could add an ACL (Access Control Layer) module to laravel such as: https://github.com/intrip/laravel-authentication-acl or https://github.com/kodeine/laravel-acl

Cheers!

**Comment by jadjoubran** [comment]
Hi @rooferz thanks for your suggestion!
I am not sure but don't these packages provide the same functionality that Laravel 5.1.1 introduced? 
http://laravel.com/docs/5.1/upgrade#upgrade-5.1.11
http://laravel.com/docs/5.1/authorization

If not, can you please point out the difference, as I have not worked with Laravel's ACL yet.
And if they're the same, then maybe we can team up to provide sample policies. What do you think?

Cheers

**Comment by ptondereau** [comment]
Indeed, Laravel have inclued policies system and sure, I'd be glad to help you.
The question now is on AngularJS level which I'm a beginner on...

Do you think, it's a better idea if Front and Backend end are provided by laravel render engine than Angular only itself ?

**Comment by jadjoubran** [comment]
> Do you think, it's a better idea if Front and Backend end are provided by laravel render engine than Angular only itself ?

hmm would that work? (using blade)

My initial thoughts would be the following:
in our case, we can't use ACLs on the front-end without having to redefine them.. So we can probably use all the features except for blade's `@can()` method
That becomes a bit similar to `ng-show` and `ng-if` but maybe we can provide a directive to ease this.. but this would also require duplication of policies so I'm not really sure..
I'd love to get your feedback. Also @Bodom78 and @GrahamCampbell

**Comment by ptondereau** [comment]
IMHO, I think, in order to obtain a full separation of data provider and client, it would be logic that Angular handle ACL but with Laravel such as a RESTful service.
BUT javascript may be unsecure with sensitive data...

For the moment, I think Laravel is better to achieve this. In the end, it ends with 2 SPA (1 for Back & 1 for Front) and I think it more safe.

But in the back-end, if you have some "grade" with user, It's about blade.

**Comment by jadjoubran** [comment]
Javascript validation/ACL is strictly for the User Experience - we can never rely on it for security.
Knowing that the main ACL is going to be implemented in the backend, I think the following would be extremely useful to users of this package:
- [ ] route authentication based on a closure (integrated within `ui-router`) - maybe if you have multiple user types: `client` & `admin`
- [ ] route authentication based on JWT - #41 

Let me know what you think

**Comment by ptondereau** [comment]
sounds good to me!

**Comment by jadjoubran** [comment]
Closing this for now, since the direction of this starter package changed a bit..
If anyone can provide a recipe or plugin as mentioned in #149, I'd be happy to document it :smile:
