### ISSUE TITLE
Partial views logic

### ISSUE THREAD

**Issue by AArmin** [jadjoubran/laravel5-angular-material-starter#73]
First off, congratulations for making this amazing project. I hope it gets the recognition and the credit it deserves.

My question is this: how do you go about loading partial views for states' templateUrl?

On a very simple CRUD example, and in pseudo-code:
- Data model "staff" has a detail view and a create/edit view.
- state "app.staff.create" needs to load "form.html" partial.
- state "app.staff.show" needs to load "detail.html" partial
- getView() method for templateUrl will look for a folder called "staff", and a file "staff.html", but I'd like to keep all of my partials within the "staff" feature folder, "staff.html" being the container for most of them.

Now I can simply not use the getView() helper, but I'm wondering if you had some kind of logic for loading partials in mind (based on all of your other clever solutions :))

Thanks!

**Comment by jadjoubran** [comment]
Hi @AArmin 
Thank you for your kind words :smile: 

How about using `getView('staff/detail')`?

Let me know if it works for you

**Comment by Bodom78** [comment]
@AArmin Remember that ui-router is quite powerful so don't feel restricted by the example in the starter project. If you have not looked at the ui-router wiki it's very worthwhile. 

To start with check out [this](https://github.com/angular-ui/ui-router/wiki/Multiple-Named-Views) and [this](https://github.com/angular-ui/ui-router/wiki/Multiple-Named-Views#view-names---relative-vs-absolute-names) which I think will be of use to you.

Also if the getView() method does not meet you requirement you can always add some parameters to add more functionality maybe like so (Not tested):

```
var getView = function(viewName, viewPath, fileName) {
    // If no viewPath is passed set a default.
    var path = viewPath ||  './views/app/';

    // If no fileName is passed use the viewName.
    var file = fileName || viewName

    return path  + viewName + '/' + file+ '.html';
};
```

This works the same but has some optional parameters you can use. Leave them out and it works as it originally did.

**Comment by jadjoubran** [comment]
Amazing answer @Bodom78 
Closing this for now - @AArmin feel free to comment if this works for you or if you have any question
