### ISSUE TITLE
Process integration

### ISSUE THREAD

**Issue by odyright** [jadjoubran/laravel5-angular-material-starter#75]
hello @jadjoubran ; hello @Bodom78 
I followed your instructions and I've made ​​much progress in my project , really thank you .
However, I want to know if it was possible to integrate an admin template in this repository ?
I'm afraid to break my work.
But @Bodom78 had explained how to do that by theming angular, 

> To theme Angular Material you should read their documentation at https://material.angularjs.org/latest/#/Theming/03_configuring_a_theme
> This file you will use to modify with what you learn from the Angular Material docs is located in <code>angular/config/theme.js</code>
> Add any less files you like in the angular/app folders, as long as gulp watch is running it will get compiled into the project.
> Example add <code>angular/material/mystyles.less</code> run gulp watch and add any css you like.
> To style the sidebar you can modify the existing <code>angular/app/sidebar/sidebar.less</code>

but i'm so confuse i don't know if i should use same method.

i want to add this admin template <a href="http://triangular.oxygenna.com/">Triangular Angular Material admin template</a> or <a href="http://fuse-angular-material.withinpixels.com/dashboard">Fuse Angular Material admin template</a>

**Comment by jadjoubran** [comment]
Hi @odyright 
No worries!

If you want to theme angular material, you just have to open the `theme.js` file and fix the 3 colors - for more info follow this [link](https://material.angularjs.org/0.11.2/#/Theming/03_configuring_a_theme).

If you want to add a new template, you should follow their installation instructions - if you need further help, provide us with the installation links.

@Bodom78 feel free to add more info

**Comment by Bodom78** [comment]
Yes, the Angular Material config I mentioned is only how you change the colours for Angular Material as per their docs and not to be confused with laying out and custom styling their components.

Sorry I'm not familiar with Triangular or Fuse so you would need to follow their instructions on how they are used.

At a glance Triangular looks like a full frontend solution. If you were going to use that then I would imagine you build you whole frontend then separately use something like Laravel or any server side framework/language to build your API.

**Comment by odyright** [comment]
i'm glad, yes it's true what you said, @jadjoubran, @Bodom78 as you said laravel is more server side and  agular material front-end side. but I said I'm afraid because your repository is ready so (laravel+ang-mat). I 'm starting and I'll give you my result using your work as exemple.

or do you suggest me another practice?

**Comment by Bodom78** [comment]
I wouldn't suggest another practice as I think it's up to you as the developer to evaluate and choose what is right for the project requirements. Don't be afraid to try out as much as you can prior to starting as the foundation of your application is the most important thing.

**Comment by jadjoubran** [comment]
True! You can easily create a new git branch if you're worried about breaking your code

**Comment by odyright** [comment]
Thank you @jadjoubran , thank you @Bodom78 i'll come back.

**Comment by jadjoubran** [comment]
Sure! Closing this for now. Feel free to ask again or even open a new thread

**Comment by MohamedQabbani** [comment]
@odyright what is up? i also need to integrate template to this repository?

**Comment by odyright** [comment]
hello @MohamedQabbani you have to follow the instruction given from your template.

**Comment by norabouhssis** [comment]
hello  @jadjoubran ,@Bodom78 , i hope you're doing great.
i really thank you, i'm progressing a lot in my project, i just want to use an admin template that i downloaded, but i don't know how to integrate it to the repository. can you help me please
thank you, hello  @MohamedQabbani , how are you? did you managed to integrate your template?

**Comment by norabouhssis** [comment]
this is the template that i want to integrate:http://akveo.com/blur-admin-mint/#/dashboard
