### ISSUE TITLE
Gulp watch and new html views

### ISSUE THREAD

**Issue by jfhernandeze** [jadjoubran/laravel5-angular-material-starter#76]
Hello, I an new to gulp and every time I add a new folder in angular/app like:

angular/app/mymodule/index.html
angular/app/mymodule/mymodule.js

gulp watch doesn't  update the app, I have to stop it, and do again gulp && gulp watch, and it takes some tome to do gulp, so this is slowing me down, how can I add new "modules" for my app and make "gulp watch" really acknowledge them

**Comment by jadjoubran** [comment]
Can you try updating your dependencies? 
Run `npm install` and try again 

Let me know if it works for you

**Comment by jfhernandeze** [comment]
npm install and every file I add in that folder will be updated?

**Comment by jadjoubran** [comment]
`npm install` so we can make sure you have the latest version of Elixir & gulp. 

After that, creating a new fever should be automatically picked up by the watcher 

Let me know if it works for you

**Comment by jadjoubran** [comment]
@jfhernandeze is the issue happening when you run `artisan ng:feature test` for example?

**Comment by mtdavidson** [comment]
@jadjoubran I've seen this issue as well but haven't had time to investigate it yet. As far as I know everything is up to date as it can be.

**Comment by jadjoubran** [comment]
@mtdavidson thanks for sharing!
So for example if you run `artisan ng:feature test` and then change and trigger a change in any of the generated files, `gulp` wouldn't recognize these changes?

**Comment by jadjoubran** [comment]
I can confirm that this is not working when I have `gulp watch` running. If I run `artisan ng:feature test` the new test folder (and its components) will not be picked up by the watcher

**Comment by jadjoubran** [comment]
I found the issue:
Gulp watch https://github.com/floatdrop/gulp-watch/issues/104
references an issue in Gaze
https://github.com/shama/gaze/issues/84

The only solution for now, would be to relative paths instead of absolute paths.
I wasn't able to fix that a few months ago because of the defaults of Laravel elixir (which was in version 2 at that time).
I will try to fix the `elixir.json` file in order to get rid of absolute paths.

**Comment by jadjoubran** [comment]
I tried getting rid of absolute paths and it still doesnt' work.. I also cleared my npm cache, cleared my node modules and re-installed (using npm 3)
Maybe anyone has an idea?

**Comment by ChadTaljaardt** [comment]
Is this still an issue?

**Comment by jadjoubran** [comment]
Unfortunately, yes :disappointed:

**Comment by kujtimiihoxha** [comment]
@jadjoubran I think you could use `gulp-watch` it does not have this problems if you want I could help implement this.

**Comment by jadjoubran** [comment]
@kujtimiihoxha oh nice.. and all the elixir tasks will keep on working as expected? 😄 
Yeah it would be great, thanks!

**Comment by kujtimiihoxha** [comment]
@jadjoubran I will see what I can do ,I have not tested if  `gulp-watch` and `elixir` work together, as soon as I have something finished I will send a pull request.

**Comment by jadjoubran** [comment]
👍
