### ISSUE TITLE
Updating angular-material to latest version (0.11.4) [updated] to 1.0.0

### ISSUE THREAD

**Issue by ghost** [jadjoubran/laravel5-angular-material-starter#83]
Is it possible to update angular-material (0.10.1) to the latest version (0.11.4) without breaking anything? 

https://github.com/angular/material/blob/master/CHANGELOG.md

**Comment by Bodom78** [comment]
I'm pretty sure there were some changes around the 0.11.2 mark that will cause issues with the current layout (Content will be forced below the sidebar area).

I believe wrapping the sidebar and content with a <div layout="row" layout-fill> fixes it but this needs testing.

**Comment by ghost** [comment]
Thanks for the answer. This starter kit is awesome!

**Comment by jadjoubran** [comment]
@regisaih thanks for your suggestion and @Bodom78 thanks for your awesome contribution :D
I actually gave it a quick try, and the only issues that I was able to see were the `sidebar` and `tabs`.
The sidebar issue is only with background colors, the tabs one looks theme related
so @regisaih if you need to upgrade in your project, you should be good to go, but watch out for breaking changes in their changelog (like renaming `offset` to `flex-offset`)
And we should work on a fix soon

@Bodom78 let me know if you wanna do it or not so we don't work on it both

Cheers!

**Comment by Bodom78** [comment]
@jadjoubran I can take a look in a few days so if the update is not too urgent I'll be happy to do it.

**Comment by jadjoubran** [comment]
Not urgent since most users are able to update, thanks man!

**Comment by Bodom78** [comment]
Angular Material is now on RC1 for version 1.0.0 so I might hold off a little until the 1.0.0 release.

**Comment by jadjoubran** [comment]
Sounds great!

**Comment by jadjoubran** [comment]
Hi @Bodom78 
I just peeked at angular material's release cycle and they seem to be planning for an rc3 and possibly an rc4 before the 1.0 release (they're currently at rc2).
So let's not do this fix for version 2.x since I started working on version 3.x

**Comment by Bodom78** [comment]
@jadjoubran Agreed, will leave it for V3.

**Comment by jadjoubran** [comment]
This is probably something that I need to take care of in the `DialogService`
https://github.com/angular/material/blob/master/CHANGELOG.md#breaking-changes

**Comment by jadjoubran** [comment]
This is going to be part of the new design rewrite for version 3 (so we don't need to `upgrade` the old version)
