### ISSUE TITLE
Version 3 brainstorming

### ISSUE THREAD

**Issue by jadjoubran** [jadjoubran/laravel5-angular-material-starter#88]
I started drafting some ideas for the upcoming version 3.

I'd love to get the feedback of users of this repository.

The brainstorming is happening on a private trello board.

I just have a few cards that you can comment on or maybe add new ones.

@GrahamCampbell and @Bodom78 can I add you to the trello board? Your feedback is very important

If anyone else is interested, drop me an email or comment here and I'll invite you to the board.

You can leave the board whenever you want, don't worry about it being spammy.

Thanks

---

**Update**

Draft is almost finalized, so the board is now public

https://trello.com/b/tZ997reo/laravel-angular-material-starter

Feel free to comment or add new cards

**Comment by jadjoubran** [comment]
@rooferz and @masterpowers as well!

**Comment by Bodom78** [comment]
@jadjoubran Happy to contribute what I can. I'm @fadykhalife on trello.

**Comment by jadjoubran** [comment]
Great! We have 2 contributors so far, thanks @Bodom78 and @rooferz

**Comment by ChadTaljaardt** [comment]
Can i an invite but i will mainly just be observing and i can contribute where i can but cant promise anything. :+1:

**Comment by jadjoubran** [comment]
Hi @ChadTaljaardt 
Sure thing!
You don't have to contribute with code, upvoting cards and/or commenting is one of the most valuable contributions
Feel free to send me your trello email by email (check my github profile)

**Comment by jadjoubran** [comment]
Awesome contributions on the trello board! Thanks everyone
If anyone's still interested in joining, feel free to ping me
Cheers

**Comment by willmkt** [comment]
Hi, can you add me to the trello board also @willancorreia

Thanks..

**Comment by jadjoubran** [comment]
@willmkt done, thanks!

**Comment by jadjoubran** [comment]
Added board link since we're done brainstorming

**Comment by jadjoubran** [comment]
Thanks for everyone who contributed.
If you're interested, you can grab the latest version and test issues that are marked with [Version 3 Testing](https://github.com/jadjoubran/laravel5-angular-material-starter/issues?q=is%3Aopen+is%3Aissue+label%3A%22Version+3+Testing%22)
To do so, make sure to download using `composer create-project jadjoubran/laravel5-angular-material-starter:dev-master`

**Comment by rafalradomski** [comment]
Hi @jadjoubran I just installed laravel5-angular-material-starter and I have few suggestion. 

I see a lot of features, but when I opening project locally I don't see any example of:
- documentation how start working with project
- authentication (JWT Authentication) - login, register, reset pass page
- sample page with calls to api maybe users  or to do list?
- how remove the # from urls
- examples of how to use potencial of laravel and angularjs in real projects like 
  -- upload files? 
  -- forms validation?

.. and try to add your project to http://yeoman.io/generators/ then more people will start using it.

Good luck with new features...

**Comment by jadjoubran** [comment]
Hi @radiart 
Thank you for your feedback
- documentation is still pending, I'm going to add videos as well. Check out the [trello board](https://trello.com/b/tZ997reo/laravel-angular-material-starter) to monitor the progress
- There's a demo for login, in the JWT Auth page
- this is still pending as well
- I'll add this suggestion as a recipe
- this will also be covered in videos + how to write integration tests for them

This is not a yeoman generator, so I can't add it to yeoman.. it has to be a node module

Let me know if you have other suggestions
Cheers :smile:

**Comment by jadjoubran** [comment]
If all goes well, we should expect a release in the coming 2-3 weeks :smile: 
With a new neat design & shiny docs. Tutorial videos will follow asap

**Comment by jadjoubran** [comment]
Shiny new docs https://laravel-angular.readme.io/

I would love to get your feedback
And if anyone feels like reviewing the docs (or at least 1 section), let me know how it goes :smile:

**Comment by Bodom78** [comment]
@jadjoubran Skimmed through the docs and I must say the readability of the docs brilliant compared to githubs formatting, so much better.

I would like to at some stage go through the docs installing and modifying as I go along as I figure that's the best way to see what is missing and what could be improved. 

I wish I could contribute more, maybe if I survive crunch time at the office. Loving the progress this project has been making, keep up the great work.

**Comment by jadjoubran** [comment]
Thanks @Bodom78 
No worries :smile:

**Comment by ChadTaljaardt** [comment]
The docs are so much better now!!

**Comment by jadjoubran** [comment]
:+1: :smile:

**Comment by ptondereau** [comment]
Nice docs and so much clear.
I have a suggestion according to this new thing.

You could extract all pages in angular/ folder to the new docs because I think they are related to documentation and not really to start something.

In the repo, It should make more sense to just offer sample page such as login page (with JWT), mini dashboard (small header/footer, sidebar with fake link) and maybe a dummyfake homepage.

**Comment by jadjoubran** [comment]
Hi @rooferz 
Thanks for your suggestion :smile: 
I've already implemented this in the last push
Feel free to check it out, but it still needs design review from @nicolesaidy

JWT functionality is baked in, but a sample login screen is missing.. but indeed it makes sense.. I've added it to the trello board

**Comment by jadjoubran** [comment]
So version 3 has been officially launched today :smile: 
Thank you all for your contributions

As usual, feedback, comments & questions are always welcome

Demo: http://laravel-angular.io
Docs: http://laravel-angular.readme.io
Screencasts are coming soon ;)

**Comment by shiruken1** [comment]
If it's alright, could I give the [login form](https://trello.com/c/LIqTVohr/82-jwt-login-form-with-functionality) a try? I'm needing the functionality anyways, so might as well pitch in, right? :smile:

**Comment by jadjoubran** [comment]
@shiruken1 Of course it's alright!!
Feel free to open a PR and we can continue the discussion there :smile:
