### ISSUE TITLE
ng artisan commands generator

### ISSUE THREAD

**Issue by m33ch** [jadjoubran/laravel5-angular-material-starter#99]
Hi all,

first of all, thank you for your initiative. It's awesome!

I am a newbie of angular and laravel but I would like to contribute to the development of this project.
I read a Todo on trello board so i try to create a package for artisan commands based on the commands that are already existing.

This is my [repository](https://github.com/m33ch/Laravel-ng-artisan-generate).
I hope it can return usefull.

p.s sorry for bad english =D

**Comment by jadjoubran** [comment]
Hi @m33ch 

That's a great initiative, thank you so much!

The repository looks very promising

Would you mind sending me an email so we can set a plan on finalizing the repo?

Cheers

**Comment by m33ch** [comment]
Hi @jadjoubran 

of course.
Can you suggest how I can go or what to improve?

Thanks

**Comment by jadjoubran** [comment]
Closed in favor of https://github.com/jadjoubran/laravel-ng-artisan-generators/

**Comment by jadjoubran** [comment]
Working on finalizing this.
Thanks again @m33ch

**Comment by m33ch** [comment]
I'm happy to contribute! 😁
